### ISSUE TITLE
Unknown exception in headURL

### ISSUE THREAD

**Issue by grooves12** [SiCKRAGETV/sickrage-issues#1945] opened 2015-07-01 09:22 UTC
I am getting the following error with all NZB providers after updating recently.

"Unknown exception in headURL https://www.usenet-crawler.com/getnzb/abe8514e04ea4c4d04eb5fe85f1001d0.nzb&i=26944&r=**********"

**Comment by fonix99** [comment] 2015-07-01 13:23
There is a very long "Issu" thread I opened some days ago. https://github.com/SiCKRAGETV/sickrage-issues/issues/1852

U need to downgrade to version 4.0.26 - that was the latest one, which worked for us with that kind of ssl-problem (don't know the exact background why it was working than but not working now, guess some updates who had to be done, but causes other problems for some kind of users like us).

**Comment by annabellor** [comment] 2015-07-01 22:38
I have the same issue and I did what @fonix99 did, downgrade to tag v4.0.26 and it worked again. The master branch was not working for me, I was getting the same error as @grooves12 and @fonix99 .

I have Sickrage installed on a qnap 419p II

**Comment by fernandog** [comment] 2015-07-01 23:22
We have a huge subtitle problem now. Will get back to this soon

**Comment by bouwew** [comment] 2015-07-09 16:08
FYI, I managed to install pyopenssl on my QNAP TS-419P.
You need to have Optware installed and enabled.

Enter at the command prompt:

easy_install-2.7 pip
ipkg update
ipkg install gcc
ipkg install openssl-dev
/opt/local/bin/pip2.7 install -U setuptools pip pyopenssl==0.13.1

After that I receive the message: "Successfully installed pyopenssl-0.13.1".

**Comment by neoatomic** [comment] 2015-07-09 16:49
@bouwew Thanks for letting us know how to install it on QNAP. :) 

@fernandog Maybe add it to the Wiki.?

**Comment by bouwew** [comment] 2015-07-10 07:28
Unfortunately, I still see the "Unknown exception in headURL" in the log :(

**Comment by bouwew** [comment] 2015-07-10 07:42
SR Version:	BRANCH: (master) / COMMIT: (ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8) 

Parts of my log:

[/code]2015-07-10 09:17:15 INFO     SEARCHQUEUE-BACKLOG-255326 :: No needed episodes found during backlog search for: [Defiance]
2015-07-10 09:16:45 INFO     SEARCHQUEUE-BACKLOG-255326 :: [AutoNZB] :: Performing episode search for Defiance
2015-07-10 09:16:45 INFO     SEARCHQUEUE-BACKLOG-255326 :: Skipping Defiance.S03E04.720p.HDTV.x264-2HD, URL check failed. Bad result from provider.
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('HEAD', url, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 496, in head
AA    resp = session.head(url, timeout=timeout)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1343, in headURL
2015-07-10 09:16:45 WARNING  SEARCHQUEUE-BACKLOG-255326 :: Traceback (most recent call last):
2015-07-10 09:16:45 WARNING  SEARCHQUEUE-BACKLOG-255326 :: Unknown exception in headURL https://api.oznzb.com/getnzb/2ced0a7bba8b935d2471b33b45eec7a5.nzb&i=52194&r=**********

**Comment by fonix99** [comment] 2015-07-10 21:01
Thanks for your guide bouwew, worked great. But like u I still getting the warning message with the latest master. 

So I have to stick with v4.0.26...

**Comment by miigotu** [comment] 2015-07-11 01:18
@fonix99 if you update to latest master, and change line 1308 from:
```python
session.verify = certifi.where()
```
to:
```python
session.verify = False
```

And then delete cache/sessions/*

Does it work? I might need to make this option configurable.

**Comment by fernandog** [comment] 2015-07-11 01:27
Or fallback?

**Comment by miigotu** [comment] 2015-07-11 01:31
@fernandog I would like to make it automatically fall back, but users should be able to choose if they want to accept non-verified ssl connections. There are too many situations where one would absolutely not want to allow this without prior investigation.

**Comment by fernandog** [comment] 2015-07-11 01:40
So an option to "auto fallback to non-verified" - default off ?

**Comment by miigotu** [comment] 2015-07-11 01:48
Maybe we can make it default to on, and always log a warning when it is falling back about to disable it they need to change it in config.ini (probably doesnt need to be a gui option)

Another (probably better option) is this:

Properly catch the error in order to have some statistics about which urls are throwing this errror. I know that womble has this problem (fake/self-signed certificate)

If we get the certificates for these self signed providers, we can add the certificate to our ca_certs, and it will verify properly without falling back.

**Comment by fernandog** [comment] 2015-07-11 02:21
Agree with the better option.

**Comment by garfin-au** [comment] 2015-07-15 08:58
Hi, I believe i'm having same issue.. latest master on debian server. 

noob question.. how do i roll back to 4.0.26 , and/or what file is the file that I am change line 1308 
from: 
session.verify = certifi.where()
to:
session.verify = False

??

**Comment by miigotu** [comment] 2015-07-15 09:00
@garfin-au In newest master you can change it in config/general on the advanced tab.

**Comment by garfin-au** [comment] 2015-07-15 09:05
Verify SSL Certificates (Disable this for broken SSL installs (Like QNAP)

This? unticked, restarted, same issue.. Grrr.

**Comment by miigotu** [comment] 2015-07-15 09:09
@garfin-au I doubt you are having the same issue. This issue is fixed on latest master/develop and had nothing to do with ssl.verify anyways.

**Comment by garfin-au** [comment] 2015-07-15 09:31
Oh,ok.. if it makes more sense, move my chatter to a new bug/issue ?

```
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/opt/SickRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/opt/SickRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/opt/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/opt/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/opt/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/opt/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/opt/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/opt/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/opt/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('HEAD', url, **kwargs)
AA  File "/opt/SickRage/lib/requests/sessions.py", line 496, in head
AA    resp = session.head(url, timeout=timeout, allow_redirects=True)
AA  File "/opt/SickRage/sickbeard/helpers.py", line 1336, in headURL
2015-07-15 17:42:14 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Traceback (most recent call last):
2015-07-15 17:42:14 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Unknown exception in headURL https://xyzzy.info/getnzb/fbb554cfb69c7894e20d52463c6114f2.nzb&i=13&r=**********
2015-07-15 17:42:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Quality of Counting.Cars.S04E17.A.Legend.on.Two.Wheels.720p.HDTV.x264-DHD is HDTV
2015-07-15 17:42:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Found result Counting.Cars.S04E18.Black.White.and.Hotrod.All.Over.720p.HDTV.x264-DHD at https://xyzzy.info/getnzb/c156b9ad8f3c98c8ea589d40f4ac61ba.nzb&i=13&r=**********
2015-07-15 17:42:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Found result Counting.Cars.S04E17.A.Legend.on.Two.Wheels.720p.HDTV.x264-DHD at https://xyzzy.info/getnzb/fbb554cfb69c7894e20d52463c6114f2.nzb&i=13&r=**********
2015-07-15 17:42:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [xyzzy] :: Skipping Counting.Cars.S04E18.Black.White.and.Hotrod.All.Over.720p.HDTV.x264-DHD, URL check failed. Bad result from provider.
```

**Comment by miigotu** [comment] 2015-07-15 09:34
install pyOpenSSL

**Comment by garfin-au** [comment] 2015-07-15 10:04
```
apt-get install python-openssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-openssl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.
```
Updated & confirmed.. but same story.

**Comment by miigotu** [comment] 2015-07-15 10:35
`82 not upgraded`
Also, the recommended method is to remove python-openssl, and install python-pip, then `sudo pip install -U pyopenssl==0.13.1`
Not sure which version of ubuntu/debian you are using, but I am using ubuntu gnome trusty (and previously debian jessie) and it works just fine.

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by garfin-au** [comment] 2015-07-15 10:52
I'm on debian squeeze.. its always just worked, never saw a need to 
upgrade/change. I'll update the 82 firstly, and pray i dont fix one 
issue and cause another... deb box hosts a number of things, not just 
SiCKRAGE..
if thats still a no go.. i guess i'll have to try to remove 
python-openssl, and install python-pip, then sudo pip install -U 
pyopenssl==0.13.1  :|

------ Original Message ------

**Comment by garfin-au** [comment] 2015-07-15 11:07
```
OpenSSL/crypto/crypto.c:886: warning: implicit declaration of function ‘init_crypto_netscape_spki’

OpenSSL/crypto/crypto.c:888: warning: implicit declaration of function ‘init_crypto_crl’

OpenSSL/crypto/crypto.c:890: warning: implicit declaration of function ‘init_crypto_revoked’

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools; __file__='/root/build/pyopenssl/setup.py'; execfile('/root/build/pyopenssl/setup.py')" install --single-version-externally-managed --record /tmp/pip-JjtOut-record/install-record.txt failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/pip/basecommand.py", line 120, in main
    self.run(options, args)
  File "/usr/lib/pymodules/python2.6/pip/commands/install.py", line 165, in run
    requirement_set.install(install_options)
  File "/usr/lib/pymodules/python2.6/pip/req.py", line 1243, in install
    requirement.install(install_options)
  File "/usr/lib/pymodules/python2.6/pip/req.py", line 540, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/pymodules/python2.6/pip/__init__.py", line 226, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command /usr/bin/python -c "import setuptools; __file__='/root/build/pyopenssl/setup.py'; execfile('/root/build/pyopenssl/setup.py')" install --single-version-externally-managed --record /tmp/pip-JjtOut-record/install-record.txt failed with error code 1
```

last few lines from pip.log after what appears to be a failed install.

**Comment by garfin-au** [comment] 2015-07-15 11:09
...and yet SR has just snatched the backlog of shows , YAY ! i think.. :?

**Comment by miigotu** [comment] 2015-07-15 11:25
Should be OK, but SSL verify won't work without the crypto extension, so I would make sure its unchecked.

**Comment by garfin-au** [comment] 2015-07-15 11:50
Thanks for all your help... I'll monitor a little closer than normal for the next few days and ensure it behaves.

**Closed** 2015-07-15 11:51 UTC
Labels: 1: Bug / issue, 2: Low Priority

**Comment by miigotu** [comment] 2015-07-15 11:53
Alternatively, you could:
```bash
sudo apt-get install build-essential libffi-dev python-dev
sudo pip uninstall pyopenssl
sudo pip install -U pyopenssl==0.13.1
```
That should build in the crypto extension.

**Comment by bartley69** [comment] 2015-07-21 08:57
Any anyone able to link me with the optware.ipkg?

I cannot find it in the qnap app store or anywhere else online.

**Comment by bartley69** [comment] 2015-07-29 10:07
Bump, anyone?

**Comment by bouwew** [comment] 2015-07-31 14:16
@bartley69, you need to install Python 2.7 on your QNAP first. You can find it in Developer Tools.
Once you have done that, you must issue the 5 commands I listed in my post, one by one.

**Comment by bartley69** [comment] 2015-08-01 04:05
@bouwew, everything goes sweet until I execute the last command - /opt/local/bin/pip2.7 install -U setuptools pip pyopenssl==0.13.1

I am greeted with the following error - -sh: /opt/local/bin/pip2.7: No such file or directory

<pre>
login as: admin
admin@192.168.0.12's password:
[~] # ipkg update
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /Packages.gz
Inflating http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable/P                                                                                                                               ackages.gz
Updated list of available packages in /opt/lib/ipkg/lists/cs08q1armel
Successfully terminated.
[~] # ipkg install gcc
Installing gcc (4.2.3-1) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /gcc_4.2.3-1_arm.ipk
Installing binutils (2.19.1-1) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /binutils_2.19.1-1_arm.ipk
Installing libc-dev (2.5-5) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /libc-dev_2.5-5_arm.ipk
Installing libnsl (2.5-4) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /libnsl_2.5-4_arm.ipk
Configuring binutils
update-alternatives: Linking //opt/bin/strings to /opt/bin/binutils-strings
Configuring gcc
Configuring libc-dev
Configuring libnsl
Successfully terminated.
[~] # ipkg install openssl-dev
Installing openssl-dev (0.9.8v-2) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /openssl-dev_0.9.8v-2_arm.ipk
Installing openssl (0.9.8v-2) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable                                                                                                                               /openssl_0.9.8v-2_arm.ipk
Configuring openssl
Configuring openssl-dev
Successfully terminated.
[~] # /opt/local/bin/pip2.7 install -U setuptools pip pyopenssl==0.13.1
-sh: /opt/local/bin/pip2.7: No such file or directory
[~] #
</pre>

Any ideas?

**Comment by miigotu** [comment] 2015-08-01 06:40
try just `pip2.7 install -U setuptools pip pyopenssl==0.13.1` or `pip install -U setuptools pip pyopenssl==0.13.1`

**Comment by bartley69** [comment] 2015-08-01 06:44
<pre>login as: admin
admin@192.168.0.12's password:
[~] # pip2.7 install -U setuptools pip pyopenssl==0.13.1
-sh: pip2.7: command not found
[~] # pip install -U setuptools pip pyopenssl==0.13.1
-sh: pip: command not found
[~] #
</pre>

**Comment by miigotu** [comment] 2015-08-01 06:54
You need to install pip.

This might work:
`ipkg install python-pip`

**Comment by bartley69** [comment] 2015-08-01 07:09
<pre>
login as: admin
admin@192.168.0.12's password:
[~] # ipkg install python-pip
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package python-pip.
Check the spelling or perhaps run 'ipkg update'
[~] #
</pre>

**Comment by miigotu** [comment] 2015-08-01 08:06
Possible solution below, but first you must read my rant.

You really should try to solve your problem by yourself before asking us to do your googling for you. We don't have ant of this specialized hardware, so you instantly have an advantage over us for figuring this out.

If I can figure out a potential solution in 30 seconds by googling then you should be able to do it quicker than it is for me to reply. Honestly, it's annoying when typing a response and instructions take like 5 minutes for information found in 30 seconds of searching.

try this command first:
`ipkg install python27 py27-setuptools`

then try these until one works:
`easy_install2.7 pip`
or
`easy_install pip`

then:

`pip2.7 install -U setuptools pip pyopenssl==0.13.1`
or
`pip install -U setuptools pip pyopenssl==0.13.1`

Again, you are the one with the hardware, so search first about the hardware.

**Comment by bouwew** [comment] 2015-08-01 08:10
Type the following to find the exact path of the pip2.7-application on your NAS:

find / -name pip2.7 -print

Then type this full path on the command-line, followed by:

install -U setuptools pip pyopenssl==0.13.1

**Comment by miigotu** [comment] 2015-08-01 08:13
btw, Don't take my rant as me being a dick. I don't mind helping people who try to help themselves, but I'm not tech support for your nas =P

I would rather spend an hour coding and helping ALL of SR users at once (by coding) than answer one persons question about the same topic 20 times.

**Comment by bartley69** [comment] 2015-08-01 13:28
This did the trick!
<pre>
ipkg install python27 py27-setuptools
easy_install-2.7 pip
/opt/local/bin/pip2.7 install -U setuptools pip pyopenssl==0.13.1
</pre>

All good miigotu, I know I should try harder. I have been trying to solve this issue but I have been finding it difficult to solve. I have been a windows user my entire life up until I got this NAS. This has been my first ever experience with linux and I am extremely new to it. I know I don't understand basic things but I'm trying to get up to speed. Apologies for bugging you guys, I can understand your frustrations. I absolutely don't take it personally man, I would probably get annoyed too at some bloke asking questions which to you, seem rather easy :P I really appreciate what you, and the fellow developers do for all of us. I hope you do feel some appreciation for the work that you do because it really is incredible. I freaking love the software and it seems to get better every update. Thanks again mate.
