### ISSUE TITLE
Can't download torrents using torcache - Failed to send torrents to all clients

### ISSUE THREAD

**Issue by belialboy** [SiCKRAGETV/sickrage-issues#1932] opened 2015-06-29 19:28 UTC
So I'm running SiCKRAGE (BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)) on my QNAP TS-451 (f/w 4.1.4 Build 20150522). Torrents that SiCKRAGE finds it is poking to Transmission (v2.84-b23) via RPC (Which is confirmed with the test as "Success: Connected and Authenticated"), but very recently that's all fallen over in a heap. I haven't changed any settings, but I'm now seeing log entries like below:

    AA. Error: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
    AARelease Group: KILLERS[rarbg]
    AASize: 917386042
    AAName: Dig.S01E02.720p.HDTV.x264-KILLERS[rarbg]
    AAQuality: HDTV
    AAEpisode: [<sickbeard.tv.TVEpisode object at 0x9a326cc>]
    AAExtra Info:
    AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
    AA    return codecs.utf_8_decode(input, errors, True)
    AA  File "/opt/lib/python2.7/encodings/utf_8.py", line 16, in decode
    AA    message = meThread + u" :: " + msg
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/logger.py", line 133, in log
    AA    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 160, in _get_torrent_hash
    AA    result = self._get_torrent_hash(result)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 186, in sendTORRENT
    AATraceback (most recent call last):
    2015-06-29 20:12:27 ERROR    SEARCHQUEUE-BACKLOG-275278 :: Transmission: Failed Sending Torrent
    AABTFailure: not a valid bencoded string
    AA    raise BTFailure("not a valid bencoded string")
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/lib/bencode/bencode.py", line 68, in bdecode
    AA    torrent_bdecode = bdecode(result.content)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 157, in _get_torrent_hash
    AATraceback (most recent call last):
    2015-06-29 20:12:27 ERROR    SEARCHQUEUE-BACKLOG-275278 :: Unable to bdecode torrent
    AA
    2015-06-29 20:12:22 INFO     SEARCHQUEUE-BACKLOG-275278 :: Downloading Dig.S01E02.720p.HDTV.x264-KILLERS[rarbg] from KickAssTorrents
    AA. Error: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
    AARelease Group: ABH[rarbg]
    AASize: 1379847402
    AAName: DIG.S01E09.Jehoshaphat.720p.WEB-DL.DD5.1.H.264-ABH[rarbg]
    AAQuality: 720p WEB-DL
    AAEpisode: [<sickbeard.tv.TVEpisode object at 0xf1e28eec>]
    AAExtra Info:
    AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
    AA    return codecs.utf_8_decode(input, errors, True)
    AA  File "/opt/lib/python2.7/encodings/utf_8.py", line 16, in decode
    AA    message = meThread + u" :: " + msg
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/logger.py", line 133, in log
    AA    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 160, in _get_torrent_hash
    AA    result = self._get_torrent_hash(result)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 186, in sendTORRENT
    AATraceback (most recent call last):
    2015-06-29 20:12:20 ERROR    SEARCHQUEUE-BACKLOG-275278 :: Transmission: Failed Sending Torrent
    AABTFailure: not a valid bencoded string
    AA    raise BTFailure("not a valid bencoded string")
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/lib/bencode/bencode.py", line 68, in bdecode
    AA    torrent_bdecode = bdecode(result.content)
    AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 157, in _get_torrent_hash
    AATraceback (most recent call last):
    2015-06-29 20:12:20 ERROR    SEARCHQUEUE-BACKLOG-275278 :: Unable to bdecode torrent
    AA
    2015-06-29 20:12:12 INFO     SEARCHQUEUE-BACKLOG-275278 :: Downloading     DIG.S01E09.Jehoshaphat.720p.WEB-DL.DD5.1.H.264-ABH[rarbg] from KickAssTorrents
    2015-06-29 20:12:12 INFO     SEARCHQUEUE-BACKLOG-275278 :: Quality of Dig.S01E02.720p.HDTV.x264-KILLERS[rarbg] is HDTV
    2015-06-29 20:12:12 INFO     SEARCHQUEUE-BACKLOG-275278 :: Quality of Dig.S01E09.720p.HDTV.x264-KILLERS[rarbg] is HDTV
    2015-06-29 20:12:11 INFO     SEARCHQUEUE-BACKLOG-275278 :: Quality of DIG.S01E09.Jehoshaphat.720p.WEB-DL.DD5.1.H.264-ABH[rarbg] is 720p WEB-DL
    2015-06-29 20:12:05 INFO     SEARCHQUEUE-BACKLOG-275278 :: [KickAssTorrents] :: Performing episode search for DIG
    2015-06-29 20:12:05 INFO     SEARCHQUEUE-BACKLOG-275278 :: Building internal name cache for DIG
    2015-06-29 20:12:05 INFO     SEARCHQUEUE-BACKLOG-275278 :: Beginning backlog search for: [DIG]`
Now I've seen the bdecode errors before, and so I switched my torrent searches to just kat... but now I'm seeing them again, and I can't tell if it's Transmission or SiCKRAGE that's causing the issue. Certainly Transmission is downloading other torrents, so I'm asking the SiCKRAGE community if this is a known issue? (Can't see anything in the boards...) (I'm happy to be proved wrong, FTR!)

**Comment by fernandog** [comment] 2015-06-30 11:52
disable all proxies: global (proxy host setting) and provider

**Comment by fernandog** [comment] 2015-06-30 16:18
https://github.com/SiCKRAGETV/sickrage-issues/issues/1940

**Comment by belialboy** [comment] 2015-07-01 18:15
Ok, I've confirmed that the global proxy setting was off anyway and have turned off the torrent search provider proxy. But am now getting another (similar) error:

`  2015-07-01 19:04:25 ERROR    SEARCHQUEUE-MANUAL-292174 :: Transmission: Failed Sending Torrent
`
`  AA</html>
`
`  AA</body>
`
`  AA</script>
`
`  AA})();
`
`  AA       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
`
`  AA       sc.src = document.location.protocol + '//s.torcache.net/sc.js';
`
`  AA      var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
`
`  AA(function() {
`
`  AA_scq.push(['load']);
`
`  AA_scq.push(['addSlot', '_47ec71d7b7be19d934c4ddbefc0aa90c']);
`
`  AA_scq.push(['setAccount', '_d0b70e33563de9bece3faa2ee3558e1e']);
`
`  AA_scq.push(['setHost', 's.torcache.net']);
`
`  AA_scq.push(['setDebug', false]);
`
`  AAvar _scq = _scq || [];
`
`  AA<script type="text/javascript">
`
`  AA<div id="_47ec71d7b7be19d934c4ddbefc0aa90c"></div>
`
`  AA	</div> 
`
`  AA		</div>
`
`  AA
`
`  AA</center>
`
`  AA	<p>You can use <a title="Magnet link" href="magnet:?xt=urn:btih:7681ADEE289E4DF66E12369D966A2390D710B85E&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.ccc.de%3A80" onclick="_gaq.push(['_trackEvent', 'Download', 'Magnet Link']);">magnet link</a> to download.</p>
`
`  AA<center>
`
`  AA</script>
`
`  AA    setTimeout(function () { window.location = 'http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent'; }, 5000);
`
`  AA<script type="text/javascript" charset="utf-8">
`
`  AA<center>Your <a href="http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent">torrent file</a> download will start in a few seconds...</center>
`
`  AA
`
`  AA</center>
`
`  AA</script>
`
`  AA  _scq.push(['addSlot', '_801a36d4e167c7184d4c696d2e103004']);
`
`  AA  var _scq = _scq || [];
`
`  AA<script type="text/javascript">
`
`  AA<div id="_801a36d4e167c7184d4c696d2e103004"></div>
`
`  AA<center>
`
`  AA<br />
`
`  AA			<h2>Torcache is a free service for caching torrent files online.</h2>
`
`  AA			<h1> Downloading... </h1>
`
`  AA		<div class="row-fluid">
`
`  AA	<div class="container-fluid">
`
`  AA	</div></div>
`
`  AA		</div>
`
`  AA			</div>
`
`  AA													</ul>
`
`  AA					<li><a href="/api"><i class="icon-wrench icon-white"></i> API</a></li>
`
`  AA									<li class="active"><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
`
`  AA				<ul class="nav">
`
`  AA			<div class="nav-collapse">
`
`  AA			<a class="brand" href="/">Torcache</a>
`
`  AA		<div class="container-fluid">
`
`  AA	<div class="navbar navbar-fixed-top"><div class="navbar-inner">
`
`  AA<body>
`
`  AA	</head>
`
`  AA	<link href="http://torcache.net/css/main.css" media="all" type="text/css" rel="stylesheet">
`
`  AA<script src="http://torcache.net/bundles/bootstrapper/js/bootstrap.min.js"></script>
`
`  AA	<script src="http://torcache.net/bundles/bootstrapper/js/jquery-1.8.0.min.js"></script>
`
`  AA<link href="http://torcache.net/bundles/bootstrapper/css/bootstrap-responsive.min.css" media="all" type="text/css" rel="stylesheet">
`
`  AA<link href="http://torcache.net/bundles/bootstrapper/css/nav-fix.css" media="all" type="text/css" rel="stylesheet">
`
`  AA	<link href="http://torcache.net/bundles/bootstrapper/css/bootstrap.min.css" media="all" type="text/css" rel="stylesheet">
`
`  AA	<title>Torcache - Torrent Cache</title>
`
`  AA	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
`
`  AA<head>
`
`  AA<html lang="en">
`
`  AABTFailure: not a valid bencoded string
`
`  AA    raise BTFailure("not a valid bencoded string")
`
`  AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/lib/bencode/bencode.py", line 68, in bdecode
`
`  AA    torrent_bdecode = bdecode(result.content)
`
`  AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/sickbeard/clients/generic.py", line 157, in _get_torrent_hash
`
`  AATraceback (most recent call last):
`
`  2015-07-01 19:04:25 ERROR    SEARCHQUEUE-MANUAL-292174 :: Unable to bdecode torrent
`
`  AA
`
`  2015-07-01 19:04:24 INFO     SEARCHQUEUE-MANUAL-292174 :: Downloading Dark.Matter.S01E03.720p.WEB-DL.DD5.1.H.264-ECI[rarbg] from KickAssTorrents
`
`  2015-07-01 19:04:24 INFO     SEARCHQUEUE-MANUAL-292174 :: Quality of Dark.Matter.S01E03.720p.HDTV.HEVC.x265-RMTeam.[720P][HEVC] is HDTV
`
`  2015-07-01 19:04:24 INFO     SEARCHQUEUE-MANUAL-292174 :: Quality of Dark.Matter.S01E03.720p.HDTV.x264-KILLERS is HDTV
`
`  2015-07-01 19:04:24 INFO     SEARCHQUEUE-MANUAL-292174 :: Quality of Dark.Matter.S01E03.SPANISH.ESPAÑOL.720p.HDTV.x264-NEWPCT is HDTV
`
`  2015-07-01 19:04:24 INFO     SEARCHQUEUE-MANUAL-292174 :: Quality of Dark.Matter.S01E03.720p.HDTV.x264-KILLERS[rartv] is HDTV
`
`  2015-07-01 19:04:23 INFO     SEARCHQUEUE-MANUAL-292174 :: Quality of Dark.Matter.S01E03.720p.WEB-DL.DD5.1.H.264-ECI[rarbg] is 720p WEB-DL
`
`  2015-07-01 19:04:19 INFO     SEARCHQUEUE-MANUAL-292174 :: [KickAssTorrents] :: Performing episode search for Dark Matter
`
`  2015-07-01 19:04:19 INFO     SEARCHQUEUE-MANUAL-292174 :: Building internal name cache for Dark Matter
`
`  2015-07-01 19:04:19 INFO     SEARCHQUEUE-MANUAL-292174 :: Beginning manual search for: [Dark Matter - 1x03 - Episode Three]`

Which it occurs to me is _not_ downloading the torcache torrent file. Don't think this is duplicate FTR.

**Comment by fernandog** [comment] 2015-07-01 18:17
@miigotu seems torcache added "download will start in a few seconds..."

**Comment by fernandog** [comment] 2015-07-01 18:20
@miigotu maybe we can use regex to get the direct URL to download:

```
{ window.location = 'http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent'; }
```

**Comment by miigotu** [comment] 2015-07-01 19:27
@fernandog Yes I saw that before. Don't have time to mess with it now subtitles are being a pain in my ass. I pass the same values to the same functions inside SR and no subs DL, but in subliminal CLI it works, I added debug lines and my args generate the same parameters passed to he same function~ wtf.

**Comment by fernandog** [comment] 2015-07-01 19:37
@belialboy please do:
stop SR
edit SickRage/sickbeard/providers/generic.py
delete line 57: 'http://torcache.net/torrent/' + torrent_hash + '.torrent',
save
start SR
try again please

**Comment by fernandog** [comment] 2015-07-01 19:51
@miigotu why don't you ask Diaoul/subliminal for help?

**Comment by belialboy** [comment] 2015-07-01 20:52
Do you mean line 154?

`149                 if not torrent_hash:`
`150                     logger.log("Unable to extract torrent hash from link: " + ex(result.url), logger.ERROR)`
`151                     return (urls, filename)`
`152`
`153                 urls = [`
`154                     'http://torcache.net/torrent/' + torrent_hash + '.torrent',`
`155                     'http://zoink.ch/torrent/' + torrent_name + '.torrent',`
`156                     'http://torrage.com/torrent/' + torrent_hash + '.torrent',`
`157                 ]`
`158             except:`
`159                 urls = [result.url]`
`160         else:`
`161             urls = [result.url]`

I've now done this... And it's now working! Whoop! Thanks guys.

Making and exception for torcache handling does seems a little annoying. I don't write python; if I did I'd help out to fix it. Sorry.

**Comment by fernandog** [comment] 2015-07-01 21:16
Ive alrerady PRed to develop. Wait to be on master.

**Comment by miigotu** [comment] 2015-07-02 09:15
@fernandog Just removing torcache from the bt cache providers won't solve this issue, as some providers give torcache links directly from their json/html (kickass ?)

What happens if we catch this result, and then request it again using the same session in 5 seconds (after the timer is up)?

**Comment by fernandog** [comment] 2015-07-02 12:10
https://github.com/SiCKRAGETV/sickrage-issues/issues/1954

**Comment by fernandog** [comment] 2015-07-02 12:11
@miigotu but how to do that only to torcache? If provider has the getURL def we have to change all providers and the getURL in generic. any other solution?

**Comment by fernandog** [comment] 2015-07-02 12:14
https://github.com/SiCKRAGETV/sickrage-issues/issues/1955

**Comment by fernandog** [comment] 2015-07-02 21:51
https://github.com/SiCKRAGETV/sickrage-issues/issues/1958

**Comment by miigotu** [comment] 2015-07-03 02:35
`If provider has the getURL def we have to change all providers and the getURL in generic. any other solution?`

@fernandog If a provider has a getURL defined it still needs rewritten, as all of them need to use the one in generic.py or it isn't handled properly for caching.

**Comment by miigotu** [comment] 2015-07-03 03:47
@fernandog I need to understand better what triggers the js timer. Flood protection/rate limit? If it is just 
```
if time_since_last_request < 5:
    trigger_timer
```

Thats easy to fix.

If it is something like this:

```
if num_requests_in_(some amount of time) > some_number and time_last_request < 5:
    trigger timer
```

Its a little more difficult, since we don't know the variables that trigger it.

Maybe it is just a random trigger, or 
```
if num_requests in forever > some_number:
    trigger_timer
```

I think it definitely has something to do with the number of requests, as we definitely hit it once per search result with headURL and a delay in between. HTTP HEAD really doesn't use any resources/bandwidth on either end, which is why I switched to it. I'm pretty sure they just limit number of requests per minute or something to prevent spiders/scrapers from scraping their whole DB (DMCA ppl)

Can anyone find a way to contact the administrators/owners of torcache?

**Comment by abeloin** [comment] 2015-07-03 07:57
@fernandog Without full requests debug log it is difficult to see what is causing the issue in this case, but I would suggest checking the referer string in the request made by SR when requesting the torrent file. My guess is that it's not empty and that is triggering the webpage:

This trigger the webpage
```
curl -L -j -v --referer "https://kat.cr" --user-agent "Mozilla/4.0" http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent
```

But not this:
```
curl -L -j -v --user-agent "Mozilla/4.0" http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent
```

**Comment by miigotu** [comment] 2015-07-03 08:19
@abeloin thanks for finding a way to trigger the timer.

I did just add a commit that removes Content-Type header from get and head requests, since it is only valid for post and put requests. This is exactly where I started looking was in our passed headers xD.

I can pop referrer if the url matches `r'http(s)?://torcache.net.*'` if we verify this is the cause, but I haven't seen any referrer set in the headers when i `print vars(session.headers)`

The only time I have seen referrer set is when a proxy is used:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/generic.py#L139
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/generic.py#L194

From a quick find and grep:

```
./sickbeard/tvcache.py:143:            self.provider.headers.update({'Referer': self.provider.proxy.getProxyURL()})
./sickbeard/providers/generic.py:139:            self.headers.update({'Referer': self.proxy.getProxyURL()})
./sickbeard/providers/generic.py:194:            self.headers.update({'Referer': self.proxy.getProxyURL()})
./lib/subliminal/providers/addic7ed.py:201:        r = self.session.get(self.server + subtitle.download_link, timeout=10, headers={'Referer': subtitle.page_link})
./lib/feedparser/feedparser.py:2764:        request.add_header('Referer', referrer)
```

**Comment by miigotu** [comment] 2015-07-03 08:21
This works great lol:
`curl -L -j -v --referer "http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent" --user-agent "Mozilla/4.0" http://torcache.net/torrent/7681ADEE289E4DF66E12369D966A2390D710B85E.torrent`

**Comment by abeloin** [comment] 2015-07-03 09:07
>  but I haven't seen any referrer set in the headers when i print vars(session.headers)
I don't have a machine to test on but have you tried to set the Glypeproxy on and then off to see if the referer is still set?

**Comment by miigotu** [comment] 2015-07-03 10:28
Hmm, would make sense since I actually make the sessions persist now and caching is actually working for all calls to getURL. Updating cachecontrol and all the changes I made helped so much, just little things still popping up like this since then.

**Comment by miigotu** [comment] 2015-07-03 12:08
@abeloin You think I should pop the referer if not using proxy, or set the referer to the base of the url we are calling?

popping is what normal spec behavior should be, but setting the referrer to the domain we are calling to will most likely bypass the timers and any hotlinking detection, not just for torcache but also other sites.

**Comment by abeloin** [comment] 2015-07-03 19:16
@miigotu Clearing the value is, I think, the best choice as requests doesn't add referer by default.

**Comment by miigotu** [comment] 2015-07-03 20:55
@abeloin 
https://github.com/SiCKRAGETV/SickRage/commit/ddffe6516fe448c27f5b357f784e4a54ff9f1daf

It still wont work with proxy, because we have to se referer or proxy doesnt work.

**Comment by abeloin** [comment] 2015-07-04 00:29
@miigotu It should work when we set the referer for the glypheproxy as it is the proxy who does the request and they don't put any referer as far as I know.

I will try it with a small script(I wish I had my development machine it would have taken 5 mins to test!)

**Comment by miigotu** [comment] 2015-07-04 01:05
@abeloin I think they leave the referer header intact, because if I use proxy it fails 100%, without proxy 100% success. Also, before the referer header was not being removed when proxy was once enabled and then disabled, it now does.

Maybe we should try the request without adding referer, even with proxy enabled, then fall back to handling the page that says we cant hotlink if it triggers, and then also fall back and handle the glyphe ssl warning?

Maybe some combination of head requests can tell us info we need without actually requesting the url up to 3 times? Any header links returned in the hotlink trigger or or glyphe ssl warning? I can test eventually, just so many different things on my list atm lol.

**Comment by abeloin** [comment] 2015-07-04 02:02
@miigotu Do you have the requests log when it fail?

If not try merging the code below(part of the script I used to test this issue) into logger.py:
```
import logging
import requests

# These two lines enable debugging at httplib level (requests->urllib3->http.client)
# You will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# The only thing missing will be the response.body which is not logged.
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

# You must initialize logging, otherwise you'll not see debug output.
logging.basicConfig() 
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

s = requests.Session()
s.get('http://radio-canada.ca')
```
The try and requests.packages.urllib3 should be enough to produce enough data.

Also you should check the answer returned, as mine was returned gziped even if I didn't ask for it(set to none).

No worries I do understand, so many things to do and only 24 hours in a day! ;)

**Comment by fernandog** [comment] 2015-07-06 12:03
https://github.com/SiCKRAGETV/SickRage/commit/ddffe6516fe448c27f5b357f784e4a54ff9f1daf

**Comment by miigotu** [comment] 2015-07-06 12:57
It's fixed in develop fernandog, as long as they don't have a proxy set. Maybe down the road we can fix it with proxy too, but for now its ok.

**Closed** 2015-07-06 13:01 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
