### ISSUE TITLE
SR invalid torrent

### ISSUE THREAD

**Issue by loungebob** [SiCKRAGETV/sickrage-issues#2793] opened 2015-09-13 14:02 UTC
Not sure if SR is the culprit or if it lies somewhere else but since that whole not being able to update, multiple notifications windows and no show images/banners SR puts torrent files in my blackhole that are not valid.

Windows 10 10532 x64
BRANCH: (master) / COMMIT: (e1e4c284e10f13cebf4277bbd6924d6d5085d1ce)

SR downloads the torrent upon finding the ep and deposits it into the blackhole directory. qbittorrent ignores it saying:
```
13.09.2015 15:50:44 - This file is either corrupted or this isn't a torrent.
13.09.2015 15:50:44 - Unable to decode torrent file: 'G:\__PROCESSING\BT\Blunt.Talk.S01E04.HDTV.x264-BATV[ettv].torrent'
```
```
SR logs show this: 
2015-09-13 15:47:52 WARNING  SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Failed to download any results
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Downloading a result from KickAssTorrents at http://btdig.com/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent
2015-09-13 15:47:52 WARNING  SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Could not download http://torcache.net/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Downloading a result from KickAssTorrents at http://torcache.net/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Downloading a result from KickAssTorrents at http://thetorrent.org/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Downloading Blunt.Talk.S01E04.HDTV.x264-BATV[ettv] from KickAssTorrents
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Quality of Blunt.Talk.1x04.(HDTV-x264-BATV)[VTV] is SDTV
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Quality of Blunt.Talk.S01E04.HDTV.x264-BATV[rartv] is SDTV
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Quality of Blunt.Talk.S01E04.HDTV.x264-BATV[ettv] is SDTV
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Ignoring result Blunt.Talk.S01E04.720p.HDTV.x264-BATV[rartv] because we don't want an episode that is 720p HDTV
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: [KickAssTorrents] :: Performing episode search for Blunt Talk
2015-09-13 15:47:52 INFO     SEARCHQUEUE-BACKLOG-281181 :: Beginning backlog search for: 
```
[Blunt Talk]

Even though it states no download, there is still a torrent file in the blackhole dir with the appropriate name (in this case the blunt talk one) but it seems corrupt. 
When I download it manually from KAT, it works just fine.

Any ideas?

PS: it happened on a couple of files, Gogglebox, Blunt Talk, Continuum. And some download ok and just add to the torrent client ok. Also, all of them load ok when downloaded manually from KAT (which is my only configured source).

**Comment by neoatomic** [comment] 2015-09-13 15:42
@loungebob Check if there are any updates and update if necessary.  
The posters/banners are working again. Do an force full update for the show, or go to mass-update and update all shows there.

**Comment by loungebob** [comment] 2015-09-13 19:23
@neoatomic thanks but not looking at posters/banners anymore, they're fine, as you mentioned.

looked into my issue with the invalid torrents file produced by SR and turns out, SR downloads the waiting page (the html info page) instead of the torrent and magnet files the page supplies after a couple of seconds waiting. I've never had this issue before.

Here's what SR saves as a .torrent file in the blackhole directory:

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Torcache - Torrent Cache</title>
	<link href="http://torcache.net/bundles/bootstrapper/css/bootstrap.min.css" media="all" type="text/css" rel="stylesheet">
<link href="http://torcache.net/bundles/bootstrapper/css/nav-fix.css" media="all" type="text/css" rel="stylesheet">
<link href="http://torcache.net/bundles/bootstrapper/css/bootstrap-responsive.min.css" media="all" type="text/css" rel="stylesheet">
	<script src="http://torcache.net/bundles/bootstrapper/js/jquery-1.8.0.min.js"></script>
<script src="http://torcache.net/bundles/bootstrapper/js/bootstrap.min.js"></script>
	<link href="http://torcache.net/css/main.css" media="all" type="text/css" rel="stylesheet">
	</head>
<body>
	<div class="navbar navbar-fixed-top"><div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="/">Torcache</a>
			<div class="nav-collapse">
				<ul class="nav">
									<li class="active"><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
					<li><a href="/api"><i class="icon-wrench icon-white"></i> API</a></li>
													</ul>
			</div>
		</div>
	</div></div>
	<div class="container-fluid">
		<div class="row-fluid">
			<h1> Downloading... </h1>
			<h2>Torcache is a free service for caching torrent files online.</h2>
<br />
<center>
<div id="_801a36d4e167c7184d4c696d2e103004"></div>
<script type="text/javascript">
  var _scq = _scq || [];
  _scq.push(['addSlot', '_801a36d4e167c7184d4c696d2e103004']);
</script>
</center>

<center>Your <a href="http://torcache.net/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent">torrent file</a> download will start in a few seconds...</center>
<script type="text/javascript" charset="utf-8">
    setTimeout(function () { window.location = 'http://torcache.net/torrent/E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B.torrent'; }, 5000);
</script>
<center>
	<p>You can use <a title="Magnet link" href="magnet:?xt=urn:btih:E4997A90C774EBC7A8BF67FDF4E6E4BD4B99582B&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.ccc.de%3A80" onclick="_gaq.push(['_trackEvent', 'Download', 'Magnet Link']);">magnet link</a> to download.</p>
</center>

		</div>
	</div> 
<div id="_47ec71d7b7be19d934c4ddbefc0aa90c"></div>
<script type="text/javascript">
var _scq = _scq || [];
_scq.push(['setDebug', false]);
_scq.push(['setHost', 's.torcache.net']);
_scq.push(['setAccount', '_d0b70e33563de9bece3faa2ee3558e1e']);
_scq.push(['addSlot', '_47ec71d7b7be19d934c4ddbefc0aa90c']);
_scq.push(['load']);
(function() {
      var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
       sc.src = document.location.protocol + '//s.torcache.net/sc.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
})();
</script>
</body>
</html>

I wouldnt know what to update, my installation seems up to date.

**Comment by duramato** [comment] 2015-09-13 19:26
this can be fixed by setting the referer of torcache as "https://torcache.net" i believe

**Comment by loungebob** [comment] 2015-09-13 19:32
@duramato where would I do that?

**Comment by Kawalskint** [comment] 2015-09-14 13:16
@loungebob I am glad you brought up this issue, as I have the exact same problem on my version of SR running under Windows 8.1. I'm also finding that SR tries to fetch multiple versions of "...the waiting page (the html info page) instead of the torrent and magnet files the page supplies after a couple of seconds waiting". This results in multiple faulty (useless) files in the blackhole.  

Maybe unrelated but I also notice that since the latest update "Branch version: Error: No branches found." under General Configuration -> Advanced Settings.

BRANCH: (master) / COMMIT: (d0bc6caa857e44f1f9bae4b50cfac8331ba13732)

**Comment by Kawalskint** [comment] 2015-09-14 13:34
Seems related:
https://github.com/SiCKRAGETV/sickrage-issues/issues/230

The problem could be to do with Blackhole. This method was working perfectly fine until latest updates and issues with broken banners (now fixed), but downloading faulty files remains.

**Comment by miigotu** [comment] 2015-09-14 14:45
Is there a proxy set for the provider? Proxy does not work for black hole if the provider only gives magnets. (never has)

**Comment by loungebob** [comment] 2015-09-14 14:48
@miigotu I have no proxies set. Actually I havent changed anything apart from updating to the latest master. It's either something SR does differently or KAT/torrentcache changed behaviour.

**Comment by Kawalskint** [comment] 2015-09-14 14:49
Nothing selected under: Search Providers -> Provider Options -> Access provider via proxy

Same as loungebob, nothing changed in my config at all. Everything was working fine until I updated SR, then banners broke (recently fixed), and faulty files into Blackhole (still faulty).

**Comment by MAscooby** [comment] 2015-09-14 15:06
Looks like whatever it is affected SickRage, CouchPotato, and Headphones & may be related to the TorCache referred (as noted above, I believe). Could be Windows-only, not sure. CouchPotato's fixed in the develop branch.

**Comment by miigotu** [comment] 2015-09-14 15:08
Seems like torcache, btdigg, and thetorrent have changed their sites. thetorrent and btdigg are returning html when the file is not found, and torcache is always using the timer now.

This is not because of SR.

Connect directly to a client.

**Comment by duramato** [comment] 2015-09-14 15:09
@miigotu its a problem with torcache ,where if the referee is anything else than "torcache.net" it does that ,and doesn't download the torrent file
BTW headphones couchpotato(now fixed ) and sonarr are also affected

**Comment by miigotu** [comment] 2015-09-14 15:11
Yes, I know about the fix for torcache, but the problem is also with btdig and thetorrent. give me awhile to fix it correctly.

This is new chnges to the torrent cache sites, not a new bug in SR.

**Comment by Kawalskint** [comment] 2015-09-14 15:15
Thanks for the insight, would seems like a number of unrelated events occurred simultaneously. If no one else is reporting the issue could also be a windows only problem?

**Comment by duramato** [comment] 2015-09-14 15:18
@Kawalskint this is a global issue not machine specific afaik prob just more people haven't noticed

**Comment by ragtag-fleet** [comment] 2015-09-14 20:13
I am experiencing the same issues, eagerly awaiting the fix...

**Comment by miigotu** [comment] 2015-09-14 22:25
Please try my fix in develop and report, thanks.

**Comment by MAscooby** [comment] 2015-09-14 22:56
Works like a charm for me. Many thanks!

**Closed** 2015-09-15 02:45 UTC
Labels: 1: Bug / issue, 3: Fix, branch: develop

**Comment by Xexiz** [comment] 2015-09-16 02:46
Does anyone know if this bug has been filed and/or fixed for couchpotato?

**Comment by OmgImAlexis** [comment] 2015-09-16 02:55
@Xexiz please got and ask that on the CouchPotato issue tracker, not here.

**Comment by Xexiz** [comment] 2015-09-16 03:02
Oke sorry :(
FYI since some of you talked about it in the comments, I found the issue: https://github.com/RuudBurger/CouchPotatoServer/issues/5412
Thanks

**Comment by loungebob** [comment] 2015-09-16 19:31
Apparently I'm too stupid to do this right. I cant update to the develop branch (change the settings in SR, it says something about different db) so I downloaded the zip file with the develop branch and deleted my local SR dir, installed develop, copied back the ini and db file (which was most likely a mistake), started SR and it updated to master again. Now my torrents still dont work. 
How do I update the changes @miigotu made?
Also, in IE 11 those endlessly looping notification windows are still an issue.

**Comment by flightlevel** [comment] 2015-09-16 22:56
@loungebob Just wait, changes won't be that far away from master

**Comment by Kawalskint** [comment] 2015-09-17 06:51
@loungebob Same here, would be great to know how to change branch from Master to Develop.

When I go to; General Configuration -> Advance Settings -> Branch Version 

And change from Maters to Develop, then click Save Changes, then restart SR, it goes back to Master and never stays on Develop.

**Comment by loungebob** [comment] 2015-09-17 10:15
copied the few changed lines from the generic.py file in develop to my local one and now it seems to work. torrents download and are proper. the next master update will probably fix the rest.

**Comment by Kawalskint** [comment] 2015-09-19 06:42
updated BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752)
seems to be working now, thanks.
