### ISSUE TITLE
Error when adding show with special characters (danish characters)

### ISSUE THREAD

**Issue by Dennisreneholm** [SiCKRAGETV/sickrage-issues#937] opened 2015-03-12 07:19 UTC
Hi.

Running sickrage BRANCH: (master) / COMMIT: (019a8b363d65db598d85173d457fa40aed6328fc) 
Python Version:	2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
Windows Server 2008 r2

I have troubles with adding my danish shows which contains Æ Ø Å
I also seem to have trouble with shows that has a & sign.

Show is called Bubber & BS På Afveje.
http://thetvdb.com/?tab=series&id=252866&lid=10

The error i get looks like this:
http://i.imgur.com/MQkVN4J.png

When i try to add a show not containing &, but only one of the danish characters Æ Ø Å, i can manually edit the show name to the correct, and find it, but i won't add it to the Sickrage database.

If you need more info, please let me know.

I've been using Sickbeard ( SB Version:	alpha (torrent_1080_subtitles) -- source : )
and there there is no problems with adding the shows.

Best regards, Dennis.

**Comment by abeloin** [comment] 2015-03-12 08:05
Have you tried searching in Dansk instead of English?

**Comment by Dennisreneholm** [comment] 2015-03-12 08:09
I can for the specific show try to search in danish, but that does not work for all the shows, and if i can find it on thetvdb, i still can't add it to the database, nothing happens when i press finish.

**Comment by Dennisreneholm** [comment] 2015-03-12 09:25
Just tried developer version, also a problem there.

**Comment by abeloin** [comment] 2015-03-12 13:38
I don't know how you start sickrage, but can you add this command before running sickrage:
`chcp 65001`
so in the command line it would look like this:
```
c:\> chcp 65001
c:\> c:\Python27\python.exe SickBeard.py --nolaunch -q
```

**Comment by Dennisreneholm** [comment] 2015-03-12 13:43
i start it via a service, which starts a .bat file which currently only has this:
C:\Python27\python D:\SickRage\SickBeard.py

ill try 
chcp 65001
C:\Python27\python D:\SickRage\SickBeard.py --nolaunch -q

**Comment by Dennisreneholm** [comment] 2015-03-12 13:45
2015-03-12 14:45:26 Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "D:\SickRage\sickbeard\webserve.py", line 2288, in massAddTable
    cur_path),
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 11: invalid continuation byte

2015-03-12 14:45:00 Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "D:\SickRage\sickbeard\webserve.py", line 2288, in massAddTable
    cur_path),
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 11: invalid continuation byte

**Comment by Dennisreneholm** [comment] 2015-03-12 13:49
Tried without the --nolaunch -q, even though i didn't think that had anything to do with it.

error:
2015-03-12 14:47:52 Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "D:\SickRage\sickbeard\webserve.py", line 651, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles))))
  File "D:\SickRage\sickbeard\browser.py", line 99, in foldersAtPath
    lambda x, y: cmp(os.path.basename(x['name']).lower(), os.path.basename(y['path']).lower()))
  File "D:\SickRage\sickbeard\browser.py", line 99, in 
    lambda x, y: cmp(os.path.basename(x['name']).lower(), os.path.basename(y['path']).lower()))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte

And i can't even see the shows with the special characters now, sickrage just kinda stalls and doesn't show them.

**Comment by abeloin** [comment] 2015-03-12 17:22
Ok remove the chcp line and start sickrage.

Can you provide all the info from "Help & Info" in config page Version, user, locale, ...

**Comment by Dennisreneholm** [comment] 2015-03-12 17:28
http://i.imgur.com/U5jp4Qk.png

User is Administrator on my Server 2008 r2, no domain.
Locale, well, the server language is english :P

**Comment by abeloin** [comment] 2015-03-12 17:30
ok in command line, what is the result of `chcp` ?

**Comment by Dennisreneholm** [comment] 2015-03-12 17:31
C:\Python27>chcp
Active code page: 850

**Comment by abeloin** [comment] 2015-03-12 17:47
I've made a mistake before: it should have been `chcp cp65001` not 65001. Can you retry with the proper command? If it doesn't work try `chcp cp1252` which a superset of cp850.

**Comment by Dennisreneholm** [comment] 2015-03-12 17:52
C:\Python27>chcp cp65001
Parameter format not correct - cp65001

C:\Python27>chcp cp1252
Parameter format not correct - cp1252

**Comment by abeloin** [comment] 2015-03-12 17:55
ok then try `chcp 1252`

**Comment by Dennisreneholm** [comment] 2015-03-12 18:01
Tried that, i can start and browse my directory, but it still looks wrong.
http://i.imgur.com/H1gGrpt.png

**Comment by abeloin** [comment] 2015-03-12 18:05
That's how you typed it? As I don't understand , can you tell me how you get to there with the invalid char?

**Comment by fernandog** [comment] 2015-03-12 18:13
@Dennisreneholm  can you check your browser encoding setting? Is it auto-detect? UTF-8?

**Comment by Dennisreneholm** [comment] 2015-03-12 18:13
No that's how sickrage converts it.

It should be Bamse på planten, but sickrage can't understand ÆØÅ så it converts it.
And it doesn't matter if i type the correct, and find it on thetvdb, because the path to the show is still wrong, as you can see in the image.

**Comment by Dennisreneholm** [comment] 2015-03-12 18:13
@fernandog How do i do that, using chrome

**Comment by fernandog** [comment] 2015-03-12 18:14
@Dennisreneholm https://support.google.com/chrome/answer/95290?hl=en

**Comment by Dennisreneholm** [comment] 2015-03-12 18:18
It is set to UTF-8, also tried auto, didn't change anyhing.

**Comment by fernandog** [comment] 2015-03-12 18:21
@Dennisreneholm 

this don't work for you?
![1](https://cloud.githubusercontent.com/assets/2620870/6624929/7948fc3a-c8cb-11e4-9b43-6ff6a34d3e6e.png)

**Comment by Dennisreneholm** [comment] 2015-03-12 18:22
The command works, but it does not help the sickrage problem.

**Comment by Dennisreneholm** [comment] 2015-03-12 18:22
ill just try again so i can link a screenshot of the error that makes

**Comment by Dennisreneholm** [comment] 2015-03-12 18:27
http://i.imgur.com/m2YmKys.png
command works.

But.
http://i.imgur.com/7kWTxAi.png
Where i put the arrow, the shows that has not been added to sickrage yet, is not appearing.
It loads for a while, then shows nothing.

**Comment by abeloin** [comment] 2015-03-13 04:00
@Dennisreneholm Can you try on a brand new sickrage install(don't point it to any of your existing shows library):
* `chcp 65001`
* `C:\Python27\python D:\SickRage\SickBeard.py --nolaunch`
* Add `Bubber & BS På Afveje`

**Comment by fernandog** [comment] 2015-03-18 22:15
@Dennisreneholm please reply or will close this

**Comment by Dennisreneholm** [comment] 2015-03-19 07:29
Hi.

I got sick last friday, so i really had no energy to keep testing then :P

Ill try a fresh installation, also on another PC, to see if the problem will re occur.

**Comment by Dennisreneholm** [comment] 2015-03-19 07:42
Fresh installation, and i copied a few series onto the PC i was testing on.
Windows 8.1 x64

Added the path for the shows:
![](http://i.imgur.com/FGVXiuh.png)

Tried adding Bamse på Planeten, but it already is wrong with the special chars.
![](http://i.imgur.com/lHuaLFI.png)

Then i corrected it, switched to danish, but it still cannot find it.
And if i could find it, the filepath at the top, is still not correct.
![](http://i.imgur.com/YL40uMi.png)

**Comment by Dennisreneholm** [comment] 2015-03-19 07:51
Nothing works if i try the chcp 65001.
![1](https://cloud.githubusercontent.com/assets/5224930/6726216/2101dffc-ce15-11e4-8657-be13bc46079f.png)

I can't add the path for the shows.
Nothing happens when i press on the folder, and if i look at the cmd windows, this error comes as i press.
![2](https://cloud.githubusercontent.com/assets/5224930/6726219/27703f32-ce15-11e4-8901-1467d37fb645.png)

**Comment by fernandog** [comment] 2015-03-23 10:43
@Dennisreneholm 

can you please edit your SickRage\sickbeard\webserve.py ?

stop SR and change this:
https://github.com/fernandog/SickRage/commit/c1addca77b5d1d970b48d9858a131459f5f65f37

**Comment by Dennisreneholm** [comment] 2015-03-23 16:50
Okay, think i did it :P

You wanted me to delete the line marked with red, and insert the line marked with green right?

**Comment by Dennisreneholm** [comment] 2015-03-23 16:52
Guess not :S
What is it i need to change?
![12311](https://cloud.githubusercontent.com/assets/5224930/6785348/591aa900-d185-11e4-8484-570c98aa8c32.png)

**Comment by fernandog** [comment] 2015-03-23 16:53
@Dennisreneholm sorry. my mistake

return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)))),ensure_ascii=False)

**Comment by TagForce** [comment] 2015-03-23 16:57
```
return json.dumps(foldersAtPath(path, True, bool(int(includeFiles))),ensure_ascii=False)
```

One too many )'s after includeFiles, @fernandog :)

**Comment by Dennisreneholm** [comment] 2015-03-23 16:57
class WebFileBrowser(WebRoot):
    def __init__(self, *args, **kwargs):
        super(WebFileBrowser, self).__init__(*args, **kwargs)

    def index(self, path='', includeFiles=False, *args, **kwargs):
        self.set_header("Content-Type", "application/json")
        return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)))),ensure_ascii=False)

    def complete(self, term, includeFiles=0, *args, **kwargs):
        self.set_header("Content-Type", "application/json")
        paths = [entry['path'] for entry in foldersAtPath(os.path.dirname(term), includeFiles=bool(int(includeFiles)))
                 if 'path' in entry]

        return json.dumps(paths)

Still error

**Comment by fernandog** [comment] 2015-03-23 17:01
@TagForce this new error I don't know what is the reason. do you know?

**Comment by fernandog** [comment] 2015-03-23 17:07
@Dennisreneholm can you send the full error / traceback?

**Comment by TagForce** [comment] 2015-03-23 17:10
```
return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)))),ensure_ascii=False)
```
Has one too many )'s...
You have 4 ('s and in total 5 )'s... You need to remove one of them behind includeFiles so it has 3 )'s

**Comment by fernandog** [comment] 2015-03-23 17:12
@#$% !

@Dennisreneholm 
return json.dumps(foldersAtPath(path, True, bool(int(includeFiles))),ensure_ascii=False)

**Comment by fernandog** [comment] 2015-03-23 17:50
@abeloin is this fix ok?

**Comment by Dennisreneholm** [comment] 2015-03-23 18:25
Now sickrage can't start.
I got a notification from NMA that a commit had been made to sickrage first time i started it, with the changed line.

**Comment by fernandog** [comment] 2015-03-23 18:30
@Dennisreneholm we pushed some updates. it's conflicting with your local change
edit config.ini and enable git_reset = 1
try run again

**Comment by abeloin** [comment] 2015-03-23 18:35
What is the result of this url: `http://localhost:8081/browser/` ?

**Comment by Dennisreneholm** [comment] 2015-03-23 18:46
Used a backup from last night, restored, added the enable git_reset = 1 and replaced the line in webserve.py.
![tabrkc3 1](https://cloud.githubusercontent.com/assets/5224930/6787762/38da54dc-d195-11e4-948e-4fe7e9bb6816.png)

**Comment by abeloin** [comment] 2015-03-23 18:48
@fernandog I think the convertion error from existing to new show happen here:
https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/js/addExistingShow.js#L27

**Comment by fernandog** [comment] 2015-03-23 18:50
@abeloin ensure_ascii=False wouldn't fix this and other possible errors?

**Comment by abeloin** [comment] 2015-03-23 18:57
No because then you to change all the json.load because it's not standard anymore.

From the doc json.load:
```
If the contents of fp are encoded with an ASCII based encoding other than UTF-8 (e.g. latin-1), then an appropriate encoding name must be specified. Encodings that are not ASCII based (such as UCS-2) are not allowed, and should be wrapped with codecs.getreader(encoding)(fp), or simply decoded to a unicode object and passed to loads().
```

From the doc json.dumps:
```
If ensure_ascii is True (the default), all non-ASCII characters in the output are escaped with \uXXXX sequences, and the result is a str instance consisting of ASCII characters only. If ensure_ascii is False, some chunks written to fp may be unicode instances. This usually happens because the input contains unicode strings or the encoding parameter is used. Unless fp.write() explicitly understands unicode (as in codecs.getwriter()) this is likely to cause an error.
```

**Comment by abeloin** [comment] 2015-03-23 19:09
@Dennisreneholm Can you try changing line 2624 in sickbeard/webserve.py in function addExistingShows:
from
`shows_to_add = [urllib.unquote_plus(x) for x in shows_to_add]`
to
`shows_to_add = [ek.ss(urllib.unquote_plus(x)) for x in shows_to_add]`

**Comment by Dennisreneholm** [comment] 2015-03-23 19:39
Just did, sickrage starts fine, same error though.
![saylyxl 1](https://cloud.githubusercontent.com/assets/5224930/6788881/c0beefc8-d19c-11e4-9da5-68e41a8b8eca.png)

**Comment by fernandog** [comment] 2015-03-24 13:09
@Dennisreneholm did you shutdown sickrage, did that changes that abeloin said, and started again SR?

**Comment by Dennisreneholm** [comment] 2015-03-24 14:27
i shutdown via webui, and saw the cmd box go away, then i started it again.

**Comment by fernandog** [comment] 2015-03-24 14:29
@Dennisreneholm can you try searching the way I did in the above image? do you get results?

**Comment by Dennisreneholm** [comment] 2015-03-24 14:34
Okay, i can find the TV show, and i can add it, but.
![50hsi9i 1](https://cloud.githubusercontent.com/assets/5224930/6803922/13612770-d23b-11e4-818b-a77e496a1778.png)
![akgk0sb 1](https://cloud.githubusercontent.com/assets/5224930/6803931/1df6b06a-d23b-11e4-8aa2-412006ea8bbc.png)

Since the filepath still is not showing correctly, the files cannot be found:
![njwkuts 1](https://cloud.githubusercontent.com/assets/5224930/6803953/37ab5592-d23b-11e4-9e45-bdaef69eb275.png)

**Comment by fernandog** [comment] 2015-03-24 14:39
@abeloin in the UI It shows OK! the problem is the path

**Comment by abeloin** [comment] 2015-03-26 16:43
@Dennisreneholm Can you try applying this PR? https://github.com/SiCKRAGETV/SickRage/pull/1652

@fernandog If you 2 mins can you test this in Linux? https://github.com/SiCKRAGETV/SickRage/pull/1652

**Comment by fernandog** [comment] 2015-03-26 17:42
works with and without this patch

**Comment by abeloin** [comment] 2015-03-26 17:51
PR merged in develop

**Comment by abeloin** [comment] 2015-03-26 17:55
@Dennisreneholm The fix is now in develop and will be in master on Sunday. Reopen if you still have issue.

**Comment by Dennisreneholm** [comment] 2015-04-09 08:33
Uhm, i just wanted to check what version i had, and after we have been messing around with my installation, i can't choose a branch version?
![gh54uoz](https://cloud.githubusercontent.com/assets/5224930/7063088/e0432940-dea3-11e4-9a96-32caaa089edc.png)

**Comment by Dennisreneholm** [comment] 2015-04-09 08:45
I copied a new DL of sickrage in my current sickrage folder and told it to overwrite, it seemed to fix it.

However, the problem i had to begin with, is still not fixed.


![pahbgmj](https://cloud.githubusercontent.com/assets/5224930/7063272/8746df06-dea5-11e4-8b83-9493fae7a6aa.png)

**Comment by abeloin** [comment] 2015-04-09 11:24
@Dennisreneholm To confirm, you get this result you add an existing show(folder) to SR? If not, can you give the steps you did to get this results? Thank you

**Comment by fernandog** [comment] 2015-04-13 15:36
@Dennisreneholm please reply or will close

**Comment by Dennisreneholm** [comment] 2015-04-15 06:13
I got this result by adding a existing show yes.
Like i've shown before.

**Comment by kotysoft** [comment] 2015-04-15 22:06
Hi,
I have same issue when trying to add an already existing show directory containing special characters (hungarian), but I don't speak english well to answer some of your questions :\

![01](http://amalon.hu/koty/sickrage-x01.jpg)
![02](http://amalon.hu/koty/sickrage-x02.jpg)
![03](http://amalon.hu/koty/sickrage-x03.jpg)
![04](http://amalon.hu/koty/sickrage-x04.jpg)
![05](http://amalon.hu/koty/sickrage-x05.jpg)
![06](http://amalon.hu/koty/sickrage-x06.jpg)
![07](http://amalon.hu/koty/sickrage-x07.jpg)
![08](http://amalon.hu/koty/sickrage-x08.jpg)
![09](http://amalon.hu/koty/sickrage-x09.jpg)

**Comment by kotysoft** [comment] 2015-04-17 08:02
I tried all things you mentioned above.
Also tried with my default cp (852) and 1250 and 65001
Also tried to change webserve.py as written before.

With default settings with default codepage it can open directory but shows and handles accents wrong.
With cp65001 it shows accents correctly, but cant browse directories (same utf_8.py python error).

Tried from scratch with Python 2.7.8 (x64) and tried with python 2.7.9 (x64).
Using Win7 (x64) hungarian, latest Chrome, also tried to change browser codepage to utf8, and 1250

Can You suggest anything please to handle my series under Windows?
I'm affraid if I use original english names for series it will solve the directory handling, but my torrent provider serving local (hungarian) titles with accents.

**Comment by kotysoft** [comment] 2015-04-18 08:59
Update:
If I'm use folders only with english characters, sickrage working like charm.

So Currently I renamed my movie folders to english names, added them (with untouched codepage)
restarted sickrage with cp65001
added hungarian names to Exceptions List (working)
set all my tv shows to Hungarian
started to mass update/rescan/rename my all episodes

Everything works fine (searching in custom RSS using special characters, too),
EXCEPT the directory browsing: When I want to browse a folder containing special any character it freeze and says the 'python utf_8.py error'. But when I writing manually it accepts and working.
(for example at manual post-processing)

**Comment by fernandog** [comment] 2015-04-18 10:56
Did you change the language? See my comments above

**Comment by kotysoft** [comment] 2015-04-18 11:09
@fernandog you mean the indexer language?

btw as I said before I read whole conversation and tried every tips.

**Comment by fernandog** [comment] 2015-04-18 11:38
Yes

**Comment by kotysoft** [comment] 2015-04-18 11:46
![11](http://amalon.hu/koty/sickrage-x11.jpg)
![11b](http://amalon.hu/koty/sickrage-x11b.jpg)

**Comment by fernandog** [comment] 2015-04-18 11:55
Use the special letters in the search

**Comment by kotysoft** [comment] 2015-04-18 14:36
![image](https://cloud.githubusercontent.com/assets/11740566/7215854/e44adfa0-e5e8-11e4-845f-54929f0e19c8.png)


1.) [Person of interest](http://thetvdb.com/?tab=series&id=248742&lid=19)
2.) [The Big Bang Theory](http://thetvdb.com/?tab=series&id=80379&lid=19)

**Comment by fernandog** [comment] 2015-04-24 01:51
@abeloin shouldn't we add decode to utf here?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L2259

with chcp 65001 it shows ok in the log but I can't see the search URL or the call to indexer:
2015-04-23 22:46:09 DEBUG    Thread-20 :: Searching for Show with searchterm: a célszemély on Indexer: theTVDB

**Comment by fernandog** [comment] 2015-04-24 18:08
@abeloin if we remove the "continue" here and add a raise we get this:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L2262

```
2015-04-24 14:59:44 DEBUG    TORNADO :: Failed doing webui request "searchIndexersForShowName": Traceback (most recent call last):
AAUnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
AA    series = series.encode("utf-8")
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 679, in search
AA    allSeries = self.search(series)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 691, in _getSeries
AA    selected_series = self._getSeries(key)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 949, in __getitem__
AA    results.setdefault(indexer, []).extend(t[search_term])
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 2259, in searchIndexersForShowName
AA    result = function(**kwargs)
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 258, in async_call
AATraceback (most recent call last):
AAUnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
AA    series = series.encode("utf-8")
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 679, in search
AA    allSeries = self.search(series)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 691, in _getSeries
AA    selected_series = self._getSeries(key)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 949, in __getitem__
AA    results.setdefault(indexer, []).extend(t[search_term])
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 2259, in searchIndexersForShowName
AA    result = function(**kwargs)
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 258, in async_call
```

**Comment by kotysoft** [comment] 2015-04-26 10:25
Well... Maybe my fault and something did wrong...
Just found this:

**SR Locale:** ('hu_HU', 'cp1250')
**Windows default locale:** 852
**Manually set locale to command line before SR starts:** 65001

**Closed** 2015-07-09 12:00 UTC
Labels: 1: Bug / issue, 3: Confirmed, 4: Fix pending, 4: Need feedback

**Comment by fernandog** [comment] 2015-07-09 13:24
Possible fix in develop

**Comment by miigotu** [comment] 2015-07-09 13:30
master =P
