### ISSUE TITLE
Language  does not exist

### ISSUE THREAD

**Issue by meokey** [SiCKRAGETV/sickrage-issues#373] opened 2015-01-10 05:32 UTC
Error

Language does not exist

Traceback

```python
Traceback (most recent call last): 
File "/usr/share/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/share/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/share/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/share/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/share/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 1165, in displayShow return t.respond() 
File "/usr/share/SickRage/cache/cheetah/_usr_share_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1154, in respond for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',')]): # generated from line 477, col 3 
File "/usr/share/SickRage/lib/subliminal/language.py", line 1034, in __init__ items.append(Language(i, languages=languages, strict=strict)) 
File "/usr/share/SickRage/lib/subliminal/language.py", line 884, in __init__ raise ValueError('Language %s does not exist' % language) 
ValueError: Language does not exist 
```
Request Info
```python
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=76290
query_arguments: {'show': ['76290']}
_start_time: 1420867441.61
headers: {'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': 'vhost:8080', 'Referer': 'http://vhost:8080/home/', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; late_view2=list; locale=en_US; user="2|1:0|10:1420844573|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|3d3d934e35693ade5a0f43694371efb49a3e7e758058a46ef8c01f167a545fdd"'}
host: vhost:8080
version: HTTP/1.1
arguments: {'show': '76290'}
_finish_time: None
query: show=76290
path: /home/displayShow
_cookies: Set-Cookie: late_view2=list Set-Cookie: locale=en_US Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: user="2|1:0|10:1420844573|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|3d3d934e35693ade5a0f43694371efb49a3e7e758058a46ef8c01f167a545fdd"
method: GET
remote_ip: 192.168.0.99

```

**Comment by fernandog** [comment] 2015-01-12 13:21
@meokey fix was fixed. please update you SR

**Comment by meokey** [comment] 2015-01-12 15:46
Hi Fernandog,

Thank you for your help.

But did I do something wrong? I updated and restart SR but still I have the same error

SickRage]sudo service SickRage stop
SickRage]sudo git pull
SickRage]sudo service SickRage start

SickRage]$ grep -i lang config.ini
subtitles_languages = en


Configuration
SR Version:	BRANCH: (develop) / COMMIT: (32da0199f2690b8b04349ebd495c6a7ad5a2b2f4) 
SR Config file:	/usr/share/SickRage/config.ini
SR Database file:	/usr/share/SickRage/sickbeard.db
SR Cache Dir:	/usr/share/SickRage/cache
SR Arguments:	['--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickrage.pid', '--datadir=/usr/share/SickRage']
SR Web Root:	
Python Version:	2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]





Error

Language does not exist

Traceback

Traceback (most recent call last): 
File "/usr/share/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/share/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/share/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/share/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/share/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 1165, in displayShow return t.respond() 
File "/usr/share/SickRage/cache/cheetah/_usr_share_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1154, in respond for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',')]): # generated from line 477, col 3 
File "/usr/share/SickRage/lib/subliminal/language.py", line 1034, in __init__ items.append(Language(i, languages=languages, strict=strict)) 
File "/usr/share/SickRage/lib/subliminal/language.py", line 884, in __init__ raise ValueError('Language %s does not exist' % language) 
ValueError: Language does not exist 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=261557
query_arguments: {'show': ['261557']}
_start_time: 1421077127.58
headers: {'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2267.0 Safari/537.36', 'Dnt': '1', 'Host': 'vhost:8080', 'Referer': 'http://vhost:8080/home/', 'Cookie': 'plushHistPerPage=9999999; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; late_view2=list; wanted_view2=details; PPA_ID=3d5t0nmeo57rsv7jbo76nnhl55; webfx-tree-cookie-persistence=wfxt-4+wfxt-6; user="2|1:0|10:1420834048|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|f321397f6a5d170078e68793ffdc46875826267adc23d53b9b5bd9c5ac01fc8d"'}
host: vhost:8080
version: HTTP/1.1
arguments: {'show': '261557'}
_finish_time: None
query: show=261557
path: /home/displayShow
_cookies: Set-Cookie: PPA_ID=3d5t0nmeo57rsv7jbo76nnhl55 Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushHistPerPage=9999999 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: user="2|1:0|10:1420834048|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|f321397f6a5d170078e68793ffdc46875826267adc23d53b9b5bd9c5ac01fc8d" Set-Cookie: wanted_view2=details Set-Cookie: webfx-tree-cookie-persistence=wfxt-4+wfxt-6
method: GET
remote_ip: 192.168.0.200

View Log(Errors)

**Comment by markheloking** [comment] 2015-01-18 13:47
@meokey please use markdown in the future

**Comment by markheloking** [comment] 2015-03-19 11:44
@fernandog where is this a duplicate of? I think it's good to link to the duplicate in the future, so people know where to continue the discussion.

**Comment by abeloin** [comment] 2015-03-20 00:29
Maybe related to this: https://github.com/Diaoul/subliminal/issues/96

**Comment by fernandog** [comment] 2015-03-20 00:31
We need to update and keep up with subliminal updates

**Comment by fernandog** [comment] 2015-03-22 02:05
@meokey @markheloking is this still a bug? We haven't' had reports about this.

**Comment by fernandog** [comment] 2015-03-22 02:06
https://github.com/SiCKRAGETV/SickRage/issues/1275

**Comment by fernandog** [comment] 2015-03-22 02:06
https://github.com/SiCKRAGETV/sickrage-issues/issues/237

**Comment by fernandog** [comment] 2015-03-22 02:06
https://github.com/SiCKRAGETV/sickrage-issues/issues/457

**Closed** 2015-03-22 02:07 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
