### ISSUE TITLE
lib.shutil_custom fails on startup

### ISSUE THREAD

**Issue by faidwen** [SiCKRAGETV/sickrage-issues#844] opened 2015-03-04 04:02 UTC
Version af20b6e90506c49280ca7f17eb13d1f647cf502c
Python 2.6.6

Executing /etc/rc.d/init.d/sickrage start ..

Starting sickrage: Traceback (most recent call last):
  File "/root/.sickrage/SickBeard.py", line 33, in <module>
    import lib.shutil_custom
  File "/root/.sickrage/lib/shutil_custom/__init__.py", line 4, in <module>
    from shutil import SpecialFileError, Error
ImportError: cannot import name SpecialFileError
[FAILED]

**Comment by maxcore** [comment] 2015-03-04 04:05
+1 ..............

**Comment by nekkidtruth** [comment] 2015-03-04 04:16
Same issue here, but different output.

Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 69, in <module>
    import sickbeard
  File "/home/xxxxx/.sickrage/sickbeard/__init__.py", line 29, in <module>
    shutil.copyfile = lib.shutil_custom.copyfile_custom
NameError: name 'shutil' is not defined

**Comment by HickBoy** [comment] 2015-03-04 04:46
Same issue, albeit another output with similar results:

[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage] # /etc/init.d/sickbeard-tvrage.sh start
x86_64
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Updating SickBeard-TVRage
HEAD is now at af20b6e Merge pull request #1308 from abeloin/patch-shutil_copy
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 69, in <module>
    import sickbeard
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/__init__.py", line 29, in <module>
    shutil.copyfile = lib.shutil_custom.copyfile_custom
NameError: name 'shutil' is not defined


And the first 30 lines from the file listed (after comments):

from __future__ import with_statement

import webbrowser
import datetime
import socket
import os
import re
import os.path
import lib.shutil_custom

shutil.copyfile = lib.shutil_custom.copyfile_custom

**Comment by faidwen** [comment] 2015-03-04 05:02
I don't think SpecialFileErrors exists in 2.6.6 python.

Can others verify what Python version they are on??  

I think it first exists in 2.7

**Comment by Thraxis** [comment] 2015-03-04 05:27
I'm on Python 2.7.3 and am having the same issue

**Comment by Thraxis** [comment] 2015-03-04 05:39
adding
```python
import shutil

before
```python
import lib.shutil_custom 

In the <sickrage install folder>\sickbeard\__init__.py fixed the problem for me

**Comment by faidwen** [comment] 2015-03-04 05:58
That works for Python 2.7+

On Python 2.6 you will need to remove the SpecialFileErrors reference.  I just changed mine to Errors instead of SpecialFileErrors and it appears to start up again.

**Comment by maxcore** [comment] 2015-03-04 06:03
@Thraxis thx dude now working :)

**Comment by bitzorro** [comment] 2015-03-04 07:28
@Thraxis  I just did as u said and added; "import shutil" before "import lib.shutil_custom"
running dev branch and it worked.
Then i changed to master and it wont start again, i opend the file  __init__.py
now i cant find the line "import lib.shutil_custom".
The __init__.py file isnt the same as in the dev branch ?

**Comment by Thraxis** [comment] 2015-03-04 07:35
@bitzorro: This is an issues specific to the Dev branch.

**Comment by bitzorro** [comment] 2015-03-04 07:38
@Thraxis 
thanks, i got it running again, doing a git pull from cmd.

**Comment by DcR-NL** [comment] 2015-03-04 08:29
Still not working for me, traceback on run:
```
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 69, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 29, in <module>
    shutil.copyfile = lib.shutil_custom.copyfile_custom
NameError: name 'shutil' is not defined
```

**Branch**
Develop

**Commit hash**
af20b6e90506c49280ca7f17eb13d1f647cf502c

**Your operating system and python version**
Linux (Synology - x86) - Python 2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)]

**Comment by seed1234** [comment] 2015-03-04 08:48
whats the update command on freenas to git pull from develop branch?

**Comment by Thraxis** [comment] 2015-03-04 08:50
This has NOT been fixed in the Dev branch yet.  If you update to the current Dev branch it will not start unless you edit the file by hand, and then only if you have a python 2.7 system

**Comment by DcR-NL** [comment] 2015-03-04 09:02
@Thraxis Whoops my bad, I saw a 'merged' pull reference and expected it to be your fix..

**Comment by Thraxis** [comment] 2015-03-04 09:06
@DcR-NL I was linking this issue to the PR that added this change so it could possibly get a bit more attention

**Comment by tchirou** [comment] 2015-03-04 09:11
Many thanks @Thraxis 
BRANCH: (develop) / COMMIT: (af20b6e90506c49280ca7f17eb13d1f647cf502c) 
Python 2.7.6 / Win 8.1
I edited like you suggested and it works like a charm
Kudos to you.

**Comment by TagForce** [comment] 2015-03-04 09:33
I've created a PR for the NameError.

**Comment by TagForce** [comment] 2015-03-04 09:57
PR has been merged. Please update to latest dev. Python 2.6 compatibility is being looked at.

**Comment by tchirou** [comment] 2015-03-04 10:18
COMMIT: (f51551dc5530c7d4a39431d1f71da8e9723d5892) works for me

**Comment by fernandog** [comment] 2015-03-04 10:22
Please for all of you what will not help test develop please use master.
develop will break a lot of times from now on as we wil test new thing

@tagforce any news about using develop DIV?

**Comment by Thraxis** [comment] 2015-03-04 10:36
I can confirm this fixes the start issues as well.
Update Now worked quite nicely with the config backup.

For those of you who edited the file by hand to get this going while waiting for the PR / patch.  Check mark the Git Reset in general preferences to allow the update to overwrite the file.

**Comment by seed1234** [comment] 2015-03-04 10:49
whats the update command on freenas to git pull from develop branch?

Thanks for the fix :)

**Comment by abeloin** [comment] 2015-03-04 12:02
@faidwen Can you try this PR : https://github.com/SiCKRAGETV/SickRage/pull/1469 It should resolve the issue with SpecialFileError

**Comment by chrism2014** [comment] 2015-03-04 15:03
after the fix i'm getting the following error when starting.

Starting SickBeard
Traceback (most recent call last):
  File "SickBeard.py", line 33, in <module>
    import lib.shutil_custom
  File "/root/sickrage_install/lib/shutil_custom/__init__.py", line 4, in <module>
    from shutil import SpecialFileError, Error
ImportError: cannot import name SpecialFileError

**Comment by abeloin** [comment] 2015-03-04 17:00
@chrism2014 You applied 1469 and you get this error? Because with the patch line 4 is a "try:" not "from shutil import SpecialFileError, Error"

**Comment by faidwen** [comment] 2015-03-04 17:27
#1469 applied, Python 2.6.6 is working again.

**Comment by abeloin** [comment] 2015-03-04 17:30
Good

**Closed** 2015-03-04 17:39 UTC
Labels: 1: Bug / issue, 2: High Priority, 3: Confirmed, 3: Fix
