### ISSUE TITLE
Quality set to HD720p but HDTV being snatched

### ISSUE THREAD

**Issue by brimur** [SiCKRAGETV/sickrage-issues#2436] opened 2015-08-07 16:04 UTC
Fully up to date install (No updates needed)

As the title says I set the quality to HD720 for some shows and HDTV 624 x 352 ~350MB files are being downloaded. The titles are similar between shows also... ".HDTV.Subtitulado.Esp.SC.avi"

**Comment by WebSpider** [comment] 2015-08-07 16:18
Please post debug logs

-----Original Message-----

**Comment by miigotu** [comment] 2015-08-07 19:40
".HDTV.Subtitulado.Esp.SC.avi" is not even HDTV quality in SR eyes, it is SDTV.

**Comment by brimur** [comment] 2015-08-10 10:54
,,,,
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Calling Transmission Client
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL] from Torlock
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Monova] :: Transaction with 9 queries executed
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picked The.Last.Ship.S02E09.HDTV.480p.x264.AAC-VYTO.[P2PDL] as the best
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Quality of The.Last.Ship.S02E09.HDTV.480p.x264.AAC-VYTO.[P2PDL] is HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picking the best result out of [u'The.Last.Ship.S02E09.HDTV.480p.x264.AAC-VYTO.[P2PDL]']
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picked The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL] as the best
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Quality of The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL] is HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picking the best result out of [u'The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL]']
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picked True.Detective.S02E08.HDTV.480p.x264.AAC-VYTO.[P2PDL] as the best
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Quality of True.Detective.S02E08.HDTV.480p.x264.AAC-VYTO.[P2PDL] is HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picking the best result out of [u'True.Detective.S02E08.HDTV.480p.x264.AAC-VYTO.[P2PDL]']
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picked Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL] as the best
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Quality of Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL] is HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Picking the best result out of [u'Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL]']
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Found result The.Last.Ship.S02E09.HDTV.480p.x264.AAC-VYTO.[P2PDL] at http://www.torlock.com/tor/4350027.torrent
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status is wanted or skipped, getting found episode
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status: 3 (Wanted)
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Checking if found episode The Last Ship S02E09 is wanted at quality HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: The.Last.Ship.S02E09.HDTV.480p.x264.AAC-VYTO.[P2PDL]
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Found result The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL] at http://www.torlock.com/tor/4350562.torrent
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status is wanted or skipped, getting found episode
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status: 3 (Wanted)
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Checking if found episode The Strain S02E05 is wanted at quality HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Invalid scene release: the.strain.s02e05.720p.hdtv.hevc.x265.rmteam.mkv contains x265, ignoring it
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: the.strain.s02e05.720p.hdtv.hevc.x265.rmteam.mkv
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Found result True.Detective.S02E08.HDTV.480p.x264.AAC-VYTO.[P2PDL] at http://www.torlock.com/tor/4350211.torrent
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status is wanted or skipped, getting found episode
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status: 3 (Wanted)
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Checking if found episode True Detective S02E08 is wanted at quality HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: True.Detective.S02E08.HDTV.480p.x264.AAC-VYTO.[P2PDL]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Invalid scene release: true.detective.s02e08.720p.hdtv.hevc.x265.rmteam.mkv contains x265, ignoring it
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: true.detective.s02e08.720p.hdtv.hevc.x265.rmteam.mkv
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Invalid scene release: True.Detective.S02E08.INTERNAL.720p.HDTV.2CH.x265.HEVC-PSA.mkv contains x265, ignoring it
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: True.Detective.S02E08.INTERNAL.720p.HDTV.2CH.x265.HEVC-PSA.mkv
2015-08-10 11:21:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Found result Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL] at http://www.torlock.com/tor/4350409.torrent
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status is wanted or skipped, getting found episode
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Existing episode status: 3 (Wanted)
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Checking if found episode Falling Skies S05E07 is wanted at quality HDTV
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: Falling.Skies.S05E07.HDTV.480p.x264.AAC-VYTO.[P2PDL]
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Invalid scene release: falling.skies.s05e07.720p.hdtv.hevc.x265.rmteam.mkv contains x265, ignoring it
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Using cached parse result for: falling.skies.s05e07.720p.hdtv.hevc.x265.rmteam.mkv
2015-08-10 11:21:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Torlock] :: Transaction with 9 queries executed

,,,,

**Comment by neoatomic** [comment] 2015-08-10 16:12
Strange, For a torrent to be recognized as HDTV it needs to include : 

`File name contains 720p and HDTV and x264, and not 1080p] `

If you look at the title it clearly doesn't contain those, so should never get recognized as HDTV.
`The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL]`


```
Found result The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL] at http://www.torlock.com/tor/4350562.torrent
Existing episode status is wanted or skipped, getting found episode
Existing episode status: 3 (Wanted)
Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
Checking if found episode The Strain S02E05 is wanted at quality HDTV
Using cached parse result for: The.Strain.S02E05.HDTV.480p.x264.AAC-VYTO.[P2PDL]
Invalid scene release: the.strain.s02e05.720p.hdtv.hevc.x265.rmteam.mkv contains x265, ignoring it
Using cached parse result for: the.strain.s02e05.720p.hdtv.hevc.x265.rmteam.mkv
```

**Comment by djoole** [comment] 2015-08-27 15:27
Same problem occuring several times here..
If a dev can point me to the code part to check, i'm ok to have a look.

**Comment by miigotu** [comment] 2015-08-27 16:21
The quality hdtv in SR IS HD720p.

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L200L258

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L363L382

**Comment by djoole** [comment] 2015-08-27 22:28
Can't see nothing wrong in here : 
```
checkName = lambda list, func: func([re.search(x, name, re.I) for x in list])
(...)
        elif checkName(["720p", "hdtv", "x264"], all) or checkName(["hr.ws.pdtv.x264"], any) and not checkName(
                ["1080[pi]"], all):
            return Quality.HDTV
```
I file like `Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi`shouldn't pass in this if... yet it does

**Comment by djoole** [comment] 2015-08-27 22:36
I've made this test script and it returns SD, not HD : 
```
# coding: utf8
import re

#name = "Tyrant.S02E11.HDTV.720p.x264.Subtitulado.Esp.SC.avi"
name = "Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi"

checkName = lambda list, func: func([re.search(x, name, re.I) for x in list])

if checkName(["720p", "hdtv", "x264"], all) or checkName(["hr.ws.pdtv.x264"], any) and not checkName(
                ["1080[pi]"], all):
    print("HD!")
else:
    print("SD!")
```

I think the problem is not here but where the sceneQuality() function is used..

**Comment by miigotu** [comment] 2015-08-27 22:44
It should return SD, because "Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi" is SD.

**Comment by djoole** [comment] 2015-08-27 22:45
@miigotu Yes, but it returns HD, see logs below : 
```
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Parsed Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi into Tyrant - S02E11 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Checking if found episode Tyrant S02E11 is wanted at quality HDTV
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Any,Best = [ HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ HDTV ]
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Existing episode status: 3 (Wanted)
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Existing episode status is wanted or skipped, getting found episode
2015-08-26 14:40:57 INFO     SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Found result Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi at magnet:?xt=urn:btih:AC950EBDAD3D52101A05E078656580C863A67DC9&dn=tyr$
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Picking the best result out of [u'Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi']
2015-08-26 14:40:57 INFO     SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Quality of Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi is HDTV
2015-08-26 14:40:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Picked Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi as the best
2015-08-26 14:40:57 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi from KickAssTorrents
```

FYI each time i get this problem of hdtv SD file snatched instead of 720 HD, it seems to be with KAT provider.

**Comment by brimur** [comment] 2015-08-27 23:46
Just wanted to add, I have had it happen with multiple providers, my post above is for Torlock for example but I have seen it happen with KAT and Monova

**Comment by miigotu** [comment] 2015-08-28 01:02
@brimur we dont have a monova provider....

@djoole can try with episode only search and season search fallback disabled?  I have a potential fix here.

**Comment by djoole** [comment] 2015-08-28 01:18
@miigotu I did what you asked, but unfortunately now SR is snatching a web-dl before getting the chance to snatch the offending file.
But looking at the logs, it seems SR still analyse it has HD and not SD : 
```
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Using cached parse result for: Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Checking if found episode Tyrant S02E11 is wanted at quality HDTV
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Any,Best = [ HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ HDTV ]
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Existing episode status: 6402 (Snatched (1080p WEB-DL))
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Episode already exists and the found episode has same/lower quality, ignoring found episode
2015-08-28 03:13:29 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: None of the conditions were met, ignoring found episode
2015-08-28 03:13:29 INFO     SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Ignoring result Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi because we don't want an episode that is HDTV
2
```

**Comment by djoole** [comment] 2015-08-28 01:25
OK i managed to force SR to snatch the "bad" files with custom only HDTV quality.
It seems it still want to download it : 
```
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Using cached parse result for: Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Checking if found episode Tyrant S02E11 is wanted at quality HDTV
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Any,Best = [ HDTV ] [ None ] Found = [ HDTV ]
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Existing episode status: 3 (Wanted)
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Existing episode status is wanted or skipped, getting found episode
2015-08-28 03:20:50 DEBUG    SEARCHQUEUE-BACKLOG-268094 :: [KickAssTorrents] :: Found result Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi at magnet:?xt=urn:btih:AC950EBDAD3D52101A05E078656580C863A67DC9&dn=tyrant+s02e11+hdtv+subtitulado+esp+sc+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
```
But several other HDTV files are found, and this time I'm lucky, it picks another one which is 720p

But if the `Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi`would have been alone, it would have picked it.

**Comment by brimur** [comment] 2015-08-28 01:26
@miigotu True, I mostly use custom RSS feeds and one of them is for Monova

**Comment by miigotu** [comment] 2015-08-28 02:11
@djoole that is not enough of the log. You need to put full debug logs on gist.

**Comment by miigotu** [comment] 2015-08-28 03:26
@djoole @brimur you guys could try the provider-cleanup branch and see if the issue still happens for kat/tpb

**Comment by djoole** [comment] 2015-08-28 07:23
@miigotu Full logs here (snatch around 03:20:50, offending file Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi) : 
https://gist.github.com/djoole/5874e4a600f82ee796bc

**Comment by djoole** [comment] 2015-08-28 07:26
@miigotu Won't be able to try provider-cleanup branch until monday now.
Hope someone can test it.

To reproduce it, you need to look for ep 211 of Tyrant, Custom quality profile with HDTV only, KAT provider activated only, and look for `Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi`in the logs.

This release should be detected as SDTV and not HDTV.

**Comment by miigotu** [comment] 2015-08-28 08:41
This is the indication of the issue:

```python
>>> Quality.sceneQuality('Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi')
32768
>>> Quality.nameQuality('Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi')
4
```
Where 32768 is "Unknown"
and 4 is "HDTV"

Both of these should return the same quality in this case.

Digging further.

**Comment by miigotu** [comment] 2015-08-28 08:58
I see what is happening now. It is seeing this as a file SR has renamed before.

This part would be able to be fixed easily with a fixed hachoir (it currently isnt closing file handles).

I am going to merge this fix. If any real breakage happens due to it we will just be forced to fix and PR to hachoir sooner.

**Comment by miigotu** [comment] 2015-08-28 10:14
@djoole @brimur this should be fixed in develop. Let me know if it is not.

**Closed by miigotu** 2015-08-28 10:14 UTC
Labels: 1: Bug / issue

**Comment by brimur** [comment] 2015-08-28 10:58
Thanks @miigotu, appreciated.

**Comment by djoole** [comment] 2015-08-28 13:30
@miigotu Thanks a lot, I'll try to test it tonight.

**Comment by djoole** [comment] 2015-08-29 09:31
You did it @miigotu : 
```
2015-08-29 11:30:11 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Parsed Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi into Tyrant - S02E11 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-08-29 11:30:11 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Checking if found episode Tyrant S02E11 is wanted at quality Unknown
2015-08-29 11:30:11 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Any,Best = [ HDTV ] [ None ] Found = [ Unknown ]
2015-08-29 11:30:11 DEBUG    SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Don't want this quality, ignoring found episode
2015-08-29 11:30:11 INFO     SEARCHQUEUE-MANUAL-268094 :: [KickAssTorrents] :: Ignoring result Tyrant.S02E11.HDTV.Subtitulado.Esp.SC.avi because we don't want an episode that is Unknown
```

Thanks a lot!

**Comment by AdeHub** [comment] 2015-09-07 08:18
Can anything be done about this one on kat?
```Catastrophe 2015 S01E01 720p HDTV 2CH x265 HEVC-PSA```

**Comment by miigotu** [comment] 2015-09-07 19:57
@AdeHub i dont knowb what you mean.

**Comment by fernandog** [comment] 2015-09-07 19:58
@AdeHub if you don't want x265 HEVC (new codec) add it to ignore words in SR settings

**Comment by AdeHub** [comment] 2015-09-07 20:00
Sickrage is snatching that when I think it shouldn't, file size is only 64.15 MB

**Comment by fernandog** [comment] 2015-09-07 20:04
Yes. Size is half but quality is same as 128mb

**Comment by miigotu** [comment] 2015-09-07 20:06
@AdeHub stop judging by file size. It is supposed to be snatched. Only worry about it if the file does not play correctly for you, in that case add HEVC,x265 to ignore words.

**Comment by AdeHub** [comment] 2015-09-08 09:16
Thanks guys, wlll ignore these for now as they don't play on all my devices

**Comment by brimur** [comment] 2015-09-08 09:43
Off topic but you are lucky to have any devices (other than a PC) that can play them :) As far as I know very few devices can decode HEVC in hardware. I'm surprised more haven't been developed

**Comment by miigotu** [comment] 2015-09-08 10:23
@brimur tru not much can decode it in hardware, but we dont discriminate by codec in SR for other codes so we cant make this a special case. At least with HEVC you can add it to ignore words.

**Comment by brimur** [comment] 2015-09-08 10:36
@miigotu Totally, I wouldn't expect that at all, you guys are platform independent.
