### ISSUE TITLE
rTorrent:  Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by ahaghgoo** [SiCKRAGETV/sickrage-issues#1105] opened 2015-04-04 04:22 UTC
SickRage can't send torrents to rTorrent.

----
## Configuration
SR Version:	BRANCH: (master) / COMMIT: (ff7aee90fd26db93cc571be1cb5c62a6fcf08e19) 
SR User:	admin
SR Locale:	(None, None)
SR Config file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
SR Database file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
SR Cache Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
SR Log Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
SR Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

--

## Log

2015-04-03 17:32:06 ERROR    SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-03 17:31:36 INFO     SEARCHQUEUE-BACKLOG-72231 :: Downloading .2015.03.20.720p.HDTV.x264-BATV from BTN
2015-04-03 17:31:25 ERROR    SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-03 17:30:55 INFO     SEARCHQUEUE-BACKLOG-94571 :: Downloading .S05.1080p.WEB-DL.DD5.1.H.264-BS from BTN

I removed the names of the torrents. 

----

## Torrent Search Settings

![screenshot 2015-04-03 21 06 54](https://cloud.githubusercontent.com/assets/1308002/6991375/7541490e-da45-11e4-95de-cdc6c0588a99.png)

**Comment by abeloin** [comment] 2015-04-04 04:50
Thanks

**Comment by abeloin** [comment] 2015-04-04 04:51
Maybe related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1061

**Comment by fernandog** [comment] 2015-04-04 22:04
https://github.com/SiCKRAGETV/sickrage-issues/issues/1105

**Comment by abeloin** [comment] 2015-04-05 02:20
@fernandog Why #1105 which is this post?

**Comment by fernandog** [comment] 2015-04-05 02:34
Sorry. Using phone. Deleted

**Comment by fernandog** [comment] 2015-04-05 02:35
#1061

**Comment by abeloin** [comment] 2015-04-05 02:57
@fernandog I ask him to open the issue hence my previous message : Maybe related to #1061
See my comment on https://github.com/SiCKRAGETV/sickrage-issues/issues/242#issuecomment-89497424

**Comment by fernandog** [comment] 2015-04-07 11:41
@ahaghgoo please update and report back

**Comment by ahaghgoo** [comment] 2015-04-07 19:59
What can I update you guys with on this? I’m getting the same errors.  

Thanks again for the consideration! -A
 

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 7, 2015 at 4:41:59, Fernando (notifications@github.com) wrote:

@ahaghgoo please update and report back

**Comment by abeloin** [comment] 2015-04-08 02:12
After updating Sickrage with the latest version from Sunday, you still have the same issue? If so provide debug log when sending torrent to rtorrent

**Comment by ahaghgoo** [comment] 2015-04-08 06:26
Unfortunately, I cannot currently replicate the error as BTN has gone down. And before realizing BTN went down, I thought I could see if a restart of SickRage would help since I saw the error in the log after the automatic update.  The restart though also cleared the log so I don’t have what I saw in the log when I loaded SickRage earlier today. 

I’ll report back when BTN is back up.  

Thanks, 
-A

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 7, 2015 at 19:12:52, Alexandre Beloin (notifications@github.com) wrote:

After updating Sickrage with the latest version from Sunday, you still have the same issue? If so provide debug log when sending torrent to rtorrent

**Comment by fernandog** [comment] 2015-04-10 12:49
@ahaghgoo any news?

**Comment by ahaghgoo** [comment] 2015-04-10 18:45
No, unfortunately not: 

2015-04-10 11:09:25 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: Unknown error while accessing BTN: ProtocolError for api.btnapps.net: 302 Moved Temporarily
2015-04-10 11:09:25 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: No data returned from BTN
2015-04-10 10:29:25 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: Unknown error while accessing BTN: ProtocolError for api.btnapps.net: 302 Moved Temporarily
2015-04-10 10:29:25 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: No data returned from BTN
2015-04-10 09:49:23 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: Unknown error while accessing BTN: ProtocolError for api.btnapps.net: 302 Moved Temporarily
2015-04-10 09:49:23 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: No data returned from BTN
2015-04-10 09:09:24 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: Unknown error while accessing BTN: ProtocolError for api.btnapps.net: 302 Moved Temporarily
2015-04-10 09:09:24 SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: No data returned from BTN

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 10, 2015 at 5:49:23, Fernando (notifications@github.com) wrote:

@ahaghgoo any news?

**Comment by abeloin** [comment] 2015-04-10 18:48
https://broadcasthe.net/maintenance.htm

**Comment by ahaghgoo** [comment] 2015-04-12 07:18
BTN is back up but I’m currently experiencing connectivity issues.  Not sure if they’re fully up yet.  

2015-04-12 00:14:47 WARNING SEARCHQUEUE-MANUAL-155201 :: Connection error [Errno 1] _ssl.c:499: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error while loading URL 

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 10, 2015 at 11:48:42, Alexandre Beloin (notifications@github.com) wrote:

https://broadcasthe.net/maintenance.htm

**Comment by abeloin** [comment] 2015-04-12 15:25
Check your openssl version. It could be the reason why you get a protocol mismatch

https://www.ssllabs.com/ssltest/analyze.html?d=broadcasthe.net&s=141.101.118.104&hideResults=on

**Comment by ahaghgoo** [comment] 2015-04-13 02:34
Thanks Alexandre, 

The connectivity issue corrected itself and SickRAGE downloaded most of the shows that I subscribed to.  Unfortunately it did not post process the downloaded shows and it did not download any of the Real Time shows and I received one entry of this error and I couldn’t find the entry in the regular log as it didn’t have entries that went that far back: 

2015-04-12 12:34:30 SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined

I know that there are quite a few issues there but not sure if they’re related so that’s why I stated them in the mail for clues and troubleshooting’s sake.  

Thanks again for the consideration!  

-A

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 12, 2015 at 8:25:42, Alexandre Beloin (notifications@github.com) wrote:

Check your openssl version. It could be the reason why you get a protocol mismatch

https://www.ssllabs.com/ssltest/analyze.html?d=broadcasthe.net&s=141.101.118.104&hideResults=on

**Comment by ahaghgoo** [comment] 2015-04-13 03:25
Ok I restarted and I received the errors with more details: 

2015-04-12 20:19:46 ERROR    SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined
AA
AAtimeout: timed out
AA    data = self._sock.recv(left)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/socket.py", line 378, in read
AA    data = response.read(1024)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 139, in parse_response
AA    return self.parse_response(sock.makefile())
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 129, in single_request
AA    return self.single_request(host, handler, request_body, verbose)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
AA    verbose=self.__verbose
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
AA    return self.__send(self.__name, args)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py", line 1224, in __call__
AA    getattr(p, func_name)(torrent)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 314, in load_torrent
AA    torrent = self.auth.load_torrent(result.content)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/rtorrent.py", line 107, in _add_torrent_file
2015-04-12 20:19:16 INFO     SEARCHQUEUE-BACKLOG-72231 :: Downloading Real.Time.With.Bill.Maher.2015.03.20.720p.HDTV.x264-BATV from BTN
2015-04-12 20:19:16 INFO     SEARCHQUEUE-BACKLOG-72231 :: Quality of Real.Time.With.Bill.Maher.2015.03.20.720p.HDTV.x264-BATV is HD TV
2015-04-12 20:19:13 INFO     SEARCHQUEUE-BACKLOG-72231 :: [BTN] :: Performing episode search for Real Time with Bill Maher
2015-04-12 20:19:13 INFO     SEARCHQUEUE-BACKLOG-72231 :: Building internal name cache for Real Time with Bill Maher
2015-04-12 20:19:13 INFO     SEARCHQUEUE-BACKLOG-72231 :: No scene exceptions update needed
2015-04-12 20:19:13 INFO     SEARCHQUEUE-BACKLOG-72231 :: Beginning backlog search for: [Real Time with Bill Maher]
2015-04-12 20:19:12 INFO     SEARCHQUEUE-BACKLOG-80646 :: No needed episodes found during backlog search for: [Frontline]
2015-04-12 20:19:11 INFO     SEARCHQUEUE-BACKLOG-80646 :: Performing season pack search for Frontline
2015-04-12 20:19:11 INFO     SEARCHQUEUE-BACKLOG-80646 :: FALLBACK SEASON PACK SEARCH INITIATED ...
2015-04-12 20:19:10 INFO     SEARCHQUEUE-BACKLOG-80646 :: [BTN] :: Performing episode search for Frontline
2015-04-12 20:19:10 INFO     SEARCHQUEUE-BACKLOG-80646 :: Building internal name cache for Frontline
2015-04-12 20:19:10 INFO     SEARCHQUEUE-BACKLOG-80646 :: No scene exceptions update needed
2015-04-12 20:19:10 INFO     SEARCHQUEUE-BACKLOG-80646 :: Beginning backlog search for: [Frontline]
AANone
2015-04-12 20:19:10 ERROR    SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined
AA
AAtimeout: timed out
AA    data = self._sock.recv(left)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/socket.py", line 378, in read
AA    data = response.read(1024)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 139, in parse_response
AA    return self.parse_response(sock.makefile())
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 129, in single_request
AA    return self.single_request(host, handler, request_body, verbose)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
AA    verbose=self.__verbose
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
AA    return self.__send(self.__name, args)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py", line 1224, in __call__
AA    getattr(p, func_name)(torrent)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 314, in load_torrent
AA    torrent = self.auth.load_torrent(result.content) 
AA File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/rtorrent.py", line 107, in _add_torrent_file 

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 12, 2015 at 19:34:15, Afshin Haghgoo (ahaghgoo@gmail.com) wrote:

Thanks Alexandre, 

The connectivity issue corrected itself and SickRAGE downloaded most of the shows that I subscribed to.  Unfortunately it did not post process the downloaded shows and it did not download any of the Real Time shows and I received one entry of this error and I couldn’t find the entry in the regular log as it didn’t have entries that went that far back: 

2015-04-12 12:34:30 SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined

I know that there are quite a few issues there but not sure if they’re related so that’s why I stated them in the mail for clues and troubleshooting’s sake.  

Thanks again for the consideration!  

-A

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 12, 2015 at 8:25:42, Alexandre Beloin (notifications@github.com) wrote:

Check your openssl version. It could be the reason why you get a protocol mismatch

https://www.ssllabs.com/ssltest/analyze.html?d=broadcasthe.net&s=141.101.118.104&hideResults=on

**Comment by bonega** [comment] 2015-04-15 10:41
I am getting the same problem with a specific show.
Can I provide anymore info? The stacktrace is more or less the same as the previous poster.

**Comment by fernandog** [comment] 2015-04-15 11:34
@ahaghgoo 

from your log: "timed out"

check if rtorrent is running and check your user/pass/IP settings

**Comment by fernandog** [comment] 2015-04-15 11:48
@ahaghgoo didn't you received "Return code undefined" anymore?

**Comment by ahaghgoo** [comment] 2015-04-15 23:46
Hi Fernando, 

I’ve checked my login, and it currently logs in properly to BTN.  Additionally the “Return code undefined” errors are still persisting.  Let me know how I can provide any additional info that’s necessary.  Thanks!  -A 

015-04-15 09:20:13 SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-15 09:19:32 SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-15 03:20:42 SHOWQUEUE-REFRESH :: No episode number found in /share/Multimedia/Television/House, M.D./Season 5/']XZASDop[.mkv, ignoring it
2015-04-14 21:20:07 SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-14 21:19:24 SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-14 09:19:53 SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined 
2015-04-14 09:19:15 SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 15, 2015 at 4:48:50, Fernando (notifications@github.com) wrote:

@ahaghgoo didn't you received "Return code undefined" anymore?

**Comment by fernandog** [comment] 2015-04-15 23:55
@ahaghgoo check if this torrents are already in rtorrent (Maybe its giving this error because its duplicate)

**Comment by ahaghgoo** [comment] 2015-04-16 00:11
Yes, they’re in but SickRage has considered them as “snatched” rather than “downloaded” and processed.  The errors are preventing the snatches from being processed.  -A 

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 15, 2015 at 16:55:30, Fernando (notifications@github.com) wrote:

@ahaghgoo check if this torrents are already in rtorrent (Maybe its giving this error because its duplicate)

**Comment by bonega** [comment] 2015-04-21 09:05
I still have the same problem in 057e85a3e32a44cf4912d02662dd3de9f9679d5e

**Comment by abeloin** [comment] 2015-04-21 12:56
@bonega Provide the debug log associated with the error.

**Comment by ahaghgoo** [comment] 2015-04-22 02:12
Is the debug log any different than the regular log?  In any case I’d like to update this by saying while SickRAGE downloads the torrents for currently running shows (even though for some reason they don’t get processed), it doesn’t download the torrents for any backlogged shows.  Here’s an example: 

2015-04-21 19:05:49 ERROR    SEARCHQUEUE-MANUAL-84947 :: rTorrent: Unable to send Torrent: Return code undefined
AA
AAtimeout: timed out
AA    data = self._sock.recv(left)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/socket.py", line 378, in read
AA    data = response.read(1024)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 139, in parse_response
AA    return self.parse_response(sock.makefile())
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 129, in single_request
AA    return self.single_request(host, handler, request_body, verbose)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
AA    verbose=self.__verbose
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
AA    return self.__send(self.__name, args)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py", line 1224, in __call__
AA    getattr(p, func_name)(torrent)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 314, in load_torrent
AA    torrent = self.auth.load_torrent(result.content)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/rtorrent.py", line 107, in _add_torrent_file
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Downloading Boardwalk.Empire.S04.1080p.BluRay.DTS.x264-VietHD from BTN
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Every ep in this season is needed, downloading the whole torrent Boardwalk.Empire.S04.1080p.BluRay.DTS.x264-VietHD
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 84947 AND season in  4]
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-KDL is 1080p BluRay
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.576p.BluRay.DD5.1.x264-HiSD is Unknown
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.BluRay.x264-DEMAND is Unknown
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080p.BluRay.DTS-HD.MA5.1.H.264-HDWinG is 1080p BluRay
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.HDTV.x264-BTN is SD TV
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.720p.HDTV.x264-BTN is HD TV
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.720p.HDTV.DD5.1.x264-NTb is HD TV
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080i.HDTV.DD5.1.MPEG2-CtrlHD is RawHD TV
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080p.HDTV.x264-BTN is 1080p HD TV
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.720p.BluRay.DD5.1.x264-DON is 720p BluRay
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.720p.BluRay.x264-DEMAND is 720p BluRay
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080p.BluRay.x264-ROVERS is 1080p BluRay
2015-04-21 19:05:19 INFO     SEARCHQUEUE-MANUAL-84947 :: Quality of Boardwalk.Empire.S04.1080p.BluRay.DTS.x264-VietHD is 1080p BluRay
2015-04-21 19:05:18 INFO     SEARCHQUEUE-MANUAL-84947 :: [BTN] :: Performing season pack search for Boardwalk Empire
2015-04-21 19:05:18 INFO     SEARCHQUEUE-MANUAL-84947 :: Building internal name cache for Boardwalk Empire
2015-04-21 19:05:18 INFO     SEARCHQUEUE-MANUAL-84947 :: No scene exceptions update needed
2015-04-21 19:05:18 INFO     SEARCHQUEUE-MANUAL-84947 :: Beginning manual search for: [Boardwalk Empire - 4x12 - Farewell Daddy Blues]

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 21, 2015 at 5:56:27, Alexandre Beloin (notifications@github.com) wrote:

@bonega Provide the debug log associated with the error.

**Comment by abeloin** [comment] 2015-04-22 02:52
@ahaghgoo Yes it provide additional info to help find the issue. See the readme on the page where you opened your issue: https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

Check your rtorrent config, it doesn't respond to add torrent request. Can you provide the logs from rtorrent?

**Comment by ahaghgoo** [comment] 2015-04-22 03:45
Not that I know of.  I cross posted this on the QNAP rtorrent forum where the developer regular checks and responds to issues (http://forum.qnap.com/viewtopic.php?f=146&t=109508).  Maybe he can provide some insight on the communication issue between rtorrent and SickRAGE.

I looked at the log again and it looks like it’s an xmlrpc issue.  I ran into a similar issue when trying to use BarMagnet on my iPhone to communicate with rtorrent.  BarMagnet would “see” rtorrent, but it wouldn’t load any of the torrents from rtorrent.  The developer of BarMagnet added a different option to communicate with rtorrent via the httprpc plugin that comes with rutorrent (https://github.com/Novik/ruTorrent/tree/master/plugins/httprpc).  

So my question is, could SickRAGE be set to communicate with rtorrent via the httprpc plugin?  

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 21, 2015 at 19:52:15, Alexandre Beloin (notifications@github.com) wrote:

@ahaghgoo Yes it provide additional info to help find the issue. See the readme on the page where you opened your issue: https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

Check your rtorrent config, it doesn't respond to add torrent request. Can you provide the logs from rtorrent?

**Comment by abeloin** [comment] 2015-04-22 04:04
@ahaghgoo It's already supported as I use it.

Your url should be something like this: `https://localhost/rutorrent/plugins/httprpc/action.php`

**Comment by ahaghgoo** [comment] 2015-04-22 04:14
Yes, I forgot.  I did have it set similarly: scgi://localhost:5000/rutorrent/plugins/httprpc/action.php

So I was experiencing these errors with the httprpc plugin.   

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 21, 2015 at 21:04:41, Alexandre Beloin (notifications@github.com) wrote:

@ahaghgoo It's already supported as I use it.

Your url should be something like this: https://localhost/rutorrent/plugins/httprpc/action.php

**Comment by abeloin** [comment] 2015-04-22 04:18
Don't use scgi as the schema, use http or https.

**Comment by ahaghgoo** [comment] 2015-04-22 04:35
Unfortunately I can’t get it to connect using http or https.  I’ll have to await for the QNAP rtorrent developer to see if he can address the issue why rtorrent can’t communicate with SickRAGE.  -A 

--
Afshin Haghgoo 
ahaghgoo@gmail.com

On April 21, 2015 at 21:18:51, Alexandre Beloin (notifications@github.com) wrote:

Don't use scgi as the schema, use http or https.

**Comment by abeloin** [comment] 2015-04-22 14:08
Can you post a screenshot of your rtorrent settings in SR?

**Comment by bonega** [comment] 2015-04-22 17:14
Here is a link to my debug: https://gist.github.com/bonega/216fe04d7f45fff4e531#file-gistfile1-py
Using hdbits as a search provider.
It seems to affect only season packs.
(Right now I can't confirm that any season packs can be downloaded, even though I am pretty sure that some were successful)

**Comment by fernandog** [comment] 2015-04-22 17:22
https://github.com/SiCKRAGETV/sickrage-issues/issues/1382

**Comment by fernandog** [comment] 2015-04-22 17:23
https://github.com/SiCKRAGETV/sickrage-issues/issues/1255

**Comment by abeloin** [comment] 2015-04-22 23:41
@bonega Do you use rtorrent with the http rpc pplugin? If so, can you switch to the http(s) version?

**Comment by bonega** [comment] 2015-04-23 09:29
@abeloin No, I was using scgi.
It should probably have a warning-text until it is fixed.

With httprpc it works as intended.
Thanks.

**Comment by ahaghgoo** [comment] 2015-04-24 01:14
@abeloin I reviewed the screenshot you linked to and I couldn't get the http to work.  So I went back to using scgi which is in the screenshot below.  My rtorrent install on my QNAP NAS is located here, which I can ssh into: [hostname:22]/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/www/ui/rtorrent

![screenshot 2015-04-23 18 09 49](https://cloud.githubusercontent.com/assets/1308002/7310623/2f84c72a-e9e4-11e4-9001-b2618e6def7d.png)

**Comment by fernandog** [comment] 2015-07-17 15:40
@ahaghgoo do you still have this issue??

**Comment by masterxdk** [comment] 2015-07-18 22:24
Hi, 

I have the same problem on my QNAP... And if i try to use scgi it takes time before it fails. By using http, it fails instantaneously.

Host, port and credentials is correct and double checked

**Comment by fernandog** [comment] 2015-07-20 13:48
@masterxdk need full logs with debug enable in advanced settings

**Comment by fernandog** [comment] 2015-07-23 15:30
@ahaghgoo is this an issue for you? otherwise will close

**Comment by raymondtrueman** [comment] 2015-07-25 15:00
@fernandog Dont close this, I also get this error every now and again. I will post debug logs when it happens again

**Comment by fernandog** [comment] 2015-07-25 15:13
make sure you have debug enabled in SR settings

**Comment by raymondtrueman** [comment] 2015-07-25 15:20
I just enabled it now

**Comment by fernandog** [comment] 2015-07-29 15:11
@raymondtrueman no errors?

**Comment by raymondtrueman** [comment] 2015-07-29 15:18
@fernandog Yes I did get the error, and I think I know whats happening. When a torrent is snatched that already exists in rtorrent queue it returns an "unknown" return code. Dont know if you want to have a look at catching that return code and rather logging an warning instead of an error when that code is returned

**Comment by fernandog** [comment] 2015-07-29 15:19
@raymondtrueman thanks! I'm wondering if other problems can cause unknown return code

**Comment by raymondtrueman** [comment] 2015-07-30 20:33
Yes, its definitely possible, this error comes up every now and again on this issue list. Maybe we can try and print the return codes in the log so we know what they look like. Or we can contact rtorrent developers to give us a doc in order to interpret the return codes. Here is a pastebin of the thread that led up to the error in my case if it helps: http://pastebin.com/R75DT8Wj

**Comment by Noktam** [comment] 2015-08-07 03:43
Same problem, only with btn, i try with both 
https://localhost/rutorrent/plugins/httprpc/action.php
and
scgi://localhost:5002

And i get : 
2015-08-07 05:35:12 ERROR    SEARCHQUEUE-BACKLOG-3332 :: [BTN] :: rTorrent: Unable to send Torrent: Return code undefined
AA
AAtimeout: timed out
AA    data = self._sock.recv(left)
AA  File "/usr/lib/python2.7/socket.py", line 380, in read
AA    data = response.read(1024)
AA  File "/opt/sickrage/lib/rtorrent/lib/xmlrpc/scgi.py", line 139, in parse_response
AA    return self.parse_response(sock.makefile())
AA  File "/opt/sickrage/lib/rtorrent/lib/xmlrpc/scgi.py", line 129, in single_request
AA    return self.single_request(host, handler, request_body, verbose)
AA  File "/opt/sickrage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
AA    verbose=self.__verbose
AA  File "/opt/sickrage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
AA    return self.__send(self.__name, args)
AA  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
AA    getattr(p, func_name)(torrent)
AA  File "/opt/sickrage/lib/rtorrent/__init__.py", line 314, in load_torrent
AA    torrent = self.auth.load_torrent(result.content)
AA  File "/opt/sickrage/sickbeard/clients/rtorrent_client.py", line 107, in _add_torrent_file
2015-08-07 05:34:42 INFO     SEARCHQUEUE-BACKLOG-3332 :: [BTN] :: Downloading Doctor.Who.2005.S07.720p.Bluray.DD5.1.x264-NTb from BTN

**Comment by raymondtrueman** [comment] 2015-08-31 20:51
@fernandog The "Need Feedback" lable should be removed from this issue

**Comment by fernandog** [comment] 2015-09-30 02:13
@ahaghgoo @raymondtrueman @Noktam do you still have this issue?

**Comment by raymondtrueman** [comment] 2015-09-30 07:55
@fernandog  I personally haven't had the issue in a while but the root cause of the issue has not been resolved. It can definitely pop up again, unless somebody actually did do something in the code, but I'm not sure

**Comment by miigotu** [comment] 2015-09-30 09:20
likely there were changes to the code. since it hasn't been reported in so long I would guess it is resolved, not that the core issue is unresolved.

**Closed** 2015-09-30 09:20 UTC
Labels: 1: Bug / issue, 3: Confirmed, 4: Fix pending, 4: Need feedback

**Comment by fernandog** [comment] 2015-09-30 11:00
@raymondtrueman why root cause was not resolved?

**Comment by jaffacake** [comment] 2015-11-09 22:27
I'm getting the same issue, but it's only happening for one specific torrent, others just worked fine. I'm running the latest version on QNAP too: 

2015-11-09 22:25:40 ERROR    SEARCHQUEUE-BACKLOG-153021 :: [TorrentLeech] :: rTorrent: Unable to send Torrent: Return code undefined
AA
AAtimeout: timed out
AA    data = self._sock.recv(left)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/socket.py", line 380, in read
AA    data = response.read(1024)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 139, in parse_response
AA    return self.parse_response(sock.makefile())
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 129, in single_request
AA    return self.single_request(host, handler, request_body, verbose)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
AA    verbose=self.__verbose
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
AA    return self.__send(self.__name, args)
AA  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py", line 1233, in __call__
AA    getattr(p, func_name)(torrent)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 314, in load_torrent
AA    torrent = self.auth.load_torrent(result.content)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/rtorrent_client.py", line 105, in _add_torrent_file
