### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-153021 :: Torrent file content is empty

### ISSUE THREAD

**Issue by HardbitCoded** [SiCKRAGETV/sickrage-issues#2088] opened 2015-07-13 08:37 UTC
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 23:30:12) [GCC 4.8.2]**
Operating System: **Linux-3.4.61+-armv7l-with-Linaro-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@010325315d75ed7aab47619b57106bcca6d280f6
Link to Log: https://gist.github.com/a3b0b3a20876db6d2af1
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: Torrent file content is empty
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by HardbitCoded** [comment] 2015-07-13 08:39
Hello, please find here extra info on the error
AA
AAContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
AA    raise ContentDecodingError(e)
AA  File "/home/***/SickRage/lib/requests/models.py", line 661, in generate
AA    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
AA  File "/home/***/SickRage/lib/requests/models.py", line 733, in content
AA    r.content
AA  File "/home/***/SickRage/lib/requests/sessions.py", line 613, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/***/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/home/***/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True)
AA  File "/home/***/SickRage/sickbeard/helpers.py", line 1381, in getURL

**Comment by miigotu** [comment] 2015-07-13 11:00
torrage sent an invalid result, if it's a one time thing ignore it.

**Comment by fernandog** [comment] 2015-07-13 11:06
@HardbitCoded do you use proxy?

**Comment by HardbitCoded** [comment] 2015-07-13 12:53
@fernandog -> No, I don't use a proxy.
@miigotu -> I'll cleanup the logs and check it again later. As it only happens when setting files to download.

**Comment by ripper1967** [comment] 2015-07-21 14:56
i am having a problem like this only with piratebay at the moment,not producing an error but not searcing any further for it after here is part of the log https://gist.github.com/ripper1967/e6978eb9eede93431477

**Comment by fernandog** [comment] 2015-07-21 14:57
@miigotu was fixing it or already fixed

**Comment by ripper1967** [comment] 2015-07-21 14:59
i am up to date  with master commit, sorry i didnt say that. are you saying the fix is in dev or being fixed?

**Comment by fernandog** [comment] 2015-07-21 15:02
being fixed. not yet in dev

**Comment by ripper1967** [comment] 2015-07-21 15:04
ok  thanks..

**Comment by ripper1967** [comment] 2015-07-21 15:22
ok forget mine fernandog, the torrent dont exist sorry, i tryed searching for it

**Closed** 2015-07-21 23:59 UTC
Labels: 1: Support / question

**Comment by dali01** [comment] 2015-07-22 17:50
@miigotu Why was this issue closed? The problem is still there, at least for TPB...
```
2015-07-22 19:17:08 WARNING  SEARCHQUEUE-BACKLOG-255192 :: Torrent file content is empty
2015-07-22 19:17:08 WARNING  SEARCHQUEUE-BACKLOG-255192 :: Content-Encoding was gzip, but content was not compressed
2015-07-22 19:17:08 INFO     SEARCHQUEUE-BACKLOG-255192 :: Downloading Call.The.Midwife.4x08.HDTV.x264-FoV[ettv] from ThePirateBay
```

**Comment by fernandog** [comment] 2015-07-22 17:54
@dali01 if you download that torrent from TPB, you will see that i's a bad torrent

**Comment by dali01** [comment] 2015-07-22 18:00
@fernandog Bad? I added the magnet link manually in Transmission, and the file downloaded immediately. So it is definitely working...

**Comment by fernandog** [comment] 2015-07-22 18:02
@dali01 are you on develop or master?

**Comment by dali01** [comment] 2015-07-22 18:08
@fernandog I'm on master

**Comment by fernandog** [comment] 2015-07-22 18:10
@dali01 please try develop with that same episode/show. force manual search and see post logs

**Comment by dali01** [comment] 2015-07-22 18:23
@fernandog Yes, switching to develop seems to have fixed the issue! Thank you for that.

**Comment by fernandog** [comment] 2015-07-22 18:26
@dali01 we disabled a cache site that was providing bad files

**Comment by dali01** [comment] 2015-07-22 18:33
@fernandog Will that be merged into master branch now? I don't want to stay on develop branch unless it's necessary. Thanks again for the fix.

**Comment by fernandog** [comment] 2015-07-22 18:36
soon. don't know exactly when

you can go back to master, stop SR and make manually this changes in SR:
https://github.com/SiCKRAGETV/SickRage/commit/b72e4c33769a9aa80db45e0fc851024642c14ed2
