### ISSUE TITLE
[APP SUBMITTED]: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by rrd911** [SiCKRAGETV/sickrage-issues#256] opened 2014-12-21 21:32 UTC
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@49ea8f5ac7841f6654509d48d72506923bc47c2a
Pastebin Log URL: http://pastebin.com/c9gnjVvn
### ERROR
```
Thread-745 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/raydias/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/raydias/sickrage/sickbeard/webserve.py", line 1994, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/home/raydias/sickrage/sickbeard/processTV.py", line 180, in processDir
    process_result = process_media(path, [video], nzbName, process_method, force, is_priority)
  File "/home/raydias/sickrage/sickbeard/processTV.py", line 407, in process_media
    process_result = processor.process()
  File "/home/raydias/sickrage/sickbeard/postProcessor.py", line 931, in process
    proper_path = ep_obj.proper_path()
  File "/home/raydias/sickrage/sickbeard/tv.py", line 2342, in proper_path
    result = self.formatted_filename(anime_type=anime_type)
  File "/home/raydias/sickrage/sickbeard/tv.py", line 2397, in formatted_filename
    return self._format_pattern(name_groups[-1], multi, anime_type)
  File "/home/raydias/sickrage/sickbeard/tv.py", line 2193, in _format_pattern
    replace_map = self._replace_map()
  File "/home/raydias/sickrage/sickbeard/tv.py", line 2143, in _replace_map
    '%0E': '%02d' % self.episode,
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by markheloking** [comment] 2015-01-05 17:21
Closing as it should be fixed in https://github.com/SiCKRAGETV/SickRage/commit/68e4acaf3730a114ccabc9585d8958676257142d.
Please report back if the problem persists.

**Comment by QuadPiece** [comment] 2015-07-28 15:04
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/40ec96ef0aed473e8198
### ERROR
```
SEARCHQUEUE-MANUAL-295224 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: %d format: a number is required, not NoneType
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by krandor** [comment] 2015-07-31 02:57
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8fa7a4bb777c9192bd706115579e540eed8461b2
Link to Log: https://gist.github.com/83628200cffbaa3609d3
### ERROR
```
SEARCHQUEUE-MANUAL-278626 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: %d format: a number is required, not NoneType
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-07-31 10:59
@miigotu out pattern format sxxexx won't work with absolute number isn't?

**Comment by miigotu** [comment] 2015-07-31 12:24
It never gets an absolute number, and even if it happened to, the numbers would be at worst 0 not None.

When we search by absolute number it still creates an episode object with the xem/indexer data mapped form the absolute number.

**Comment by fernandog** [comment] 2015-07-31 12:25
None is the cause of this issue.

**Comment by miigotu** [comment] 2015-07-31 12:28
Yes, but not because of absolute number. The search was
`search_string: http://www.nyaa.se/?page=rss&sort=2&term=Fate.Stay.Night.Unlimited.Blade.Works&cats=1_0`

**Comment by fernandog** [comment] 2015-07-31 12:38
if is not sxxee and not absolut, what is that?!

**Comment by miigotu** [comment] 2015-07-31 14:44
the nyatorrents provider is coded wrong. likely a poor job at copy and pasting from another fork.

**Comment by bb12489** [comment] 2015-08-06 01:15
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@47b2d5651f0c7ef1d8d20523dee85bc950d17e14
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79886 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: %d format: a number is required, not NoneType
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Greg0rz** [comment] 2015-08-06 02:55
Just wanted to say that I am also experiencing this issue.

Seems to be related to items that are all capital letters of scene names.

2015-08-05 22:43:25 SEARCHQUEUE-MANUAL-295224 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: %d format: a number is required, not NoneType

**Comment by miigotu** [comment] 2015-08-06 04:21
Nope, nyaatorrents provider is totally broken. it is not coded right for get_season_search_strings and get_episode_search_strings.

**Comment by krandor** [comment] 2015-08-07 02:55
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@9956e7beb05a387d7fbe68883c48dcb01230be6a
Link to Log: https://gist.github.com/d742ebaec8302993b5e6
### ERROR
```
Thread-63 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/krandor/.sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/krandor/.sickrage/sickbeard/webserve.py", line 2306, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/krandor/.sickrage/sickbeard/processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/krandor/.sickrage/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/home/krandor/.sickrage/sickbeard/postProcessor.py", line 988, in process
    releaseName = show_name_helpers.determineReleaseName(self.folder_path, self.nzb_name)
  File "/home/krandor/.sickrage/sickbeard/show_name_helpers.py", line 358, in determineReleaseName
    if filterBadReleases(folder):
  File "/home/krandor/.sickrage/sickbeard/show_name_helpers.py", line 71, in filterBadReleases
    NameParser().parse(name)
  File "/home/krandor/.sickrage/sickbeard/name_parser/parser.py", line 416, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/home/krandor/.sickrage/sickbeard/name_parser/parser.py", line 272, in _parse_string
    (s, e) = helpers.get_all_episodes_from_absolute_number(bestResult.show, [a])
  File "/home/krandor/.sickrage/sickbeard/helpers.py", line 724, in get_all_episodes_from_absolute_number
    ep = show.getEpisode(None, None, absolute_number=absolute_number)
  File "/home/krandor/.sickrage/sickbeard/tv.py", line 284, in getEpisode
    logger.log(str(self.indexerid) + u": An object for episode S%02dE%02d didn't exist in the cache, trying to create it" % (season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Greg0rz** [comment] 2015-08-07 16:56
Any plans to fix this? I'm not very good at python but if there's no plans I can start working on understanding the provider architecture and attempt to contribute.  

Let me know. Thanks,
Greg

**Comment by miigotu** [comment] 2015-08-07 19:37
Its in _get_season_search_strings and _get_episode_search_strings in sickbeard/providers/nyaatorrents.py. No time to fix it right now, and it is low priority as there are plenty of better/better working providers in SR.

If you want to fix it feel free to contribute, but be prepared for feedback on your patch.

**Comment by Greg0rz** [comment] 2015-08-09 21:49
Is there any reason that the Daily Searcher would work, but using SEARCHQUEUE-MANUAL would not?

Perhaps that could relate to a quick fix.  In the meantime I'm taking a look at the provider code..

**Comment by miigotu** [comment] 2015-08-09 22:14
daily search just updates rss cache from the provider. It does not call _get_season_search_strings or _get_episode_search_strings like backlog or manual search.

**Comment by Greg0rz** [comment] 2015-08-10 22:31
So far so good:

    def _get_season_search_strings(self, ep_obj):
        return [x for x in show_name_helpers.makeSceneSeasonSearchString(self.show, ep_obj)]

    def _get_episode_search_strings(self, ep_obj, add_string=''):
        return [x for x in show_name_helpers.makeSceneSearchString(self.show, ep_obj)]

**Comment by miigotu** [comment] 2015-08-11 03:53
@Greg0rz pr that change to develop if it works.

**Comment by Greg0rz** [comment] 2015-08-16 19:00
Not really sure how to do that.  Here is a link to the code:
http://pastebin.com/raw.php?i=CPs7TYMm

**Comment by WebSpider** [comment] 2015-08-16 21:38
I just sent in the PR on your behalf: SiCKRAGETV/sickrage-issues#2310

**Comment by joakim93** [comment] 2015-08-31 07:21
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/082b4a78b24a8c0b6a3c
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2274, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 212, in processDir
    for dir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 302, in validateDir
    process_failed(os.path.join(path, dirName), nzbNameOriginal, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 539, in process_failed
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/failedProcessor.py", line 68, in process
    segment = parsed.show.getEpisode(parsed.season_number, episode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 284, in getEpisode
    logger.log(str(self.indexerid) + u": An object for episode S%02dE%02d didn't exist in the cache, trying to create it" % (season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment] 2015-09-01 05:27
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/ae0eb8ba59ede04af552
### ERROR
```
Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2268, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 212, in processDir
    for dir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 302, in validateDir
    process_failed(os.path.join(path, dirName), nzbNameOriginal, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 539, in process_failed
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/failedProcessor.py", line 68, in process
    segment = parsed.show.getEpisode(parsed.season_number, episode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 284, in getEpisode
    logger.log(str(self.indexerid) + u": An object for episode S%02dE%02d didn't exist in the cache, trying to create it" % (season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment] 2015-09-01 05:48
Apparently not fixed in all cases

**Closed** 2015-09-28 20:31 UTC
Labels: 1: Bug / issue

**Comment by Ikucuk** [comment] 2015-10-03 20:59
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8da2f08a098731dc648794f137177ade2f4bb49
Link to Log: https://gist.github.com/df3641120fe0b53818e5
### ERROR
```
Thread-54 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2157, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 230, in processDir
    for dir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "C:\SickRage\sickbeard\processTV.py", line 370, in validateDir
    NameParser().parse(video, cache_result=False)
  File "C:\SickRage\sickbeard\name_parser\parser.py", line 420, in parse
    file_name_result = self._parse_string(base_file_name)
  File "C:\SickRage\sickbeard\name_parser\parser.py", line 273, in _parse_string
    (s, e) = helpers.get_all_episodes_from_absolute_number(bestResult.show, [a])
  File "C:\SickRage\sickbeard\helpers.py", line 891, in get_all_episodes_from_absolute_number
    ep = show.getEpisode(None, None, absolute_number=absolute_number)
  File "C:\SickRage\sickbeard\tv.py", line 288, in getEpisode
    logger.log(str(self.indexerid) + u": An object for episode S%02dE%02d didn't exist in the cache, trying to create it" % (season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment] 2015-10-15 20:31
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7
Link to Log: https://gist.github.com/060a73adeecc746671e6
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1990, in setSceneNumbering
    ep_obj = self._getEpisode(show, absolute=forAbsolute)
  File "/home/home/SickRage/sickbeard/webserve.py", line 633, in _getEpisode
    epObj = showObj.getEpisode(absolute_number=int(absolute))
  File "/home/home/SickRage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment] 2015-10-15 20:33
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7
Link to Log: https://gist.github.com/ffc3343c5ec16d6399f8
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1990, in setSceneNumbering
    ep_obj = self._getEpisode(show, absolute=forAbsolute)
  File "/home/home/SickRage/sickbeard/webserve.py", line 633, in _getEpisode
    epObj = showObj.getEpisode(absolute_number=int(absolute))
  File "/home/home/SickRage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment] 2015-10-15 20:35
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7
Link to Log: https://gist.github.com/93be056adaa18e5baddb
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1990, in setSceneNumbering
    ep_obj = self._getEpisode(show, absolute=forAbsolute)
  File "/home/home/SickRage/sickbeard/webserve.py", line 633, in _getEpisode
    epObj = showObj.getEpisode(absolute_number=int(absolute))
  File "/home/home/SickRage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment] 2015-10-15 20:38
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7
Link to Log: https://gist.github.com/e441d8d94e44e8b0fd0a
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1990, in setSceneNumbering
    ep_obj = self._getEpisode(show, absolute=forAbsolute)
  File "/home/home/SickRage/sickbeard/webserve.py", line 633, in _getEpisode
    epObj = showObj.getEpisode(absolute_number=int(absolute))
  File "/home/home/SickRage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment] 2015-10-15 20:39
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7
Link to Log: https://gist.github.com/da2f88e5c303b81a5b1e
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1990, in setSceneNumbering
    ep_obj = self._getEpisode(show, absolute=forAbsolute)
  File "/home/home/SickRage/sickbeard/webserve.py", line 633, in _getEpisode
    epObj = showObj.getEpisode(absolute_number=int(absolute))
  File "/home/home/SickRage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/home/SickRage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-10-15 20:40
Anime? Absolute number? Air by date?

**Comment by duramato** [comment] 2015-10-15 20:42
@fernandog Set a show to anime,and enable scene numbering then try to set a scene absolute
And it should give the error...

**Comment by fernandog** [comment] 2015-10-15 20:50
@miigotu any idea how to handle that? We have a lof of 

%s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode)

**Comment by miigotu** [comment] 2015-10-15 22:43
`%s S%02dE%02d" % (self.show.indexerid, self.show.name, season or 0, episode or 0)`
