### ISSUE TITLE
backlog search ineffective 

### ISSUE THREAD

**Issue by sgtwtf** [SiCKRAGETV/sickrage-issues#496] opened 2015-01-26 19:48 UTC
Maybe a configuration on my part but i don't know whats wrong. When it searcher for a new episode that airs now. it finds it no problem. 
However, if i go into that show and click search the next day it won't find anything. quality does not matter.

I discovered this while troubleshooting my Mythbusters. I can manually go to my indexer and find and download the file and SR will post-process as expected but it will not find on its own.
I am running SR BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Python 2.7.3
http://pastebin.com/UMJZaJjW

**Comment by fernandog** [comment] 2015-01-26 19:55
@sgtwtf have you enabled in all providers "daily search" and "backlog search" ?

**Comment by sgtwtf** [comment] 2015-01-26 20:00
Yes they are. A long time ago I didn't and I figured that out then. I don't
see what is wrong

**Comment by abeloin** [comment] 2015-01-26 20:08
It's looking for S01E01
```
Search string: http://kickass.so/usearch/MythBusters+S01E01%7C1x01+category%3Atv/?field=seeders&sorder=desc&rss=1
```

**Comment by sgtwtf** [comment] 2015-01-26 20:20
For a portion it is. It also searches nzbgeek and oznzbd

**Comment by abeloin** [comment] 2015-01-26 20:37
It is weird as sickrage says it's looking for 1x4 but actually request search results for 1x1 to nzbgeek and oznzbd.

Could you try with another episode and posting the resulting log?

**Comment by fernandog** [comment] 2015-01-26 20:41
@sgtwtf we don't support changes in the code like changing thepiratebay to use oldpiratebay. 
please try without TPB and post new log please.

**Comment by sgtwtf** [comment] 2015-01-26 20:47
new log http://pastebin.com/V6bz7Uwh

And just an FYI i did not change one piece of code i wouldn't know where to start lol

**Comment by fernandog** [comment] 2015-01-26 21:00
@sgtwtf I don't remember SR changing TPB to OldPB. Sorry.
will check

**Comment by sgtwtf** [comment] 2015-01-26 21:01
No it OK, its fine. Just want to give the experts what they want how they
want it.

**Comment by fernandog** [comment] 2015-01-26 21:03
@sgtwtf the results for this show don't follow scene naming pattern so SR can't snatch.

**Comment by abeloin** [comment] 2015-01-26 21:04
Now for 1x6 it's lookin for 1x4.

@sgtwtf Which provider are you using?

**Comment by sgtwtf** [comment] 2015-01-26 21:05
What does that mean? If the show has a season. 1 episode 6 and there is a
file that has the show name with matching episode and season why wouldn't
it grab the file?

**Comment by sgtwtf** [comment] 2015-01-26 21:07
I had scene numbering at one point but I took it off before I posted my
issue..my provider is nzbgeek. I can manually grab files with no issue from
that site.

**Comment by abeloin** [comment] 2015-01-26 21:12
@sgtwtf In the Mythbusters show page in sickrage, look on the left were the stars and country flag are. You should 3 icons after ```(2003) - 44 minutes```: imdb, (thetvdb or rage) and xem
Which icon is the second one? Look like a tv with antenna or like brown circle eye?

**Comment by sgtwtf** [comment] 2015-01-26 21:14
its thetvdb then xem

**Comment by sgtwtf** [comment] 2015-01-26 21:16
i tried a different tv series and same issue. am i the only one that can't do manual searches?

**Comment by sgtwtf** [comment] 2015-01-26 21:17
![image](https://cloud.githubusercontent.com/assets/7502836/5908572/af61ebd8-a55d-11e4-8645-adc8f6c13b00.png)

**Comment by abeloin** [comment] 2015-01-26 21:23
In a different series you look for 1x04 and searching for 1x01 also?

**Comment by abeloin** [comment] 2015-01-26 21:25
Also you should enable scene numbering.

**Comment by sgtwtf** [comment] 2015-01-26 21:55
I tried on a current seasons EP of big bang theory still no luck.

**Comment by fernandog** [comment] 2015-01-26 22:02
The result Mythbusters.S01E01.SDTV.Jet.Assisted.Chevy-NZBgeek doesn't seem to be a valid episode that we are trying to snatch, ignoring
- Missing codec info.
The result Mythbusters-S01E03-Larrys.Lawn-Chair.Balloon.Goldfinger.Poppy-Seed.Drug.Test-NZBgeek doesn't seem to be a valid episode that we are trying to snatch, ignoring
- Missing codec info
The result Mythbusters.S01E03.SDTV.Larrys.Lawn-Chair.Balloon.Goldfinger.Poppy-Seed.Drug.Test.DVDRip-memetic-NZBgeek doesn't seem to be a valid episode that we are trying to snatch, ignoring
- Missing codec info

**Comment by abeloin** [comment] 2015-01-26 22:24
@sgtwtf Do you have a log?

@fernandog I think the issue is related to xem. If you look the xem page for (mythbusters)[http://thexem.de/xem/show/285], you will see ep4 is mapped to ep1.

**Comment by fernandog** [comment] 2015-01-26 22:33
@abeloin yes. but all torrents for this show don't have he correct naming pattern.
closing this issue.

**Comment by sgtwtf** [comment] 2015-01-26 22:33
But it does the same thing for the big bang theory

**Closed by fernandog** 2015-01-26 22:33 UTC
Labels: 1: Support / question

**Comment by fernandog** [comment] 2015-01-26 22:34
@sgtwtf new logs please.
