### ISSUE TITLE
[Feature Request] Set debug=1 before submitting an issue

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1987] opened 2015-07-07 13:24 UTC
logs don't have debug so making hard to "debug"

**Comment by miigotu** [comment] 2015-07-09 06:17
@fernandog why not just disable submitting issues altogether if debug = 0?

**Comment by neoatomic** [comment] 2015-07-09 10:16
We can also consider to enable debug=1 by force when a user adds a git user-name/password.

**Comment by miigotu** [comment] 2015-07-09 10:24
I think we should be encouraging users to investigate their problems before submitting an issue, but that's just me. `click submit` -> `you must enable debug and experience the error again` = no reports that cant be reproduced at least by the user.  The more time we spend explaining things to people the less time we have to fix real problems.

On a side note, things that should be self explanatory in the ui but we constantly get questions about should be looked into making more noob friendly. Also, if any option can be made automated in some ingenious way to eliminate it form the ui we need to do that.  SR does so much that it can seem cluttered or too complex and overwhelming to a new user, and they spam issues because they don't know whats going on.

**Comment by miigotu** [comment] 2015-07-09 10:25
Also, when debug is on, the default drop-down should be set to debug in the log, a lot of people dont realize to switch it to debug so they can see the error.

**Comment by neoatomic** [comment] 2015-07-09 10:34
Agreed. But we need to realize that we wont get all the errors than, as some wont be submitted by users that (for whatever reason) don't enable the debug function.

**Comment by miigotu** [comment] 2015-07-09 12:08
That's good, we don't need every error that can happen with user error, we need real errors and be able to notice the persistent ones easier.

If a user has an error and they try to submit it, and they got a popup saying they need to enable debug and reproduce, we don't get fluke errors that cant be reproduced, and the user will take more time to maybe notice the cause before submitting.

Flooding with 100 issues a day is not productive, because we surely do not have that many errors.

**Comment by fernandog** [comment] 2015-07-24 15:50
I'm not sure if makes sense anymore. I reads directly from LOG file:

```
        try:
            # read log file
            log_data = None

            if os.path.isfile(self.logFile):
                with ek.ek(codecs.open, *[self.logFile, 'r', 'utf-8']) as f:
                    log_data = f.readlines()
                    
            for i in range (1 , int(sickbeard.LOG_NR)):
                if os.path.isfile(self.logFile + "." + str(i)) and (len(log_data) <= 500):
                    with ek.ek(codecs.open, *[self.logFile + "." + str(i), 'r', 'utf-8']) as f:
                            log_data += f.readlines()

            log_data = [line for line in reversed(log_data)]
```
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/logger.py#L170

**Comment by miigotu** [comment] 2015-07-24 21:37
if debug is 0 it doesn't write debug to log file does it?

**Comment by fernandog** [comment] 2015-07-24 21:49
So not make sense the FR. Error happened before

**Comment by miigotu** [comment] 2015-07-24 22:26
Thats why I suggested to not allow the issue to be submitted, but tell them enable debug and reproduce before they can submit =P

**Comment by fernandog** [comment] 2015-07-24 22:28
Why not force enable debug for all until we are not 100% stable?

**Comment by WebSpider** [comment] 2015-07-24 23:03
100% stable is a myth. Forcing debug for all will result in very fast rolling over of logfiles.

**Comment by WebSpider** [comment] 2015-08-14 15:19
Isn't this in https://github.com/SiCKRAGETV/SickRage/releases/tag/v4.0.48 ?

**Comment by miigotu** [comment] 2015-08-14 16:03
In a slightly different approach yes. This FR was to enable debug when sending an issue automagically. My change just prevents submission if debug=0. I think that approach is the best we can do, so closing this now.

**Closed by miigotu** 2015-08-14 16:03 UTC
Labels: 1: Feature request
