### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u2013' in position 63: ordinal not in range(128)

### ISSUE THREAD

**Issue by FelipeSQ** [SiCKRAGETV/sickrage-issues#2874] opened 2015-09-20 11:38 UTC
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6d7fd7062f8d827f88c53994db696d81270c8354
Link to Log: https://gist.github.com/ce7ba7d8f0d40e5ab059
### ERROR
```
SHOWQUEUE-REFRESH :: 71663: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment] 2015-09-20 12:39
@FelipeSQ U need to use this package. The one u are currently using is outdated.
http://apps.qnap.community/11-community/17-qsickrage

The error itself is related to a special character.

**Comment by FelipeSQ** [comment] 2015-09-20 15:24
Hey Neo, thanks for that. Maybe that was why I didn't see any new updates on the past month then. I will try it here, thanks!

**Comment by medariox** [comment] 2015-09-20 16:44
@FelipeSQ Does the video contain embedded subtitles? If yes, SickRage won't download the subtitles that are already there (embedded), unless you have checked the option "Ignore subtitles embedded inside video file?" in your subtitles search settings. Anyway, what are your subtitle directory setting? Do you use a relative or absolute path?

The main problem, as you already said, seems to be related to some unrecognized characters in the embedded subtitles.

**Comment by FelipeSQ** [comment] 2015-09-20 17:04
Yeah. Sorry about not adding more info. So here it goes:

I always check to ignore the embed subtitles and i download them in 2
languages. Also, i add the language code to the subtitle name, and they
always go directly in the same directory as the files.

For this3 specific shows (family guy. Tje simpsons and hannibal). I added
them to sickrage at the same and always had trouble with the subtitles on
them, since the beggining. I already tried deleting everything and
recreating yhe folders and re-adding them to sickrage.

Here is the weird thing, sickrage will download, rename, and properly place
all the subtitlws files together with the videos. They just won't show as
downloaded (with the languages you have) for the show, nor will play in the
wdtv. And I got this error while trying a full refresh of any of the 3
shows. I do know that hannibal has some episodes names with french accents,
and that could be related. But I never understood family guy nor simpsons...

Also, the weird thing about the wdtv not being able to catch those
subtitles intrigues me even more. For those that use wdtv's, you know that
it can play almost anything, i am not streaming, i use a network share and
it all works well with all the other series. Even wayward pines that I
added to sickrage after adding the 3 mentioned that have the problem.

It really might be something in the subtitle file, since they are
downloaded and renamed, just never displayed.

I will do a file search to find any uncommon characters.  Thanks, guys!

**Comment by Psychoteur** [comment] 2015-09-27 09:06
Hello,
I've got the same errors on two separate installation. 
My personal installation all the file have been downloaded via Sickrage.

Here is some logs: 

       2015-09-27 10:56:59 FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 53: ordinal not in range(128)

        2015-09-27 10:56:59 FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 59: ordinal not in range(128)

        2015-09-27 10:56:59 FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 57: ordinal not in range(128)

**Comment by medariox** [comment] 2015-09-27 13:32
Sadly I can't reproduce any of the errors you guys are having, please look here for suggestions: https://github.com/SiCKRAGETV/sickrage-issues/issues/2965

**Comment by fernandog** [comment] 2015-09-27 13:45
@FelipeSQ please set locale to UTF-8 (specially LC_ALL) to user running SR. Check the user here: localhost:xxxx/config

Read here:
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by fernandog** [comment] 2015-09-27 13:47
@medariox he has a file with special chars and his locale it's not utf-8. this error happens when reading the file name

**Comment by neoatomic** [comment] 2015-09-30 11:20
There was a fixed pushed to master. Should be fixed now thanks to @medariox 
So make sure to update sickrage.

**Closed by neoatomic** 2015-09-30 11:20 UTC
Labels: 1: Support / question

**Comment by fernandog** [comment] 2015-09-30 11:22
@FelipeSQ
