### ISSUE TITLE
[Feature Request] Preview Rename should use downloaded episodes not snached

### ISSUE THREAD

**Issue by tdev5** [SiCKRAGETV/sickrage-issues#1420] opened 2015-04-25 18:45 UTC
The Preview Rename page uses snatched episodes to propose new names. It should use downloaded episodes.

Currently, when an episode is downloaded, and a higher quality is snatched, it wants to use the snatched quality in the new filename. AFAIK, if the download fails, it'll never propose the right names.

BRANCH: (master)
COMMIT: (975c0dd208c59cac8fd8a77a91da5d1dfc7235df)

**Comment by fernandog** [comment] 2015-04-25 23:35
@TagForce bug or FR?

**Comment by tdev5** [comment] 2015-04-26 00:56
I consider it a bug. It seems like an oversight, since you don't want people renaming things to the wrong quality, release group, release type, etc.

**Comment by tdev5** [comment] 2015-04-26 01:06
Oops, I see you were asking TagForce, not me.

**Comment by TagForce** [comment] 2015-05-01 12:12
@tdev5 @fernandog Sorry for taking so long to answer. Busy week at work, no spare time at home either... ugh... Almost done though.

As for the Preview Rename:
It uses the episode location in the database, and checks that with the episode's proper_path.
Proper_path is a function that reads an episode's information from the DB, and creates a filename according to the naming conventions that you have.
If that's information related to a snatched episode, then yes, it will use that information. We cannot change that behaviour at the moment, but tdev5 is right in that this is an oversight.

I would consider this a Feature Request, born from a wrong design decision earlier.
What we need to do is quite simply seperate the snatched episode information from the current episode information, as we're losing information that we might still want to use later on.
This change requires a lot of changes to the internal workings of SR, though, so that'll be a project on its own to be undertaken by a group once the number of issues goes down.

While this is being implemented, we should stop development of other major features, and limit ourselves to simple bugfixes (you the ones that can be fixed with 2 or 3 lines of code), as changing this behaviour will have a major impact on basically every part of SR.

Among others, the major parts that will need to be changed include:
- providers (as they download a release and will need to return the data somewhere else now)
- Post Processing (as it uses the episode info to name the files, and will now need to pick and choose either the snatched information, or the episode information)
- The database (as it will require more tables to store the information in)
- Webserve (as it will need to be able to display the new information)

Basically, I think about half of SR will need to be able to distinguish between snatched and completed information.

Ironically, one of the few parts that will not need to be changed is the renamer, as we will automatically be providing that with the correct information when we seperate the information.

We will need to evaluate all the parts of SR that need adapting before we do anything, and we need to design the new information in such a way that we can use it for future features (like download client management, so the snatched information needs the torrent hash/jobID as well).

I propose to take this on in 2 parts:
- The database change. Evaluate all the proposed features that require a change in the database. Decide on whether we'll implement the FR, and do the database update in one large update. This will save us from having to explain to users why they cannot go back to master from develop over and over again. Even if we're not using fields, it won't hurt having them in the database for future use.
- The code changes. Unfortunately I think this will need to be done in one large change. The information being seperated has so many ties with so many different pieces of code that I think taking it slowly will cause more harm than do good. This also means that development of other features will need to be paused until we're done with this part, and have a new stable code-base.

**Comment by tdev5** [comment] 2015-05-01 13:14
Am I right that there is a relationship between this issue, and #674?

For instance, see the [mockup here](https://github.com/SiCKRAGETV/sickrage-issues/issues/674#issuecomment-96896250), with status, downloaded quality, and snatched quality in separate columns.

**Comment by TagForce** [comment] 2015-05-01 14:23
@tdev5 Yes, the root cause for both requests being made is that SR has no way of storing snatched episode information other than the actual episode information.

**Comment by OmgImAlexis** [comment] 2015-09-26 14:09
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Closed by OmgImAlexis** 2015-09-26 14:09 UTC
Labels: 1: Feature request
