### ISSUE TITLE
UI Update hides "Edit" Button (and others) for Series

### ISSUE THREAD

**Issue by nrk666** [SiCKRAGETV/sickrage-issues#2279] opened 2015-07-22 17:07 UTC
BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

Not really a bug, maybe just a UI issue. The Top Menu (News, IRC, Shows, etc) expands to cover series "Edit" and other buttons if the browser isn't wide enough on series view. This should probably push that menu element down if not wide enough. 

![sr_menucovered](https://cloud.githubusercontent.com/assets/8151400/8831740/5d0e49b2-3072-11e5-8b6b-bfcea99e3983.jpg)

![sr_menu-uncovered](https://cloud.githubusercontent.com/assets/8151400/8831743/621faff4-3072-11e5-960e-3e9a2def574a.jpg)

**Comment by fernandog** [comment] 2015-07-22 17:21
Really don't know how to fix it.

@SiCKRAGETV/moderators any of you know well html/JS?

**Comment by miigotu** [comment] 2015-07-23 03:25
We could just shorten up some of the labels maybe, or replace them with icons.

Coming Episodes could be just Coming or Coming Soon
Logs & Errors could be just Logs

**Comment by fernandog** [comment] 2015-07-23 15:18
or crop Support image =)
in fact we should change image to "donation" of something.

**Comment by nrk666** [comment] 2015-07-24 14:00
I know you are trying, but cropping images isn't a solution. However, I am also clueless with html/JS so I have little to offer in the way of help on this. 

Can "IRC" be moved into the tools drop down? It's a good feature, but its use is probably limited to a small % of SR users.

**Comment by miigotu** [comment] 2015-07-24 14:20
Until the feature is well known among users we need to keep it up there. We want to encourage users to come there for help FIRST before creating issues, to lighten our daily load a little bit trying to manage questions we have previously answered hundreds of times.

Smaller images IS a solution, it may not have given enough real estate back yet, but it is a move in the right direction. Later, I hope to change that image entirely. And there is discussion of shortening the text labels up a bit.

`Coming Episodes` can easily be just `Coming`
`Logs & Errors` can easily be just `Logs`

**Comment by fernandog** [comment] 2015-07-24 14:22
I don't agree with tabs name changing.

Maybe a better fix is with buttons HTML alignment. I think they are float (that why they are hidded)
should be something else than float. not html expert

**Comment by fernandog** [comment] 2015-07-24 14:34
@MGaetan89 suggestions?!

**Comment by miigotu** [comment] 2015-07-24 14:39
float is the right way for them to be, that is irrelevant to overlap.

**Comment by nrk666** [comment] 2015-07-24 15:48
Changing image size is not a solution, it only provides a temporary band-aid at best. fernandog is totally correct when pointing out future additions causing the same issue, which means the real issue was never solved, only mitigated. I realize this isn't a critical bug, so I'm really not trying to be an ass about it, but lets call a spade a spade here. The top menu bar shouldn't overlap the function buttons beneath it, no matter how big/full that top menu bar is. Those functional buttons should be pushed down the page so as not to be overlapped based on browser width. Solve that problem, and it never comes back regardless of how many images/buttons/menus wind up in the top bar. 

I wish I had the knowledge to help out here, but python/html/JS isn't my forte. If you ever need large scale (petabyte+) storage engineering, lemme know. :)

**Comment by miigotu** [comment] 2015-07-24 21:48
The spade of it is, this UI is going to be replaced soon with one rewritten using mako. I agree that it "should" wrap, but wrapped divs look like ass and after we spend the time to make it wrap the next step will end up just being "damn that looks stupid, let's shorten up/reduce the number of items in the top bar temporarily until mako"

I don't see a good reason to go worrying about a css fix when a simple text change will do for now until mako replaces cheetah in august. (if the change is that immediately necessary at all)

**Comment by fernandog** [comment] 2015-07-24 21:50
How small is your screen??
my laptop is old and I dont have this

**Comment by miigotu** [comment] 2015-07-24 21:56
@fernandog I think he is reporting this issue using a cell phone. Although I also do not have this problem on my GS3

**Comment by MGaetan89** [comment] 2015-07-24 21:57
@fernandog Maybe it's possible to push the content down when the top bar needs more space.
I can try to suggest something after I'm done with #976 

@miigotu On a cell phone, the menu would collapse in a "hamburger" menu, so I think the issue is on a laptop.

**Comment by fernandog** [comment] 2015-07-24 22:00
maybe the collapse width is good for him

**Comment by miigotu** [comment] 2015-07-24 22:03
@MGaetan89

I can make it happen here now, just by changing width of my browser. Its only an issue for a range of like 40 pixels before it collapses the top bar to hamburger. Just increase the width of when it changes to hamburger menu to match closer to the width we added to the top bar and then eat the hamburger.

**Comment by nrk666** [comment] 2015-07-25 00:45
Nah, not mobile. I have a 4K monitor @ 3840x2160, but having a giant browser just isn't something I do, I have it set a certain way for some other windows that border it, so "just make it wider" messes with some other stuff. I didn't realize there were plans to replace the entire UI, so if this isn't worth it, whatever. It doesn't occur on my iPad because the entire top bar menu is behind a button you have to push to even see the top bar menu (which on iPad is more of a side menu).

**Comment by DigitalBrains1** [comment] 2015-07-25 09:15
I always use SickRage from my netbook, with a 1024x600 screen. The browser is always maximized. I was baffled when an update maybe two weeks ago or something made a lot of buttons disappear. I had no idea why.

When I saw this bug report, I opened SickRage, pressed Ctrl-minus and laughed out loud when the buttons re-appeared :).

This netbook is running Debian jessie/stable, and the browser is Iceweasel (unbranded Firefox, Build identifier: Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0).

**Comment by miigotu** [comment] 2015-07-25 09:40
It will get fixed soon enough, patience.

**Comment by DigitalBrains1** [comment] 2015-07-25 09:54
Sure, no worries. I was just replying to 

>How small is your screen??
>my laptop is old and I dont have this

**Comment by miigotu** [comment] 2015-08-24 10:36
Temp fixed by editting bootstrap (terrible option but thats how it was done before in SR, as bootstrap was previously modified)

**Closed by miigotu** 2015-08-24 10:36 UTC
Labels: 1: Bug / issue, 3: Confirmed
