### ISSUE TITLE
Renamer - manually edit (SQL) database

### ISSUE THREAD

**Issue by xxx1983** [SiCKRAGETV/sickrage-issues#391] opened 2015-01-12 12:23 UTC
Dear reader(s),

In my collection I want to rename all my files in a way that the quality and the releasegroup is noted. When I import (manually post-process) existing files most becomes unknown (Quality: "unknown", Releasegroup "SICKRAGE") even when the filename or included files contain the required information. I understood there is a running issue which causes this. In the meantime I would like to try to manually enter the correct info in the database.

One time I have been successful with this but I am unable to reproduce it. I am able to change and save the value of "release_group" and it remains in the database. When choosing to preview rename it still shows the "Unknown-SICKRAGE"-filename. Can you please inform me what I could do to let his work?

I am a Linux- and SQL-noob but eager to learn.

This is what I do:

1. Shutdown SICKRAGE
2. Open the database in SqliteBrowser (win) [3.3.0 - Qt version 4.8.5 SQLite version 3.8.4.3]
3. Go to the table [tv_episodes] and change the values of [release_group] of the affected records.
4. I choose [Write Changes] and [Close Database].
5. I start [SICKRAGE], go to the affected show and choose [preview rename]

Situation:

Synology NAS DSM 5.1-5021 Update 2
Sickbeard Custom 20140528-3
"/usr/local/sickbeard-custom" refers to "volume1/&appstore/sickbeard-custom/"
This folder has been shared so it is accessable by my windows computer.

SR Version: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
SR Config file: /usr/local/sickbeard-custom/var/config.ini
SR Database file: /usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir: /usr/local/sickbeard-custom/var/cache
SR Arguments: ['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:
Python Version: 2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]
Homepage http://www.sickrage.tv/
Forums http://sickrage.tv/forums/
Source https://github.com/SiCKRAGETV/SickRage/
Internet Relay Chat #sickrage on irc.freenode.net

With best regards and friendly greetings,

Maarten

**Comment by xxx1983** [comment] 2015-01-12 13:20
Branch: master
Commit hash: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
Your operating system and python version: Synology DS5.1 + Python Version: 2.7.8 (PC WIn8 x64)
What you did: See above
What happened: Info modified in database was not processed.
What you expected: That it would have been processed

This is what happens. 
The file mentioned is recorded in the database and does include the release_group. http://pastebin.com/xhReiFzb


I believe this is also mentioned in ticket #389.

**Comment by fernandog** [comment] 2015-01-19 12:05
@xxx1983 you need to review your filename pattern. 
please post an example of a file that SR could not read quality and releasegroup please

also NEVER manually change anything in the DB otherwise I can and will break your SR
we don't support this kind of change

**Comment by TagForce** [comment] 2015-01-19 14:16
@fernandog Basically what he is experiencing is what I describe in #389. Even though all the information is in the database, it is disregarded by SR when it's told to rename. It ONLY looks at the filename and the scene_name in the db, rather than looking at the relevant fields like quality and release_group.

Yes, you can avoid this problem by having the filename stored on disk utilizing the scene default of Quality-Releasegroup.ext, but that is needlessly hindering users in serving their files the way they want to. Feel free to merge this request into #389 as it's basically the same issue.

**Comment by fernandog** [comment] 2015-01-19 14:40
@TagForce but you have to agree with me that SR needs at least some basic information to work with.

**Comment by TagForce** [comment] 2015-01-19 15:08
@fernandog of course it does. I'm just saying that more often than not it DOES have this information in the db, it just doesn't use it. (I should say it has this info when SR initiated the download).

When SR post-processes a file it will update the database using the information that is available in the downloaded filename before it renames the file (aptly named release_name in the db). This will cause various fields to be filled in the db, including release_group. Then after PP it will store the new filename in the location field in the db.

When you have a naming scheme that does not include the Quality-Releasegroup convention, and you go and rename that file, if the scene-name is empty (for whatever reason) then it will always fall back to the SiCKRAGE placeholder for Release group, regardless of whether or not the release_group field has a value.

So, for instance: I use a naming convention as follows (actual example from my old database):
%SN - S%0SE%0E - %EN.%RG.%RT.ext that looks like: Falling Skies - 04x07 - Saturday Night Massacre.KILLERS.mp4 and when looking up the episode in the db I see that release_name is empty, but release_group shows KILLERS, and I go to rename the file SR will change the filename to Falling Skies - 04x07 - Saturday Night Massacre.SiCKRAGE.mp4

This tells me 2 things:
1. Sickrage doesn't use the release_group field in the db for renaming, though it would make sense for it to use this field at this point.
2. Sickrage knows that the KILLERS part in the filename is the release group, because it replaced the release group name with SiCKRAGE.

Quality isn't saved in the db other than the release_name, so it should say unknown if you have it in your naming scheme.

Now, from my point of view there's 2 possible fixes for this:
1. Use the release_group field to set the release_group when it's unclear what it should be.
2. Don't change any fields in the filename that are simply unknown but not missing. (ie Showname.S01E01.EpName.mp4 would be renamed to Showname.S01E01.EpName.SiCKRAGE.mp4, but Showname.S01E01.EpName.Bogus.mp4 would not be renamed since the expected release-group field exists in the filename).

option 1 would be the 'nicer' way to handle this.
Maybe also add the quality field to the db and use that as well.

**Comment by fernandog** [comment] 2015-01-19 15:19
will tag this as feature request. ok? we have to wait the DEV

**Comment by fernandog** [comment] 2015-01-19 15:20
@TagForce we need to rename the title for a better one. suggestion?

**Comment by TagForce** [comment] 2015-01-19 15:21
Can you move this one to #389 ? That's already a feature request for the same issue :)

**Comment by fernandog** [comment] 2015-01-19 15:22
it's already linked

**Comment by xxx1983** [comment] 2015-01-19 15:50
@fernandog: There would be a few examples where it does not process the releasegroup. When I have more time I can find some examples. It also happens with manually downloaded files. 

Little info: Before I used Sickbeard and there manually imported files containing the releasegroup (even when renamed by myself using [Showname - S01E01 - Releasegroup.ext] it did process the releasegroup in the username). The downloads of there files were not initiated by sickbeard but manually by me.

I like SickRAGE a lot more so I switched by deleting sickbeard and installing sickrage. 
Unfortunately I did not have logs, database etc. anymore.

If the original filename does not contain substractable information, some accompanied files could: (.NZB .SRR .SFV & the original .nfo/.nfo-orig) often contain the original file-name. I think this is also used by sickbeard.

Can you let me know why changing anything in the locally stored database-file is so "not done"? I was just trying to work to a solution. No bad intentions.

friendly greetings and thanks for the great work!

**Comment by fernandog** [comment] 2015-01-19 15:53
don't know. We have to wait @echel0n feedback

**Comment by TagForce** [comment] 2015-01-19 15:59
Altering the db would be your own responsibility. It's not supported, and can cripple your installation.
Just a warning. I've destroyed the db once by editing a single field on a windows machine and copying the file over to linux. (I've personally fixed your specific issue by filling all the release_name fields with filenames using the location filename and adding hdtv-%release_group% in excel and creating sql statements for that, which I fed into a sql-lite browser).

But, as I said. Unsupported, and if you break it, it's your own problem.

**Comment by xxx1983** [comment] 2015-01-19 16:10
@TagForce:Thanks! I understand the risks. 

As workaround I am going to rename all the files that cannot be renamed using an excel sheet and put it in a .bat-file. Then I will import it again. Very oldschool but it still works. Thanks for giving me the idea in your ticket!

**Comment by TagForce** [comment] 2015-01-20 08:58
@xxx1983 @fernandog 
Ok, I've gotten busy with it, and it turns out that it's not too hard, as far as I can tell.
https://github.com/TagForce/SickRage/commit/0accad927cd3e2eda0155ed92e9a4d2483697786

Needs major testing still, but it now checks if the release_group field is filled in the db. If it is, it will use that for %RG% in the renamer. If it's not filled it will resort back to using the release_name. If that doesn't exist, or it doesn't get a release_group from the release_name, then it will substitute with the SiCKRAGE placeholder.

What I need to figure out is if the release_group gets updated in the db after a file has been redownloaded, for instance.

You can try it if you want. I'll submit a pull request once I'm satisfied it works as intended and doesn't break any other functionality (as the replacement maps are also used to show examples on the settings -> episode naming tab).

**Comment by TagForce** [comment] 2015-01-20 14:39
I ran into an issue with my previous fix. Removed that commit, and readded a new one:
https://github.com/TagForce/SickRage/commit/08b90a4d91190a250d29600f9828bd4bfdc8b633

I accidentally broke the %RN (release_name) variable in the naming scheme.

It now not only uses the release_group field if available, or the release_name parsed release_group value if it's not. If the release_group field is available, it will now also use that value in the release_name if that is not available (which seems to happen more often).

So, if the release_name in the db is empty, and the release_group field is 'LOL', the resulting rename script will now return '%S.N.S%0SE%0E.%E.N-%RG' instead of '%S.N.S%0SE%0E.%E.N-SiCKRAGE' for the %RN variable.

It still needs more testing, though.

In essence, both the %RN and %RG variables will now attempt to use the release_group value, then the release_name value, and only when both fail to give a %RG value will it resort to putting SICKRAGE or SiCKRAGE in its place. If both return a valid %RG value, it will use the release_group value for the %RG variable, and the release_name value for the %RN variable.

**Comment by TagForce** [comment] 2015-01-21 14:17
@fernandog @xxx1983 @echel0n @markheloking Ok, I need some feedback.
What order should SR find releasegroups in?
I now have it like follows:
filename (the video file name, requires the use of qual-RLSGROUP naming for it to find it)
release_group field in the tv_episodes table in the db
release_name field in the tv_episodes table in the db (<- the only thing SR uses to find it atm)
'SiCKRAGE' if above 3 fail to give a release group.

If it doesn't find a release_name value, then it will also use the found releasegroup in the replacement release_name to minimize the number of files containing 'SiCKRAGE' as a releasegroup.

**Comment by fernandog** [comment] 2015-01-21 21:45
@TagForce 

cant help. dont use PP

**Comment by TagForce** [comment] 2015-01-22 00:11
I've changed the order to release_group, release_name, filename.
I've also made it save the release_group info in the db if it's not there and not equal to SiCKRAGE.

If you use filename first and there's a '-' in the filename, it will get everything after it in the filename and use that as a release group. Now, if that '-' happens to be in the episode name (J-Cat for instance), it will keep adding a Cat to the release group on every rename you do. So you end up with a file named J-Cat.Cat.Cat.Cat.Cat.mkv
Using the release_group first, and saving it when release_group doesn't yet exist will stop that from happening.

**Comment by fernandog** [comment] 2015-01-22 11:00
@TagForce IMO almost 99% of the GOOD release have the "-"

**Comment by xxx1983** [comment] 2015-02-13 22:10
My apologies for such a late update.
I did apply the commit and it worked like a charm. Many thanks for this!

**Comment by fernandog** [comment] 2015-02-13 23:40
@TagForce can you PR your commit please? thanks!

**Comment by TagForce** [comment] 2015-02-14 06:12
PR 1223 has been open for a while. :)

**Comment by fernandog** [comment] 2015-02-14 11:05
Sorry!

**Comment by fernandog** [comment] 2015-02-16 15:05
@xxx1983 develop updated. please update and report back

**Comment by xxx1983** [comment] 2015-02-16 18:51
@fernandog 
I am not sure I performed the correct action. I downloaded the develop-branch version and tested if it worked.

With the tv.py file of the [develop]-branch part of the files are not renamed correctly.
With the tv.py file of the [Releasegroup]-branch all files are renamed correctly.
Both were downloaded today (using github).

If this was not the test to perform, please inform me what I would need to do.

**Comment by TagForce** [comment] 2015-02-18 08:35
@xxx1983 Can you update to the latest develop branch? The change was only merged on the day you added your last reply, so it may be that it wan't when you updated to develop last time.

**Comment by fernandog** [comment] 2015-02-19 14:52
@xxx1983 please report back otherwise will close this

**Closed** 2015-02-20 12:18 UTC
Labels: 1: Feature request, 3: Confirmed, 3: Fix, 4: Need feedback

**Comment by xxx1983** [comment] 2015-02-20 16:29
@fernandog 
I updated to the last version of the development-branch and it worked
Result was the same as for the version of the Releasegroup-branch.
Again my thanks!

**Comment by fernandog** [comment] 2015-02-20 16:30
@TagForce effort! thanks!
