### ISSUE TITLE
Anime multi season recognizing

### ISSUE THREAD

**Issue by kvloover** [SiCKRAGETV/sickrage-issues#2662] opened 2015-09-05 15:38 UTC
Sickrage is not recognizing "S2 - 01" as being season 2 episode 1, and results in not finding the episode on trackers.

os X Yosemite 10.10.5 
BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c) 
2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

**Comment by kvloover** [comment] 2015-09-05 15:42
BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c) 
mac os X Yosemite 10.10 
2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

**Comment by WebSpider** [comment] 2015-09-05 17:49
We need more information to determine this is not a duplicate of #2623 .. Please see readme.md on how to submit this information.

**Comment by kvloover** [comment] 2015-09-05 18:08
It could potentially be fixed using #2623 however, this is not a case of differently named seasons.
But making them act as different season names is a potential fix ofcourse (although that would just be weird).

The show itself at this time is "Miss Monochrome" an anime which is in its second season.
Episodes are posted as f.e. "Miss Monochrome S2 - 10".

After downloading the episode manually and post-processing the folder using sickrage the episode is recognized as being of Season 1. Manually renaming the episodes to the format "S02E10" recognizes them correctly (using rename for example)

Log:
<script src="https://gist.github.com/kvloover/3cb144d6bb05728af017.js"></script>

Nyaatorrents holds a few fansub versions for the above episode.

**Comment by WebSpider** [comment] 2015-09-05 18:14
Still: Need more information to diagnose and solve.

Please provide information as laid out in SiCKRAGETV/sickerage-issues/readme.md .. Thanks!

-----Original Message-----

**Comment by kvloover** [comment] 2015-09-07 19:29
If you need more information, just let me know.
All the above should be in the first and second post if i'm not mistaken.

It's a general theme with all multi-season anime, so it's a rather large pain in the but at the moment.

**Closed** 2015-09-11 22:05 UTC
Labels: 4: Need more info
