### ISSUE TITLE
Multiple notifications when changing episode(s) from Ignored/Skipped to Wanted

### ISSUE THREAD

**Issue by goatbased** [SiCKRAGETV/sickrage-issues#2771] opened 2015-09-11 23:09 UTC
Hey guys,
This has been happening for about two weeks now but I'm just now getting around to documenting the issue. It happens across all shows and it really isn't just changing episodes from ignored to wanted--other notifications pop up multiple times as well (such as update notifications).

Here's a screenshot just in case it's helpful to see it in action and logs at http://pastebin.com/90kQe9Xq 

BRANCH: (master) / COMMIT: (37914618686ee70479da0fa4b2cca851fa49c5e2) 

![9-9-2015 9-10-46 pm](https://cloud.githubusercontent.com/assets/11284022/9828143/6bb39cca-589e-11e5-8648-290034a3c7b4.png)

**Comment by WebSpider** [comment] 2015-09-11 23:30
To me, this is exprected behaviour. What would you expect?

**Comment by goatbased** [comment] 2015-09-11 23:49
Up until a few weeks ago, I would select one or more episodes and set to "Wanted" and would only see one notification for "Backlog started" and one notification *per episode* of "Episode snatched"

In this specific case, I only selected a single episode and set to wanted and I dozens of notifications. The picture above only shows 9, but I probably had about 40-50 notifications. Seems strange.

**Comment by neoatomic** [comment] 2015-09-12 10:14
@WebSpider This seems to be specific to Windows that the notifications keep looping. But they stop after a refresh of the page.

@goatbased Running SickRage on a Windows machine right.?

**Comment by goatbased** [comment] 2015-09-12 16:44
@neoatomic Yep, sure are. Server runs on a Win7 x86 machine and I almost always access it from a Win7 x64 box using Firefox. In my experience, however, they do not stop after refreshing the page. In fact, just for testing, I closed firefox down entirely, reopened it, navigated to SR and the notifications were still firing.

**Comment by dirkr07** [comment] 2015-09-15 14:27
I get the same thing on my Synology so I doubt it's a windows thing.
for me it does stop though after I navigate to another page/refresh

**Comment by Rouzax** [comment] 2015-09-18 17:52
I have the same issue, if need be I can post the debug logs.
```
SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
Python Version: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
Operating System: Windows-2012Server-6.2.9200
```

**Comment by Rouzax** [comment] 2015-09-28 13:51
Is there anything you need to figure out this issue? 
It is getting really annoying :smile:

**Comment by macphistoo** [comment] 2015-09-30 20:06
Hello, I have the exact same problem since, like 1 month (I thought I was the only one!). SickRage is running on a debian box. I confirm, this is *really* annoying...  :)

**Comment by Rouzax** [comment] 2015-10-01 06:36
Maybe the title of the issue can be changed, it is with every notification that is send.

**Comment by miigotu** [comment] 2015-10-01 06:50
@Rouzax @macphistoo @dirkr07 @goatbased could you try clearing browser cache and maybe some ctrl+f5 in main shows page and displayshow ?

The only thing that changed for this was switching to a minimal jquery and bootstrap

**Comment by Rouzax** [comment] 2015-10-01 10:55
Just did a complete fresh install from the Master Git and only copied the DB and the config.ini.

Using Chrome Version 45.0.2454.101 m (64-bit) on Windows 8.1 even after ctrl+f5 or starting incognito I get multiple notifications.

IE 11 does not show a notification at all..

**Comment by macphistoo** [comment] 2015-10-02 19:04
Same for me, did clan install (debian) and tried from different computers/browsers, even from my iPhone I get the multiple notifications...

**Comment by macphistoo** [comment] 2015-10-09 18:13
Any news on this issue ?

**Comment by miigotu** [comment] 2015-10-09 18:55
@OmgImAlexis this must be windows only. I cannot reproduce it even with 10 providers enabled.

**Comment by WebSpider** [comment] 2015-10-09 19:00
It happened to me once on mobile, win8.1 ... That was like a week ago

-----Original Message-----

**Comment by macphistoo** [comment] 2015-10-09 19:51
@miigotu it is not since my box running SickRage is under debian and I have the same issue from the safari browser of my iPhone.

**Comment by miigotu** [comment] 2015-10-09 20:24
it has nothing to do with the SERVER, its about what OS the BROWSER is on.

It does not happen in linux browsers.

**Comment by macphistoo** [comment] 2015-10-09 20:57
I will try to find a linux box and let you know.

**Comment by OmgImAlexis** [comment] 2015-10-09 22:03
Okay, I think I may know the issue. The version of pnotify that we use is super old and from memory is customised for SickBeard from before SickRage existed. Converting it all over to native web notifications would fix this.

**Comment by Rouzax** [comment] 2015-10-10 10:19
I also have this on my Android tablet using the chrome browser.

**Comment by Rouzax** [comment] 2015-10-26 10:22
Is there a timeframe when this will be fixed?

**Comment by Rouzax** [comment] 2015-10-27 11:20
After some extra testing I found that this is also related to using a reverse proxy to access the SR site.
When accessing the site directly I don't get the multiple notifications.

**Comment by fernandog** [comment] 2015-10-27 12:38
@miigotu do you have reverse proxy too?

**Comment by Rouzax** [comment] 2015-10-27 12:58
In my case it is a MS IIS reverse proxy.

**Comment by goatbased** [comment] 2015-10-27 13:30
Great find! +1 for IIS ARR.

**Comment by WebSpider** [comment] 2015-10-27 13:45
Im not seeing it anymore using an nginx reverse proxy.

Will share my config on wiki when wanted

-----Original Message-----

**Comment by macphistoo** [comment] 2015-10-27 18:56
+1 I'm using ARR too !!!

**Comment by alisonatwork** [comment] 2015-10-31 23:02
I think this might be fixed in the next release. I committed a change today that sends a no-cache header; the problem I was seeing on IE/Edge was that it'd get the first notification and then keep giving 304s back without even asking the server. Now it should go back to the server on each poll.

**Comment by miigotu** [comment] 2015-10-31 23:32
I think it might also be due to the request handler object not being added to the context thatn is passed to the mako template render function.

Will be cleaning up quite a bit of code that I had added before to work around that, since I got the template lookup working correctly now.

**Comment by Rouzax** [comment] 2015-11-02 13:37
Latest Master Git seems to fix the issue. :+1: :trophy: 
SR Version:	BRANCH: (master) / COMMIT: (533d8c1a0b2b20ed7c52dff3dbc3fc6b4eefa0a1)

**Closed** 2015-11-02 14:14 UTC
Labels: 1: Bug / issue
