### ISSUE TITLE
FINDPROPERS pulling releases not even marked as "PROPER"

### ISSUE THREAD

**Issue by nrk666** [SiCKRAGETV/sickrage-issues#1825] opened 2015-06-15 14:47 UTC
sickrage.log.2:2015-06-15 08:18:33 INFO     FINDPROPERS :: Found a proper that we need: Some.TV.Show.S02E05.720p.HDTV.x264-SOMEGROUP 

sickrage.log.2:2015-06-15 08:18:27 DEBUG    FINDPROPERS :: Found new proper: Some.TV.Show.S02E05.720p.HDTV.x264-SOMEGROUP

Neither release was an actual "PROPER", just some scrub group releasing an episode which caused me to download and overwrite my perfectly good archived copy. 

Doesn't proper matching at least regex on "PROPER"?

**Comment by fernandog** [comment] 2015-06-15 14:53
@miigotu related to RemoveWords fix PR? The proper was the issue that @abeloin did that RemoveWords feature

**Comment by fernandog** [comment] 2015-06-15 14:55
@nrk666 please provider FULL logs

**Comment by miigotu** [comment] 2015-06-15 16:23
@fernandog databases can can incorrect info before/after my change to removeWords. I had to manually run some SQL on my db,

https://gist.githubusercontent.com/miigotu/c2322c9bfa16fb0ecf89/raw/c4cd9df07211aa3de873cb529c61fd33fb9cb050/remove_sub_rlsgroup

**Comment by miigotu** [comment] 2015-06-15 16:25
@nrk666 what quality was the original archived copy? I think there might be an issue with another change I made that should be midified to fix this.

**Comment by fernandog** [comment] 2015-06-15 16:26
@miigotu is it possible to add this code to run once at boot ?

**Comment by miigotu** [comment] 2015-06-15 16:43
@nrk666 Also, is this show set to use custom quality settings???

**Comment by miigotu** [comment] 2015-06-15 16:44
@fernandog I'm not sure of a good way to make it only run once and not on every boot.

**Comment by fernandog** [comment] 2015-06-15 17:13
@miigotu what's the best solution then?

**Comment by miigotu** [comment] 2015-06-15 17:30
@nrk666 The full debug logs are needed for me to determine the issue properly.

**Comment by miigotu** [comment] 2015-06-15 17:40
Not sure if this is an actual bug yet, but it is top priority until we find out.

**Comment by nrk666** [comment] 2015-06-16 13:22
Sorry, I don't have the log anymore, it rotated off. But, it happened again with a totally different show, but that log has also rotated out. I'll increase the archived log size, but I'll have to wait for it to happen again. 

It is clear to me that in neither case was "PROPER" or "REPACK" in the release name (based on sabnzbd log), and the previously downloaded quality was the exact quality desired (and configured in sickrage), so only a proper/repack release should have even been downloaded afterwards. 

I increased the default log size from 1mb to 100mb, that should keep it around longer. I'll dump a log when it happens again.

**Comment by nrk666** [comment] 2015-06-16 13:27
To answer your earlier questions: 

1. Original dl quality for show is set to 720p, original downloaded quality was 720p. Worked exactly as it should. 

2. No, I have no Custom TV Quality settings, I use the SickRage predefined settings as I have never had any reason to change them. 

3. The subsequent downloads, while not propers, were also 720p, however they were scrub group rips and not to "scene" standards as far as encoding. The first releases were the right releases, and sure, if a proper comes out for some reason, get the proper, but these latest downloads were normal scrub releases after the fact and while still 720p, substandard, which is why this is irritating.

**Comment by miigotu** [comment] 2015-06-16 15:04
Provider? I'm leaning towards a configuration or database problem here, since noone else is reporting this issue. I mean you would think people would be shouting pretty loud about this right?

Once an episode is archived, it isnt even included in proper search anymore afaik, and regex IS used to identify propers, and is correct.

**Comment by nrk666** [comment] 2015-06-16 15:26
It's not in an archived state, it was just downloaded a few days ago. 

The chain is this: new episode for TV Show X airs, SickRage downloads episode, processes it, then stops, exactly as you would expect. At some point over the next couple days, a scrub group will upload a dupe, not labelled as proper/repack, and SR will download that too. I expect this to happen if the release is marked as proper/repack, but that isn't the case. 

I use one of the more popular private usenet indexers. I also have sickrage configured to check some popular trackers for backlog (backlog only, not daily), but in this case all of the dupes are coming from usenet sources. 

Believe me, I understand your hesitation, I know how it is to support software and people coming up with half stories and incomplete information, you'll just have to take my word for it that I am not some idiot. Something seems broken to me here, and it broke within the last 2-3 weeks. I have been using SR for over a year now and never had this happen before, except when a release was correctly marked proper/repack, which I expect. The difference is that these releases are not marked as propers/repacks and are not quality scene releases, just some second tier group crap. 

As far as other people complaining, its not super easy to spot unless you are watching for it. To most people, it looks like a regular proper/repack download, but I had to use sabnzbd to check the release names and they are not proper/repacks. The only reason I noticed is that I started watching an original downloaded episode, stopped it, then came back a day later, and the quality was total shit because it had been redownloaded, so I looked into what happened and stumbled on this issue. 

I'll upload a log the next time it happens, the default 1mb logfile wasn't enough to keep the relevant data overnight. I bumped it to 100mb, so that should give me a couple more days.

**Comment by miigotu** [comment] 2015-06-16 16:17
I only thought it was archived because you said archived in the first post:

`just some scrub group releasing an episode which caused me to download and overwrite my perfectly good archived copy.`

Anyways, I'll wait for the logs.

**Comment by nrk666** [comment] 2015-06-16 18:01
Ah, sorry, I can see where that would be misleading. I meant "archived" in the sense of added to my library. I didn't even remember there is an "archived" status you can set for episodes, I don't have a need for it as it obfuscates the archived quality.

**Comment by Grubs** [comment] 2015-06-16 22:45
I'm also having this problem and so is a friend of mine.
Me - Windows PC setup
Friend-Synology NAS setup

Have noticed it for a couple shows in the last few weeks.

once example:

GoT.S05E08.720p.HDTV.x264-0SEC
then decided to DL
GoT.S05E08.720p.HDTV.x264-DON

Same happened with 5x09, & 5x10.

We also had it with OitNB.S03 multiple episodes downloaded more than once and none of the 2nd or 3rd releases had REPACK or PROPER in the name

**Comment by miigotu** [comment] 2015-06-16 23:12
Reports don't count without full debug logs. How could you possibly expect us (who cannot reproduce these issues) to dig through  34 providers worth of code, along with the proper code, search code, snatch code, etc without some information to narrow it down?

@fernandog this is certainly not becuase of the removeWords change, the original removeWords changes just broke SR so bad it masked these issues.  This problem is NZB only, and that is all of the info we have so far. We don't even know if their DB is broken at this point.

**Comment by Grubs** [comment] 2015-06-16 23:23
Hi @miigotu, I was just posting to confirm that I am also having the same issue. It seemed there was doubt that @nrk666's issue was more that just 1 user. I haven't yet had time to grab logs was merely  looking to see if it was a widespread issue and came across this ticket. I will gather more info and post it when I have it

The tone of you reply seems a bit over the top when I was simply trying to let you know @nrk666 isn't the only one with the issue.

**Comment by nrk666** [comment] 2015-06-16 23:46
My providers are dog & personal nZEDb I run myself. I went back through my history, and the provider that I am matching the dupes on is dog, but it doesn't matter where the original came from. So, I could match against my personal nZEDb, then get a dupe from dog, or match dog first, then get a dupe from dog (in some cases, more than one dupe), and even if the original came from a torrent tracker, the dupe came from dog. 

I dunno if that helps at all, but I haven't had a show d/l for a while (between shows it looks like, seasons just ended), and "dupe worthy" shows look to be over for the moment, so who knows how long this will take to reproduce. 

"We don't even know if their DB is broken at this point." - are you referring to my local sickrage DB? Since we now have more than one person reporting the same problem, the odds of us having the exact same DB corruption seem unlikely, although I will admit I'm no expert when it comes to that. If you have any sort of "sanity check" for the local DB, I'd be happy to run it and report results. (Mine is on ubuntu.)

**Comment by Grubs** [comment] 2015-06-16 23:54
I just had a look too @nrk666 . I can see both mine and my friends 'dupes' all come from dog from what I can see.

**Comment by miigotu** [comment] 2015-06-17 01:48
Logs or it doesn't count. =P

Seriously though, I want to fix it, but I cant without something to go on besides "It keeps resnatching propers"

Also, it is likely there is identical db corruption, as code which set specific fields related to this have recently changed, back to a working state, where it was broken for some time. Data from when it was broken can still exist in the db, and cause issues.

Here is the SQL I ran on my DB to ensure it was sane in the related fields.
https://gist.githubusercontent.com/miigotu/c2322c9bfa16fb0ecf89/raw/c4cd9df07211aa3de873cb529c61fd33fb9cb050/remove_sub_rlsgroup

**Comment by miigotu** [comment] 2015-06-17 01:56
Is it possible that #1579 is causing a situation where this happens?

Are you using blackhole or a client api to download torrents/nzb's?

**Comment by miigotu** [comment] 2015-06-17 01:59
Heh, maybe I will write a little test script to check those fields in db, and potentially fix them after asking.

**Comment by Grubs** [comment] 2015-06-17 02:02
I've got debug and logging enabled now. Also changed logs to 10 x 100mb.

My friend and I are both using SickRage + SABnzbd via API

**Comment by miigotu** [comment] 2015-06-17 02:41
depends on what OS you are on. On linux, you can use sqlite3 command line:
`sqlite3 sickbeard.db`
And input each of the lines from that gist one by one.

**Comment by miigotu** [comment] 2015-06-17 02:42
After a new "proper" is snatched, is it set to state "Snatched (Proper)" in the webUI?

**Comment by miigotu** [comment] 2015-06-17 03:01
@nrk666 @Grubs  all of your nzb indexers are newznab powered?

**Comment by Grubs** [comment] 2015-06-17 03:55
Hi @miigotu , I'm on windows. I'll have a search, should have sql lite installed.

No, it doesn't show 'Proper' in webUI either.

I noticed all of mine that did it first used geek then dog. I can also confirm the original snatched was completed and shows Downloaded before the 2nd release was snatched (quite a few hours later)

**Comment by miigotu** [comment] 2015-06-17 04:06
dog and geek are set in SR using the custom nzb provider tab? I'm trying to narrow down which complicated string of provider calls to follow in sickrage code.

**Comment by miigotu** [comment] 2015-06-17 04:56
Seems the code in newznab.py and generic.py for findPropers could be improved.

I think the issue is, when searching a newznab provider with proper or repack in the string, it is returning non propers from the search engine, or using cached results from the daily search. These are not then verified to be PROPER|REPACK, nor are they verified to ONLY replace a downloaded episode when it is the same quality AND release group.

This issue would only happen on some custom newznab providers.

**Comment by Grubs** [comment] 2015-06-17 05:03
Correct. They are both using the custom nzb provider tab.

**Comment by miigotu** [comment] 2015-06-17 05:47
Correct, because before I fixed newznab, it rarely worked to even search, and before that, I fixed a problem where ignored/required words, propers, and failed handling was totally broken (removeWords).

The initial removeWords fix was intended to fix proper duplicates, but it actually totally broke alot of things. The real problem with the propers was and now is again with the newznab findPropers code.

**Comment by nrk666** [comment] 2015-06-17 13:24
@miigotu : Client API, SR feeds the nzb direct to an instance of sabnzbd 

@miigotu : I don't know what backend dog uses, but it uses the newznab API, but my personal indexer is near stock nZEDb. 

@miigotu : both of my configured indexers are from the custom indexer settings

I can also confirm this only started about 2-3 weeks ago, 4 at the most. 

I'll run those SQL commands in an hour or two and see if anything happens. 

Sounds like we are making some progress. 

I also am going to try something, I'm going to build a new ubuntu VM from scratch with a clean SR db, seed a couple of shows that I had problems with, and then let it sit to see if it grabs some non-propers, then I'll have a logfile for you. It might take me a day or so depending on how busy work is, but it's the least I can do. But, if your theory is correct about the DB corruption, then this might be a bad test as a fresh DB would skip any circumstances that caused it to go bad. 

Maybe a feature request : set the default log size to something a little larger?

**Comment by nrk666** [comment] 2015-06-17 13:30
I ran those SQL commands on my sickbeard.db and all ran ok with no errors.

**Comment by nrk666** [comment] 2015-06-17 15:07
Ok, I created a brand new instance on a fresh machine. 

Steps taken: 

1. installed ubuntu fresh, ran updates
2. installed python-cheetah and pyopenssl
3. install sickrage from git
4. adjust startup scripts
5. copied "config.ini" from main sickrage to srtest, modified to match new host (dir's, etc)
6. Verified all provider (indexers, trackers) information was the same
7. seeded SR with two shows that caused me issues in the past, manually set quality to "HDTV", marked old episodes as "skipped" 
8. modified config.ini to set "debug = 1" 
9. Changed proper search from 4hrs to 90mins, could have gone shorter I suppose
10. Changed destination for NZB files to "blackhole" because I don't actually want to download the dupes, just see the release names? - Might need confirmation to see if this ruins what you are looking for, but if SR is going to send something to sab, then it already decided to download a proper, so I don't see how it makes much of a difference, but I could be wrong. 
11. changed logfile to 1gb just to be safe. 
12. restarted SR to make sure all config changes were re-read. 
13. Awaiting proper search.

**Comment by nrk666** [comment] 2015-06-17 15:10
I don't know if there is logic to skip a FINDPROPER if the show status was set manually for episodes I had SR discover, so this might be a waste of time. If SR only performs FINDPROPERS on episodes it handled itself, then this is probably a stupid test. If you can send me some SQL code to cheese the SR database into thinking it downloaded all of these episodes instead of a manual setting, I'll do it.

**Comment by miigotu** [comment] 2015-06-17 16:18
You can force a proper search in manage->manage searches.

As for the blackhole, yes it could cause a difference, but you can try to reproduce it with blackhole first.
There is a known issue at least with torrents where it is sending the wrong torrent via api, but the correct one is downloaded with blackhole - #1579 .

It does need an old release name for propers to work, IE: SR needs to have snatched and post processed the original episode itself. So let it snatch the original, and then rename the .nzb file to .mp4 and move it to your PP folder on the test setup, then let it post process it.

**Comment by nrk666** [comment] 2015-06-17 16:26
Hmm, then my test isn't going to work, I just copied the initial files from my existing library. Most of these shows won't be downloadable anymore anyways (missing blocks). 

So, this test probably won't work then. I'll see about letting it fetch the episode (drop the nzb into the blackhole), then rename my existing library file to the release name, then manually putting it in the PP dir to let SR handle it, but I can't do that til I get home from work.

**Comment by nrk666** [comment] 2015-06-17 16:57
I do have a question though, if I do set a "blank" SR instance to pull nzb's from an indexer, will it pull the newest ones first (which will render this test moot) or pull from the first time it was indexed? If it pulls the latest indexed result, then I'm in the same boat as my regular SR instance, waiting for some scrub to upload a new release without "PROPER" in the name. 

Just want to know if this is worth testing or not I guess. I want to get you some logs, but most of the shows in question seasons just ended, so not super likely to get a lot more dupes for those.

**Comment by miigotu** [comment] 2015-06-17 22:41
@nrk666 Not sure, trying never hurts.

**Comment by nrk666** [comment] 2015-06-18 21:10
Ok, I've got this running now: 

1. Fresh ubuntu vm
2. Fresh git pulled instance of SR (as of today, there were 29 commits avail on my regular SR instance, so this is fully updated, dunno if anyone found something and fixed it, new commits coulda been anything, so I dunno) 
3. copied config.ini with my provider info in it (with "debug = 1")
4. Added two shows
5. Set recent season of both shows to "Wanted" 
6. SR instance pulled nzb's for all episodes
7. I manually copied the downloaded nzb files and renamed them to "mkv" keeping the filename intact, moved the files into SR's PP dir. 
8. Did a manual SR PP to import the "media". 
9. Files were imported into SR database, should be considered "pulled" and "processed" from a release rather than any manual insertion and marked as downloaded in season overview. 

Currently, waiting to see if any dupes get pulled from the indexers. Since it pulled the most recent nzb's off the indexer, I'm not super confident this will find any new dupes since its been a week since these seasons wrapped up. But, if it does, I'll have a logfile with debug info for you. 

Thanks for your patience.

**Comment by miigotu** [comment] 2015-06-18 21:12
There were many fixes which could affect the original issue here, you really should update your regular SR instance xD.

**Comment by nrk666** [comment] 2015-06-19 00:14
Oh, I did update my original, I just wanted to be clear that my test was using todays commits. I always update my regular instance, don't sweat that.

**Comment by nrk666** [comment] 2015-06-19 18:59
Ok, I think I got a few hits. Some of the adds were actual propers, but it looked like some weren't. 

https://gist.github.com/nrk666/525ef04ef67fc4f16dc8  is the logfile for today when it all happened.

**Comment by miigotu** [comment] 2015-06-19 19:36
Heh, it's only the repack search that returns titles without repack|proper

**Comment by miigotu** [comment] 2015-06-19 19:41
Try changing line 325 of sickbeard/providers/newznab.py to `search_terms = ['.proper.']`

**Comment by nrk666** [comment] 2015-06-19 21:10
Maybe I'm misunderstanding, but if I change line 325, in def findPropers, won't that stop it from actually finding repacks (repacks are ok...)? 

Anyways, made this change and restarted SR: 

325:#        search_terms = ['.proper.', '.repack.']
326:        search_terms = ['.proper.']

**Comment by miigotu** [comment] 2015-06-20 02:41
This is the thing, repacks are considered propers by sickrage, but there is no 'PROPER', 'REPACK', or 'iNTERNAL' tag in the filename so people think the proper finder is returning non-propers. Either a repack has the version in the nzb incremented and thats how they distinguish it, or the newznab providers are returning non-proper/repack.

The proper finder is working fine, its the indexers fubar, so we need to remove repacks from the proper finder.

**Comment by miigotu** [comment] 2015-06-20 03:37
Scratch that, proper is working kinda, for a few providers.
It seems there are some inconsistencies with proper finding implementations across the various providers that need to be fixed. I have identified quite a few problems.

**Comment by Koal4** [comment] 2015-06-20 13:41
I'm having the same problem. I notice this week that my SR was redownloading a lot of stuff that I already had. Also when checking the filename or releasename it doesn't even mention proper. It looks like it is just grabbing releases that are newly posted.

here's a debug log if it's desired: http://pastebin.com/LGCt9uvY

**Comment by miigotu** [comment] 2015-06-20 13:45
@Koal4 1.) there is no proper finder thread ran in that debug log. 2.) disable find propers for now, until I can rewrite half of half of the providers to fix it.

**Comment by Koal4** [comment] 2015-06-20 13:50
Ye, the debug log was not complete. Is there no easy way to get it into 1 file instead of editting those 5 log files into 1?

Anyway: here's the ful log which should include de proper finder 

https://gist.github.com/Koal4/6605da96fb7ca243b354

**Comment by miigotu** [comment] 2015-06-20 13:58
@Koal4 I already know what the problem is, it is just a very involved fix to make it uniform across all providers and I haven't got it done yet.

Biggest problem is that newznab providers return repacks without "repack" in the title, which causes confusion. Repacks arent necessary unless there is a problem with the initial file anyways.
For now, make this change in `sickrage/providers/newznab.py`
Line 325 change 
`search_terms = ['.proper.', '.repack.']`
to:
`search_terms = ['.proper.']`

Be sure not to change the number of spaces at the beginning of the line. Then restart SR.

**Comment by fernandog** [comment] 2015-06-20 14:10
@miigotu are you going to PR that fix about clean cache? or isn't an issue?

**Comment by miigotu** [comment] 2015-06-20 14:11
@fernandog Hey just needs to clear cache because his rss and indexer cache has non-propers in them.

**Comment by miigotu** [comment] 2015-06-20 14:12
I haven't found the exact problem with the clearcache thing either, must be owner/permissions related.


IE: SR run as a different user one time makes cache files that cannot be removed by the normal SR user.

**Comment by nrk666** [comment] 2015-06-20 16:41
Ok, sounds like you got a handle on it now, I'm going to nuke my test instance. 

Thanks for your patience on getting a logfile.

**Comment by miigotu** [comment] 2015-06-20 17:28
@nrk666 Yep, thanks. That log put me right to where it was failing, and let me see how much work needs to be done to make all providers work the same in that sense.

**Comment by Koal4** [comment] 2015-06-20 18:58
I made the adjustment what you suggested earlier on and restared SR. However I don't think its working because I redownloaded OITNB show because it was replaced with a release I didn't liked. But now the proper check run has ran again and it started to redownload some of the eps again from a different release thinking they are propers..

https://gist.github.com/Koal4/cfffbd9a73220d68bb7d

**Comment by miigotu** [comment] 2015-06-20 19:28
@Koal4 can you open the nzb of the incorrect proper snatch and paste it on gist?

**Comment by Koal4** [comment] 2015-06-20 19:36
How do you mean open the nzb?

I had the following release Orange.Is.The.New.Black.S03E08.Fear.and.Other.Smells.1080p.NF.WEBRip.DD5.1.x264-NTb\

And it redownloaded: Orange.Is.the.New.Black.S03E08.1080p.WEBRip.x264-2HD/orange.is.the.new.black.s03e08.1080p.webrip.x264-2hd.mkv

**Comment by miigotu** [comment] 2015-06-20 19:42
I meant the nzb file, but you arent using blackhole so you dont have it, my bad.

Try changing line 332 of sickbeard/providers/newznab.py from:
`alt_search = ('nzbs_org' == self.getID())`
to:
`alt_search = True`

**Comment by Koal4** [comment] 2015-06-20 19:44
Thanks, idd i don't use blackhole.

If you meant open it like a text file then the output is here https://gist.github.com/Koal4/13b5c9f01a409fe8395d (can stil download it from my indexer)

**Comment by miigotu** [comment] 2015-06-20 19:51
I'm gonna rewrite this junk over the next few days. Right now we just assume that when we search an nzb indexer for '.proper.' or '.repack.' they will only return results containing '.proper.' or '.repack.'

Should be a no brainer to expect a search to return only results that you searched for right?

**Comment by Koal4** [comment] 2015-06-20 19:55
Haha idd, all i can confirm is that this is issue is something from the last few weeks. Before that I never had any issues with the propersearch. I started to notice this problem because it was redownloading OITNB every few days which was driving me crazy because i didn't understand why untill earlier on :) 

Anyway i've made the change what you have suggested so I will know more later on

**Comment by miigotu** [comment] 2015-06-20 20:13
@Koal4 proper search didn't work at all before.

Proof its the indexers, who use newznab as their backend, all have the same bug:
http://newshost.co.za/?s=Jericho+proper
See there are ones returned without proper in the list?

**Comment by miigotu** [comment] 2015-06-20 22:20
Can I borrow someone's dognzb login/key? Trying to test fixes with sick beard index and they have blocked us somehow again.

**Comment by miigotu** [comment] 2015-06-20 22:45
or nzbcat

**Comment by miigotu** [comment] 2015-06-21 10:24
Test latest develop branch pl0x

**Comment by nrk666** [comment] 2015-06-21 22:17
Switched to dev branch.

**Comment by nrk666** [comment] 2015-06-22 13:13
Dev branch pulled actual propers, but only from torrent sources. 

Usenet FINDPROPERS gave this in the error log: 2015-06-22 06:16:27 FINDPROPERS :: [someindexer] :: Error while searching someindexer, skipping: global name 're' is not defined

**Comment by miigotu** [comment] 2015-06-22 15:03
Ew, missed the import for re. Pushing.

**Comment by nrk666** [comment] 2015-06-23 16:20
Anything specific you want me to look for on the dev branch? I'm just curious about switching back to master. So far, the dev branch seems to be working, haven't seen the "re" error lately, but I've been applying the new commits as they come down.

**Comment by miigotu** [comment] 2015-06-23 16:48
No reason to switch back to master just yet if you dont need to.

It helps to have the fixes checked for a few days, and I have been working on a few bigger fixes as well in develop.

**Comment by nrk666** [comment] 2015-06-23 17:43
Ok, no prob.

**Comment by miigotu** [comment] 2015-06-26 01:32
@nrk666 @Koal2 @Grubs 
Should be fixed in master now too.

**Closed by miigotu** 2015-06-26 01:32 UTC
Labels: 1: Bug / issue, 2: High Priority, 3: Confirmed

**Comment by nrk666** [comment] 2015-06-26 14:48
Thanks for looking into this, you guys are doing some good work.
