### ISSUE TITLE
ValueError: timestamp out of range for platform time_t 

### ISSUE THREAD

**Issue by chemmah** [SiCKRAGETV/sickrage-issues#840] opened 2015-03-03 22:11 UTC
ValueError: timestamp out of range for platform time_t appears when attempting to browse show list. Still able to look at settings and such. Attempted fresh rebuild with no previous data and had the same result once rebuilt and TV show directories scanned.

SR Version:	BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9) 
Python Version:	2.7.8 (default, Oct 18 2014, 16:06:04) [GCC 4.9.1]
Platform arch is PPC, OS is Debian 7.

Log, host and client IPs replaced with 'host' and 'client':
```
2015-03-03 16:50:05 ERROR    Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 706, in index
    return t.respond()
  File "/opt/SickRage/cache/cheetah/_opt_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 920, in respond
    _v = VFN(VFFSL(SL,"calendar",True),"timegm",False)(VFN(VFFSL(SL,"ldatetime",True),"timetuple",False)()) # u'$calendar.timegm($ldatetime.timetuple())' on line 539, col 135
  File "/opt/SickRage/lib/dateutil/tz.py", line 114, in dst
    if self._isdst(dt):
  File "/opt/SickRage/lib/dateutil/tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t
Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 706, in index
    return t.respond()
  File "/opt/SickRage/cache/cheetah/_opt_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 920, in respond
    _v = VFN(VFFSL(SL,"calendar",True),"timegm",False)(VFN(VFFSL(SL,"ldatetime",True),"timetuple",False)()) # u'$calendar.timegm($ldatetime.timetuple())' on line 539, col 135
  File "/opt/SickRage/lib/dateutil/tz.py", line 114, in dst
    if self._isdst(dt):
  File "/opt/SickRage/lib/dateutil/tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t
2015-03-03 16:50:05 ERROR    Uncaught exception GET /home/ (client)
HTTPServerRequest(protocol='http', host='host:8081', method='GET', uri='/home/', version='HTTP/1.1', remote_ip='client', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, defl
ate, sdch', 'Host': 'host:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/40.0.2214.95 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0', 'Cache-Control': 'max-age=0'})
Traceback (most recent call last):
  File "/opt/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/opt/SickRage/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/opt/SickRage/tornado/concurrent.py", line 226, in <lambda>
    lambda future: callback(future.result()))
  File "/opt/SickRage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/opt/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/opt/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/opt/SickRage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 706, in index
    return t.respond()
  File "/opt/SickRage/cache/cheetah/_opt_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 920, in respond
    _v = VFN(VFFSL(SL,"calendar",True),"timegm",False)(VFN(VFFSL(SL,"ldatetime",True),"timetuple",False)()) # u'$calendar.timegm($ldatetime.timetuple())' on line 539, col 135
  File "/opt/SickRage/lib/dateutil/tz.py", line 114, in dst
    if self._isdst(dt):
  File "/opt/SickRage/lib/dateutil/tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t
```

**Comment by fernandog** [comment] 2015-03-03 22:18
@chemmah do you have change timestamp enable in PP?

**Comment by abeloin** [comment] 2015-03-03 22:27
One of your shows as an invalid time

**Comment by chemmah** [comment] 2015-03-03 23:28
@fernandog No I do not

@abeloin Time pulled from theTVDB/TVRAGE or another timestamp?

**Comment by abeloin** [comment] 2015-03-04 00:27
Yes tvdb/tvrage, any show you added recently?

**Comment by chemmah** [comment] 2015-03-05 02:31
Yes a couple. I am rebuilding again, one by one. However, I am surprised that the program will end up in this state simply by a date being off from an uncontrolled source like theTVDB or TVRAGE. Would that not be a bug to fix, add a bit of code to proof dates and replace them with a safe tag if they fail the proof so it doesn't simply fail when this occurs?

**Comment by abeloin** [comment] 2015-03-05 03:32
I agree with you. The error happen in a third party library, we need to be able to reproduce the error so I can submit the issue to the one who created dateutil.

Use the mass update page to open each show until you find the one causing the issue.

**Comment by chemmah** [comment] 2015-03-05 13:34
It is Judge Judy from theTVDB. I was able to view the show in Mass Update, however as I was building a new SickRage instance this is where things went wrong. I brought back up my original SickRage instance, went into the show directly, and removed it. It is now working fine.

**Comment by fernandog** [comment] 2015-03-05 13:41
@abeloin should we check if indexer has a wrong time set and override it to 00:00 ?

**Comment by abeloin** [comment] 2015-03-05 13:59
That show is a mess.

Ref: http://thetvdb.com/?tab=series&id=71221&lid=7

**Comment by abeloin** [comment] 2015-03-05 14:00
Season 19, episode 149 airdate: 2915-02-24

**Comment by fernandog** [comment] 2015-03-05 14:27
"The reason fromtimestamp has trouble (on some systems) is that it is based on system C functions. The documentation notes that this is often constrained to the years 1970 to 2038. timedelta on the other hand is custom-built for Python, and handles durations up to slightly less than one billion day"
http://stackoverflow.com/questions/10588027/converting-timestamps-larger-than-maxint-into-datetime-objects

**Comment by chemmah** [comment] 2015-03-05 17:54
I went in and fixed theTVDB for that. If dateutil cannot be fixed, perhaps a verbose error in the log stating where it's choking on data from theTVDB?

**Comment by abeloin** [comment] 2015-03-05 19:35
This PR will print an "Invalid date" instead of crashing.

**Comment by fernandog** [comment] 2015-03-07 23:36
@chemmah can you update and report back if issue is fixed?

**Comment by fernandog** [comment] 2015-03-09 00:28
@chemmah merged into master. please update and report back

**Closed** 2015-03-09 21:51 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: master

**Comment by chemmah** [comment] 2015-03-09 21:59
Confirmed the fix works
