### ISSUE TITLE
Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'

### ISSUE THREAD

**Issue by timrettop** [SiCKRAGETV/sickrage-issues#328] opened 2015-01-04 04:14 UTC
Branch: Master
Commit Hash: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
Environment: Ubuntu 14.04 Python 2.7.6

Upon a successful PROPER result, I'm getting an error in the logs as described in the title.  

I have not altered my config settings for Ignore Words from the default: german,french,core2hd,dutch,swedish,reenc,MrLss

Here is the relevant log information: 

```
2015-01-03 19:32:19 INFO     FINDPROPERS :: [TorrentBytes] :: Searching for any new PROPER releases from TorrentBytes
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Using ALL regexes
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Unable to parse the filename Transformers.Rescue.Bots.S01E15.PROPER.720p.HDTV.x264-FiHTV into a vali
d show
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Using ALL regexes
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Parsed Marvels.Agents.of.S.H.I.E.L.D.S02E08.REPACK.720p.HDTV.x264-KILLERS into Marvels Agents of S H
 I E L D - S2E8 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Successful match! Result Marvels.Agents.of.S.H.I.E.L.D.S02E08.REPACK.720p.HDTV.x264-KILLERS matched to show Marvel's Agents of S.H.I.E.L.D.
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: Picking the best result out of [u'Marvels.Agents.of.S.H.I.E.L.D.S02E08.REPACK.720p.HDTV.x264-KILLERS']
2015-01-03 19:32:19 INFO     FINDPROPERS :: Quality of Marvels.Agents.of.S.H.I.E.L.D.S02E08.REPACK.720p.HDTV.x264-KILLERS is HD TV
2015-01-03 19:32:19 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
Traceback (most recent call last):
  File "/home/tim/.sickrage/sickbeard/scheduler.py", line 80, in run
    self.action.run(self.force)
  File "/home/tim/.sickrage/sickbeard/properFinder.py", line 52, in run
    propers = self._getProperList()
  File "/home/tim/.sickrage/sickbeard/properFinder.py", line 148, in _getProperList
    if not pickBestResult(curProper):
  File "/home/tim/.sickrage/sickbeard/search.py", line 224, in pickBestResult
    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):
AttributeError: 'NoneType' object has no attribute 'rls_ignore_words'
2015-01-03 19:32:19 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/home/tim/.sickrage/sickbeard/scheduler.py", line 80, in run\n    self.action.run(self.force)\n  File "/home/tim/.sickrage/sickbeard/properFinder.py", line 52, in run\n    propers = self._getProperList()\n  File "/home/tim/.sickrage/sickbeard/properFinder.py", line 148, in _getProperList\n    if not pickBestResult(curProper):\n  File "/home/tim/.sickrage/sickbeard/search.py", line 224, in pickBestResult\n    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):\nAttributeError: \'NoneType\' object has no attribute \'rls_ignore_words\'\n'
```

**Comment by fernandog** [comment] 2015-01-05 09:11
@timrettop  what about the ignore word for that show?
there's two ignore words: global and per show.

**Comment by timrettop** [comment] 2015-01-05 15:51
There are no Ignored or Required words for the show either.  I haven't taken advantage of that feature yet with any show.

**Comment by flashburn2012** [comment] 2015-01-10 01:45
Same problem I'm having. I also haven't modified the ignore words at all.

**Comment by asimov6** [comment] 2015-01-11 21:45
Same problem here: 
2015-01-11 21:28:29 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

**Comment by lussierj** [comment] 2015-01-13 21:15
Same problem as well. Running on Windows 8.1. 
Here's section of log
---------------------------------------
2015-01-13 10:28:23 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-01-13 10:28:23 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-01-13 10:28:23 INFO     EVENT-QUEUE :: Aborting all threads
2015-01-13 10:26:57 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Connection unexpectedly closed: timed out
2015-01-13 10:25:33 INFO     POSTPROCESSER :: Folder name (Man.vs.Wild.S04.720p.hdtv.x264) appears to be a valid release name. Using it.
2015-01-13 10:25:33 INFO     POSTPROCESSER :: Trying to clean any empty folders under M:\Videos\TV Shows\Man vs. Wild\Season 04
2015-01-13 10:25:33 INFO     POSTPROCESSER :: Analyzing name u'man.vs.wild.s04e02.Alabama.720p.hdtv.x264-gnarly.mkv'
2015-01-13 10:25:33 INFO     POSTPROCESSER :: Analyzing name None
2015-01-13 10:25:33 INFO     POSTPROCESSER :: Processing T:\Completed\Man.vs.Wild.S04.720p.hdtv.x264\man.vs.wild.s04e02.Alabama.720p.hdtv.x264-gnarly.mkv (None)
2015-01-13 10:25:05 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2015-01-13 10:25:05 INFO     FINDPROPERS :: Quality of MythBusters.S15E01.REPACK.HDTV.x264-W4F.mp4 is SD TV
2015-01-13 10:25:05 INFO     FINDPROPERS :: [TorrentDay RSS] :: Searching for any new PROPER releases from TorrentDay RSS
2015-01-13 10:25:05 INFO     FINDPROPERS :: [Torrenting RSS] :: Searching for any new PROPER releases from Torrenting RSS
2015-01-13 10:25:05 INFO     FINDPROPERS :: [Shazbat Recent] :: Searching for any new PROPER releases from Shazbat Recent
2015-01-13 10:25:05 INFO     FINDPROPERS :: [Shazbat Followed] :: Searching for any new PROPER releases from Shazbat Followed
2015-01-13 10:25:03 INFO     FINDPROPERS :: [TorrentDay] :: Searching for any new PROPER releases from TorrentDay
2015-01-13 10:24:52 INFO     FINDPROPERS :: [TorrentBytes] :: Searching for any new PROPER releases from TorrentBytes
2015-01-13 10:24:52 INFO     FINDPROPERS :: [TvTorrents] :: Searching for any new PROPER releases from TvTorrents
2015-01-13 10:24:52 INFO     FINDPROPERS :: Beginning the search for new propers
2015-01-13 10:21:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found

**Comment by mikkelnl** [comment] 2015-01-15 21:55
Same here!

**Comment by Vodka2014** [comment] 2015-01-16 09:17
Same issue on OE 5.0 using audo

**Comment by Vodka2014** [comment] 2015-01-16 09:18
Is there an workaround at all for this in the system at all ?

**Comment by Micha77** [comment] 2015-01-16 13:53
Same problem here on BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'

**Comment by Vodka2014** [comment] 2015-01-18 11:07
Since the update that was released today the Propers is getting processed and no errors in the SickRage Logs. I just need a proper to get updated to the nzb sites to see if it grabs it. Other then that all looking good so far.

**Comment by markheloking** [comment] 2015-01-18 11:13
Lets close it then. If you see that anything is still off, please reopen/report back @Vodka2014 .

**Comment by Vodka2014** [comment] 2015-01-18 11:16
So i just added a new show and it did find the PROPER Releases :) 

Without me adding them manually. Thanks Team :)

**Comment by Tlabok** [comment] 2015-01-18 13:54
I still see the error msg appear after today's update for the master branch.
````
2015-01-18 12:28:38 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
````

**Comment by Vodka2014** [comment] 2015-01-18 14:34
@ TIabok

I just checked mine again and this is what i got:

2015-01-18 16:33:16 INFO     FINDPROPERS :: Completed the search for new propers, next check in approx. 1h, 29m
2015-01-18 16:33:11 INFO     FINDPROPERS :: [NZBs.org] :: Searching for any new PROPER releases from NZBs.org
2015-01-18 16:33:08 INFO     FINDPROPERS :: [NZB.su] :: Searching for any new PROPER releases from NZB.su
2015-01-18 16:33:08 INFO     FINDPROPERS :: Beginning the search for new propers
2015-01-18 16:33:08 INFO     Thread-21 :: Find propers search forced

I am using OE with the audo addon and SickRage Version: BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)

**Comment by markheloking** [comment] 2015-01-18 14:37
@Vodka2014 please use markdown in the future.

**Comment by Tlabok** [comment] 2015-01-18 15:32
@ Vodka2014
I have just activated debug. This is what I got:

````
2015-01-18 16:25:09 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2015-01-18 16:25:09 INFO     FINDPROPERS :: Quality of [Commie].Aldnoah.Zero.-.14.[5D3C3137].mkv is Unknown
2015-01-18 16:25:06 INFO     FINDPROPERS :: [KickAssTorrents] :: Searching for any new PROPER releases from KickAssTorrents
2015-01-18 16:25:06 INFO     FINDPROPERS :: [EZRSS] :: Searching for any new PROPER releases from EZRSS
2015-01-18 16:25:06 INFO     FINDPROPERS :: [NyaaTorrents] :: Searching for any new PROPER releases from NyaaTorrents
2015-01-18 16:24:35 INFO     FINDPROPERS :: [Animezb] :: Searching for any new PROPER releases from Animezb
2015-01-18 16:24:07 INFO     POSTPROCESSER :: Successfully processed
2015-01-18 16:24:01 INFO     FINDPROPERS :: [nzbs.in] :: Searching for any new PROPER releases from nzbs.in
2015-01-18 16:23:58 INFO     FINDPROPERS :: [nzbgeek] :: Searching for any new PROPER releases from nzbgeek
2015-01-18 16:23:58 INFO     FINDPROPERS :: [Womble's Index] :: Searching for any new PROPER releases from Womble's Index
2015-01-18 16:23:57 INFO     FINDPROPERS :: [Sick Beard Index] :: Searching for any new PROPER releases from Sick Beard Index
2015-01-18 16:23:57 INFO     FINDPROPERS :: Beginning the search for new propers
2015-01-18 16:23:56 INFO     Thread-38 :: Find propers search forced
````
SR Version: 	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
On a Qnap TS-439 Pro.
Python version: 	2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1].

**Comment by Tlabok** [comment] 2015-01-19 15:27
Any chance of this being reopened? I can't imagine that I'm the only one for whom the problem hasn't been solved. The difference appears to be in the use of torrent indexers.

**Comment by abeloin** [comment] 2015-01-20 02:40
@Tlabok Try changing in (master)sickbeard/properFinder.py
 line 148 from "bestResult = pickBestResult(curProper)" to "bestResult = pickBestResult(curProper, parse_result.show)" and restart sickrage.

**Comment by Tlabok** [comment] 2015-01-20 07:44
@abeloin Thanks for advice.
In my sickbeard/properFinder.py
line 148 reads
````
if not pickBestResult(curProper):
```
So, should I change this to
```
if not pickBestResult(curProper, parse_result.show):
```
?
Or is my properFinder.py not correct?

**Comment by Tlabok** [comment] 2015-01-20 07:57
I can't test this, as the Qnap package is reloaded when I restart. Will have to wait for commit to be included in master update.

**Comment by Tlabok** [comment] 2015-01-21 13:41
I have updated my Qnap SickRage package from SickBeard-TVRage_140428.qpkg (which is linked to from the sickrage.tv forum FAQ page) to SickBeard-TVRage_141024.qpkg.

This error has not returned since. Not sure what caused it or what has changed.

**Comment by Vodka2014** [comment] 2015-01-21 18:58
OK so the error started again for me. I do not know what changed.

**Comment by abeloin** [comment] 2015-01-21 19:49
@Tlabok 
Yes it is correct modification.

**Comment by Vodka2014** [comment] 2015-01-21 21:21
This mod work thanks abeloin :) 

Now lets see if this will be stable for the new few days.

**Comment by Electr0Fi** [comment] 2015-01-22 03:23
I've got this issue too. It just happened this morning.
SR Version: BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 

This is what is in my Debug Log:
```
2015-01-22 09:46:46 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/home/aperture/.sickrage/sickbeard/scheduler.py", line 80, in run\n    self.action.run(self.force)\n  File "/home/aperture/.sickrage/sickbeard/properFinder.py", line 52, in run\n    propers = self._getProperList()\n  File "/home/aperture/.sickrage/sickbeard/properFinder.py", line 148, in _getProperList\n    if not pickBestResult(curProper):\n  File "/home/aperture/.sickrage/sickbeard/search.py", line 224, in pickBestResult\n    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):\nAttributeError: \'NoneType\' object has no attribute \'rls_ignore_words\'\n'
AAAttributeError: 'NoneType' object has no attribute 'rls_ignore_words'
AA    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):
AA  File "/home/aperture/.sickrage/sickbeard/search.py", line 224, in pickBestResult
AA    if not pickBestResult(curProper):
AA  File "/home/aperture/.sickrage/sickbeard/properFinder.py", line 148, in _getProperList
AA    propers = self._getProperList()
AA  File "/home/aperture/.sickrage/sickbeard/properFinder.py", line 52, in run
AA    self.action.run(self.force)
AA  File "/home/aperture/.sickrage/sickbeard/scheduler.py", line 80, in run
AATraceback (most recent call last):
2015-01-22 09:46:46 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
```

**Comment by fernandog** [comment] 2015-01-22 10:51
@Electr0Fi please try this fix: https://github.com/abeloin/SickRage/commit/0ae2b034847277f2b180584589882c5ab9499327

**Comment by fernandog** [comment] 2015-01-22 10:52
will close when merged

**Comment by abeloin** [comment] 2015-01-22 12:31
@Electr0Fi Since you're on the master branch the pull request @fernandog provided won't apply properly, see previous comment link for line to change:
https://github.com/SiCKRAGETV/sickrage-issues/issues/328#issuecomment-70615819

**Comment by Electr0Fi** [comment] 2015-01-23 02:10
@abeloin So I just manually change that line in the file? I don't need to do any pulling?

**Comment by abeloin** [comment] 2015-01-23 02:21
@Electr0Fi Yes until the fix is merge into master

**Comment by Vodka2014** [comment] 2015-01-28 20:49
So far so good it is stable.the only issue i have is if i have the username and password setup it breaks again. Other then that this is good.

**Comment by abeloin** [comment] 2015-01-29 02:06
@Vodka2014 What exactly is the error when you activate the login?

**Comment by fernandog** [comment] 2015-01-29 23:51
@timrettop  please update SR and report back please. Fix was merged

**Comment by Vodka2014** [comment] 2015-01-30 18:09
Will set it up again and revert back as soon as i can. If the issue is diffrent to the errors listed above will open a new issue list of that is ok.

**Comment by abeloin** [comment] 2015-02-05 15:43
@Vodka2014 Had issue reverting?

**Comment by timrettop** [comment] 2015-02-05 16:14
@abeloin Since updating, I've not received that error any longer.  
I have received one error that is in the FINDPROPERS thread,  but unfortunately my debug logs don't go back to the 2nd: 

2015-02-02 20:02:16 FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'size'

**Comment by timrettop** [comment] 2015-02-05 16:20
@abeloin I ran a force check on find propers, and it seems like a different error message, should I file it separately?

**Comment by abeloin** [comment] 2015-02-05 16:38
@timrettop For the no attribute size, check #323 for [a fix](https://github.com/SiCKRAGETV/sickrage-issues/issues/323#issuecomment-72682877)

For your 2nd comment, what's the error?

**Comment by timrettop** [comment] 2015-02-05 16:46
@abeloin I wasn't clear in that second comment, I meant that the size error seems different than the error reported in this bug.  

I'd say this can be closed. 
Thanks!

**Comment by abeloin** [comment] 2015-02-05 16:52
@timrettop Good and thank you for the testing.

@fernandog Can you close this issue? Thank You

**Closed** 2015-02-05 18:16 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: master
