### ISSUE TITLE
Mark download as bad and retry - does not work

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#652] opened 2015-02-18 08:53 UTC
I have to change status to "wanted" first (was snatched) otherwise it will not download a new version....

SR Version:	BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede) 
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

**Comment by TagForce** [comment] 2015-02-18 08:56
@hoefs Can you provide a log of SR from when you click the mark as bad and retry button?
It seems to work just fine here.

**Comment by fernandog** [comment] 2015-02-18 10:44
@TagForce I this issue is about to not download same quality if we do manual search, the manual search will only try to find proper or better quality

**Comment by hoefs** [comment] 2015-02-18 13:04
Even if it is snatched? My problem is:
snatch finds web-dl (does not download but has status snatched), I click search and mark as bad and in the logs it keeps telling me that it does not find a better quality than web-dl... If I say it is bad, it should download another copy?

**Comment by fernandog** [comment] 2015-02-18 22:53
@TagForce here we should ask user not to mark as bad download but if he want to re-download same quality or just search for better quality/proper.

Is there a way to get the user input in the code below?

```
        if quality in anyQualities + bestQualities:
            if epStatus in (WANTED, UNAIRED, SKIPPED):
                logger.log(u"Existing episode status is wanted/unaired/skipped, getting found episode", logger.DEBUG)
                return True
            elif manualSearch and (WINDOW.ALERT RESPONSE == True:
                logger.log(
                    u"Re-download same episode as requested by user ",
                    logger.DEBUG)
                return True
```
https://github.com/SiCKRAGETV/SickRage/blob/8b3f431ae1fd687b629896a4476b6af0308e60c2/sickbeard/tv.py#L1223

**Comment by fernandog** [comment] 2015-02-19 00:34
@abeloin

**Comment by abeloin** [comment] 2015-02-19 01:12
@fernandog Yes?

**Comment by fernandog** [comment] 2015-02-19 01:15
Is there a way to get the user input in the code below?

Code above

**Comment by abeloin** [comment] 2015-02-19 01:17
Let me check

**Comment by abeloin** [comment] 2015-02-19 01:34
By the way: this commit state we should use wanted first: https://github.com/SiCKRAGETV/SickRage/commit/8b3f431ae1fd687b629896a4476b6af0308e60c2

**Comment by fernandog** [comment] 2015-02-19 01:39
I would set this a festure request. its a better solution to ask the user.

**Comment by abeloin** [comment] 2015-02-19 01:39
>Is there a way to get the user input in the code above?

It look like manualSearch was intended to do that

**Comment by abeloin** [comment] 2015-02-19 01:43
manualSearch is true when manual search, false when backlog and true when failed

**Comment by abeloin** [comment] 2015-02-19 02:01
You could modify sickbeard/search_queue.py#L161 to include manualSearch, and update the reference.
Change sickbeard/webserve.py#L1786 to include manualSearch, and update the reference.
Then from gui/slick/js/ajaxEpSearch.js@L128 ask the question.

**Comment by TagForce** [comment] 2015-02-19 19:11
@fernandog @abeloin Wait... I suddenly understand what the problem is.
My opinion (not going to be a popular one) is that it should download any quality it finds. It should not care about the already downloaded quality, basically because we've just told it that the one we have is no good, and it needs to be replaced.

If you want a higher quality release than the one you have? It's already searching for one in the backlog. That's not what the Manual Search button is for. You can force the backlog for the episode.

I even believe that the manual search button should be removed entirely if failed downloads is turned off, and an episode is downloaded. It should be replaced with an option to remove the episode from disk and set the status back to wanted.

Manual Search should be used in the following cases:
1) When failed downloads is on, and you want to tell SR that a download has failed and please try again.
2) If you want to force search for an episode it hasn't found yet.

Everything else should be done through backlog searches.
Note that both scenarios above have no need for a quality requirement. We have no (valid) video file for an episode, so any quality we want is fine.

Wouldn't you agree?

**Comment by hoefs** [comment] 2015-02-19 19:19
Mark as bad should remove the file and search for another one... even if status is snatched or downloaded or...

**Comment by abeloin** [comment] 2015-02-19 19:34
@TagForce See commit https://github.com/abeloin/SickRage/commit/8b3f431ae1fd687b629896a4476b6af0308e60c2 which disable that functionality.

**Comment by TagForce** [comment] 2015-02-19 19:42
@abeloin @fernandog Yes, and I think it should be reverted. Manual search is not for searching for higher qualities, it's for searching an episode. That's what I take it to mean, anyway.

**Comment by hoefs** [comment] 2015-02-19 19:52
@TagForce correct!!!

**Comment by fernandog** [comment] 2015-02-20 10:39
@TagForce @abeloin 

**about manual search**
. As the name we force a MANUAL SEARCH. This was made to force search. Some users set the search frequency to 8, 12 or 18 hours and higher backlog frequency. This manual is to force a search ONLY to that episode. Backlog and search need resources and a 10-20min-60 search frequency it not possible on some setups

My suggestion is the same: ask user if the wants to download the same quality or force search for proper or high quality for every "MANUAL SEARCH" button push OR we add this option to config.ini
We can't force user do something if we can ask him what do to. Otherwise SR code will be a lot smaller.

**about failed**
I still think user should be able to mark as FAILED without PP (read this user comment:
https://github.com/SiCKRAGETV/sickrage-issues/issues/657#issuecomment-75055167 ) gborri 

this way user could implement failed through API or web UI ( https://github.com/SiCKRAGETV/sickrage-issues/issues/52 ). 
@Hellowlol

fase 1: I think it's not a big change in the code. Just start FAILED process (the same process PP runs) when user set manually as FAILED in the show page. 
fase2: failed using API.

@echel0n as this is a big change and you want to approve this changes before merging them, what do you think?

**Comment by xstefanx** [comment] 2015-02-24 06:44
I believe I've run into issues with this process as well, but I thought I would post here to see if this would be fixed by the planned process. 

I had previously downloaded a show. I had deleted the episodes from my drive because they were downloaded prior to having set up hard links and renaming and they were originally posted with the wrong episode numbers. When I go to redownload them manually I get the pop up about marking the download as failed. No matter what I do I can not download the episode from this point, as it only sees it as being a failed download. 

I assume the proposed fix would allow me to manually search and force a redownload of the same quality/version right?

**Comment by fernandog** [comment] 2015-02-24 09:46
Set as WANTED and do a manual search

**Comment by xstefanx** [comment] 2015-02-24 14:08
That's what I'm doing when I see this problem. http://i.imgur.com/vJz9yQS.png

**Comment by fernandog** [comment] 2015-02-24 14:09
just click yes

**Comment by xstefanx** [comment] 2015-02-24 14:53
That doesn't work. It gives me this when I do that. http://i.imgur.com/nLfJFU6.png

I have the show set up to grab 720p, and there are actually two versions that meet that requirement on the site. It's ignoring them. I presume because they've been marked as failed.

**Comment by fernandog** [comment] 2015-02-24 15:01
Did you set as WANTED before manual search?

**Comment by xstefanx** [comment] 2015-02-24 15:01
Yes, I did.

**Comment by xstefanx** [comment] 2015-02-24 15:23
Something along the lines of this would also help to resolve this issue I think. https://github.com/SiCKRAGETV/sickrage-issues/issues/699#issuecomment-75708901

**Comment by fernandog** [comment] 2015-03-06 17:38
@hoefs please enable failed downloads in search settings. new downloads will work with the "failed" feature (previous don't)

**Closed by fernandog** 2015-03-06 17:38 UTC
Labels: 1: Feature request, 1: Support / question
