### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'getOverview'

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#1291] opened 2015-04-16 21:18 UTC
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/288da00500d851b4c468
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1966, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1926, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
AttributeError: 'NoneType' object has no attribute 'getOverview'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ripper1967** [comment] 2015-04-16 21:19
after complete mass update still have the error.

**Comment by fernandog** [comment] 2015-04-16 22:14
@ripper1967 can you try to open all your tv-shows pages and report the one that is raising this error?

**Comment by Tlabok** [comment] 2015-04-17 08:07
I have the same problem. I have looked at all my shows' pages but nothing happens when I do that.

**Comment by TagForce** [comment] 2015-04-17 08:54
@ripper1967 @Tlabok Have you guys recently removed a show from SR?
The error originates from getEpisodes, which is run when you manually search for an episode.
The only way for this error to happen is when ShowObj is None, and that can only happen when findCertainShow returns None, which should only happen when the show is not in your list.

So, basically, I'm thinking the cause for this is a stale episode being searched for a show that is no longer in your list.

**Comment by TagForce** [comment] 2015-04-17 09:28
@fernandog I've just reproduced this error...
I added a very old show to my SR to make sure there would be episodes that won't be found...
I selected an episode, and hit manual search...
Ran through the search perfectly fine. Went back to the showpage, and removed it.
Went back to /home, and manually searched for an episode on a different show.
*boom*
```
11:06:13 ERROR::Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\user\git\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\Users\user\git\SickRage\sickbeard\webserve.py", line 1966, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "C:\Users\user\git\SickRage\sickbeard\webserve.py", line 1926, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
AttributeError: 'NoneType' object has no attribute 'getOverview'
```

It seems to only happen when you search an episode for a show after you've just deleted a show for which an episode is still being searched. Hmmm.

**Comment by Tlabok** [comment] 2015-04-17 09:33
So the problem is that SR keeps looking for episodes after a show has been removed? I recently removed some shows that were cancelled/ended.

**Comment by TagForce** [comment] 2015-04-17 09:38
@ripper1967 @Tlabok 
Can you guys add the following lines to webserve.py lines at 1918 (stop SR first):
```
            if not ShowObj:
                logger.log('No Show Object found for show with indexerID: ' + searchThread.show.indexerid, logger.ERROR)
```

Please mind the indentation.
Then please restart SR. It should still throw the exception, but should also show the showid for which the error occurred right before it.

I think restarting SR (or simply waiting) will fix the error eventually, so it may not happen again. That is fine too, at least I know that it happens when removing shows while a search is in progress and I'll just return results when ShowObj is None. I would like to find the root cause for this, so logging with the error still in place might help.

**Comment by Tlabok** [comment] 2015-04-17 09:45
@TagForce 
I can't change and restart SR because of the way my Qnap package works.

**Comment by TagForce** [comment] 2015-04-17 10:00
@Tlabok Ok, no problem... I'll add the log, return result anyway so the exception is gone.
PR that to develop, which will be merged into master on sunday.

If the error is still occurring we can look for it next week.

**Comment by Tlabok** [comment] 2015-04-17 10:01
@TagForce 
Thanks!

**Comment by TagForce** [comment] 2015-04-17 10:07
@fernandog https://github.com/SiCKRAGETV/SickRage/pull/1787

**Comment by fernandog** [comment] 2015-04-17 10:18
merged in develop

**Comment by ripper1967** [comment] 2015-04-17 11:25
TagForce, if not ShowObj:
                logger.log('No Show Object found for show with indexerID: ' + searchThread.show.indexerid, logger.   
that did the trick for me no more error and you was correct i had moved like 150 shows from one drive to a larger drive and removed a few as well then boom that error

**Comment by fernandog** [comment] 2015-04-17 11:29
@TagForce do you think is worth to check if show is in search queue before remove it ?

**Comment by ripper1967** [comment] 2015-04-17 11:33
well i think its because i have such a large collection and it may still be searching, is there a way of telling it not to remove a show that is  queued

**Comment by ripper1967** [comment] 2015-04-17 11:33
oops already asked lol..

**Comment by TagForce** [comment] 2015-04-17 11:45
@fernandog @ripper1967 Well... I'd think not removing a show when you want to remove it will cause a lot of confusion...

My solution would be to include an extra step in the removal of a show, namely setting all the episodes for the show to ignored, and then removing all the searches for that show from the searchQueues. That should stop this from happening.

My PR effectively stops the Exception from happening, and will tell you that the show no longer exists (or at least that it no longer can be found) so the urgency for a fix is gone. That means we can fix all the other stuff, and get back to this later and fix it properly.

**Comment by ripper1967** [comment] 2015-04-17 12:03
sounds good to me, your Pr did fix it for me as well but i did figure out with out your Pr, if i removed all the shows then just restarted sick rage before a new search the error wasn`t produced ,but if i just removed show then did a search it would produce...

**Comment by fernandog** [comment] 2015-04-17 12:09
will close this an open a FR with low priory for that

**Closed by fernandog** 2015-04-17 12:09 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
