### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by rafaelrosars** [SiCKRAGETV/sickrage-issues#1379] opened 2015-04-22 13:51 UTC
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-121361 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by cyberundertaker** [comment] 2015-04-22 13:58
@fernandog 

I got the same error:

2015-04-22 15:40:37 SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:28 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-04-22 15:40:28 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-04-22 15:40:27 FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: 521 Server Error: Origin Down
2015-04-22 09:40:36 SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by abeloin** [comment] 2015-04-22 14:07
Dupe of #1231, reply in that issue

Post results of `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`

Also have a look at issue #978

**Closed by abeloin** 2015-04-22 14:07 UTC

**Comment by rafaelrosars** [comment] 2015-04-22 21:31
My python is LibreSSL 2.1. How can i solve?

**Comment by abeloin** [comment] 2015-04-22 23:57
@rafaelrosars Use issue #1231 for discussion and Post results of `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`
