### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't decode byte 0x9d in position 35: character maps to <undefined>

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#779] opened 2015-02-26 18:48 UTC
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@fdd1f63bdbf007df87943f9776ac9b80cc8e3353
### ERROR
```
Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\webserve.py", line 231, in async_call
    result = function(**kwargs)
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\webserve.py", line 1204, in displayShow
    return t.respond()
  File "C:\Users\Pedro\Desktop\SickRage-master\cache\cheetah\_Users_Pedro_Desktop_SickRage_master_gui_slick_interfaces_default_displayShow_tmpl.py", line 605, in respond
    if _v is not None: write(_filter(_v))
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\webserve.py", line 91, in filter
    filtered = val.decode(sickbeard.SYS_ENCODING).encode('ascii', 'xmlcharrefreplace')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35: character maps to <undefined>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment] 2015-02-26 19:58
One of your show as this [”](http://www.charbase.com/201d-unicode-right-double-quotation-mark) in their name.

**Comment by abeloin** [comment] 2015-02-26 20:03
filtered = val.decode('utf-8').encode('ascii', 'xmlcharrefreplace')

**Comment by pct00** [comment] 2015-02-26 21:16
@abeloin seems to have fixed it, before i wasnt able to open the show page, however when trying to make the rescan or update a new error is shown on console but not logged. want me to open a separate issue for it ?

21:14:09 DEBUG::SHOWQUEUE-REFRESH :: Parsed C:\Users\Pedro\Desktop\-ANIME\One Piece\One Piece - 000 - SD TV - .avi into One Piece - ENone [A
BS: [0]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']]
Exception in thread SHOWQUEUE-REFRESH:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\show_queue.py", line 421, in run
    self.show.refreshDir()
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 1044, in refreshDir
    self.loadEpisodesFromDir()
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 414, in loadEpisodesFromDir
    curEpisode = self.makeEpFromFile(ek.ek(os.path.join, self._location, mediaFile))
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 640, in makeEpFromFile
    episode = int(curEpNum)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by abeloin** [comment] 2015-02-26 23:18
@pct00 The error is because your episode number is 0 and should be > 0

**Comment by pct00** [comment] 2015-02-27 07:54
i have several episodes 0 because SR messed up the postprocessing and renaming

solution is delete them manually?
the previous behaviour was SR recognized them as additional episodes for the show/season and created new entries on them

**Comment by abeloin** [comment] 2015-02-27 13:06
I'll look in the other issues but I remember seeing something about disabling episode 0 because it conflicted with air date regex.

**Comment by abeloin** [comment] 2015-03-01 04:27
PR Merged, update develop branch

**Comment by fernandog** [comment] 2015-03-01 10:24
@pct00 please update and report back

**Comment by abeloin** [comment] 2015-03-01 11:20
PR reverted issue https://github.com/SiCKRAGETV/sickrage-issues/issues/796

**Comment by abeloin** [comment] 2015-03-01 20:45
@pct00 Can you test this PR it replace the previous one? https://github.com/SiCKRAGETV/SickRage/pull/1442

**Comment by icebal** [comment] 2015-03-02 12:16
im testing this as i write this, waiting for the error to pop up, usually happens in 15-20 minutes

**Comment by icebal** [comment] 2015-03-02 12:24
was able to force download all subtitles and did not receive the error :D

**Comment by fernandog** [comment] 2015-03-02 12:34
@icebal are you using the latest develop update? if so, we can close the issue

**Comment by icebal** [comment] 2015-03-02 12:39
im using the latest update (i believe) plus the above patched in

**Comment by icebal** [comment] 2015-03-02 12:51
nooopoe my bad, BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9)

**Comment by fernandog** [comment] 2015-03-02 12:52
@icebal can you switch to develop in general>advanced>github and try reproduce the error?

**Comment by icebal** [comment] 2015-03-02 12:53
trying it now

**Comment by icebal** [comment] 2015-03-02 12:58
not seeing any, got through all the anime, where most of my errors came from

**Comment by fernandog** [comment] 2015-03-02 13:03
@icebal when you switch from master>develop, did SR restarted automatically?

**Comment by icebal** [comment] 2015-03-02 13:04
it did, and only one process going. still no errors and have gone through all my shows with no errors.

**Comment by icebal** [comment] 2015-03-02 13:05
still no sign of the other issue with the log files getting stuck either

**Comment by fernandog** [comment] 2015-03-02 13:07
@icebal ok will close this issue

**Closed by fernandog** 2015-03-02 13:07 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback
