### ISSUE TITLE
[Feature Request] Show Episode History in "Coming Episodes" calendar view to catch missed shows 

### ISSUE THREAD

**Issue by shovelhed** [SiCKRAGETV/sickrage-issues#991] opened 2015-03-18 14:30 UTC
Currently it requires a lot of clicking about to see if you've actually gotten (snatched, downloaded) the shows in your list. You need to manually travel the show list figuring out which shows were on yesterday and if they were successfully grabbed.

It would be useful to have some amount of history (user configurable?) in the Coming Episodes area when looking at a calendar view to determine what was missed and at the same time enabling you to get in to those shows to catch up with manual searches or what not.

**Comment by fernandog** [comment] 2015-03-18 14:33
@shovelhed we already have this

stop SR,
edit config.ini
set `coming_eps_missed_range` to any value you want. Mine is 30;

**Comment by shovelhed** [comment] 2015-03-18 14:41
Amazing. Sorry if I wasted your time. I searched all over for this and assumed it wasn't available.  Could this be exposed through the UI to users?

Also, Calendar view still defaults to a one week view even after setting the value as described. It shows Today -> Tuesday next week.

**Comment by fernandog** [comment] 2015-03-18 14:44
@shovelhed will try to add to the interface settings

about calendar will have to check that

**Comment by fernandog** [comment] 2015-03-18 16:31
@shovelhed calendar only show future shows. not missed. not an issue

**Comment by fernandog** [comment] 2015-03-18 16:38
@shovelhed if I make calendar to respect `coming_eps_missed_range` I get this:

In my case is 30 days

![calendar](https://cloud.githubusercontent.com/assets/2620870/6713870/d437fe96-cd73-11e4-884b-db8f88b8fd48.png)

@tchirou @timrettop  what  do you think? do you want to see missed in calendar?

**Comment by tchirou** [comment] 2015-03-18 16:44
Yeah actually it is a good idea
My need to have the webcal in the google calendar is to have the daily google email at 5am with what have aired (I am in GMT+1) and see in the history tab of SR if I have the same shows with downloaded.
it is quite tedious and wold be easier to see autimatically in the coming episodes tab if there are missed shows
:+1:

**Comment by tchirou** [comment] 2015-03-18 16:46
When you say missed, it can be sntached but not downloaded right ?

**Comment by shovelhed** [comment] 2015-03-18 16:48
Yeah, while that view is awful, the idea is sound.  Sonarr does this (no images)
![images](https://cloud.githubusercontent.com/assets/11539816/6714137/17362198-cd6d-11e4-9c27-126a51b59f2e.jpg)

**Comment by tchirou** [comment] 2015-03-18 16:49
Personally I use the list layout of the coming episodes page

**Comment by fernandog** [comment] 2015-03-18 16:55
@tchirou me too

**Comment by abeloin** [comment] 2015-03-18 23:09
@fernandog Why not simply add an option to show the snatched on the page? This way any show not present are downloaded, snacthed are shown along the missed in another color. This should resolve the OP issue. As for download history, it's not the job of the coming episode but rather should be added in the history section.

**Comment by tchirou** [comment] 2015-03-19 08:30
Ok I didn't understand at first the specifics of the calendar view

As I said, I use the list layout. It already shows the missed episodes, whici is currently are the "not snatched" shows, which is quite handy.

But it is limited as as soon as a show is snatched, it disappears from the coming episodes list.
But hen we have to go to the history page and check if all snatched are downloaded. This is to me too much a human and manual process which can be a pain when you have a lot of shows daily, as I do and I think a lot of people do.

So I know this is not what OP discussed in the first place but I think it coul be nice to have the possibility in the coming episodes list layout to see the "snatched but not downloaded" shows, like you can see the paused show if you want : you connect to SR, you just have to take a look to check there is no "not snatched" (former "missed") and no "snatched" (which means snatched but not downloaded). So if everything is alright, you know it in 1 second and you don't have to keep checking the history page.
I can post a new issue to reference it if you need me to do. I really think it would be useful to almost everybody.

**Comment by fernandog** [comment] 2015-03-19 10:31
The big problem here is a lot if users have his entire library as " snatched" and not downloaded. If we add this, it should be off by default.
IMO adding snatched misses the point of the page.

What I do to see all snatchedc(despite the cell phone notification using NMA) is to access this page:
http://localhost:8081/manage/episodeStatuses?whichStatus=2

also there is the history page that shows snatched AND downloaded.

If more users want this we should change "coming episodes" page name.

**Comment by shovelhed** [comment] 2015-03-19 11:07
May else that's it. Coming episodes could instead show everything thereby
reducing clutter of another page.

Like the image I posted from sonarr: past,  present,  future,  snatched and
perhaps even currently downloading episodes could all be colour coded.

**Comment by tchirou** [comment] 2015-03-19 11:38
Well I wasn't aware of the http://localhost:8081/manage/episodeStatuses?whichStatus=2
So if snatched but not downloaded, they appear here ? This is nice. I should pay more attention to this "manage" section
Would be nice to have the option in the coming episodes list as we could see in the same time the not snatched and the snatched but not downloaded

**Comment by MGaetan89** [comment] 2015-07-08 19:12
This is a duplicate of #473, no? So one of them could be closed. IMO, #473 can be closed, as discussion happened here.

**Comment by OmgImAlexis** [comment] 2015-09-26 14:00
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Closed by OmgImAlexis** 2015-09-26 14:00 UTC
Labels: 1: Feature request
