### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#178] opened 2014-12-19 03:50 UTC
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:20:40) 
[GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5e1298f801648204fa62456e86d02bf53f61d1c5

debug log : http://pastebin.com/pDb5Nz1a
### ERROR
```
SEARCHQUEUE-MANUAL-271910 :: Transmission: Failed Sending Torrent: Halt.And.Catch.Fire.S01E01.FRENCH.1080p.WEB-DL.H264-AUTHORiTY - 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by t0per** [comment] 2015-01-08 14:02
Same issue here, still can't send to transmission with T411 provider.

Thanks

**Comment by lucianot54** [comment] 2015-01-12 14:54
Same problem since a long time. I investigated and for me the problem is sickrage doesn't keep authentication and/or it missed data". In cache/sessions/ folder, i don't have file for t411.

I tried to send a manual request and the following request works :
```
POST /users/login/ HTTP/1.1
Host: www.t411.me
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://www.t411.me/users/login/
Cookie: __cfduid=.......; __utma=3462......8.1; __utmb=346....378; __utmc=346...5; __utmz=34....1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); Adk2_popUp={'numOfTimes':...., 'exdate':'Mon, 12 Jan 2015 12:16:21 GMT'}; last_access=14......1; __utmt=1
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: ....

login=login&password=password&remember=1
```

Maybe clean the useless data but i think we need force the Referrer to have an authentication.
echel0n fixed the problem for the content-type but i have again the problem too.

After a good authentication of t411, you have a cookie like that :
```
Cookie: 
last_access=14...1;
__utmt=1;
uid=104...2;
pass=cd......5b;
authKey=4b........5;
authApi=10......d
```

I can't investigate more because t411 is down at this time, but i hope help you.

**Comment by lucianot54** [comment] 2015-01-13 14:10
It works for me; problem with the user-agent, cookie and cloudfare :
https://github.com/SiCKRAGETV/SickRage/pull/1181

**Comment by lucianot54** [comment] 2015-01-13 14:32
It works for me, anyone can confirm?

**Comment by fernandog** [comment] 2015-01-13 14:36
@lucianot54 we have to wait @echel0n. Her child has born and he's getting a personal time.

**Comment by lucianot54** [comment] 2015-01-13 14:42
No problem, there's no rush :)

**Comment by jeryagor** [comment] 2015-01-13 17:26
Your fix is working on my side as well. :+1:

**Comment by fernandog** [comment] 2015-01-14 17:47
@maxcore @Alouch47 @Zabie can we close this issue after the new develop update?

**Comment by fernandog** [comment] 2015-01-16 10:47
@lucianot54 @jeryagor  can you verify this issue?
https://github.com/SiCKRAGETV/sickrage-issues/issues/420

Is this provider still working?

**Comment by d1g2w3** [comment] 2015-01-17 22:06
This fix also works for me. Great work :)

**Comment by markheloking** [comment] 2015-01-18 12:16
Closing this since it should be solved. Please do report back if the issue persists.

**Closed by markheloking** 2015-01-18 12:16 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Confirmed, 4: Fix pending, branch: develop

**Comment by maxcore** [comment] 2015-01-21 05:11
Thx for the fix ! Work perfect!

**Comment by GTrebaol** [comment] 2015-01-28 00:08
Work nicely here, thanks
