### ISSUE TITLE
Backlog episode search using season settings

### ISSUE THREAD

**Issue by cwallace** [SiCKRAGETV/sickrage-issues#718] opened 2015-02-22 00:24 UTC
BRANCH: (develop)
COMMIT: (fbcadb278054808639884dca5804d544bbc0a675) 
Python Version:	2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]
OS: Ubuntu 14.10

What you did: Added show to backlog

What happened: Backlog searches for IPT include partial word searches (S01) for episode search mode, which IPT search does not support and SceneAccess is searching archive rather than normal search, which is only supposed to be used for season searches.

What you expected: IPT should not be including the season in the search query as IPT doesn't support partial word matches. SceneAccess should not be searching archive unless it's in season mode per the provider:

                if mode == 'Season':
                    searchURLS += [self.urls['archive'] % (search_string)]
                else:
                    searchURLS += [self.urls['search'] % (search_string, self.categories)]
                    searchURLS += [self.urls['nonscene'] % (search_string)]
                    searchURLS += [self.urls['foreign'] % (search_string)]

 
Log showing it is searching in episode mode:
http://pastebin.com/QvcNVanX

**Comment by fernandog** [comment] 2015-02-22 17:11
@cwallace can you make a proposed PR?

**Comment by cwallace** [comment] 2015-02-22 17:46
I don't know python or the project well enough to submit a PR. It would most definitely break something else. 

That said I don't believe the issue is with either provider. It seems season mode is being passed to the provider even though it has been disabled and is not falling back to individual episode mode. If I add episodes individually they are found and snatched, but if I add multiple episodes it looks like it is forcing season mode. 

Here are my settings:
http://i.imgur.com/izIavdG.png
http://i.imgur.com/RYNEjBi.png

**Comment by fernandog** [comment] 2015-02-22 18:45
@cwallace what is IPT season mode setting in search provider settings?

**Comment by flightlevel** [comment] 2015-02-22 23:51
Looks like the same issue as this https://sickrage.tv/forums/forum/help-support/bug-issue-reports/9612-ipt-backlog-not-getting-any-results

IPT won't do wildcard searching (eg TvShowName S01 won't find TvShowName S01E01, TvShowName S01E15 etc)

Two options I see
1. Strip the season number so it just searches for TvShowName and NOT TvShowName S01
2. Search for each episode individually (Not sure if this is possible without huge code changes though)???

**Comment by cwallace** [comment] 2015-02-23 03:42
@fernandog It is set to episodes only with fallback turned off.

@flightlevel I believe the problem is that sickrage is searching in season mode even though it is disabled. By only selecting episodes one at a time I'm able to successfully snatch backlogged shows, but anything more than one episode and sickrage is attempting to search in season mode. This would be fine for full seasons that have completed, but for seasons which have not yet completed (and therefore don't have full season torrents available) it doesn't work at all. SCC is a perfect example - sickrage is only searching the archive section which only contains full seasons and will not search the regular torrent section whenever I attempt to add more than one episode to backlog.

**Comment by mtosic** [comment] 2015-02-25 11:24
I have similar behaviour for BTN

BRANCH: (master)
COMMIT: (2d8aad80cdfb8983832206af445039de0decded9) 
Python Version: 2.7.8
OS: Windows 8.1

What I expected:
I've added BTN as search provider and I want following behavior when I add a show (to minimize number of torrents snatched):
1. Download season packs of previous seasons
2. Download individual episodes (up-to-date) of current season (if it's currently airing / not completed yet)

What I did:
Provider setting for BTN are:
1. Season search mode: Season pack only
2. Season search fallback: Checked

What happened:
1. It sets all episodes for all seasons to "Wanted"
2. It downloads season packs for previous seasons
3. If current season is airing, status of individual episodes remain in "Wanted" and don't get downloaded, unless I press manual search, but that defeats the purpose of automation

**Comment by fernandog** [comment] 2015-02-25 11:49
@mtosic I think the season pack works when all episodes are already aired.

**Comment by fernandog** [comment] 2015-02-25 11:51
@coolius can you confirm IPT don't do season search?

**Comment by coolius** [comment] 2015-02-25 12:12
Forgive me, I don't have much experience with season searches but I can confirm that IPT (and TorrentDay) don't support partial searching so any search for eg "Arrow S03" returns nothing. The fallback option seems to work for me when doing a manual search.

**Comment by fernandog** [comment] 2015-02-25 13:17
@abeloin 
my suggestion is:
create a new config for each provider with (config only not UI)
iptorrents_season_enabled = 1 or 0

config_provider should read this config and disable the "Season search mode" radiobuttons using javascript

what do you think?

**Comment by mtosic** [comment] 2015-02-25 15:11
What happens in this scenario:
1. Show is airing
2. Download season packs of previous seasons
3. Download individual episodes (up-to-date) of current season (if it's currently airing / not completed yet)

If I choose "episodes only" and "Season search fallback", will the result be:
1. Download individual series for aired seasons
2. Download season pack

**Comment by abeloin** [comment] 2015-02-25 16:35
This should fix when searching manually: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L466
```
        # Always search for episode when manually searching when in sponly and fallback false
        if search_mode == 'sponly' and manualSearch == True and curProvider.search_fallback == False:
            search_mode = 'eponly'
```

As for the the backlog, if you enable the fallback option it will switch depending on the search mode: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L466
```
            elif not curProvider.search_fallback or searchCount == 2:
                break

            if search_mode == 'sponly':
                logger.log(u"FALLBACK EPISODE SEARCH INITIATED ...")
                search_mode = 'eponly'
            else:
                logger.log(u"FALLBACK SEASON PACK SEARCH INITIATED ...")
                search_mode = 'sponly'
```


Introdution season pack search Ref: https://github.com/SiCKRAGETV/SickRage/commit/e96035ff4fbb33d098e03008a483e382fe03cca5#diff-0a0def536617657159afe93c856bc62d

**Comment by fernandog** [comment] 2015-02-25 16:49
@abeloin if all episodes are aired and wanted (full season wanted) but user is manually searching for a single episode, then it's correct to use eponly. don't you think?

**Comment by abeloin** [comment] 2015-02-25 16:55
@fernandog That is what the snippet of code does:
```
        # Always search for episode when manually searching when in sponly and fallback false
        if search_mode == 'sponly' and manualSearch == True and curProvider.search_fallback == False:
            search_mode = 'eponly'
```

**Comment by fernandog** [comment] 2015-02-25 16:56
@abeloin so I misunderstood when you wrote "This should fix when searching manually:"

**Comment by abeloin** [comment] 2015-02-25 17:23
@fernandog I think we are saying the same thing:
Searching manually meaning clicking on the hourglass to look specifically for that episode. If Season mode and fallback are enabled, no problem it will fallback to episode search after searching for season. The problem is if Season mode is enable but fallback isn't it will never find results for that specific episode because sickrage is expecting a season in findresults.

**Comment by abeloin** [comment] 2015-02-25 17:33
@fernandog For the backlog, i think we simply need to override the findSearchResults from generic to:
```
    def findSearchResults(self, show, episodes, search_mode, manualSearch=False):
        return generic.TorrentProvider.findSearchResults(self, show, episodes, 'eponly', manualSearch)
```
Or add self.supportsSearchMode in generic.py and add it to findSearchResults which would set search_mode to eponly and hides it from the webui

**Comment by fernandog** [comment] 2015-02-25 17:44
@abeloin whatever it's better. is it about this comment https://github.com/SiCKRAGETV/sickrage-issues/issues/718#issuecomment-75944721 ?

**Comment by mtosic** [comment] 2015-02-25 18:11
I opened a new issue with more information, from discussion I think it's not the same as this one.
Issue: https://github.com/SiCKRAGETV/sickrage-issues/issues/767

**Comment by cwallace** [comment] 2015-02-26 00:52
@mtosic this is the same behavior I'm seeing, but with IPT and SCC. Even if I have mode set to episode search and try to add a season which either 1) hasn't finished or 2) doesn't have a full season torrent available, Sickrage isn't searching for individual episodes. The only way I can get Sickrage to download in either of those two scenarios is to add each show individually.

**Comment by abeloin** [comment] 2015-02-27 00:20
@cwallace Can you test this PR https://github.com/SiCKRAGETV/SickRage/pull/1424 ?

**Comment by abeloin** [comment] 2015-02-27 00:25
@cwallace Can you test this PR https://github.com/SiCKRAGETV/SickRage/pull/1425 ?

**Comment by abeloin** [comment] 2015-03-01 04:12
@cwallace Have you tried the PRs?

**Comment by fernandog** [comment] 2015-03-03 16:53
@cwallace still waiting....

**Comment by fernandog** [comment] 2015-03-04 00:51
fixed in develop

**Closed by fernandog** 2015-03-04 00:51 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: develop
