### ISSUE TITLE
[Feature Request] Add socket.io/websocket api

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2658] opened 2015-09-05 08:06 UTC
If we added in a socket.io/websocket api as well as the normal api then we wouldn't need to poll for new messages and waste bandwidth and loading time. We also wouldn't need to refresh the page every 5 minutes like we currently do.

**Comment by WebSpider** [comment] 2015-09-05 08:12
Duplicate of your own #2586

**Closed by WebSpider** 2015-09-05 08:12 UTC
Labels: 5: Duplicate

**Comment by OmgImAlexis** [comment] 2015-09-05 08:30
Oops. Didn't think I had opened an issue on this yet.
