### ISSUE TITLE
Config > General page

### ISSUE THREAD

**Issue by cardgone** [SiCKRAGETV/sickrage-issues#307] opened 2014-12-30 18:37 UTC
I am a beginner and not good with Linux, but I have run sickbeard for the last 4 years on my mac.  I am now setting up a new mac and tried to install the latest version of SickRage yesterday as it sounds GREAT!   I will need some step by step instructions on how to fix this, but if nobody can help, then at least how to uninstall so I can go back to sickbeard, although I would really like to get this working as it sounds like much improved features.

On the config options, I am not getting a WEBUI page here, I get the following:
Error

'NoneType' object is not iterable

Traceback
```python
Traceback (most recent call last): 
File "/Applications/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/Applications/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/Applications/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/Applications/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/Applications/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/Applications/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/Applications/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/Applications/SickRage/cache/cheetah/_Applications_SickRage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 
```
Request Info
```python
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1419964360.95
headers: {'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5', 'Host': 'localhost:8081', 'Cache-Control': 'max-age=0'}
host: localhost:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/general/
method: GET
remote_ip
```

![screen shot 2014-12-30 at 12 36 49 pm](https://cloud.githubusercontent.com/assets/10351668/5581483/8f35c8d6-9020-11e4-8ccf-eff133e63d33.png)

**Comment by neoatomic** [comment] 2015-01-02 17:24
Be patient. With the holidays tings dont move as fast as normally do. 
Did you do a clean install or did you use your old (sickbeard) config.ini & sickbeard.db?
As a workaround you could edit the settings manually in the config.ini, that might solve your problem till the developers can take a look at this.

**Comment by markheloking** [comment] 2015-01-05 16:51
@echel0n is indeed still away for the holidays as far as I can tell. Please be patient with the developers.

**Comment by markheloking** [comment] 2015-01-05 16:52
@andyblac do you have any idea whether you run the master or dev branch?

**Comment by fernandog** [comment] 2015-01-06 11:09
@cardgone 
From FAQ

Error while searching ..., skipping: 'NoneType' object is not iterable'''

**Close Sickbeard, then delete cache.db in your SickBeard directory. This may solve the problem.**

If you still have the same issues, search the repository for the error message (without the specific provider name) and if there's an open issue, copy your log (at Debug level). If no such issue exists, open a new one.

https://github.com/SiCKRAGETV/SickRage/wiki/Frequently-Asked-Questions

**Comment by markheloking** [comment] 2015-01-06 11:11
@fernandog good find!

**Comment by fernandog** [comment] 2015-01-06 11:17
@markheloking we must keep updating this FAQ and tell users to read it.
I can't edit it. Can you?

**Comment by markheloking** [comment] 2015-01-06 12:23
@fernandog no. We're in the same group in terms of acces rights. the problem is that the wiki falls under SiCKRAGETV/SickRage and not sickrage-issues. We don't have write acces in SiCKRAGETV/SickRage.

**Comment by michaelburton** [comment] 2015-01-10 18:32
I can confirm the same issue, both the TypeError (with the same traceback) when visiting General Config and the inability for SickRage to restart itself after shutting down.

Branch: master, commit 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
OS: FreeBSD 9.3 (in a fresh jail)
Python: 2.7.9
Log: The only error is identical to those already posted
Config: Completely new installation, data dir was empty before starting SickRage so it has nothing to do with cache.db

**Comment by sacii** [comment] 2015-01-10 21:34
Fresh install

```
SR Version:		BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
SR Arguments:	['--datadir=/usr/home/sacii/.config/sickrage-torrents', '--daemon', '--pidfile=/usr/home/sacii/.config/sickrage-torrents/sickrage-torrents.pid']
Python Version:	2.7.9 (default, Dec 23 2014, 11:29:06) [GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)]
OS:				Nas4free 9.2.0.1 (FreeBSD 9.2-RELEASE-p4) x64-embedded
```

When adding the '--daemon' and '--pidfile' options I get the TypeError with the same Traceback but somewhat different Request Info when visiting General Config:

```
Error

'NoneType' object is not iterable

Traceback

Traceback (most recent call last): 
File "/usr/local/share/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/share/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/share/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/share/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/share/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/share/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/share/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/share/sickrage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/local/share/sickrage/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/usr/home/sacii/.config/sickrage-torrents/cache/cheetah/_usr_local_share_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1420922368.18
headers: {'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Host': 'nas4free.lan:65069', 'Referer': 'http://nas4free.lan:65069/comingEpisodes/', 'Cookie': 'user="2|1:0|10:1420484646|4:user|44:MTkzNDI4ZTBlZTc4YjlkYjdlMDUwYjAwM2VlZmM2NDc=|32bd2813d65db37a154b52e640e38cba4d93744e11cb9a7618e3afa0aca1b64d"; PHPSESSID=d73b08b8d162bf8ef6b9ef3a33845b59'}
host: nas4free.lan:65069
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/general/
_cookies: Set-Cookie: PHPSESSID=d73b08b8d162bf8ef6b9ef3a33845b59 Set-Cookie: user="2|1:0|10:1420484646|4:user|44:MTkzNDI4ZTBlZTc4YjlkYjdlMDUwYjAwM2VlZmM2NDc=|32bd2813d65db37a154b52e640e38cba4d93744e11cb9a7618e3afa0aca1b64d"
method: GET
remote_ip: 192.168.1.103
```

Restart still fails with a timeout.

If I start SickRage with only the '--datadir' option, restart fails and generates the following in the console log:

```
Exception in thread EVENT-QUEUE:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/share/sickrage/sickbeard/event_queue.py", line 31, in run
    self.callback(type)
  File "./SickBeard.py", line 482, in shutdown
    install_type = sickbeard.versionCheckScheduler.action.install_type
AttributeError: CheckVersion instance has no attribute 'install_type'
```

**Comment by RobMadrid** [comment] 2015-01-11 19:15
Hi, I have the same problem - clicking on anything that takes me to. MyIP:MyPort/config/general
SR Version:	BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]

It's a completely fresh install on Ubuntu 14.04 32bit
Connecting via Chrome on Windows 7
Exactly the same error, but a few extra bits of data in the Request  Info. - Please let me know if you need any further information.

**Comment by brando56894** [comment] 2015-01-12 17:00
Same issue on FreeBSD, deleting cache.db doesn't help.

**Comment by fernandog** [comment] 2015-01-12 19:24
@brando56894 

stop your SR, edit config.ini and make sure version_notify = 1
start SR and try again please

please post you config.ini settings:
```
[General]
git_autoissues = 
git_reset = 
branch = 
git_remote = 
git_remote_url = 
cur_commit_hash = 
cur_commit_branch = 
git_path = ""
```

**Comment by RobMadrid** [comment] 2015-01-13 06:52
Version notify was already at 1.

[General]
git_autoissues = 0
git_reset = 0
branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
cur_commit_branch = ""
git_path = ""

**Comment by otto2k** [comment] 2015-01-15 12:09
Got the same issue on a Popcorn Hour A410 with Python 2.7.9.

**Comment by RobMadrid** [comment] 2015-01-18 06:34
Just pulled last commit
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Can now connect to General Tab. This issue is resolved for me. Thanks

**Comment by markheloking** [comment] 2015-01-18 12:36
On BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)  here, everything is working as it should. Are you on the same commit right now @RobMadrid?

**Comment by RobMadrid** [comment] 2015-01-19 07:38
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)  now seems to be consistently working. Thanks @markheloking

**Comment by markheloking** [comment] 2015-01-19 09:21
Closing as it seems to be fixed. Please do report back if the issue persists.

**Comment by fernandog** [comment] 2015-01-19 09:27
I had this error yesterday and I seems it's a timeout issue connection to GIT to retrieve info (list branch and etc) using HTTPS. I tried to SSH and "git pull" and after a long while I got a timeout

As I haven't change anything in my setup I tried restart my RPI and still nothing.
I got pissed and restart all my hardware (internet modem, wireless and etc). Issue fixed

**Comment by RobMadrid** [comment] 2015-01-19 09:32
I had a power failure which reset my router hadn't put the 2 together as server restart had not addressed it - @fernandog may have found the root cause.

**Comment by fernandog** [comment] 2015-01-19 10:29
To fix this in SR side we must add a check here for empty result

https://github.com/SiCKRAGETV/SickRage/blob/0abbdf3d44e65c06aa4672e63db1fe35983454ad/sickbeard/versionChecker.py#L759

```
    def list_remote_branches(self):
        gh = github.GitHub(self.github_repo_user, self.github_repo, self.branch)
        return [x['name'] for x in gh.branches() if x and 'name' in x]
```

**Comment by michaelburton** [comment] 2015-01-19 19:22
I was still having the issue after updating, so I decided to do a bit of debugging myself.

It seems that `CheckVersion.list_remote_branches` (from versionChecker,py) was returning None because `updater` hadn't been set, and `updater` wasn't set in the `CheckVersion` constructor because `sickbeard.gh` was None. Tracing back to when `gh` should have been created, it turns out that I was getting an SSL certificate verification error when connecting to Github. I updated the security/ca_root_nss port making sure that the ETCSIMLINK option was enabled and everything now works as expected.

Figuring this out would have been much easier if the exception handler in sickbeard/__init__.py line 565 made a log entry instead of silently failing.

**Comment by fernandog** [comment] 2015-01-19 19:50
@michaelburton the fix was not merged yet. Did you change manually the file?

**Comment by michaelburton** [comment] 2015-01-20 15:52
No, I just fixed my underlying configuration problem (out-of-date SSL certificates in my FreeBSD jail) which raised an SSLError when SR tried to connect to Github during startup (sickbeard/\_\_init\_\_.py, line 565).

Patching the config_general template will allow the page to load even when SR can't connect to Github. You'll also need to edit either SickRage.py or sickbeard/versionChecker.py so that SR can restart itself.

In `CheckVersion.\_\_init\_\_` (sickbeard/versionChecker.py, line 41), the `install_type` attribute is only assigned if `sickbeard.gh` has been set, and it won't be if SR couldn't connect to Github. The restart code (SickBeard.py, line 482) tries to access `install_type` to determine which update command to run, which raises an `AttributeError` and prevents SR from restarting.

As I said before, an exception while connecting to Github should definitely be logged whereas it's currently silently ignored.

**Comment by fernandog** [comment] 2015-01-20 15:55
@michaelburton do you know how to fix it? can you do a PR?

**Comment by michaelburton** [comment] 2015-01-20 19:13
I'd rather not have to fork the repo just to add one line of code, it should be enough to add `install_type = None` at the top of `CheckVersion.__init__`.

If you want to add Github connection error logging as well, [this patch should do the job](http://pastebin.com/7Q2LFRBZ).

**Comment by fernandog** [comment] 2015-01-20 19:26
@michaelburton like this?

**Comment by michaelburton** [comment] 2015-01-20 19:52
Sorry, that should've been `self.install_type = None`. My Python is somewhat rusty.

**Comment by fernandog** [comment] 2015-01-20 20:43
@michaelburton how to reproduce the error and test the fix?

**Comment by michaelburton** [comment] 2015-01-20 21:04
1. Prevent your machine from connecting to github.com (add it to /etc/hosts, pull the network cable, etc.)
2. Start Sickrage
3. Try restarting from the web UI, it will stop but not restart itself

**Comment by sacii** [comment] 2015-01-27 19:00
@michaelburton

Thank you for pointing out the symlink option in the security/ca_root_nss  port (it should be a default). I checked that option and rebuilt devel/git (which rebuilt security/ca_root_nss among other ports). After fixing the ports, a fresh git clone of sickrage fixed all my problems with the General Configuration page. Very good catch on your part.

**Comment by sacii** [comment] 2015-01-29 21:38
@michaelburton

Additional notes:

The security/ca_root_nss port creates two symlinks, one under /etc/ssl and the other under /usr/local/etc/ssl (openssl standard). However, python, since 2.7.9, does not find the symlink under /usr/local/etc/ssl. Additionally, the symlink under /etc/ssl does not survive reboots on embedded systems (which I use). Therefore, I have to reestablish the symlink under /etc/ssl after a reboot in order for sickrage to work correctly. It is a python bug, not a sickrage bug.

**Comment by fernandog** [comment] 2015-01-29 23:37
@cardgone @RobMadrid @andyblac 
 please update SR and report back please. Fix was merged

**Comment by michaelburton** [comment] 2015-01-30 01:35
@sacii You might be able to recreate the symlink with a cron `@reboot` command.

**Comment by andyblac** [comment] 2015-01-30 02:14
yup, confirmed fixed. thanks.

**Closed** 2015-01-30 08:16 UTC
Labels: 1: Bug / issue, 2: High Priority, 3: Confirmed, 3: Fix, 4: Need feedback, branch: master

**Comment by sacii** [comment] 2015-01-31 03:28
@michaelburton

I opted to recreate the symlink at the beginning of my sickrage startup script.
