### ISSUE TITLE
Unrar executable not found; is installed and working

### ISSUE THREAD

**Issue by yochaigal** [SiCKRAGETV/sickrage-issues#2917] opened 2015-09-22 21:43 UTC
SickRage version:
BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) 
Running Arch Linux 64bit. Python 3.4.3.

Logs show "Rar Not Supported:" and Unpack checkmark says "Unrar Executable not found."
Logs: https://gist.github.com/yochaigal/b7cce99176f5141bc30b

I've got unrar installed from Arch repos (/usr/bin), works just fine. I've symlinked to /usr/local/bin, problem persists. 

Thanks

**Comment by miigotu** [comment] 2015-09-22 22:54
you likely have the open source free version of unrar. SR requires unrar-nonfree (the one from the official unrar website)

**Comment by yochaigal** [comment] 2015-09-22 23:41
I have the unrar from [Extra], which is non-free:
Name           : unrar
Version        : 1:5.3.4-1
Description    : The RAR uncompression program
Architecture   : x86_64
URL            : http://www.rarlab.com/rar_add.htm
Licenses       : custom
Groups         : None
Provides       : None
Depends On     : gcc-libs
Optional Deps  : None
Required By    : None
Optional For   : evince  file-roller  sickrage-git
Conflicts With : None
Replaces       : None
Installed Size : 299.00 KiB
Packager       : Giovanni Scafora <giovanni@archlinux.org>
Build Date     : Wed 16 Sep 2015 12:12:08 AM EDT
Install Date   : Tue 22 Sep 2015 07:39:39 PM EDT
Install Reason : Explicitly installed
Install Script : No
Validated By   : SHA256 Sum

**Comment by yochaigal** [comment] 2015-09-22 23:47
When I download the rar executable from http://www.rarlab.com/rar/rarlinux-x64-5.3.b4.tar.gz, and place it in /usr/bin and /usr/local/bin, the problem persists. I don't think this is a FOSS vs closed-source issue.

**Comment by miigotu** [comment] 2015-09-23 00:41
restarted after? not at a PC right now to help

**Comment by yochaigal** [comment] 2015-09-23 00:43
Yes, I restarted the service every attempt.
Besides I've restarted both the service and the computer itself many times.

**Comment by miigotu** [comment] 2015-09-23 02:49
yes, I was referring to the PC, not SR, so thanks for clarifying you did restart the computer.

Make sure you have gcc-libs
`pacman -S gcc-libs`

You should completely __purge rar__ and unrar, and remove any links you manually had, then install this:
http://www.rarlabs.com/rar/rarlinux-x64-5.3.b4.tar.gz

Also, in a terminal, just type `unrar | head -n2` and show me the output.

**Comment by yochaigal** [comment] 2015-09-23 11:15
I have gcc-libs-multilib; I cannot remove it and replace it because half of
my software would stop working (it relies on multilib). That said, I don't
think it makes a difference.
I have already completely purged rar (and made sure there are no leftovers)
and manually installed that exact version of unrar.
I really don't think it is the version of unrar I'm using that is the
problem.
Output of unrar | head -n2:
UNRAR 5.30 beta 4 freeware      Copyright (c) 1993-2015 Alexander Roshal


Again, I understand the difference in unrar versions. I have the correct
one.

**Comment by miigotu** [comment] 2015-09-23 11:43
Hey, no worries, I just have to cover all bases and make sure I explicitly make every distinction and not miss any common mistakes.

The code that handles unrar is a library, and has not changed in ages. Every issue we have had to work through with anyone in the past was solved by removing and reinstalling unrar, after making sure it was the free version, and making sure they reboot and had it in the path.

I can look at the library and see if there is an update we need to do, and maybe double check the code there. It is possible a bug exists in the library that has no been previously exposed.

**Comment by miigotu** [comment] 2015-09-23 11:43
non-free*

**Comment by yochaigal** [comment] 2015-09-23 11:51
Unpacking worked on the last release; I updated from within SR and only
noticed the issue after that.

**Comment by yochaigal** [comment] 2015-09-25 13:20
Latest git release has the same issue.

BRANCH: (master) / COMMIT: (070e1ba55b74f2d5cbf41602c690cdf55fb0576c)

**Comment by ajdunevent** [comment] 2015-09-27 22:30
I have essentially the same set-up,
Arch Linux x86_64
python: v3.4.3
python2: v2.7.10
unrar: 5.30 beta 4 freeware [non-free version from EXTRA installed to /usr/bin/]
BRANCH: (master)
COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da),
and am experiencing the same issue.
It seems to have coincided with thousands of error messages similar to "time data '2003-06-30 01:59' does not match format '%d-%m-%y %H:%M'" but I don't pay that much attention to the error logs until I need to so they could be entirely unrelated.

**Comment by WebSpider** [comment] 2015-09-28 20:24
This seems to be a duplicate of #2613

**Comment by yochaigal** [comment] 2015-09-28 20:26
I'm not sure about that - while I do have the same error in my logs, the "fix" listed there does not work for me (e.g. falling back to an older version of unrar). Maybe I'll take another look.

**Closed** 2015-09-28 20:55 UTC
Labels: 1: Support / question
