### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by roger83** [SiCKRAGETV/sickrage-issues#892] opened 2015-03-09 04:38 UTC
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) 
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
Link to Log: https://gist.github.com/f8ef8f20a0085a1963d6
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2176, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 228, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 459, in process_media
    result.result = processor.process()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 809, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 562, in _find_info
    (cur_show, cur_season, cur_episodes, cur_quality, cur_version) = cur_attempt()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 546, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 496, in _analyze_name
    parse_result = np.parse(name)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/name_parser/parser.py", line 417, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/name_parser/parser.py", line 195, in _parse_string
    show = helpers.get_show(bestResult.series_name, self.tryIndexers, self.trySceneExceptions)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 949, in get_show
    logger.log(u"Error when attempting to find show: " + name + " in SickRage: " + str(e), logger.DEBUG)
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by roger83** [comment] 2015-03-09 04:50
Sick rage does not seem to auto process anymore. When I auto process I get this error.

**Comment by TagForce** [comment] 2015-03-09 11:05
seems related to https://github.com/SiCKRAGETV/sickrage-issues/issues/870

**Comment by jeanpaulrh** [comment] 2015-03-09 11:32
It seems to be related to an '-' in the file name. I had this issue with an ubuntu iso torrent.

**Comment by fernandog** [comment] 2015-03-09 18:33
@TagForce maybe we need str(name) ?

**Comment by fernandog** [comment] 2015-03-09 21:38
@roger83 update master and report back if this was fixed

**Comment by roger83** [comment] 2015-03-11 03:49
This seems to be working.

**Comment by TagForce** [comment] 2015-03-11 08:25
Still weird that it should try to look for a show without a name.

**Comment by fernandog** [comment] 2015-03-11 16:08
@TagForce isn't show.name instead of just name?

show = helpers.get_show(bestResult.series_name, self.tryIndexers, self.trySceneExceptions)

**Comment by TagForce** [comment] 2015-03-11 16:11
bestResult.series_name = name inside get_show.
```def get_show(name, tryIndexers=False, trySceneExceptions=False):```

**Comment by fernandog** [comment] 2015-03-11 16:14
@TagForce that fix as a "band aid" for another problem or not? I'm concerned

**Comment by TagForce** [comment] 2015-03-11 17:01
I don't know what the cause for this is.

**Comment by abeloin** [comment] 2015-03-12 03:39
@TagForce Notice this line in the log:
`Thread-38 :: Processing /share/CACHEDEV1_DATA/Download/sabnzbd/complete/tv/Black.Sails.S02E04.720p.WEB-DL.DD5.1.H.264-BS-NZBgeek/.@__thumb/s100nZ6xJmWUdpeOMYAFPZcWVeWh8R4ZAToHtR7.mkv (None)`
Look at the file name it is starting with S100, it will match the 'season only' regex.
See this test results from the regex: https://regex101.com/r/wP1nD6/1
This will results in a positive match with an `None` name.

_analyze_name in sickbeard/postProcessor.py specify that it can return None on show see this (link)[https://github.com/SiCKRAGETV/SickRage/blob/a23364f6e0e074c9f5b31421bf2a6a7e54cb584c/sickbeard/postProcessor.py#L481]

getshow() in sickbeard/helpers.py was able to handle a None before (this commit)[https://github.com/SiCKRAGETV/SickRage/commit/de5db9be64fd125f0ea61f9a30ccc7284702255b#diff-b5b8a08b64bbb0d1fd57beeeb56221bdR1090]

So the only reason it's failing is because the logger line was added which trip in case it's `None`.

This is why I added the check to return `None` because it will return a `None` anyway so there is no need to do all these checks

**Comment by TagForce** [comment] 2015-03-12 08:55
@abeloin The issue with the S100 files is fixed by making sure it skips hidden folders (specifically created the fix for this QNAP issue where the QNAP adds thumbnails using an extension that belongs to a video file), so it shouldn't happen too often.

But yeah, if it can be called using None as a name, then it should be able to handle None as a name, so returning None if name = None is a proper fix. I'll consider this matter solved, then. :)

**Comment by abeloin** [comment] 2015-03-12 17:14
@roger83 Can you update sickrage, a fix has been pushed.

**Comment by fernandog** [comment] 2015-03-13 13:10
@roger83 please reply!

**Comment by roger83** [comment] 2015-03-13 16:33
I updated on 3/9 and everything worked well since then! Also updated yesterday, and things still work as well.

**Closed** 2015-03-13 16:36 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, branch: develop
