### ISSUE TITLE
Too many requests per minute

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1202] opened 2015-04-12 16:42 UTC
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-254243 :: Rarbg Too many requests per minute.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbnoimi** [comment] 2015-04-12 16:45
NOTE: I'm using TOR through privoxy because many torrent websites are forbidden in my country.

**Comment by mbnoimi** [comment] 2015-04-12 16:48
[Here](http://hastebin.com/yepujotalo.xml) you can find full debug log.

**Comment by Thraxis** [comment] 2015-04-13 06:52
Duplicate of issue https://github.com/SiCKRAGETV/sickrage-issues/issues/1159

**Closed by Thraxis** 2015-04-13 06:52 UTC
Labels: 5: Duplicate

**Comment by mbnoimi** [comment] 2015-04-13 08:01
> Duplicate of issue #1159

Hold on.
Read [debug's log](http://hastebin.com/yepujotalo.xml) please. You'll see that error isn't the same as #1159

**Comment by Thraxis** [comment] 2015-04-13 14:24
If the error in the debug log is NOT for "Rarbg Too many requests per minute." then you need to either fix this bug report to reflect that or submit a bug report for the issue you say is in the debug log.

**Comment by fernandog** [comment] 2015-04-13 14:27
https://github.com/SiCKRAGETV/sickrage-issues/issues/1131

**Comment by fernandog** [comment] 2015-04-13 14:28
@mbnoimi please update. was fixed in last night update. You are using an old versions of SR

**Comment by mbnoimi** [comment] 2015-04-13 20:58
@fernandog Works perfectly now

Thank you guys.
