### ISSUE TITLE
default folder not used when adding new shows

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#606] opened 2015-02-15 14:16 UTC
i have 3 tv libraries which are separate folders for sickrage. the default library should be the third one in the list. i’ve marked the third one as default and it is flagged with an asterisk in the list.
when i directly add a show from the "search show" page sickrage chooses the first directory an not the default one. same when i go through the individual pages. its always the first directory that is selected instead of the default one

branch develop
commit c62d8f2c799edd7daad5648f45276a3464d83a9e

**Comment by fernandog** [comment] 2015-02-15 16:11
@abeloin.

this is the cause.
Do you know a better way to fix this and the original issue?

https://github.com/SiCKRAGETV/SickRage/issues/1178

https://github.com/SiCKRAGETV/sickrage-issues/issues/286

**Comment by abeloin** [comment] 2015-02-15 16:26
@udochrist Try the following pull request: https://github.com/SiCKRAGETV/SickRage/pull/1318 . It will fix your issue.

**Comment by abeloin** [comment] 2015-02-15 16:39
@fernandog The root cause of issue #286 is the jquery update which broke a lot of code and PR1178 wasn't a fix as it simply hard coded the value. #286 was resolved by PR1192.

The code to select the default path is in rootDirs.js

**Comment by fernandog** [comment] 2015-02-15 17:09
@abeloin ok. thanks!

**Comment by fernandog** [comment] 2015-02-16 00:14
@udochrist  develop updated. please test and report back

**Comment by udochrist** [comment] 2015-02-16 06:13
Checked and confirmed working. Thx for the superfast fix.

**Closed** 2015-02-16 09:48 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, branch: develop
