### ISSUE TITLE
[Feature Request] Add bitmetv/bB/tTN torrent providers

### ISSUE THREAD

**Issue by fferraro87** [SiCKRAGETV/sickrage-issues#533] opened 2015-02-02 09:31 UTC
can you add new torrent search providers(bitmetv,bB,tTN etc etc) and delete old and not working (like tvtorrents)?
thanks anyway

**Comment by daveyboy37** [comment] 2015-03-01 10:55
Agree with this totally :-)

**Comment by jtwill** [comment] 2015-07-22 15:29
Note that SickGear recently added TTN (transmithe.net), so hopefully the SG code can be used to jumpstart a SickRage implementation for tTN.

https://github.com/SickGear/SickGear/blob/develop/sickbeard/providers/transmithe_net.py

**Comment by daveyboy37** [comment] 2015-09-08 23:27
Thanks for the info jtwill... Lets hope that's the case. 
PS neotomic. I still have the tTN invite if it helps....Same for TVChaos.

**Comment by flightlevel** [comment] 2015-09-09 00:01
bitmetv have an RSS which works with SickRage, but the site is so dead that I wouldn't worry about it. Good example where being excessive with the ratio kills a site. So hard to upload anything, so you can't download.

**Comment by daveyboy37** [comment] 2015-09-09 22:12
Hence the need for Ratio free trackers...AnyWho!! 
The preference here seems to be for crap public trackers, or movie trackers that have the odd TV Show. Ask for a dedicated TV tracker and you are f*****. 
TtN for example... The site owner contacted SickRage and SickGear in June due to the number of requests he got... Anyone with a TtN account can verify this.
SickGear up and running 2 days later... SickRage.... Still waiting.. Despite the requests here also. 
24 hours ago I didn't even know SickGear existed. 
Result = Im outta here... If i wanna see a S**t load of movie trackers I will load up Couch.

**Comment by flightlevel** [comment] 2015-09-10 02:13
@daveyboy37 Happy to have a go at it if you have an invite
Never heard of tTN to be honest until now. I find Freshon works great, so have never gone looking.

**Comment by daveyboy37** [comment] 2015-09-10 10:20
@flightlevel .

Appreciated but I have already migrated to SickGear.... and Yeah I love Freshon too.

**Comment by daveyboy37** [comment] 2015-09-12 20:14
@flightlevel 

Hey mate. Is the offer still open to have a look at TtN... I'm having one issue after another with SickGear so Im gonna migrate back on my days off. I would rather have reliable results than additional providers. No worries if you cant spare the time, but if you get chance get back to me with an addy for me to send an invite.

**Comment by flightlevel** [comment] 2015-09-14 05:55
@daveyboy37 
Yep, will have a go, should be in the next week.
email is here https://gist.github.com/flightlevel/a939d64717c0deb0424b

**Comment by daveyboy37** [comment] 2015-09-15 06:55
@flightlevel 
Oh man... I was sure i had some invites left but it seems not. 
Oddly enough rss feeds picked up 3 torrents over the last couple of days (although with no backlog search). Anyway its gonna have to go on the backburner until i get some more invites. 

There was one other tracker that i was even more desperate to get running that definitely doesn't even pick up on rss. 
tvchaosuk.com It has the most complete listing of UK shows I have ever seen from the 60's to present day. 
 Amazingly Its available apparently in Sonarr via Jacket already. I was kind of tempted to have a look at Sonarr but after all the hassle with SickGear I think i'm gonna pass :-)
Anyway i don't know if you fancy a shot at it...I definitely do have one invite and i'm offering a $50 bounty if i can get it running on SickRage. If you want to give it a go the invite has to be activated in 24 or 48 hours I think (or it's lost).... but there's no hurry beyond that.

**Comment by miigotu** [comment] 2015-09-15 07:20
@daveyboy37 I'll add it for a bounty lol. send the invite to miigotu@gmail

**Comment by daveyboy37** [comment] 2015-09-15 07:24
@miigotu Just to clarify the bounty is if it can be confirmed fully working. 
Confirm thats ok and I will send the invite now.

**Comment by miigotu** [comment] 2015-09-15 07:45
sure. won't be too difficult. its the foreign language ones that are annoying to add.

**Comment by daveyboy37** [comment] 2015-09-15 07:46
@miigotu 
Haha yes indeed. This will be the best $50 I spent in a long time. :-)

**Comment by daveyboy37** [comment] 2015-09-16 07:59
@flightlevel 
I just donated a small amount to TtN so i now have a couple of invites if you are still willing to have a look. However the link to your email is now giving a 404 error?

**Comment by flightlevel** [comment] 2015-09-16 08:26
@daveyboy37 
https://gist.github.com/flightlevel/07677dfca72acab410ff

**Comment by daveyboy37** [comment] 2015-09-16 08:51
@flightlevel 
Done!!

**Comment by miigotu** [comment] 2015-09-16 15:45
should have the tvchaos one done today or tomorrow, as long as my internet comes back up. stupid maintenance.

**Comment by daveyboy37** [comment] 2015-09-16 15:49
@miigotu 
Awesome news.:-)

**Comment by flightlevel** [comment] 2015-09-17 07:31
TTN now in develop branch https://github.com/SiCKRAGETV/SickRage/pull/2517
They need an API

**Comment by daveyboy37** [comment] 2015-09-17 08:24
@flightlevel 
Hey thanks flightlevel. I have always tended to use the master branch. 
I have git installed (running on Windows). How would i try the develop branch? 
I kinda thought it was via admin Command Prompt
cd C:\SickRage 
git checkout develop
doing that i get a message about
sickbeard/__init__.py being overwritten and i need to stash or commit before switching? 

Also i know little about how the providers work. What's the significance in the tracker having an api?
Will it not work without it? Work but in a limited way? 
Sorry for the newbie questions. :-(

**Comment by miigotu** [comment] 2015-09-17 10:06
seems you have local modifications then, because that's exactly how you switch.

what's the output of `git diff`

**Comment by daveyboy37** [comment] 2015-09-17 11:20
@miigotu
Yeah I screwed something up but i'm sorted now and running on develop. Thanks for the tip!! :-)
Will have a look at TtN shortly when i get back home. 
Going back to the api thing that Flightlevel mentioned whats the significance of the tracker not having an api?

**Comment by miigotu** [comment] 2015-09-17 11:43
@daveyboy37 https://github.com/SiCKRAGETV/SickRage/pull/2519

I haven't tested it very extensively yet, but I will merge it so you can. I at least got it to search for and snatch an episode of "Antiques Road Trip".

**Comment by flightlevel** [comment] 2015-09-17 13:05
@miigotu 
An API just spits results back in plain text, nicely formatted. Much easier to program against. Whereas a webpage looks all nice with pictures but is harder to extract the correct information.
No real disadvantage now that its done, along as they don't change the design of the site.
I would recommend though going into your TTN profile and increasing the torrents per page to 100 just in case a search produces more than 20 results.

**Comment by daveyboy37** [comment] 2015-09-17 13:15
@flightlevel 
Thanks for the info, I have altered the setting as suggested. :-)

**Comment by daveyboy37** [comment] 2015-09-17 14:22
@flightlevel 
You got Paypal? Since I offered some bucks to miigotu for TVChaos it only seems right that I send you a few beers too :-)
I really appreciate both your efforts.

**Comment by flightlevel** [comment] 2015-09-18 01:29
Thanks @daveyboy37 can you send it to @miigotu
He puts more effort into SR, than most do their full time job!
I'm just learning a bit of Python, so it was a good test for me.
Let us know how it works, I did give a test run, but there is nothing like the real thing

**Comment by daveyboy37** [comment] 2015-09-18 08:07
@flightlevel 
Yeah everyone involved and especially @miigotu is doing a great job. Really looking forward to the "archive with quality" to be fully working. That in particular was a feature that I really hoped to see. I really like being able to see the quality even when archived.
I had a "discussion" last night where it was suggested that SickGear is way more stable. It wasnt my experience at all. But apparently I need only compare the issue/bug/feature request count of both to "know" I should be using SickGear.  From what I see in issue and bugs there are a huge number of dupe issues and a high number that are simply provider requests. .

Anways thanks for the work on TtN. I have had a few snatches so its looking good. Season Packs I'm not too worried about from TtN but I will monitor it when any packs get snatched. 
If you ever want any more Python practice TorrentShack is another tracker that has been requested and gets a +1 from me. I got invited the other day and have it set in Couch Potato and was seeing blistering speeds. I just have a liking for ratio-less trackers at the moment.(well ones that I have a hope in hell of getting invited to) :-)
Sadly I'm gonna have to wait to gain an invite to give for (Tsh)

**Comment by miigotu** [comment] 2015-09-18 08:30
SickGear has less issue/bug/fr because noone uses it really xD. No users means noone to care to test or report/request. They have less than 1% market share, SB 4.4%.... SR > 50% (this includes headphones, couchpotato, sonarr/nzbdrone)

**Comment by daveyboy37** [comment] 2015-09-18 09:14
@miigotu 
Yep you're preaching to the converted :-)
Things i missed when I tried SickGear in a VM the other week. 
1.News Section.
2.No sign of Archive by quality being implemented. (any eta on this being up and running btw?)
3 No contrast in color for Show Lists in simple view. 

SickRage, couchpotato and Plex changed my whole torrenting habits for the better. 

:-)

**Comment by miigotu** [comment] 2015-09-18 09:18
compound archiving status is still missing a few small tweaks. webapi and webserve are blocking switching to them atm, but I dont want to touch the code there as it is being refactored atm. Shouldnt be too long, once I get something started its usually never more than a few weeks at most.

**Comment by daveyboy37** [comment] 2015-09-18 09:25
@miigotu 
Awesome stuff.

**Comment by neoatomic** [comment] 2015-09-18 14:32
As the provider was added i'm going to close this. (but you can still continue to post/discuss)

**Comment by daveyboy37** [comment] 2015-09-21 15:08
Can i bump this for BitMeTV that was also mentioned in the initial post ?
I have the required invite if anyone wants to give it a shot anytime.

**Comment by miigotu** [comment] 2015-09-21 15:19
@daveyboy37 save it for me =P I rather write them the first time than to have to go back and figure out what went wrong later.

**Comment by daveyboy37** [comment] 2015-09-21 15:21
@miigotu 

No problem :-)

**Comment by OmgImAlexis** [comment] 2015-09-26 14:04
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Closed by OmgImAlexis** 2015-09-26 14:04 UTC
Labels: 1: Feature request

**Comment by crimsdings** [comment] 2015-10-26 15:19
since there is no search on feathub (what the hell) http://feathub.com/SiCKRAGETV/SickRage/+235

**Comment by miigotu** [comment] 2015-10-26 18:10
Without an account I can't add it.

**Comment by daveyboy37** [comment] 2015-10-27 14:10
@miigotu 

I still have an invite. Let me know if you need it and I will send to the same email addy as I did the TVChaos unless you say different. :-)

**Comment by miigotu** [comment] 2015-10-27 14:26
@daveyboy37 sure, send it

**Comment by daveyboy37** [comment] 2015-10-27 14:45
@miigotu 
Crap looks like a season pack snatch just dipped my ratio below what's needed to send invites. :-(
Will check back here in a few days when I get it back up to the requirement and see if you still need it.

**Comment by miigotu** [comment] 2015-10-27 14:51
lol ok. You dont need ipt btw do you?

**Comment by daveyboy37** [comment] 2015-10-27 15:06
No mate. 
I have it but seldom need to use it. 
Its well blocked here in the UK beyond using hxxp://94.23.149.123/t? to login. 
Using the proxy was intermittent too. No problem tho as I tend to dislike trackers with rars. 
MoreThan is snatching pretty much every episode for me nowadays with TL and HDT as backups for packs. 
I'm trying to earn an invite to send on TV-Vault.. its a TVChaos type site with plenty of old stuff but with a less chaotic interface. 
Rest assured when I earn an invite to hand out I will be pestering you again my friend. :-)

**Comment by miigotu** [comment] 2015-10-28 01:00
Providers are so simple. I can add a million of them if I have axx...

**Comment by daveyboy37** [comment] 2015-11-08 08:08
Hey miigotu.
Managed to get a TV-Vault invite at last so i sent it ya .:-)
Needs to be picked up within 3 days it seems. 

Thanks again my friend :-)

Also was just wondering... as Im pretty heavily into documentaries as well is there any issue with adding ScienceHD when i manage to get an invite to send?

**Comment by miigotu** [comment] 2015-11-08 08:33
"its a TVChaos type site with plenty of old stuff but with a less chaotic interface. "

Lol, worse for parsing! xD

Sure I can try.

**Comment by daveyboy37** [comment] 2015-11-08 15:55
Haha..
Yeah i was meaning merely the content is similar to TVCuk.
The tracker itself uses more mainstream naming so hopefully parsing shouldn't be a major PITA :-)
