### ISSUE TITLE
Episode status unchanged after downloading them in a better quality, SR keeps downloading them.

### ISSUE THREAD

**Issue by liquex** [SiCKRAGETV/sickrage-issues#2841] opened 2015-09-17 16:47 UTC
My SickRage doesn't change the episode status after donwloading them in a better quality. For most shows I have the following quality settings:
* Initial: 720p HDTV, 720p WEB-DL, 720p BluRay
* Replace with: 720p WEB-DL, 720p BluRay
* Archive First Match enabled.

So for example if there are some episodes downloaded in 720p HDTV quality and SickRage then snatches and downloads the same episodes as 720p BluRay releases. The files are downloaded and postprocessed correctly, even the quality in the filename is changed to 720p BluRay. But in SickRage the episode status remains on "Snatched (Best) 720p BluRay", so they are downloaded over and over again, which causes a lot of traffic. Sometimes the status isn't even changed to snatched inbetween, it just remains on "Downloaded HDTV", but better releases are still downloaded.

I use the SickRage internal postprocessor (Scan and Process), not sabToSickbeard.

* Branch: master
* Commit: 7694b70047796dc0c9c812300a090f78a4240f46
* OS: Debian wheezy
* Python: 2.7.3
* Downloaders: SABnzbd only, no torrents etc.

Naturally I tried the usual simple stuff like restarting and updating SR. Any ideas?
Cheers!

**Comment by bobbysteel** [comment] 2015-09-17 20:06
This is happening to me too but I haven't been able to diagnose in the logs yet why it's occurring.

**Comment by OmgImAlexis** [comment] 2015-09-18 05:49
The 1080p copy was added twice to uTorrent.

![screen shot 2015-09-18 at 3 17 40 pm](https://cloud.githubusercontent.com/assets/6525926/9952741/789a37ee-5e18-11e5-8c95-1ac72adb032e.png)

**Comment by bobbysteel** [comment] 2015-09-18 14:19
In my case (not sure it's the same) it seems to not be recognizing the 720p Bluray properly. The relevant log line that seems to recur

2015-09-18 06:46:46 DEBUG    SHOWQUEUE-REFRESH :: Since this file has been renamed, I checked /mnt/Resources/TV/Better Call Saul/Season.01/Better.Call.Saul.S01E08.RICO.720p BluRay.mkv and found quality 720p HDTV

Hence it keeps looking for a Bluray version and keeps sending the NZB over and over again.

**Comment by fernandog** [comment] 2015-09-18 14:22
Problably the space between 720p and Bluray

**Comment by liquex** [comment] 2015-09-18 14:29
Was there a change in how SR parses names? It worked fine in the past, I only noticed this issue in the last couple of weeks.

The strange thing is... Why does it even rely on the name? It already "knows" that a 720p BluRay release was snatched and downloaded / processed, because it did all that. I get that it has to check if the file was moved and renamed in order to change the status, but it would be weird relying on the file name to change the status if the whole process (snatching, downloading, processing) was handled internally.

**Comment by fernandog** [comment] 2015-09-19 02:51
@miigotu the space "S01E08.RICO.720p BluRay.mkv" here can cause this issue?

**Comment by miigotu** [comment] 2015-09-19 03:10
Missing codec, the file WAS renamed.

**Comment by fernandog** [comment] 2015-09-19 03:14
@liquex did you renamed the file using another script outside SR or even manually? Seems it wasn't renamed by SR

**Comment by liquex** [comment] 2015-09-19 07:29
@fernandog I used sabToSickbeard in the past, but switched to the SR internal postprocessor.

**Comment by OmgImAlexis** [comment] 2015-09-19 07:33
@miigotu mine added the 1080p twice to uTorrent, is this a separate issue?

**Comment by miigotu** [comment] 2015-09-20 19:06
Anyone notice if https://github.com/SiCKRAGETV/SickRage/commit/2c67cca39ee9712f5198ef7d680e3210ea517aff has helped this?

**Comment by MGaetan89** [comment] 2015-09-20 19:11
Oops, have to change my default branch back to `master` so I stop closing issues when I update my fork...

**Comment by miigotu** [comment] 2015-09-21 11:35
@liquex still happening with develop?

**Comment by liquex** [comment] 2015-09-21 14:05
@miigotu I'll have to check in the evening, although it could be a bit hard to reproduce since I changed the status of all the affected episodes manually in order to save traffic.

**Comment by liquex** [comment] 2015-09-26 08:29
@miigotu The problem persists somewhat. I have an episode "Snatched (Best) 720p WEB-DL" and it was downloaded (three times already), but the status hasn't changed. This one could be due to "WEBRip" in the release name instead of "WEB-DL". All I could find in the debug logs was that the episode was already processed and that the folder wasn't deleted because there's an episode in it (I think because the first of the redownloads was processed).

I know it's a separate issue but it would be really useful to be able to filter the logs by date, maybe for the last seven days or something like that. The first redownload happened yesterday but all the logs I can find are from today.

**Comment by bobbysteel** [comment] 2015-09-26 09:06
I've seen it though when it's WEB-DL. I've been just manually marking
episodes as downloaded 720p-WEBDL when this happens, so I can't reproduce
for logs at the moment. Definitely seems to be when I've got archive
qualities custom set to 720p-HDTV, 720p-WEBDL both, as it seems to not
actually be changing the status from snatched to downloaded or archived,
thus creating a loop.
FWIW, the SABNZBd pause duplicates feature is what's catching this for me
so it's not a big hassle...

**Comment by fernandog** [comment] 2015-10-06 03:04
@liquex can we close?

**Comment by liquex** [comment] 2015-10-07 15:08
@fernandog Yes, seems fine so far. If there's another issue it would probably be separate and I could open another issue on the tracker or even try to fix it myself. Cheers!

**Closed** 2015-10-07 15:10 UTC
Labels: 1: Bug / issue, 3: Fixed, 4: Need feedback
