### ISSUE TITLE
New update thread checker

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#3065] opened 2015-10-02 09:49 UTC
With the new theread checker i cannot update as there is always something running, either post porcessing or sub checker
Ive even tried auto updater and even that cant update
Wouldnt it better to have a option to disable it?

**Comment by SiCKRAGEB0T** [comment] 2015-10-02 09:49
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment] 2015-10-02 10:32
Sadly thats not a real solution, it should just work correctly. 
Otherwise end-users will open issues with "cant update" etc. And i'm not really looking forward to explain a 100+ time how to disable that function. Also not functioning correctly will frustrate the end-users.

I myself haven't had any problems, but my searches are not very fast and i use scripts.

**Comment by duramato** [comment] 2015-10-02 10:42
@fernandog care to comment ?,since you were the one that added it..

**Comment by fernandog** [comment] 2015-10-02 11:10
That PR wasnt merged

**Comment by duramato** [comment] 2015-10-02 11:24
yes it was...

**Comment by miigotu** [comment] 2015-10-02 11:41
@fernandog the change to webserve `_run_backup_if_safe` or whatever.

**Comment by fernandog** [comment] 2015-10-02 11:45
Should we revert the fix then? He sets his PP to 6min. So its always running.
The problem is updating while PP is really processing and not just 'scanning'

**Comment by miigotu** [comment] 2015-10-02 11:49
For now it need reverted, later we need to remove those thread checks in versionChecker, and just pause the threads to update.

It doesnt matter what SR happens to be doing, when a call to update is made it needs to be made.

**Comment by duramato** [comment] 2015-10-02 11:49
and what is PP is moving a file?

**Comment by miigotu** [comment] 2015-10-02 11:54
@duramato If you pause the thread, there can be at most 1 item running in the queue. You then use a thread lock and the lock blocks from continuing in the thread you are in until the item in the queue finishes. You update, unpause the queue, and restart. When it is shutting down for restart, all of the threads will close gracefully and finish whatever work they need to to be safe.

**Closed** 2015-10-02 12:08 UTC
Labels: 1: Bug / issue, 3: Fixed, branch: develop
