### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by mkools** [SiCKRAGETV/sickrage-issues#316] opened 2015-01-01 16:04 UTC
Whenever I go to general settings I get this error:

http://pastebin.com/WSx6SKDt

Next when I tried to set an episode to ignored I got this error:

http://pastebin.com/LE0jTE4v

I'm using python 2.7.9 on FreeBSD 10.1. Is this the correct version to use with sickrage? I get a lot of these errors lately. 

I already did a complete new installation, but the same errors show up.

**Comment by fernandog** [comment] 2015-01-03 18:19
the first issue is already opened by another user.

how did you installed? 
did you "git clone"?

**Comment by mkools** [comment] 2015-01-04 09:28
Yes I did a git clone.

Thanks.

**Comment by abeloin** [comment] 2015-01-21 08:55
@mkools 
Can you tell me the branch/commit hash of your sickrage installation?

* First error: See SiCKRAGETV/sickrage-issues#307 for more info
* Second error:
Form the log, it look like it's trying to set the episode status as undefined.
```
uri: /home/setStatus?show=255192&eps=3x9&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['3x9'], 'show': ['255192']}
```

**Comment by markheloking** [comment] 2015-01-22 12:13
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by markheloking** [comment] 2015-01-22 12:13
Shouldn't we close this since it's a duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/307? Or is it that much different?

**Comment by fernandog** [comment] 2015-01-25 01:58
closing. no reply and it's a user script issue.

**Closed by fernandog** 2015-01-25 01:58 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Unconfirmed, 4: Need more info
