### ISSUE TITLE
[Meta] Wiki

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2967] opened 2015-09-26 06:25 UTC
What wiki are we using? There's one for sickrage and one for sickrage-issues. The links on the two repo's README all seem to point to the old one from sickrage. Should we not move it all over to sickrage and delete the wiki on sickrage-issues?

@SiCKRAGETV/moderators

**Comment by WebSpider** [comment] 2015-09-26 06:58
If that means the right people can still edit the Wiki, I think its better to use the main Wiki, and move all the content over from -issues

 

Van: X O [mailto:notifications@github.com] 
Verzonden: zaterdag 26 september 2015 08:27
Aan: SiCKRAGETV/sickrage-issues <sickrage-issues@noreply.github.com>
CC: Nils <nils@familievogels.nl>
Onderwerp: [sickrage-issues] [Meta] Wiki (#2967)

 

What wiki are we using? There's one for sickrage and one for sickrage-issues. The links on the two repo's README all seem to point to the old one from sickrage. Should we not move it all over to sickrage and delete the wiki on sickrage-issues?

@SiCKRAGETV/moderators <https://github.com/orgs/SiCKRAGETV/teams/moderators>

**Comment by neoatomic** [comment] 2015-09-26 09:53
Not a good idea. We chose sickrage-issues for end-users wiki and sickrage is for developer wiki.
The problem is when you move all to sickrage, only fernandog and miigotu can edit the wiki. Also it is the location of the donate page, and dont like the idea that every1 has modifying access to that.

So i can expect some help writing the wiki pages from now on.? :P

**Comment by OmgImAlexis** [comment] 2015-09-26 09:57
@neoatomic either way we need the links going to the correct wikis. We could always add the donation link to the readme instead?

**Comment by neoatomic** [comment] 2015-09-26 10:08
@OmgImAlexis The readme needs some updating for sure, not only the wiki links...
The current wiki/donation setup works well, so i'm not in favor of messing with that unless there is a good reason.

**Comment by neoatomic** [comment] 2015-09-26 12:14
Will close this, as its better discussed here https://github.com/SiCKRAGETV/sickrage-issues/issues/589

**Closed by neoatomic** 2015-09-26 12:14 UTC
