### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by adrianmace** [SiCKRAGETV/sickrage-issues#730] opened 2015-02-23 12:40 UTC
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) 
[GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p8-amd64-64bit-ELF**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/6586b414125f54ab30ca
### ERROR
```
Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 309, in index
    return self.redirect('/home/')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-02-23 12:44
@adrianmace what are the steps to reproduce it?

**Comment by Hellowlol** [comment] 2015-02-23 12:50
You should edit the gist as it contains your apikey to nzb.su. Shouldn't this be masked?

**Comment by fernandog** [comment] 2015-02-23 12:52
@Hellowlol it should!. maybe when echel0n added that feature, it only worked for UI, not gist.

**Comment by adrianmace** [comment] 2015-02-23 12:55
@fernandog @Hellowlol thanks for the warning, I have removed the gist for now.

I'm not entirely sure on the steps to reproduce however I know I wasn't doing anything specific it just appeared when I clicked into a TV Show.

**Comment by fernandog** [comment] 2015-02-23 12:56
closing as is duplicate

**Closed by fernandog** 2015-02-23 12:56 UTC
Labels: 5: Duplicate

**Comment by Hellowlol** [comment] 2015-02-23 13:03
@fernandog It was a part for several but the first one was https://github.com/SiCKRAGETV/SickRage/commit/9eefc8034bc77b9c36b50b42bef20ba7f110cc06#diff-1716b2a4b5a6b712365fc5f089022831

Just press the history button on that file.

The app submit should be disabled until this is fixed, i guess there are alot of compromised account out there :P

**Comment by fernandog** [comment] 2015-02-23 13:09
@abeloin help here

**Comment by fernandog** [comment] 2015-02-23 13:52
just to be safe, we must add a code to delete all gist from the user.

**Comment by Hellowlol** [comment] 2015-02-23 16:49
They are added from the config here https://github.com/SiCKRAGETV/SickRage/blob/93f0f0ad1fa278afb17f73d47c099b82a766dede/sickbeard/config.py#L435

**Comment by abeloin** [comment] 2015-02-23 16:49
@fernandog Looking at the code it's only masking items with the word password in it.

**Comment by fernandog** [comment] 2015-02-23 16:51
The aboce GIST hides API

**Comment by abeloin** [comment] 2015-02-23 16:53
@fernandog My guest is that he removed it himself

**Comment by fernandog** [comment] 2015-02-23 16:54
ops... sorry

can't wed change to:

```
if bool(item_name.find('password') + 1) or bool(item_name.find('api') + 1) or bool(item_name.find('username') + 1):
```

**Comment by abeloin** [comment] 2015-02-23 17:14
Ok the issue is that the code check for api_key but the data is stored in key:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/__init__.py#L1119

**Comment by fernandog** [comment] 2015-02-23 17:19
@abeloin 
_apikey
_api
api_key

**Comment by abeloin** [comment] 2015-02-23 17:32
It's a mess part of it save it under key and the other part expected api_key

**Comment by abeloin** [comment] 2015-02-23 18:48
Merge PR which fix the issue: https://github.com/SiCKRAGETV/SickRage/pull/1401

**Comment by fernandog** [comment] 2015-02-23 18:55
@abeloin thanks!
