### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by SimonKberg** [SiCKRAGETV/sickrage-issues#636] opened 2015-02-17 16:50 UTC
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@1ad9ed453985f1fccdcd7eac97970cef1cb324c1
Link to Log: https://gist.github.com/0269551d95e30c75a3da
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/media/sdk1/home/simonkberg/.sickrage/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ChaniD** [comment] 2015-02-18 03:56
i'm getting the same error

**Comment by abeloin** [comment] 2015-02-18 05:30
Duplicate of #231

**Closed by abeloin** 2015-02-18 05:30 UTC
