### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by johnkillerbob** [SiCKRAGETV/sickrage-issues#679] opened 2015-02-20 07:25 UTC
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-45-generic-i686-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
### ERROR
```
SEARCHQUEUE-BACKLOG-255326 :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-02-20 08:36
@johnkillerbob can you send full logs please?

**Comment by johnkillerbob** [comment] 2015-02-20 08:53
I hope this is the relevant part of the log, I don't know what I'm doing ;)

2015-02-20 07:16:45 INFO     SEARCHQUEUE-BACKLOG-255326 :: Downloading Defiance.S02E12-E13.HDTV.x264-KILLERS from TorrentBytes
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Calling Transmission Client
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Requested a POST connection to url http://localhost:9091/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Requested a POST connection to url http://localhost:9091/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Response to POST request is {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":true,"blocklist-size":352161,"blocklist-url":"http://****.bitsurge.net/public/biglist.p2p.gz","cache-size-mb":4,"config-dir":"/var/lib/transmission-daemon/info","dht-enabled":true,"download-dir":"/mnt/media/downloads/completed","download-dir-free-space":707076812800,"download-queue-enabled":true,"download-queue-size":5,"encryption":"required","idle-seeding-limit":30,"idle-seeding-limit-enabled":true,"incomplete-dir":"/mnt/media/downloads/incomplete","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":1024,"peer-limit-per-torrent":512,"peer-port":51414,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":0.0010,"seedRatioLimited":true,"speed-limit-down":500,"speed-limit-down-enabled":true,"speed-limit-up":5,"speed-limit-up-enabled":true,"start-added-torrents":true,"trash-original-torrent-files":true,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.84 (14307)"},"result":"success"}

2015-02-20 07:16:45 ERROR    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/home/****/.sickrage/sickbeard/clients/generic.py", line 171, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/home/****/.sickrage/sickbeard/clients/generic.py", line 151, in _get_torrent_hash
    info = bdecode(result.content)["info"]
  File "/home/****/.sickrage/lib/bencode/bencode.py", line 66, in bdecode
    r, l = decode_func[x[0]](x, 0)
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Exception raised when sending torrent: 'NoneType' object has no attribute '__getitem__'

**Comment by fernandog** [comment] 2015-02-20 22:59
@gborri can you check this? Do you know transmission code don't you?

**Comment by fernandog** [comment] 2015-02-22 11:15
@gborri

**Comment by DcR-NL** [comment] 2015-02-22 11:40
Saw the same thing happening: http://pastebin.com/CjGFmXzX (line 80).

BRANCH: (develop) / COMMIT: (652c9f33f92b3c74c0256bb3aafae5e8dc014c89) 
Python Version: 2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)]

**Comment by fernandog** [comment] 2015-02-22 11:43
Can you check transmission connection test?

**Comment by DcR-NL** [comment] 2015-02-22 11:51
@fernandog Test returns 'Success'. 21 minutes before the error it snatched two season packs from AlphaRatio, so the connection is fine.

**Comment by fernandog** [comment] 2015-02-22 12:30
maybe there is something wrong with that torrent

**Comment by DcR-NL** [comment] 2015-02-22 12:38
@fernandog Maybe, but manually downloading the same torrent and adding it to transmission works fine (just tried it).

**Comment by fernandog** [comment] 2015-02-22 13:09
if is a temporary error, the traceback should be supressed and show a warning.

**Comment by gborri** [comment] 2015-02-23 10:54
@fernandog sorry i didn't see it.
i don't know so good transmission code. 
It happens also to me also with manual search, but if i retry it will start correct.

**Comment by gborri** [comment] 2015-02-23 10:58
@fernandog if i'm not wrong seems that happen when the result vaiable is empty. i don't know why

**Comment by fernandog** [comment] 2015-02-23 11:00
@gborri can you check the logs for something like this?

I think transmission failed to respond and result in a None result, creating this error.

```
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Requested a POST connection to url http://localhost:9091/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Requested a POST connection to url http://localhost:9091/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
```

**Comment by abeloin** [comment] 2015-02-23 21:25
@fernandog There nothing to do here, the debug info is helpful for us:

This is the debug message which include a copy of the traceback
```
Traceback (most recent call last):
  File "/home/****/.sickrage/sickbeard/clients/generic.py", line 171, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/home/****/.sickrage/sickbeard/clients/generic.py", line 151, in _get_torrent_hash
    info = bdecode(result.content)["info"]
  File "/home/****/.sickrage/lib/bencode/bencode.py", line 66, in bdecode
    r, l = decode_func[x[0]](x, 0)
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-02-20 07:16:45 DEBUG    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Exception raised when sending torrent: 'NoneType' object has no attribute '__getitem__'
```
and this is the error message:
```
2015-02-20 07:16:45 ERROR    SEARCHQUEUE-BACKLOG-255326 :: Transmission: Failed Sending Torrent
```

The issue is in torrentbytes.py, it doesn't provide all the data for that release.

**Comment by fernandog** [comment] 2015-02-23 22:11
@abeloin ok! if this happens again or another issue we see what we can do. closing

**Closed by fernandog** 2015-02-23 22:11 UTC
Labels: 1: Bug / issue, 3: Confirmed, 4: Fix pending, branch: master
