### ISSUE TITLE
No episodes will be found anymore

### ISSUE THREAD

**Issue by fonix99** [SiCKRAGETV/sickrage-issues#1852] opened 2015-06-19 05:15 UTC
Hi there, 

since a few days sickrage failed to find new episodes (nzb files). 

I am using the latest master of sickrage on a QNAP system with nzbget as downloader. All worked fine, since a couple days ago. 

Usually my system is up 24/7, so Sickrage scans every 6 hours for new episodes, backlog is set to 720hours. I also tried to set "search", "backlog" on "start" and restarted the service, but also no episodes (nzb files) will be downloaded and send to nzbget. 

At first I thought my newznab service could have a problem, but it works fine with a sonarr on my windows machine, so it has to be sickrage.

I read in the forum, that some people have reported an equal problem recently. So any kind of idea, what the problem is?

I also checked my debug logged, but it is nothing really in there.

```
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Transaction with 1 queries executed
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Checking if found episode 1x1 is wanted at quality HDTV
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Any,Best = [ HDTV, 720p WEB-DL, 1080p WEB-DL ] [ None ] Found = [ HDTV ]
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Existing episode status: 3 (Wanted)
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-06-19 07:11:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Found result The.Astronaut.Wives.Club.S01E01.720p.HDTV.X264-DIMENSION at https://nzb.cat/getnzb/9e32fb3051b3bb287fa2d860e3dfb8c4e08a2457.nzb&i=2319&r=**********
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Checking if found episode 1x1 is wanted at quality HDTV
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Any,Best = [ HDTV, 720p WEB-DL, 1080p WEB-DL ] [ None ] Found = [ HDTV ]
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Existing episode status: 3 (Wanted)
2015-06-19 07:11:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-06-19 07:11:14 INFO     SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Found result The.Astronaut.Wives.Club.S01E01.720p.HDTV.X264-DIMENSION at https://nzb.cat/getnzb/6aee50a54150062818c08273e4587cdf3f8edaa6.nzb&i=2319&r=**********
2015-06-19 07:11:15 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Picking the best result out of [u'The.Astronaut.Wives.Club.S01E01.720p.HDTV.X264-DIMENSION', u'The.Astronaut.Wives.Club.S01E01.720p.HDTV.X264-DIMENSION']
2015-06-19 07:11:15 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Unknown exception while loading URL https://nzb.cat/getnzb/9e32fb3051b3bb287fa2d860e3dfb8c4e08a2457.nzb&i=2319&r=**********
2015-06-19 07:11:15 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Unknown exception while loading URL https://nzb.cat/getnzb/6aee50a54150062818c08273e4587cdf3f8edaa6.nzb&i=2319&r=**********
2015-06-19 07:11:15 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: No result picked.
2015-06-19 07:11:15 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-06-19 07:11:15 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: formatting pattern: %SN - %Sx%0E - %EN -> The Astronaut Wives Club - 1x01 - Launch
2015-06-19 07:11:15 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NzbCat] :: All found results for The Astronaut Wives Club - 1x01 - Launch were rejected.
2015-06-19 07:11:15 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
```
Any kind of help would be great, cause at the moment, I have to download all episdos manually an it su**s^^

**Comment by miigotu** [comment] 2015-06-19 06:50
@fonix99 This is because newznab providers did not work at all before, and a new issue is revealed now that it does.

What if you put in your browser:
`https://nzb.cat/getnzb/6aee50a54150062818c08273e4587cdf3f8edaa6.nzb&i=2319&r=`
Does it work?

What about this:
`https://nzb.cat/getnzb/6aee50a54150062818c08273e4587cdf3f8edaa6.nzb&i=2319&r=&apikey=YOURAPIKEYHERE`

**Comment by miigotu** [comment] 2015-06-19 07:03
Can you invite me to nzbcat to test a fix?

**Comment by fonix99** [comment] 2015-06-19 07:14
Both links work for me - I can downloaded the nzb files.

Sorry, have no invites. If u needed I can send u my account details for testing - I can than later change the password back.

**Comment by miigotu** [comment] 2015-06-19 07:23
Strange then, I have no idea why you get the exception. Could you upload the full sickrage.log file somewhere for me?

**Comment by fonix99** [comment] 2015-06-19 07:39
http://www27.zippyshare.com/v/hBDmWrmF/file.html

This is the log after I restartet the service. Added 4 Indexer and a test database with 2 new tv shows.

**Comment by miigotu** [comment] 2015-06-19 08:55
try deleting cache/indexers/* cache/sessions/* cache/rss/* and cache.db

**Comment by neoatomic** [comment] 2015-06-19 10:37
Seems that when SR wants to load the URL to download the NZB it go's wrong. : 

```
Unknown exception while loading URL https://www.usenet-crawler.com/getnzb/d9f8053ddff8ecc0a03cb14034b5489b.nzb&i=165868&r=**********
Unknown exception while loading URL https://nzb.cat/getnzb/3d94c2fe5ad0e51a5258b02ce0da105d2655343e.nzb&i=2319&r=**********
```
So i'm wondering if its a SSL problem.?

I'm using  [Usenet-Crawler] with SABNZB without any problems. : 

```2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Transaction with 2 queries executed
2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Checking if found episode 1x5 is wanted at quality HDTV
2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ HDTV ]
2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Existing episode status: 3 (Wanted)
2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-06-16 09:20:54 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Found result Texas.Rising.Part5.720p.HDTV.x264-KILLERS at https://www.usenet-crawler.com/getnzb/91dd07b9fbf6e41170e264166745eb16.nzb&i=233093&r=**********
2015-06-16 09:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Picking the best result out of [u'Texas.Rising.Part5.720p.HDTV.x264-KILLERS']
2015-06-16 09:20:56 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Quality of Texas.Rising.Part5.720p.HDTV.x264-KILLERS is HDTV
2015-06-16 09:20:56 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Picked Texas.Rising.Part5.720p.HDTV.x264-KILLERS as the best
2015-06-16 09:20:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Texas.Rising.Part5.720p.HDTV.x264-KILLERS from Usenet-Crawler
2015-06-16 09:20:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: Sending NZB to SABnzbd
2015-06-16 09:20:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: URL: http://localhost:xxxx/api?ma_password=********&apikey=**********&name=https%3A%2F%2Fwww.usenet-crawler.com%2Fgetnzb%2F91dd07b9fbf6e41170e264166745eb16.nzb%26i%3D233093%26r%3Ddca5263b571290587f0e199a0636d4c8&cat=tv&priority=1&mode=addurl&ma_username=**********
2015-06-16 09:21:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Result text from SAB: ok
2015-06-16 09:21:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: NZB sent to SAB successfully
2015-06-16 09:21:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Checking if we should archive our first best quality match for for episode Texas.Rising.Part5.720p.HDTV.x264-KILLERS
2015-06-16 09:21:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN - %QN
2015-06-16 09:21:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Texas Rising - 1x05 - The Rise of the Republic - HDTV
2015-06-16 09:21:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transaction with 1 queries executed
```

**Comment by fonix99** [comment] 2015-06-19 13:27
still the same problem. could it be the "ssl" problem, I read about? But why it works still some days ago? This kind of problem goes back month!?

anyway, here the log after 3 hours running...

http://www27.zippyshare.com/v/xPsE7ied/file.html

**Comment by fernandog** [comment] 2015-06-19 13:31
Newsnab were fixed

**Comment by miigotu** [comment] 2015-06-19 15:06
apikey is not sent when downloading the nzb, and we have no cookie set like he does in his browser.

**Comment by fonix99** [comment] 2015-06-19 15:27
Just for testing I deleted sickrage and installed sickbeard on the qnap. Set up Sickbeard-Search and Usenet-Crawler as Searchprovider and added a show.

Works fine. So, to me with my noob knowledge it has to be something to do with inside sickrage!?

Here is the sickbeard log, after clean install: http://www31.zippyshare.com/v/tUd4TfNh/file.html

I prefer sickrage over sickbeard because of the failed download behavior, so I really don't want to go back ;) Hope anyone will find the reason what is causing the problem.

**Comment by neoatomic** [comment] 2015-06-19 15:55
@fonix99 I have removed your Sickbeard log as it contained all your API keys...

If its a bug we will find it. But first we need to locate the problem.
In the meantime can you copy&paste the info that is under "help & info" ? So we know what version etc you are running.?

ps. For uploading logs its more practical to use pastebin.com.

**Comment by fonix99** [comment] 2015-06-19 16:23
Ah ok, didn't checked the log, thank u.

http://pastebin.com/U4uY9VFf

**Comment by miklschmidt** [comment] 2015-06-22 12:54
i have the same problem, tried using different search providers, no cigar. Somethings definitely going on. Had the problem for about a week when i updated.

**Comment by bartley69** [comment] 2015-06-22 13:47
I am having this same issue, If i load the url into a browser it grabs the show fine. Otherwise in my logs i see

2015-06-22 21:38:34 WARNING SEARCHQUEUE-DAILY-SEARCH :: [nzb.su] :: Unknown exception while loading URL https://api.nzb.su/getnzb/83fc1146e904b50401c92a6a5b37b3f5.nzb&i=127007&r=**********

Is there any fix available?

**Comment by miklschmidt** [comment] 2015-06-22 13:48
@bartley69 apparently the "fix" is what broke it :D

**Comment by bartley69** [comment] 2015-06-22 13:50
Ah I see. Yes this problem only started in the last 4 or 5 days I believe? Sickrage updated and it broke mine :-(

**Comment by miklschmidt** [comment] 2015-06-22 13:51
Yup that pretty much sums it up for me as well.

**Comment by neoatomic** [comment] 2015-06-22 14:10
Try to use "http" instead of "https" in the links. That should prevent SSL problems.
See if that temp fixes it for now.

**Comment by fernandog** [comment] 2015-06-22 14:11
@miigotu can we add the BaseSSLError as another exception here or urllib3.exceptions.ReadTimeoutError?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1339

**Comment by miklschmidt** [comment] 2015-06-22 14:13
@neoatomic i can't, the usenet crawler provider is supplied with sickrage, can't modify the URL i'm afraid. I'll have to find it in the code, so it'll have to wait till i get home.

**Comment by miklschmidt** [comment] 2015-06-22 16:09
I replaced all instances i could find of https://www.usenet-crawler.org with http. Didn't seem to make a difference, the log still said http. So i got tired of that approach and just checked out v4.0.26, and everything works.

**Comment by miklschmidt** [comment] 2015-06-22 16:12
If i didn't have to restart sickrage each time i'd do a bisect, but it sounds like you guys know what's going on.

**Comment by fonix99** [comment] 2015-06-22 16:27
Good to see I am not the only one, with this kind of problem.

It seems to me, like an ssl problem, cause if I use the indexer fastnzb (which uses http instead of https) I get some results. All the indexer who uses https don't work (I tried manually to chance the URL, but didn't not work).

Like I said before, it all worked very well since the latest update and sickbeard still works. So I hope u guys will find a fix for it.

**Comment by miigotu** [comment] 2015-06-22 16:33
bisect isnt going to be very helpful.

Problem is there are major changes being made (because we are being force to by nzb providers) and we have no way of testing the changes because we have no nzb accounts.

I have tried to stick to changing newznab providers only for now, as they are the ones blocking us, but I haz no newznab provider, and the free ones have us blocked.

**Comment by fernandog** [comment] 2015-06-22 16:40
@miklschmidt maybe you can provide a temp API key to @miigotu ( you can generate another when is over). What do you think?

**Comment by miigotu** [comment] 2015-06-22 16:47
@miklschmidt did you try going to usenet-crawler on your browser?

http://downforeveryoneorjustme.com/www.usenet-crawler.org

**Comment by miigotu** [comment] 2015-06-22 16:53
https seems to work. and this newznab has open registration right now.

@fernandog @neoatomic

**Comment by fonix99** [comment] 2015-06-22 17:02
I don't what "bisect" means, but I wasn't intend to be say something bad to u guys. I really like your work and u put in it.

I just tried to explain what is going on my system ;)

**Comment by miigotu** [comment] 2015-06-22 17:09
I know what is wrong.

See how fast fixing something is when you have a provider?

The sitesSR should be providing developer access to fix problems instead of blocking SR.

**Comment by miigotu** [comment] 2015-06-22 17:57
@miklschmidt @fonix99 Please test the last commit in develop and report if I can close this or not.

**Comment by miklschmidt** [comment] 2015-06-22 18:55
@miigotu Tested, didn't work. I only have a free API key for usenet crawler so i can't really help you there. Is it too much trouble to just setup a local newznab server for development, seems like this issue isn't specific to one indexer, and it would probably be handy to test against when making larger changes.

**Comment by miklschmidt** [comment] 2015-06-22 18:57
@miigotu And yes, the URL's work fine in the browser, as i stated earlier. It's not the indexer :)

**Comment by miigotu** [comment] 2015-06-22 19:29
@miklschmidt usenet-crawler works fine here. Testing nzbcat now.

Are you on develop branch?

**Comment by miklschmidt** [comment] 2015-06-22 19:30
Strange, yes i am. I checked git log for your commit. Let me hit it with a couple other shows.

**Comment by miklschmidt** [comment] 2015-06-22 19:39
Nope, i can't make it work, pulled again to make sure i had the latest stuff, still getting the same error, no matter what i do.

**Comment by miklschmidt** [comment] 2015-06-22 19:46
I see your fix is basically just expanding the search date parameters. I'm pretty sure that has nothing to do with it, It finds the nzb, it just can't download it without something throwing an unexpected error somewhere.

**Comment by miklschmidt** [comment] 2015-06-22 19:49
Wait, it's not supposed to download it is it? That's sabnzbd's job right?

```
2015-06-22 21:38:21 WARNING  SEARCHQUEUE-BACKLOG-270633 :: Unknown exception while loading URL https://www.usenet-crawler.com/getnzb/4580cc38734c8d97d6fd3dee339f05af.nzb&i=71600&r=**********
2015-06-22 21:38:20 INFO     SEARCHQUEUE-BACKLOG-270633 :: [Usenet-Crawler] :: Found result True.Detective.S02E01.PROPER.720p.HDTV.x264-KILLERS at https://www.usenet-crawler.com/getnzb/4580cc38734c8d97d6fd3dee339f05af.nzb&i=71600&r=**********
2015-06-22 21:38:20 INFO     SEARCHQUEUE-BACKLOG-270633 :: [Usenet-Crawler] :: Performing season pack search for True Detective
```

**Comment by miigotu** [comment] 2015-06-22 19:57
Both usenet-crawler and NZBCat are both finding releases and snatching them for me now, they werent previously.
As I don't have the SSL errors, we can now safely assume it IS now an ssl problem.

It does download the .nzb file, either to a file or into memory. It then either saves the nzb to your black hole, or passes it to sabnzbd to be added.

How many api hits and grabs do you have today in https://www.usenet-crawler.com/profile ?

**Comment by fonix99** [comment] 2015-06-22 20:05
I will test the development branch in a few minutes and give u feedback.

**Comment by miklschmidt** [comment] 2015-06-22 20:09
108/14

**Comment by miigotu** [comment] 2015-06-22 20:11
@miklschmidt I'm pretty sure you are over the limit for a free user in one day there.

**Comment by miklschmidt** [comment] 2015-06-22 20:14
@miigotu even if that was the case, i've had this problem for a week and sickrage is the only service i have running that uses that API. If it's a certificate problem, then why does 4.0.26 work fine?

**Comment by miigotu** [comment] 2015-06-22 20:21
@miklschmidt since the changes, you should try and remove the cache.db, cache/sessions, cache/rss cache/indexers

Aside from that, this might be difficult to catch, as I cannot reproduce it on the current commit.

**Comment by miklschmidt** [comment] 2015-06-22 20:36
@miigotu 
> you should try and remove the cache.db, cache/sessions, cache/rss cache/indexers
I shouldn't have done that, lol, now it hangs forever.

**Comment by miigotu** [comment] 2015-06-22 20:41
It does hang the first time, while it builds the db and indexes and caches. Let it sit lol. Thats a problem for another time.

**Comment by miigotu** [comment] 2015-06-22 20:49
Its a good chance clearing the cache should work. I think its a good chance the different user-agent making your session invalid.

**Comment by fonix99** [comment] 2015-06-22 20:52
Still getting the same Error. Deleted all the Cache files like u said and tried both indexer separately.  

Nzb.cat: (8 API Hits, 0 Grabs)
https://gist.github.com/fonix99/d053a60da02d632c7832

Usenet-Crawler: (5  API Hits, 2 Grabs - but that was with v4.0.26)
https://gist.github.com/fonix99/07fd7385d558d9de744a

**Comment by miklschmidt** [comment] 2015-06-22 21:01
Mine's back, still the same error - i'll go with 4.0.26 for now, still seems to work fine. @fonix99 you sure you're on 4.0.26? Did you restart sickrage after you checkout out the 4.0.26 tag?

**Comment by miigotu** [comment] 2015-06-22 21:05
Try and update again? If it is a problem opening the output file or changing it's permission, you should now get a warning log line.

**Comment by fonix99** [comment] 2015-06-22 21:08
@miklschmidt 

This last post was with the latest dev branch for testing the changes like miigotu said.

v.4.0.26. works fine for me.

**Comment by miigotu** [comment] 2015-06-22 21:17
I'm curious is this change might be effecting you:
https://github.com/SiCKRAGETV/SickRage/compare/v4.0.26...develop#diff-ba5b5de76e0a70fd5abeaa199fe4f848L202

**Comment by fonix99** [comment] 2015-06-22 21:21
I won't any good help with that, cause I really just a noob with all that stuff. I already happy to get this branches installed on my qnap :)

**Comment by miklschmidt** [comment] 2015-06-22 21:24
@fonix99 Sorry i misread that, nevermind :)

**Comment by miklschmidt** [comment] 2015-06-22 21:28
@miigotu i'll try reverting back those 4 lines to the original 11 later and see if that makes a difference.

**Comment by fonix99** [comment] 2015-06-22 21:28
@miigotu with the changes u made in helpers.py, I still get the same warning messages

**Comment by miigotu** [comment] 2015-06-22 21:31
@fonix99 thats why I'm thinking it might be somewhere else.

@miklschmidt might fix it. idunno. Are you using blackhole or no?

**Comment by miklschmidt** [comment] 2015-06-22 21:32
@miigotu nope, not using blackhole.

**Comment by miigotu** [comment] 2015-06-22 21:34
@miklschmidt could you turn on blackhole and see if it works?

**Comment by fonix99** [comment] 2015-06-22 21:40
I tried, but no luck.

https://gist.github.com/fonix99/de3dd733e54eb2f46a5d

**Comment by miigotu** [comment] 2015-06-22 21:44
I'm pretty sure its the change I noted above, from when we removed eztv/ezrss.

@fonix99 can you try this?
Stop SR and Open sickbeard/search.py

change lines 202-205 from:
```
        if not cur_result.url.startswith('magnet'):
            cur_result.content = cur_result.provider.getURL(cur_result.url)
            if not cur_result.content:
                continue
```
to:
```
#        if not cur_result.url.startswith('magnet'):
#            cur_result.content = cur_result.provider.getURL(cur_result.url)
#            if not cur_result.content:
#                continue
```

Start SR and try snatch nzb again...

**Comment by miigotu** [comment] 2015-06-22 21:50
Eh, I wish you had debug on in that gist you posted too xD. Missing some helpful info there.

**Comment by fonix99** [comment] 2015-06-22 21:51
Sorry, I will activated on the next one.

**Comment by fonix99** [comment] 2015-06-22 21:58
https://gist.github.com/fonix99/811c3dc9540cf6060b67

Is this a debug log?

**Comment by fonix99** [comment] 2015-06-22 21:58
damit wrong button^^

**Comment by miigotu** [comment] 2015-06-22 23:18
Gotta go pick my wife up, I'll check more later.

**Comment by bartley69** [comment] 2015-06-23 00:16
I'm a bit noob, how can I downgrade to the previous version untill this is fixed? Thanks.

**Comment by miigotu** [comment] 2015-06-23 07:33
```
git reset --hard
git checkout -- .
git checkout -b  tag4026 v4.0.26
```

**Comment by bartley69** [comment] 2015-06-23 08:05
Thanks mate, done. I changed a random episode of a show to Wanted and restarted Sickrage to force the daily search and it grabbed the episode right away. I will keep monitoring this thread and switch back to master once it has hopefully been rectified.

Cheers.

**Comment by miigotu** [comment] 2015-06-23 09:23
Can one of you verify that tag v4.0.27 fails? then I can diff 26 and 27 and see a smaller diff.

**Comment by bartley69** [comment] 2015-06-23 09:28
Is it just 
git checkout -b tag4027 v4.0.27

?

**Comment by miigotu** [comment] 2015-06-23 11:34
yep

**Comment by miigotu** [comment] 2015-06-23 11:35
but the 
```
git reset --hard
git checkout --.
```
is important too, it makes sure your repo is clean

**Comment by fonix99** [comment] 2015-06-23 11:51
Test with v4.0.28:

https://gist.github.com/fonix99/df762db5addf8b84c972

**Comment by bartley69** [comment] 2015-06-23 12:07
I was on v4.0.26 which worked great, just went back to v4.0.27 again and i got the error again.

https://gist.github.com/bartley69/33eab1a39222b1527412

I will try 4.0.28 now.

Cheers.

**Comment by miigotu** [comment] 2015-06-23 12:09
I'll have just a few more to try to be sure. One sec.

**Comment by bartley69** [comment] 2015-06-23 12:15
v4.0.28 didn't grab the show, yet there are 2 episodes set to Wanted. It didn't give an error message though either?

https://gist.github.com/bartley69/49097d8cf634989efe1d

**Comment by miigotu** [comment] 2015-06-23 12:15
git checkout -b ezrss-gone be1528e5f19b9a5f846ad2110f32a2f06ce688f4
test, then:
git checkout -b before-ezrss-gone 1a9bc78eddcb757bb3879c9046378a2f71fede87
test again...

**Comment by miigotu** [comment] 2015-06-23 12:16
if one of those works and the other doesn't, I have only one place to look.

**Comment by bartley69** [comment] 2015-06-23 12:22
ezrss-gone be1528e5f19b9a5f846ad2110f32a2f06ce688f4
https://gist.github.com/bartley69/fd3fe5d2f2d0d56157b2

Error is back, trying the second one now.

**Comment by bartley69** [comment] 2015-06-23 12:27
before-ezrss-gone 1a9bc78eddcb757bb3879c9046378a2f71fede87
It worked! It added it to SAB perfectly!
https://gist.github.com/bartley69/594e0181715d60058537

**Comment by fonix99** [comment] 2015-06-23 12:27
git checkout -b before-ezrss-gone 1a9bc78eddcb757bb3879c9046378a2f71fede87

are snatching files

**Comment by miigotu** [comment] 2015-06-23 12:31
then its the problem I pointed to earlier today, I'll push a commit shortly.

**Comment by bartley69** [comment] 2015-06-23 12:34
I know Im a little retarded and I'm sorry, how do I switch to dev and master branches? Is it the similar to what we just did?
<pre>git reset --hard
git checkout -- .
git checkout develop</pre>

And just swap develop with master if that's what I want?

**Comment by miigotu** [comment] 2015-06-23 12:36
yep, as long as you haven't committed anything to develop/master

**Comment by bartley69** [comment] 2015-06-23 12:38
Thankyou! And thanks for looking into the issue for us and solving! I'm off to bed, 8:45pm and early start in the morning. I will check in the morning and see if it's all fixed in the master branch. Thanks again for your help!

**Comment by miigotu** [comment] 2015-06-23 12:45
how simple the changes are to follow when you only have one commit to compare xD>
https://github.com/SiCKRAGETV/SickRage/compare/1a9bc78eddcb757bb3879c9046378a2f71fede87...be1528e5f19b9a5f846ad2110f32a2f06ce688f4

**Comment by fonix99** [comment] 2015-06-23 12:50
great to hear that u found it :) looking forward for the next release.

**Comment by miigotu** [comment] 2015-06-23 12:56
Thing is, the same place may be the cause of #1579, but for now I will just revert this section.

**Comment by miigotu** [comment] 2015-06-23 13:02
Merged to develop, can I haz test?

**Comment by fonix99** [comment] 2015-06-23 13:32
I tried the latest dev. No warnings, but also no snatching. Maybe I did something wrong!? How can I make a clean install from dev? Like I said, I am a noob an I guess I made a dirty install (just copy&paste with WinSCP to the Sickrage dir location on my Qnap.^^

Back to v4.0.26 and it works again.

**Comment by bartley69** [comment] 2015-06-23 13:41
Switched to dev and did git pull, got the update of 2 commits. However i had the same results, no errors but no snatches.

**Comment by miigotu** [comment] 2015-06-23 13:44
Hmm, must be on the sanitizeSceneName somehow then? Will try again tomorrow.

**Comment by fonix99** [comment] 2015-06-23 13:45
no worry, take your time

**Comment by miigotu** [comment] 2015-06-23 14:04
Committed another attempt at fixing it.

**Comment by miigotu** [comment] 2015-06-23 14:04
On develop branch.

**Comment by fonix99** [comment] 2015-06-23 14:40
https://gist.github.com/fonix99/a0e6daa7219e7ddbb1fd

With activate Black hole. If I try nzbget, it snachtes but the nzb file won't fetch.

**Comment by miigotu** [comment] 2015-06-23 17:34
lol same log 2x @fonix99 .

**Comment by miigotu** [comment] 2015-06-23 17:35
@fonix99 Its expected to get a warning for https and nzb black hole, because it doesnt use requests there and cannot verify the connection. Still using urlib2

**Comment by fonix99** [comment] 2015-06-23 17:48
Yes, I made some equal tests (because at the first time it didn't work) and posted the logs^^ I guess only the last two are important to u.

Do I understand u right, that https request only work with nzbget/sabnzb but not black hole? So, the "failed" message on the last log is "ok"? I am using only nzbget directly with sickrage, so I can live without the full black hole function atm ;)

**Comment by miigotu** [comment] 2015-06-23 18:19
I think so, but we can't be sure yet without more test results.

**Comment by fonix99** [comment] 2015-06-23 19:04
Lets see what the others have to report.

**Comment by miigotu** [comment] 2015-06-23 19:38
@fonix99 did you also update again? need to make sure my latest changes around that code didnt break it again.

**Comment by fonix99** [comment] 2015-06-23 19:59
Have not much time atm, will test it later this evening.

**Comment by miigotu** [comment] 2015-06-23 20:01
kk

**Comment by fonix99** [comment] 2015-06-23 21:36
latest dev branch looks fine to me.

https://gist.github.com/fonix99/741dd1189cdbd4453dd3

**Comment by bartley69** [comment] 2015-06-23 21:37
Just heading off to work but thought i'd try it before i left. Updated to latest version of dev branch, no error but did not grab my wanted episodes either.

https://gist.github.com/bartley69/aa3418b6ded52c8907df

**Comment by miigotu** [comment] 2015-06-23 21:38
@bartley69 if you had debug on you would see why.

**Comment by bartley69** [comment] 2015-06-23 21:41
Ok, how do I turn it on? I'm pretty noob bit doing what I can to help!

**Comment by fonix99** [comment] 2015-06-23 21:44
I did it inside sickrage. Settings - General - Advanced Settings - "Enable Debug".

**Comment by miigotu** [comment] 2015-06-23 21:54
I need to add a script that pasties the log for you =P

**Comment by bartley69** [comment] 2015-06-24 08:34
I enabled debug logging but can't find where the logs are saved to. I assumed it would be in /share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage but it is not. If I can help in any way let me know.

**Comment by miigotu** [comment] 2015-06-24 09:38
unrelated error, but I need to fix that now too.

**Comment by miigotu** [comment] 2015-06-24 09:39
Closing this for now, as it seems to be fixed, but we can still discuss here as I will get notifications.

**Closed by miigotu** 2015-06-24 09:39 UTC
Labels: 1: Bug / issue, 3: Fix

**Comment by bartley69** [comment] 2015-06-24 09:43
I'm on dev branch and mine still doesn't work? Do I need to do something else?

**Comment by miigotu** [comment] 2015-06-24 12:34
From your log there are no episodes wanted in your shows.

**Comment by miigotu** [comment] 2015-06-24 12:35
Also, when I fix the namecache thing it probably will work fine. Tomorrow.

**Comment by bartley69** [comment] 2015-06-24 13:18
But there is episodes set to wanted. It's not seeing them? I will go back to 4026 and change nothing else and see if that grabs them.

**Comment by miigotu** [comment] 2015-06-24 18:43
See my last comment. =P

**Comment by bartley69** [comment] 2015-06-25 23:44
Ok, I'm just retarded haha. I will stay on 4026 for now, let me know if you want us to switch to dev and test anything. Cheers.

**Comment by miigotu** [comment] 2015-06-26 01:54
current master should work now, let me know.

**Comment by fonix99** [comment] 2015-06-26 02:07
Something is wrong again with the latest master 4.0.28.

https://gist.github.com/fonix99/f5c930ac470b52f7f34c

The develop merged version from yesterday worked great.

**Comment by miigotu** [comment] 2015-06-26 02:14
I dont think you have all of the updates @fonix99

**Comment by miigotu** [comment] 2015-06-26 02:14
Matter of fact, I know you dont.

**Comment by fonix99** [comment] 2015-06-26 02:21
Hmm, it did "git pull" and it says "already up-to-date".

I will do my dirty install (worked every time for me^^) and see what happend.

**Comment by fonix99** [comment] 2015-06-26 02:37
Made a manual "copy&paste" installation, which worked the last times for me, but still getting this error. Tried different shows, but its the every time the same result.

Side fact. My qnap needs now to kill the sickrage process, cause it took over 45sec. and it not stopped it selfs - with the previous version it took round about 10.15sec. and sickrage stopped it self, so need to kill by my qnap.

**Comment by bartley69** [comment] 2015-06-26 02:45
Latest master not grabbing for me - https://gist.github.com/bartley69/fb949ecf59a56fcaa24a

**Comment by miigotu** [comment] 2015-06-26 03:14
shit @fonix99 I missed 2 urls.

**Comment by fonix99** [comment] 2015-06-26 03:26
np, glad to help

**Comment by miigotu** [comment] 2015-06-26 03:29
Try again.

**Comment by fonix99** [comment] 2015-06-26 03:42
The error is gone, but now our "old" problem is back.

https://gist.github.com/fonix99/f8adc60d1b3e4b13681e

**Comment by miigotu** [comment] 2015-06-26 04:44
If I start making fixes in my fork, can you just test from there? I keep making commits here for this and fooking up the history and breaking things.

**Comment by fonix99** [comment] 2015-06-26 04:46
Sure, if u tell me what I have to do - git commands for the updates or something like said. Like I said, I am a noob on that stuff ;)

**Comment by miigotu** [comment] 2015-06-26 05:16
Sure, best thing to do is rename your current SR folder so we dont mess it up.
Not sure where your db and cfg are stored, but if it is in the sickrage dir, you will want to copy it to the repo we are checking out into the same path.
```
git clone https://github.com/miigotu/SickRage.git /path/where/sickrage/WAS
cd /path/where/sickrage/WAS
git checkout unknown-exception
```
Make sure it is all set up and check if it works, check for the error. 
Then if we have to try again you just stop sickrage, do a `git pull` from inside that sickrage dir, and start sr again.

**Comment by fonix99** [comment] 2015-06-26 05:29
ok, seems to run. commit is d226c7a35a643b2b62571f4f19d074166f0d19c0!?

**Comment by miigotu** [comment] 2015-06-26 05:32
yes

**Comment by miigotu** [comment] 2015-06-26 05:34
https://github.com/miigotu/SickRage/commit/d226c7a35a643b2b62571f4f19d074166f0d19c0

**Comment by fonix99** [comment] 2015-06-26 05:35
First debug log.

https://gist.github.com/fonix99/8e96f2c0bab5a40e6f37

**Comment by miigotu** [comment] 2015-06-26 05:39
-.- Install pyOpenSSL == 0.13.1

**Comment by miigotu** [comment] 2015-06-26 05:41
These random fails have nothing to do with the code. It is all about whether the url is http or https and needs SNI.

**Comment by miigotu** [comment] 2015-06-26 05:43
Which is also the same reason I cannot reproduce the error, I has no ssl problems.

**Comment by fonix99** [comment] 2015-06-26 05:46
how do I install pyopenssl? 

I found this on the wiki page:

curl https://bootstrap.pypa.io/get-pip.py -L -k | python2.7
ipkg install openssl-dev
pip2.7 install -U setuptools pip pyopenssl==0.13.1

But the first step delivers an error: 

"Could not find a version that satisfies the requirement pip (from versions: ) No matching distribution found for pip"

**Comment by miigotu** [comment] 2015-06-26 23:01
Go to qnap forums and find the info about python 2.7.9

**Comment by fonix99** [comment] 2015-06-27 01:34
The only info I found is, that its not available for ARM processors like my Qnap 419P II.

I downgraded to v.4.0.26 and hope it will work till the ssl problem is fixed somehow ;)

Anyway, thanks for your work and time u spend to help us.

**Comment by miigotu** [comment] 2015-06-27 01:56
Complain to qnap then =P. They need to provide you with either python 2.7.9, or pyOpenSSL >= 0.13.1 (Preferably >0.14),

This requires a compiler, and development headers to install > 0.14 or pip cannot install it.

For 0.13.1, maybe you can find some info somewhere about how to install pip on your ARM QNAP.

**Comment by bouwew** [comment] 2015-07-09 15:53
Guys, I managed to install pyopenssl on my TS419P.
You need to have Optware installed and enabled.

Enter at the command prompt:

easy_install-2.7 pip
ipkg update
ipkg install gcc
ipkg install openssl-dev
/opt/local/bin/pip2.7 install -U setuptools pip pyopenssl==0.13.1

After that I receive the message: "Successfully installed pyopenssl-0.13.1".

**Comment by bartley69** [comment] 2015-07-12 06:45
Is your sickrage working correctly now bouwew on the latest master release?

**Comment by miigotu** [comment] 2015-07-12 07:17
@bartley69 it is for @fonix99

**Comment by miklschmidt** [comment] 2015-07-23 20:44
Just found some extra time on my hands and upgraded to master. It works flawlessly now after removing python-openssl from apt and installing the newest version with pip. Thanks for your help @miigotu.

**Comment by bartley69** [comment] 2015-07-23 21:09
I will just paste my post from the other thread, hope you can help.

Next issue, I'm trying to install pyopenssl but I don't know where to issue the commands? I'm running putty and in the main dir issuing the first command but it's failing? Where/how do I issue them?

Thanks.

Error - http://i.gyazo.com/a83dcc2ecb8ff1f0dd30ad64a11d2136.png

optware Installed - http://i.gyazo.com/1dabb2eafa1f9cf46e93653961c20aad.png
