### ISSUE TITLE
SUBLIMINAL TypeError: %d format: a number is required, not NoneType AND wrong flag for dutch subtitle

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#88] opened 2014-12-15 03:05 UTC
<a href="https://github.com/neoatomic"><img src="https://avatars.githubusercontent.com/u/7928052?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [neoatomic](https://github.com/neoatomic)**
_Saturday Dec 13, 2014 at 11:58 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1115 (0 comment(s))_

----

Came across this error. 

TypeError: %d format: a number is required, not NoneType

Strange thing is it did not show up in the WebUI error log.
Its only showing in the sickbeard.log file.

BRANCH: (develop) / COMMIT: (2adfa81341d86bbf50fc208799420ac08045201c) 

http://pastebin.com/ByFzWmX5

Also the little flags for the subtitle languages dont show up under "history" so that might be related.?

![naamloos](https://cloud.githubusercontent.com/assets/7928052/5423633/d905d962-82c7-11e4-9ab6-39a644edbc03.jpg)

**Comment by fernandog** [comment] 2015-02-13 11:26
@neoatomic still an issue? never heard from your here for a while.

**Comment by neoatomic** [comment] 2015-02-13 11:41
Yes still not solved.
Subtitle language i use is Dutch but if i look at the links that are used for the flag it points to completely different names. :
```
http://xxxxxxxx/images/flags/RS.png
http://xxxxxxxx/images/flags/nd.png
```
(Think dutch should be nl.png)

The subtitle (srt) files are downloaded in dutch, so they are correct.

So it seems something is going wrong when SR is creating the links for the flags.
I recall seeing a commit about using 3 character flags instead of 2, but not sure if that was related.

![1](https://cloud.githubusercontent.com/assets/7928052/6186700/4c3d92ea-b37d-11e4-877e-457d04e43d60.png)
![2](https://cloud.githubusercontent.com/assets/7928052/6186701/4c4327d2-b37d-11e4-816e-43f847ab6f12.png)

**Comment by fernandog** [comment] 2015-02-13 11:50
@neoatomic can you try develop branch?

**Comment by neoatomic** [comment] 2015-02-13 11:52
I'm at develop.
```
SR Version: 	BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 
```

**Comment by fernandog** [comment] 2015-02-13 11:55
@neoatomic check the page code and get the img url. try to open only it

**Comment by neoatomic** [comment] 2015-02-13 11:56
For RS.png i get : 

```
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 1338, in _execute
    result = yield result
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 642, in run
    value = future.result()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/concurrent.py", line 110, in result
    raise_exc_info(self._exc_info)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 189, in wrapper
    yielded = next(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 2115, in get
    self.root, absolute_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 2294, in validate_absolute_path
    raise HTTPError(404)
HTTPError: HTTP 404: Not Found 
```

So noting there...

**Comment by fernandog** [comment] 2015-02-13 12:00
should be rs.png, not RS.png

can you try copy the URL of the image (browser) and try to open rs.png ?

**Comment by neoatomic** [comment] 2015-02-13 12:02
@fernandog According to my history page its RS.png so that is the first error than.

But again the flag needs to be nl.png. (dont even know what flag RS.png is...)

**Comment by fernandog** [comment] 2015-02-13 12:10
@Abeloin, this PR shouldn't fix this?
https://github.com/SiCKRAGETV/SickRage/pull/1210/

this PR should'nt delete all single country flag files and use only the country-flags.png ?

**Comment by fernandog** [comment] 2015-02-13 12:11
@neoatomic what about the "TypeError: %d format: a number is required, not NoneType" error? still happening?

**Comment by neoatomic** [comment] 2015-02-13 12:15
No, haven't seen that error anymore. Only the flag problem is still there.

**Comment by fernandog** [comment] 2015-02-13 13:27
@neoatomic its diffent. you didn't select "multilanguage"

**Comment by abeloin** [comment] 2015-02-13 15:21
@fernandog Nope, PR1210 separate the flag used by the subtitle(language) and flag used to display a show's country. As ca(Canada) is not the same as ca(Catalan). See my comment https://github.com/SiCKRAGETV/sickrage-issues/issues/447#issuecomment-70739549

Let me check the code for the subtitle flags.

**Comment by abeloin** [comment] 2015-02-13 16:29
I've run some tests but I'm unable to reproduce the error:
![Imgur](http://i.imgur.com/IdVd21l.png)

**Comment by fernandog** [comment] 2015-02-13 16:30
@abeloin what about dutch subtitle?

**Comment by abeloin** [comment] 2015-02-13 16:32
It's the first one in the image

**Comment by abeloin** [comment] 2015-02-13 16:33
@neoatomic What the filename of the srt? Show Name.S0101.Title.srt?

**Comment by neoatomic** [comment] 2015-02-13 16:39
@abeloin Did you deselected "Subtitles Multi-Language Append language codes to subtitle filenames? " ?
Will check the filename.

**Comment by abeloin** [comment] 2015-02-13 16:55
I'm afraid I didn't. Deselected now.
Mmm.. It take the filename last 2 chars to generate the language code and the value in the db is und.

**Comment by neoatomic** [comment] 2015-02-13 17:00
Cant SR use the language code in the config.ini.? Under "subtitles_languages = nl "
Would be a easy fix than.

**Comment by fernandog** [comment] 2015-02-13 17:08
@abeloin check this comment: https://github.com/SiCKRAGETV/sickrage-issues/issues/386#issuecomment-72199095

**Comment by abeloin** [comment] 2015-02-13 19:57
@neoatomic Can you try this commit: https://github.com/abeloin/SickRage/commit/d3ab12ff64966b8a803b0a9e9891ead44ff4dc43 . It should do the trick.

Note:
* The history will always have unknown flags.
* Your current show's subtitles should be unknown.
* Subtitles download after this patch will have the proper flag.

**Comment by abeloin** [comment] 2015-02-13 20:03
@fernandog Yeah the history doesn't contain the data.

Ultimately, we will have to create a table subtitles which will track each subtitles files with their metedata. Also adding the subtitles lang to history.

**Comment by fernandog** [comment] 2015-02-13 20:34
@abeloin thanks! I agree. Let's wait to master/develop stabilizes then we make this and other changed to the DB.

**Comment by abeloin** [comment] 2015-02-13 20:45
@fernandog Yes

**Comment by abeloin** [comment] 2015-02-16 00:48
Here's the pull request: https://github.com/SiCKRAGETV/SickRage/pull/1322

**Comment by fernandog** [comment] 2015-02-16 00:52
@abeloin thanks! feel free to merge this and others local PRs you made

**Comment by fernandog** [comment] 2015-02-16 01:10
@neoatomic develop updated. please test and report back

**Comment by neoatomic** [comment] 2015-02-16 07:58
Sorry for the late reaction.
I just updated to the latest Dev. However when i try to open/click on a show in the webui i get an error.
Did try a full update for the shows but didn't help.


```
	BRANCH: (develop) / COMMIT: (72060fe6a8fb9f93fed735c52d1f9348340657c1) 
```

```
2015-02-16 06:52:19 INFO     Thread-58 :: Successfully processed
2015-02-16 08:53:18 ERROR    Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1099, in displayShow
    t = PageTemplate(rh=self, file="displayShow.tmpl")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 144, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 796, in compile
    raise e
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1199
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',')] if x != ""): # generated from line 511, col 13
                                                                                                                                                    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1099, in displayShow
    t = PageTemplate(rh=self, file="displayShow.tmpl")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 144, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 796, in compile
    raise e
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1199
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',')] if x != ""): # generated from line 511, col 13
                                                                                                                                                    ^
SyntaxError: invalid syntax
2015-02-16 08:53:18 ERROR    Uncaught exception GET /home/displayShow?show=260449 (192.168.2.14)
HTTPServerRequest(protocol='http', host='192.168.2.3:8083', method='GET', uri='/home/displayShow?show=260449', version='HTTP/1.1', remote_ip='192.168.2.14', headers={'Accept-Language': 'nl,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.2.3:8083', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.2.3:8083/home/', 'Cookie': 'sortby=date; stay_login=1; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; smplrefresh=5; id=51uFuTFw0EpUs1330LAN000223; plushHistPerPage=5'})
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 1292, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/concurrent.py", line 226, in <lambda>
    lambda future: callback(future.result()))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1099, in displayShow
    t = PageTemplate(rh=self, file="displayShow.tmpl")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 144, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 796, in compile
    raise e
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1199
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',')] if x != ""): # generated from line 511, col 13
                                                                                                                                                    ^
SyntaxError: invalid syntax
 ```

**Comment by fernandog** [comment] 2015-02-16 09:45
@neoatomic please update and report back

**Comment by neoatomic** [comment] 2015-02-16 11:19
Updated and the error when viewing a show is gone. Thank you.

**Comment by fernandog** [comment] 2015-02-16 11:36
@neoatomic what about the flag?

**Comment by neoatomic** [comment] 2015-02-16 11:44
@fernandog 
I deleted a subtitle and did a manual search from the episode list.
Now i get a flag with a "?" in the history instead op the Dutch flag.
So it still isn't working correctly...

**Comment by fernandog** [comment] 2015-02-16 12:06
@neoatomic  can you provider the link of the image with ?

**Comment by neoatomic** [comment] 2015-02-16 12:13
http://xxxxxxxxxxxx/images/flags/unknown.png

Just to be sure, as i downloaded this subtitle before can it be that the (old) info/data is pulled from sickbeard.db.? 
Otherwise i need to wait till a brand new subtitle is downloaded for an episode.

**Comment by fernandog** [comment] 2015-02-16 12:25
@neoatomic let's wait them.

**Comment by neoatomic** [comment] 2015-02-16 13:56
Did a full scan for subtitles and this error came up.

```
2015-02-16 14:45:02 DEBUG    Thread-34 :: 75897: No subtitles downloaded for episode 6x15
2015-02-16 14:45:02 DEBUG    Thread-34 :: 75897: An object for episode 6x16 didn't exist in the cache, trying to create it
2015-02-16 14:45:02 DEBUG    Thread-34 :: 75897: Loading episode details from DB for episode 6x16
2015-02-16 14:45:02 DEBUG    Thread-34 :: Setter sets location to /volume1/video/=_Series_=/South Park/South Park - S06E16 - My Future Self 'n' Me.mp4
2015-02-16 14:45:02 DEBUG    Thread-34 :: 75897: Downloading subtitles for episode 6x16
2015-02-16 14:45:15 DEBUG    Thread-34 :: 75897: Saving episode details to database
2015-02-16 14:45:15 DEBUG    Thread-34 :: STATUS IS 3204
2015-02-16 14:45:15 DEBUG    Thread-34 :: 75897: No subtitles downloaded for episode 6x16
2015-02-16 14:45:15 DEBUG    Thread-34 :: 75897: An object for episode 6x17 didn't exist in the cache, trying to create it
2015-02-16 14:45:15 DEBUG    Thread-34 :: 75897: Loading episode details from DB for episode 6x17
2015-02-16 14:45:15 DEBUG    Thread-34 :: Setter sets location to /volume1/video/=_Series_=/South Park/South Park - S06E17 - Red Sleigh Down.mp4
2015-02-16 14:45:15 DEBUG    Thread-34 :: 75897: Downloading subtitles for episode 6x17
2015-02-16 14:45:28 DEBUG    Thread-34 :: 75897: Saving episode details to database
2015-02-16 14:45:28 DEBUG    Thread-34 :: STATUS IS 3204
2015-02-16 14:45:28 DEBUG    Thread-34 :: 75897: No subtitles downloaded for episode 6x17
2015-02-16 14:45:28 DEBUG    Thread-34 :: 75897: An object for episode 7x1 didn't exist in the cache, trying to create it
2015-02-16 14:45:28 DEBUG    Thread-34 :: 75897: Loading episode details from DB for episode 7x1
2015-02-16 14:45:28 DEBUG    Thread-34 :: Setter sets location to /volume1/video/=_Series_=/South Park/South Park - S07E01 - Cancelled.mp4
2015-02-16 14:45:28 DEBUG    Thread-34 :: 75897: Downloading subtitles for episode 7x1
2015-02-16 14:45:57 ERROR    Thread-34 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>
2015-02-16 14:45:57 DEBUG    Thread-34 :: 75897: An object for episode 7x2 didn't exist in the cache, trying to create it
2015-02-16 14:45:57 DEBUG    Thread-34 :: 75897: Loading episode details from DB for episode 7x2
2015-02-16 14:45:57 DEBUG    Thread-34 :: Setter sets location to /volume1/video/=_Series_=/South Park/South Park - S07E02 - Krazy Kripples.mp4
2015-02-16 14:45:57 DEBUG    Thread-34 :: 75897: Downloading subtitles for episode 7x2
2015-02-16 14:46:10 DEBUG    Thread-34 :: 75897: Saving episode details to database
2015-02-16 14:46:10 DEBUG    Thread-34 :: STATUS IS 3204
```

```
BRANCH: (develop) / COMMIT: (431d04de4a4072d64e05d34b6a81e1ba963106ac) 
```

**Comment by fernandog** [comment] 2015-02-16 14:00
Yes. 503 Service Unavailable
We should get this error and show a log

**Comment by abeloin** [comment] 2015-02-16 14:15
@neoatomic Here's a quote of [my previous comment](https://github.com/SiCKRAGETV/sickrage-issues/issues/88#issuecomment-74316451)
>Note:
> The history will always have unknown flags.
> Your current show's subtitles should be unknown.
> Subtitles downloaded after this patch will have the proper flag.

The history database doesn't include the subtitle language hence the unknown flag. In multi, it pull from the 2 chars before the extension.
In display show, the proper language flag will be shown and kept until the file is removed.

**Comment by fernandog** [comment] 2015-02-19 11:03
@neoatomic any news?

**Comment by neoatomic** [comment] 2015-02-19 11:13
Well not really since last post. 
The flags of newly downloaded subtitles are still unknown under history.
But that is correct according to abeloin's comment. 
So i need to live with that till there is another fix.

**Comment by fernandog** [comment] 2015-02-19 11:28
will close this issue. as there's another issue for that:
https://github.com/SiCKRAGETV/sickrage-issues/issues/386

**Closed by fernandog** 2015-02-19 11:28 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: develop
