### ISSUE TITLE
[APP SUBMITTED]: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by jdfalk** [SiCKRAGETV/sickrage-issues#1349] opened 2015-04-21 06:32 UTC
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
No Log available with ERRORS: 
### ERROR
```
Thread-114 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2012, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/opt/sickrage/sickbeard/webserve.py", line 1982, in getEpisodes
    logger.log('No Show Object found for show with indexerID: ' + searchThread.show.indexerid, logger.ERROR)
TypeError: cannot concatenate 'str' and 'int' objects

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment] 2015-04-21 07:43
@jdfalk While this error will be fixed, the underlying problem needs to be addressed. This message can only be logged when you still have a search running for a show that is no longer in your list... If you restart SR the problem is gone.

**Closed** 2015-04-22 07:15 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
