### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Shazlash** [SiCKRAGETV/sickrage-issues#1437] opened 2015-04-27 12:50 UTC
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/594deb3575bf2ac2d587
### ERROR
```
SEARCHQUEUE-BACKLOG-281622 :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-04-27 15:44
@nicolasmartinelli can you check this please?

**Comment by matigonkas** [comment] 2015-04-27 16:07
@fernandog related ? http://torrentfreak.com/take-over-new-eztv-domain-name-150425/

**Comment by Shazlash** [comment] 2015-04-27 16:16
URL in eztv.py is:

self.urls = {
            'base_url': 'https://eztv.ch/',
            'rss': 'https://eztv.ch/',
            'episode': 'http://eztvapi.re/show/%s',
        }

**Comment by nicolasmartinelli** [comment] 2015-04-27 16:26
@matigonkas : not directly. The error appears for the episode search, so in http://eztvapi.re/, because for this particular episode, the link contains a torrent, not a magnet. Actually, http://eztvapi.re/ just gathers automatically the content of eztv.ch, and since you pointed it, things have been changing on the website. In the past, the magnet link was always the first link in the column, now it is not the case anymore.

To make a long story short, I'll have a look to allow a torrent file as link. Should be done by the end of the day.

**Comment by matigonkas** [comment] 2015-04-27 16:41
@nicolasmartinelli  just searched the comments on the article (the latestes comments) and both eztv.it and eztv.ch are run by the same "scammers" ,novaking its creaters "handed over" the website to them

**Comment by nicolasmartinelli** [comment] 2015-04-27 17:10
@matigonkas As long as they provide links, I will assume the provider should be available.

**Comment by pct00** [comment] 2015-04-27 18:43
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5fd354cae9b0699bd718f19fe37e2d0f856b7997
Link to Log: https://gist.github.com/1b0cbfd542ceb3fb10d6
### ERROR
```
SEARCHQUEUE-BACKLOG-258823 :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\providers\eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-04-27 18:51
@miigotu its working the dupe issue

**Comment by miigotu** [comment] 2015-04-27 19:04
@fernandog yes, as long as you dont close it. If you close the issue, it will open a new one, so it prevents us from closing and ignoring an error xD

**Comment by fernandog** [comment] 2015-04-27 19:08
@miigotu only the SSL error that is not working.

**Comment by miigotu** [comment] 2015-04-27 19:18
@fernandog notice the titles of the ssl errors are not an exact match. There are 3 line numbers reported for _ssl.c, for different versions of ssl installed. Leave all 3 open.

**Comment by miigotu** [comment] 2015-04-27 19:20
Anyways, I know what the error in this #1437 report is from, I'll create a PR.

**Comment by matigonkas** [comment] 2015-04-27 20:00
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-15-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5fd354cae9b0699bd718f19fe37e2d0f856b7997
Link to Log: https://gist.github.com/d2296e762f5da5461578
### ERROR
```
FINDPROPERS :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment] 2015-04-28 00:29
@matigonkas Please update, hotfix pushed to develop.
@Shazlash Hotfix pushed to develop branch, you could switch to develop, and update.
@fernandog should my hotfix be merged to master early?

**Comment by fernandog** [comment] 2015-04-28 01:16
@miigotu only sunday now. Or we revert fix to develop and make a PR to master. is it critical?

**Comment by miigotu** [comment] 2015-04-28 01:50
@fernandog Not that crucial, it only gives this error when the regex doesnt match.  Until this is merged to master next week, we must leave this issue open, as there will be more submissions of this error.

**Comment by neives** [comment] 2015-04-28 08:16
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/a0d592d07aca6ff4e782
### ERROR
```
SEARCHQUEUE-BACKLOG-281697 :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neives** [comment] 2015-04-28 11:15
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/d43b77750b55ee924a2a
### ERROR
```
SEARCHQUEUE-BACKLOG-258744 :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment] 2015-04-28 11:49
@neives No need to keep reporting the error, it has already been fixed in develop.

**Comment by bd2000** [comment] 2015-04-28 17:22
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/cc08e71192a43002aa7f
### ERROR
```
SEARCHQUEUE-MANUAL-258744 :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by NilsNojje** [comment] 2015-04-28 18:10
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/6960a620f8f27279e7a9
### ERROR
```
FINDPROPERS :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/home/aztech/.sickrage/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shouwy** [comment] 2015-04-29 08:22
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [EZTV] :: Failed parsing EZTV Traceback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/providers/eztv.py", line 146, in _doSearch
    title = re.search('&dn=(.*?)&', link).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment] 2015-05-07 10:34
@fernandog why reopened?

**Comment by fernandog** [comment] 2015-05-07 14:06
@miigotu your label DO NOT CLOSE =) 
was it fixed in master?

**Comment by Thraxis** [comment] 2015-05-07 15:20
How the hell did I close this by a commit to my own Repo?

**Comment by miigotu** [comment] 2015-05-07 15:42
@Thraxis Because you have write access to this repo, and in the commit message is 'Fixes SiCKRAGETV/sickrage-issues#1437'
Github auto manages that way.

@fernandog It is fixed in master and develop.

**Closed by miigotu** 2015-05-07 15:42 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, DO NOT CLOSE

**Comment by pct00** [comment] 2015-10-04 19:11
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8d5bd6afc7436ceefc79033b325fdf98925e055c
Link to Log: https://gist.github.com/cdae65ac836375fb35e6
### ERROR
```
Thread-199 :: Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pct00** [comment] 2015-10-04 19:46
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8d5bd6afc7436ceefc79033b325fdf98925e055c
Link to Log: https://gist.github.com/a8e7f9d8090965b0880d
### ERROR
```
Thread-225 :: Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pct00** [comment] 2015-10-04 22:56
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8d5bd6afc7436ceefc79033b325fdf98925e055c
Link to Log: https://gist.github.com/389cbaeceee2c981e5b7
### ERROR
```
Thread-20 :: Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pct00** [comment] 2015-10-04 22:59
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8d5bd6afc7436ceefc79033b325fdf98925e055c
Link to Log: https://gist.github.com/1845e9fd21f94c3c2d1f
### ERROR
```
Thread-214 :: Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pct00** [comment] 2015-10-04 23:01
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8d5bd6afc7436ceefc79033b325fdf98925e055c
Link to Log: https://gist.github.com/1558e4a5d4c03f774a73
### ERROR
```
Thread-202 :: Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment] 2015-10-04 23:10
Can someone lock this temporarily? I'm on mobile ATM. He is just spamming and not responding/checking my response.

**Comment by miigotu** [comment] 2015-10-04 23:10
@SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-10-04 23:15
He will open issue about not able to open issue. Lol

@pct00 please stop submitting errors!

**Comment by miigotu** [comment] 2015-10-04 23:29
@fernandog we need to add that check to the issue submitter. whether the issue is locked or not is returned by gh api.
