### ISSUE TITLE
Downloading wrong torrent when using client API, Blackhole downloads the correct torrent

### ISSUE THREAD

**Issue by Ockingshay** [SiCKRAGETV/sickrage-issues#1579] opened 2015-05-12 09:42 UTC
This morning i noticed that sickrage had downloaded a backlog search of an untouched 1080p blurary when it is suppose to only download 720p or web-dl.

So i attempted to replicate it and it seems that although SR is choosing the correct version, what it downloads from BTN is something completely different.

***
Log removed
****

What it actually sent to my Transmission is Archer.2009.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-KRaLiMaRKo.

**Comment by Ockingshay** [comment] 2015-05-12 09:44
2015-05-12 10:27:52 INFO     SEARCHQUEUE-BACKLOG-110381 :: Downloading Archer.2009.S01.720p.BluRay.x264-REWARD from BTN
2015-05-12 10:27:52 INFO     SEARCHQUEUE-BACKLOG-110381 :: Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!
2015-05-12 10:27:52 INFO     SEARCHQUEUE-BACKLOG-110381 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 110381 AND season in  1,1,1,1,1,1,1,1,1,1]
2015-05-12 10:27:52 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-KRaLiMaRKo is 1080p BluRay
2015-05-12 10:27:51 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.HDTV.H.264-NOGRP is HDTV
2015-05-12 10:27:51 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.1080p.BluRay.DTS-HD.MA5.1.H.264-Complete is 1080p BluRay
2015-05-12 10:27:51 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.576p.BluRay.DD5.1.x264-HiSD is Unknown
2015-05-12 10:27:51 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.S01.NTSC.DVD-BitHQ is Unknown
2015-05-12 10:27:50 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.432p.WEBRip.OGG.x264-DiRTY is SDTV
2015-05-12 10:27:50 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.Portable.WEB-DL.H.264-BTN is SDTV
2015-05-12 10:27:50 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.HDTV.Xvid-BTN is SDTV
2015-05-12 10:27:50 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.DVDRip.Xvid-OSiTV is SD DVD
2015-05-12 10:27:49 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.HDTV.x264-BTN is HDTV
2015-05-12 10:27:49 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.WEB-DL.H.264-NovaFilmTV is 720p WEB-DL
2015-05-12 10:27:49 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.WEB-DL.DD5.1.H.264-DON is 720p WEB-DL
2015-05-12 10:27:49 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.BluRay.x264-CtrlHD is 720p BluRay
2015-05-12 10:27:48 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.720p.BluRay.x264-REWARD is 720p BluRay
2015-05-12 10:27:48 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.1080p.BluRay.DTS.MA5.1.x264-BluDragon is 1080p BluRay
2015-05-12 10:27:48 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.1080p.BluRay.DTS5.1.x264-CtrlHD is 1080p BluRay
2015-05-12 10:27:48 INFO     SEARCHQUEUE-BACKLOG-110381 :: Quality of Archer.2009.S01.1080p.BluRay.DTS.x264-Penumbra is 1080p BluRay
2015-05-12 10:27:40 INFO     SEARCHQUEUE-BACKLOG-110381 :: [BTN] :: Performing season pack search for Archer (2009)

**Comment by Ockingshay** [comment] 2015-05-12 09:50
i repeated the backlog search and it happened again. Although SR reports it has picked Archer.2009.S01.720p.BluRay.x264-REWARD from BTN, what it downloads from BTN is Archer.2009.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-KRaLiMaRKo is 1080p BluRay

**Comment by Ockingshay** [comment] 2015-05-12 09:52
2015-05-12 10:48:09 INFO     SEARCHQUEUE-BACKLOG-110381 :: Downloading Archer.2009.S01.720p.BluRay.x264-REWARD from BTN
2015-05-12 10:48:09 DEBUG    SEARCHQUEUE-BACKLOG-110381 :: Calling Transmission Client
2015-05-12 10:48:09 DEBUG    SEARCHQUEUE-BACKLOG-110381 :: Transmission: Response to POST request is {"arguments":{},"result":"success"}

**Comment by Ockingshay** [comment] 2015-05-12 09:57
Tried it with HDBits and it produces the same scenario. This time it was another untouched bluray torrent. So looks to be a problem with a recent update in SR. This never happened on the previous commit. I will attempt to revert back a version. 

I'm running BRANCH: (master) / COMMIT: (bf2baf309bd01683fdc06d57ece0b89d53b4a180)

**Comment by MrNightRyder** [comment] 2015-05-17 09:00
I ran into this same problem... reference: https://github.com/SiCKRAGETV/sickrage-issues/issues/1615

**Comment by MrNightRyder** [comment] 2015-05-17 09:23
Ran into some recent problems with downloading 720p HDTV items off of BTN. I think the problem may be on the sickrage side but i'm not 100% certain. The logs claim that they are grabbing the proper torrent however what ends up in my torrent client isn't right. I've tried a large number of quality setups as well as included/excluded words and it claims to find matches and even matches them verbatum but when it pulls the files down it pulls the wrong .torrent. Please note that uninstalls have been tried also a complete wipe of the database for sickrage. This is also affecting multiple people all of us are on the current version: BRANCH: (master) / COMMIT: (bf2baf309bd01683fdc06d57ece0b89d53b4a180)

Here are some example searches

2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Downloading American.Horror.Story.S01.720p.HDTV.x264-BTN from BTN
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 250487 AND season in 1,1,1,1,1,1,1,1,1,1,1,1]
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.NTSC.DVD-BTN based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.NTSC.DVD-BTN is Unknown
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-HiFi based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-HiFi is 1080p BluRay
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.576p.BluRay.DD5.1.x264-HiSD based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.576p.BluRay.DD5.1.x264-HiSD is Unknown
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.1080p.USA.BluRay.DTS-HD.MA5.1.H.264-BluHD based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.1080p.USA.BluRay.DTS-HD.MA5.1.H.264-BluHD is Unknown
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.HDTV.Xvid-BTN is SDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.WEB-DL.DD5.1.Xvid-T00NG0D based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.WEB-DL.DD5.1.Xvid-T00NG0D is SDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.480p.WEB-DL.x264-mSD based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.480p.WEB-DL.x264-mSD is SDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.DVDRip.Xvid-DEMAND based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.DVDRip.Xvid-DEMAND is SD DVD
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.720p.HDTV.x264-BTN is HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.720p.WEB-DL.DD5.1.H.264-CtrlHD based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.720p.WEB-DL.DD5.1.H.264-CtrlHD is 720p WEB-DL
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.1080p.WEB-DL.DD5.1.H.264-SA89 based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.1080p.WEB-DL.DD5.1.H.264-SA89 is 1080p WEB-DL
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.720p.BluRay.x264-DEMAND based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.720p.BluRay.x264-DEMAND is 720p BluRay
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.720p.BluRay.DD.5.1.x264-TayTO based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.720p.BluRay.DD.5.1.x264-TayTO is 720p BluRay
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.1080p.BluRay.x264-CLASSiC based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.1080p.BluRay.x264-CLASSiC is 1080p BluRay
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Ignoring American.Horror.Story.S01.1080p.BluRay.DTS-HD.MA5.1.x264-JohnGalt based on required words filter: HDTV
2015-05-17 00:18:48 INFO SEARCHQUEUE-BACKLOG-250487 :: Quality of American.Horror.Story.S01.1080p.BluRay.DTS-HD.MA5.1.x264-JohnGalt is 1080p BluRay
2015-05-17 00:18:47 INFO SEARCHQUEUE-BACKLOG-250487 :: [BTN] :: Performing season pack search for American Horror Story
2015-05-17 00:18:45 INFO SEARCHQUEUE-BACKLOG-250487 :: Building internal name cache for American Horror Story
2015-05-17 00:18:45 INFO SEARCHQUEUE-BACKLOG-250487 :: No scene exceptions update needed
2015-05-17 00:18:45 INFO SEARCHQUEUE-BACKLOG-250487 :: Beginning backlog search for: [American Horror Story]

015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Downloading Suburgatory.S1.720p.HDTV.x264-BTN from BTN
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 248842 AND season in 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Quality of Suburgatory.S01.PROPER.HDTV.XviD-BTN is SDTV
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Quality of Suburgatory.S01.DVDRip.XviD-REWARD is SD DVD
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Quality of Suburgatory.S1.720p.HDTV.x264-BTN is HDTV
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Ignoring Suburgatory.S01.720p.WEB-DL.DD5.1.H.264-NFHD based on required words filter: x264
2015-05-17 00:36:19 INFO SEARCHQUEUE-BACKLOG-248842 :: Quality of Suburgatory.S01.720p.WEB-DL.DD5.1.H.264-NFHD is 720p WEB-DL
2015-05-17 00:36:18 INFO SEARCHQUEUE-BACKLOG-248842 :: [BTN] :: Performing season pack search for Suburgatory
2015-05-17 00:36:18 INFO SEARCHQUEUE-BACKLOG-248842 :: Building internal name cache for Suburgatory
2015-05-17 00:36:18 INFO SEARCHQUEUE-BACKLOG-248842 :: No scene exceptions update needed
2015-05-17 00:36:18 INFO SEARCHQUEUE-BACKLOG-248842 :: Beginning backlog search for: [Suburgatory]
2015-05-17 00:36:17 INFO Thread-155 :: Sending backlog for Suburgatory season 1 because some eps were set to wanted

**Comment by PhilJayJ** [comment] 2015-05-17 21:41
I'm experiencing this too. I'm trying to download everything in 720p HDTV but nothing I try works. I've tried the custom/HDTV quality setting and I've set required/ignored words but neither of these work.

Initially, Sickrage reports to have grabbed the correct file, but when I check my torrent client, it's actually downloading a WEB-DL, bluray, SD HDTV file - basically anything but 720p HDTV.

**Comment by miigotu** [comment] 2015-05-18 00:10
@Ockingshay Please put your logs on gist and remove them from your pists. Just put links to the log in the posts.

**Comment by nonissue** [comment] 2015-05-19 01:35
I'm having the same problem, and to add to this, after it failed and grabbed the 1080p bluray, I tried to do an individual episode search (marked as failed, include current quality in search), and instead of finding an individual episode, it re-added the 1080p full season torrent, so something weird is definitely happening.

**Comment by bitPhex** [comment] 2015-05-19 23:59
I'm not sure if this is a related issue, but I'm using BTN as my only search provider and initially, when the show first airs, it downloads the correct release, but the next day it will download multiple other versions even though I have the quality set to the 'HD' preset. 
It will also sometimes screw up the initially downloaded file, setting its file size to 0 bytes (Deleting all the data, but the useless file still remains) despite being set to use Hard-links.

**Comment by miigotu** [comment] 2015-05-20 00:41
@bitPhex First, you need to set your torrent client to download to one folder, and then move it to another folder, then have sickrage process the second folder. This will eliminated SR overwriting good files with incomplete ones.

The quality/wrong downloads is something i have been looking into.

**Comment by bitPhex** [comment] 2015-05-20 00:51
@miigotu I believe I have it setup correctly. Incomplete downloads are put in `M:\Torrents\Downloading` then moved to `M:\Torrents\seed\TV` when completed. SickRage monitors `M:\Torrents\seed\TV` for new downloads then renames and Hard-links to `M:\TV Shows`.

**Comment by miigotu** [comment] 2015-05-20 00:54
Then I don't see how the hard link can be 0b.

**Comment by bitPhex** [comment] 2015-05-20 01:09
@miigotu I don't think I have the logs anymore, but from what I can remember when it happened the first few times it gave an error along the lines of: `Hard link failed . . . File already exists . . . Copying instead.` Except it didn't copy, just destroyed the file leaving a 0b hard link in both locations, original and destination.

**Comment by 9935c101ab17a65** [comment] 2015-05-20 08:05
@bitPhex Doesn't sound like the same issue, I think it's probably best if you open a new issue.

**Comment by MrNightRyder** [comment] 2015-05-21 11:06
I second this that @bitPhex needs to make a new issue as it doesn't relate to this one.  I wish we could get some insight on the devs what they're doing about this seeing as to how this thread has been here already for 9 days and no comments on status or what their findings are.

**Comment by PhilJayJ** [comment] 2015-05-24 20:28
Is there any comment from the devs about this issue? It's been open nearly two weeks and there hasn't been a status update or comment on their findings.

**Comment by HamilcarH** [comment] 2015-05-27 12:48
I also have that issue with BTN and HDbits as providers.

**Comment by Ockingshay** [comment] 2015-05-29 21:26
This has crippled my sickrage now. I've had to turn backlog searches off as its downloading all weird and wonderful versions. 

Any update guys?

**Comment by miigotu** [comment] 2015-05-30 00:43
This is not a priority only because it requires a BTN/HDBits account to debug it, which I don't have. I can say that I don't have this problem with SCC and KAT.

**Comment by Ockingshay** [comment] 2015-05-30 06:27
Are there any other contributors with accounts? BTN is probably the biggest, most popular tv tracker out there. Unfortunately invites are near impossible for these sites, otherwise I would give you one.

**Comment by miigotu** [comment] 2015-05-30 14:30
I don't think any of the main contributors have BTN/HDBits. I'm not so sure your claim to biggest/most popular is true, lol. I don't even use my private trackers for TV atm, because none of mine are ratio-less, and most newly released TV can be gotten from public trackers just as fast as a private tracker.

**Comment by MrNightRyder** [comment] 2015-05-30 14:33
I'm going to be reaching out to the appropriate parties to see if something can be arranged for you as a developer for testing purposes.  because this really is a horrible bug that needs to be fixed

**Comment by Ockingshay** [comment] 2015-05-30 15:16
Thanks MrNightRyder, I too have asked staff for assistance.

**Comment by MrNightRyder** [comment] 2015-05-31 19:48
@miigotu what can we do to help debug this issue?  A number of us really want to see this fixed.  Also, might be worth mentioning that sonarr is working fine on BTN.  Perhaps could compare their code to yours to see what they're doing differently when the snatch is called upon by the python script.

**Comment by 9935c101ab17a65** [comment] 2015-05-31 19:54
Yah, if there's anything I can do with my BTN account, I'll do it (as long as it doesn't break the TOS).

**Comment by miigotu** [comment] 2015-05-31 21:52
@MrNightRyder @9935c101ab17a65 Not much you guys could do as I have to test, make a change, repeat over and over until i figure out wth is happenning lol. Ill try and eyeball it tomorrow again but its a shot in the dark.

**Comment by Ockingshay** [comment] 2015-06-02 15:47
I decided to test with Sickbeard and that seems to work fine. So as Sickrage (i believe) is a fork off Sickbeard are you able to use it's code to help troubleshoot this issue?

**Comment by Ockingshay** [comment] 2015-06-02 15:49
Also, would the logs from sickbeard help at all?

**Comment by Ockingshay** [comment] 2015-06-08 14:47
Any luck with this yet miigotu?

**Comment by miigotu** [comment] 2015-06-11 11:49
The more you do that, the more I ignore you. Its annoying, and when/if I find a problem and fix it you will know, without asking. Besides the point that it is not my responsibility to fix absolutely everything here, and I have not even attempted this one because I cannot reproduce it.

**Comment by Ockingshay** [comment] 2015-06-11 13:30
The reason why it's important to engage with the people that are having the issue is that it helps to speed up the troubleshooting. Now, as you have said that you cannot reproduce it i decided to try a fresh install of SickRage and it worked fine (perhaps the reason why you cannot reproduce it?). I have had SickRage installed for many months, and so something in the latest update at the time of me creating this issue has broken it. That is some more pertinent information gleamed from your simple reply and helps narrow down the commit that started the issue. 

Please though accept my apology, I must not yet understand GtHub etiquette.. for assuming a named collaborator who responds to an issue would want to take on the responsibility of collecting the data and fixing the issue.

It's the sun, i get carried away...

**Comment by miigotu** [comment] 2015-06-11 16:16
Its np, but once the issue is submitted we have a list of open things to address, we add information to each issue as it comes, when that issue becomes the top priority. Every time someone posts something new in an issue we get notifications about it and it just gets tiring with nothing but 'how's it going?' when all the information we have is already in the issue comments we made previously.

**Comment by nonissue** [comment] 2015-06-12 15:47
Was this actually fixed or is a clean install the recommended solution? Not sure why it was closed.

**Comment by Ockingshay** [comment] 2015-06-14 10:19
The tone and sarcasm of my comment was lost on miigotu, so i simply closed the issue. In answer to your question nonissue, a clean install fixed it. I tried restoring a backup of my db to a clean install of SR and it still exhibited the same issue, so there is some sort of corruption in my db that was caused by a recent update. This is unlikely to get fixed with the current collaborator's attitude, so i simply recommend starting again.

Fortunately its pretty quick to re-add everything....good luck!

**Comment by Ockingshay** [comment] 2015-06-14 16:35
Looks like it isn't actually fixed. Single episodes download fine on backlog searches, but season searches still download the wrong .torrent file.........very, very boring indeed!

**Comment by Ockingshay** [comment] 2015-06-14 16:37
2015-06-14 17:13:29 INFO     SEARCHQUEUE-BACKLOG-260449 :: Downloading Vikings.S03.1080p.WEB-DL.DD5.1.H.264-BS from BTN
2015-06-14 17:13:29 INFO     SEARCHQUEUE-BACKLOG-260449 :: Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!
2015-06-14 17:13:29 INFO     SEARCHQUEUE-BACKLOG-260449 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = 260449 AND season in  3,3,3,3]
2015-06-14 17:13:29 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.HDTV.x264-BTN is SDTV
2015-06-14 17:13:28 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.720p.HDTV.x264-KILLERS is HDTV
2015-06-14 17:13:28 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.1080i.HDTV.DD5.1.MPEG2-M0ar is RawHD
2015-06-14 17:13:28 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.720p.WEB-DL.DD5.1.H.264-BS is 720p WEB-DL
2015-06-14 17:13:27 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.1080p.AMZN.WEBRip.AAC2.0.H.264-PPKORE is 1080p WEB-DL
2015-06-14 17:13:26 INFO     SEARCHQUEUE-BACKLOG-260449 :: Quality of Vikings.S03.1080p.WEB-DL.DD5.1.H.264-BS is 1080p WEB-DL
2015-06-14 17:13:25 INFO     SEARCHQUEUE-BACKLOG-260449 :: [BTN] :: Performing season pack search for Vikings

**Comment by Ockingshay** [comment] 2015-06-14 18:13
for those with the issue, what method are you using to handle Torrent search results? I had mine set to push direct to Transmission, but i decided to re-run it using the blackhole method and every .torrent file downloaded correctly! If i then add the torrent file manually to transmission it also picks it up correctly!

**Comment by miigotu** [comment] 2015-06-14 19:19
Full log is more helpful here. Are you saying it gets the right torrent when using black-hole but not using transmission api?  I use black-hole.

**Comment by miigotu** [comment] 2015-06-14 19:20
BTW: You can can set transmission to autoload torrent files from a directory to automate black hole.

**Comment by Ockingshay** [comment] 2015-06-14 19:21
it seems so, but i've exceeded my backlog attempts for today at BTN, so cannot prove it yet. I want to re-introduce transmission but with the torrents added paused and compare.

**Comment by Ockingshay** [comment] 2015-06-14 19:27
Just run it again now and yeah, it seems to be if Sickrage sends it direct to Transmission it loads the wrong torrent file.

**Comment by Ockingshay** [comment] 2015-06-14 19:29
![transmission](https://cloud.githubusercontent.com/assets/5208756/8150106/189e9fb8-12d4-11e5-949e-54f88b805ff0.jpg)

**Comment by Ockingshay** [comment] 2015-06-14 19:30
I'll use blackhole for the time being.

**Comment by miigotu** [comment] 2015-06-14 19:35
If it works via blackhole properly, we know where to look for the problem. Verify for sure 100% it works in black hole correctly and I'll dig into it.

**Comment by Ockingshay** [comment] 2015-06-14 19:42
yeah, i can confirm enabling transmission's watchdir and using SR with blackhole works fine.

**Comment by Ockingshay** [comment] 2015-06-14 19:49
https://github.com/SiCKRAGETV/sickrage-issues/issues/1736

jyggen also appears to be using transmission looking at his log:

2015-06-01 11:31:13 DEBUG    SEARCHQUEUE-BACKLOG-269641 :: Transmission: Response to POST request is {"arguments":{"torrent-added":{"hashString":"130669055ab65f0d624cbd2fa48d8770ecdd1a6a","id":235,"name":"Chicago.PD.S01.NTSC.DVDR-SCC"}},"result":"success"}

**Comment by miigotu** [comment] 2015-06-14 20:10
Damn, Chicago.PD.S01.NTSC.DVDR-SCC is not on SCC now?

**Comment by Ockingshay** [comment] 2015-06-14 20:12
dunno, i don't use SCC, but as long as you have SR load to transmission it fails on every torrent for me.

**Comment by miigotu** [comment] 2015-06-14 20:14
Yes, but I have to totally reconfigure my transmission-daemon to do that x.X

Maybe I can use transmission directly on one of my clients for testing.

**Comment by Ockingshay** [comment] 2015-06-14 20:17
I run them both in dockers. perhaps run them both on a local windows pc?

**Comment by miigotu** [comment] 2015-06-14 20:18
Linux =P

**Comment by PhilJayJ** [comment] 2015-06-14 22:33
I'm running ruTorrent through a seedbox. I was originally sending my torrent files to ruTorrent, but I've changed this to blackhole and it looks to be working. I've tested season packs and individual episodes and they've all downloaded OK.

**Comment by miigotu** [comment] 2015-06-14 22:48
@PhilJayJ that's good news, at least we have a way for people to DL the correct item until this can be investigated further.

**Comment by miigotu** [comment] 2015-06-14 22:59
If anyone sees another issue related to this, closed or not, please reference this issue from there, and let them know about the temporary workaround using blackhole

**Comment by miigotu** [comment] 2015-06-14 23:30
Can anyone test sickbeard index using official sickbeard and give me the search urls from the log?

For now it seems backlog search is also searching the same as daily, then searching for the episode with another request.

**Comment by Messiadbunny** [comment] 2015-06-17 16:21
Yup, can confirm the same happens for me.  It seems to pull the proper URL every time but once SickRage grabs the hash that is always incorrect.  I fiddled with the code for a while but I can't make heads or tails of what's causing it to pull the wrong torrent file in the end.

**Comment by miigotu** [comment] 2015-06-17 16:54
@Messiadbunny To avoid confusion, let's try not to use the word 'proper' to describe urls/torrents/nzb's/files/etc unless we are talking about a "PROPER" =P

result.content is supposed to be a torrent file, loaded into memory.

I did notice there it says .startswith('magnet') should also check for or .endswith('.torrent') as result.url could also be a link to a torrent file.

I will get around to fixing this. But it has not been top priority since blackhole works fine and other issues have no workaround. I have just been overwhelmed fixing multiple issues, as there hasn't been very much collaborator activity lately.

**Comment by miigotu** [comment] 2015-06-26 01:36
@Ockingshay @MrNightRyder @PhilJayJ @nonissue @bitPhex @Messiadbunny

Can you guys check this in newest master or dev?

**Comment by Messiadbunny** [comment] 2015-06-26 07:46
Seems to work fine for me now, thanks.

**Closed** 2015-06-26 17:51 UTC
Labels: 1: Bug / issue, 3: Fix

**Comment by mtosic** [comment] 2015-06-30 07:38
I also have an issue. Have BTN and uTorrent as torrent client. Have an season search preference.
When I choose True Detective 720 web-dl, it just downloads 1080p AVC Season 1. It is the same for the show "The Fall".

**Comment by hennning** [comment] 2015-07-11 20:15
I have the same issue on Freenas 9.3 with Sickrage plugin installed, version BRANCH: (master) / COMMIT: (25649f25806373d1a70608add3c00d1d371b71bf) 
Downloading S04 of Homeland tells me it downloads a 720p version from DON but in fact it downloads a 1080p FLAC version.
