### ISSUE TITLE
[Feature Request] Manual Search: let user choose what to download

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#989] opened 2015-03-18 13:13 UTC
When clicking on the search button next to a episode, it would be cool if we could choose auto search or manual search which would allow us to choose which release we want. This would be the most beneficial with Anime but would also be practical with normal TV shows. The manual search could return only X number of results (maybe defined by the number of seeders for torrents and number of grabs for nzb). Also it would show all qualities in case the quality set for the show is unavailable.

**Comment by midasvo** [comment] 2015-03-18 16:27
I kind of agree with the sense that a manual search would be preferable as a fall-back in sickrage. However I would implement a box where a magnet url could be pasted if sickrage really can't find the ep you see before you. Thoughts?

**Comment by suprdave23** [comment] 2015-03-19 01:27
It should do it similar to the way Sonarr currently does manual searches. I *really* liked that feature. Example: https://forums.sonarr.tv/uploads/default/1132/bf5106162312be63.png

**Comment by fernandog** [comment] 2015-03-19 01:38
@suprdave23 IMO It misses the point of automation.

**Comment by saitoh183** [comment] 2015-03-19 01:43
Automation is great but its never 100% without error. A manual scan just allows an alternative for the cases where no matter how many times you click auto scan it fails to retrieve the desired file.

**Comment by fernandog** [comment] 2015-03-19 01:55
https://github.com/SiCKRAGETV/sickrage-issues/issues/833

**Comment by fernandog** [comment] 2015-03-19 01:57
@saitoh183 mine is 100% auto. isn't a provider issue? Maybe you need a good provider

**Comment by saitoh183** [comment] 2015-03-19 02:10
I have many providers but this is more a issue when your looking for older stuff.. new stuff is no problem and doesnt need this function but try to pick up stuff like the Wire with automation can be a pain

**Comment by hennning** [comment] 2015-08-04 14:45
This is a feature I really welcome.
It would help a lot for users that are dependent on subtitles. Not all releases gets subtitles and definitely not to all kinds of different languages.

An example: I've downloaded S03 of House of Cards from SR. It chooses a -DEMAND release for the whole season. Everything was fine until E04 where the subtitle for DEMAND was off by a few seconds. When investigating I found out that the -2HD release seems more reliable for subs for that show. Therefore I want to choose to download the -2HD release instead of the -DEMAND release for S04. In Sonarr that's as easy as a click of a button.

I could do this manually from my torrent provider but it would be so much easier to just handle everything from SR. Also I often just use my small mobile screen to manage my downloads when I'm on the road. And managing and fixing small errors like this from one place would be great.

**Comment by WebSpider** [comment] 2015-08-05 05:35
Thanks for the +1. Being vocal about which suggestions you like helps us prioritize!

**Comment by fernandog** [comment] 2015-09-25 09:03
@SiCKRAGETV/moderators 

We can make this using providers rss cache. We wont need to request any information to providers as everything is in cache.db

But not all providers has a working RSS. I think there is a issue adding results to cache. Only rarbg has all parsed cache items in cache.db

**Comment by fernandog** [comment] 2015-09-25 09:09
This is a good feature to check available qualities. For example you set bluray but only webdl is available now.

**Comment by fernandog** [comment] 2015-09-25 09:20
@miigotu what is this IGNORE? It wont insert if any data is null? What is the setting to keep cache items not being deleted or increase time to delete it? Didnt understand what it does (ignore) even searching for it.

```
            logger.log(u"Added RSS item: [" + name + "] to cache: [" + self.providerID + "]", logger.DEBUG)

            return [
                "INSERT OR IGNORE INTO [" + self.providerID + "] (name, season, episodes, indexerid, url, time, quality, release_group, version) VALUES (?,?,?,?,?,?,?,?,?)",
                [name, season, episodeText, parse_result.show.indexerid, url, curTimestamp, quality, release_group, version]]

```

**Comment by WebSpider** [comment] 2015-09-25 09:24
We indeed have some information available in cache.db to build at least the gui for this. 

Also we would need to introduce something like a forced snatch, and need to think about what to present: What about quality settings for the show, minseed/minleech: Do we honor them, or do we allow the user to override and download anything, which would also mean adjustments to the postprocessor 

-----Original Message-----

**Comment by OmgImAlexis** [comment] 2015-09-25 09:26
@WebSpider I'm pretty sure if a user downloads a crappy copy it'll still process as I manually add SDTV copies to shows even if I have them set to only 720p and 1080p, SR seems fine with them.

**Comment by hennning** [comment] 2015-09-25 09:29
How does Couchpotato handle this? They have a working manual search towards all trackers. 

Now I'm not a programmer. But I know SR does a search for all available qualities for the specified episode. Then matches them with the quality that's been chosen. 

Why not just allow this: 
When a user presses the "manual download" button search for all available releases. Then print them out on the screen with a download button next to each release. When the user presses any of the buttons change the filter to match that exact release. 

It seems to me that you already have most of the functionality in the system. Just need to implement it and create an ui around it.

**Comment by fernandog** [comment] 2015-09-25 09:30
I would start simple. A simple button in displayShow that shows JS window with all info from cache.db

**Comment by WebSpider** [comment] 2015-09-25 09:31
Ok, then I need to look into some behavior I have as a bug. I have some episodes that don't get postprocessed due to quality unknown.

-----Original Message-----

**Comment by fernandog** [comment] 2015-09-25 09:33
@WebSpider wrong issue reply?

**Comment by OmgImAlexis** [comment] 2015-09-25 09:34
@fernandog that was a reply to what I said.

**Comment by fernandog** [comment] 2015-09-25 10:09
We should not clear cache or at least only delete cache older than x days

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tvcache.py#L118

**Comment by WebSpider** [comment] 2015-09-25 10:48
I propose we add an argument to _clearCache, being the amount of hours we want to keep the cache, defaulting to 0. Doesn't break existing code, and we get more granular cache management.

-----Original Message-----

**Comment by fernandog** [comment] 2015-09-25 11:04
and we can easily implement this feature. Its only UI stuff

**Comment by miigotu** [comment] 2015-09-25 16:57
Please fix stuff before we add stuff -.-

@fernandog we need feathub

**Comment by fernandog** [comment] 2015-09-25 17:10
Lol
Mako was implemented with 30 issues open.
We have really old issues. If I knew how to fix I would fix it. Im not expert. 
Just check age of issues in 'OPEN ISSUES' link at 'ISSUE STATS'

We have new features everyday like new API or new common classes from @MGaetan89 and I dont hear complains. But its ok

**Comment by miigotu** [comment] 2015-09-25 17:13
Thats not a new feature what MGaetan is doing. It is a refactor. Sometimes a bug appears because of the refactor and needs fixed, so we make sure it gets fixed.

We have always had an api and an api builder. Parts of it were broken. Rewriting something that already exists because it is buggy is not a new feature.

**Comment by fernandog** [comment] 2015-09-25 17:19
Ok.
So no more features. Only bug fixes:

One very hight priority still open:
https://github.com/SiCKRAGETV/sickrage-issues/issues/2402

54 issues
https://github.com/SiCKRAGETV/sickrage-issues/issues?q=is%3Aopen+is%3Aissue+-label%3A"1%3A+Feature+request"+-label%3A"1%3A+Support+%2F+question"+-label%3A"3%3A+Fix"+-label%3A"3%3A+Unconfirmed"+label%3A"1%3A+Bug+%2F+issue"

20 low priority

I check all that issues. Dont know how to fix them.
Issues I know I PR.

**Comment by miigotu** [comment] 2015-09-25 17:26
#2402 More than half of that is a false positive, and only a problem if user/pass is not set for SR, and is accessible from the net, and is attacked. There are 0 reports of any attacks actually happenning.
The solution is simply form and url validation, which @OmgImAlexis will do after the js is finished refactor (which needs done before the validation)

Your link doesnt work here. This does.
https://github.com/SiCKRAGETV/sickrage-issues/issues?q=is%3Aopen+is%3Aissue+-label%3A%221%3A+Feature+request%22+-label%3A%221%3A+Support+%2F+question%22+-label%3A%223%3A+Fix%22+label%3A%221%3A+Bug+%2F+issue%22

**Comment by MGaetan89** [comment] 2015-09-25 17:26
If we have to focus on bug-fix, maybe we could have a `feature` branch where new feature can be submitted?
This new branch will have to be in sync with develop. Once we have fix all of the (or the critical) bugs, we can merge `feature` in `develop` and close it.
I understand the new of stability, but is it worth stopping potential contributions?

**Comment by miigotu** [comment] 2015-09-25 17:28
Potential contributions are fine, but redirecting @miigotu, @MGaetan89 @WebSpider or @OmgImAlexis from their current tasks is not.

**Comment by OmgImAlexis** [comment] 2015-09-26 14:00
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Closed by OmgImAlexis** 2015-09-26 14:00 UTC
Labels: 1: Feature request
