### ISSUE TITLE
Add'l watchlist providers, necessary branches included

### ISSUE THREAD

**Issue by georgeh12** [SiCKRAGETV/sickrage-issues#345] opened 2015-01-06 04:34 UTC
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
Windows 8.1
Python Version: 2.7 (r27:82525, Jul 4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]

What you did: Searched interface for options to connect watchlists (Trakt.tv, IMDB, Flixster)
What happened: Only a Trakt.tv option available for watchlists
What you expected: I would still like to see a few more options including IMDB and Flixster. I think I heard tvRage & TVDB also has similar features, mentioned here: https://sickrage.tv/forums/forum/main-category/feature-requests/1021-autoadd-show-from-tvdb-favorites-feature

**Comment by markheloking** [comment] 2015-01-06 10:22
Exact duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/343? (But changed a few words around). Anyway: IMDB is already a requested feature, please open a new feature request for Flixster.

**Closed by markheloking** 2015-01-06 10:22 UTC
