### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by topper2830** [SiCKRAGETV/sickrage-issues#1208] opened 2015-04-13 05:52 UTC
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Rarbg Too many requests per minute.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment] 2015-04-13 06:52
Duplicate of issue https://github.com/SiCKRAGETV/sickrage-issues/issues/1159

**Closed by Thraxis** 2015-04-13 06:52 UTC
Labels: 5: Duplicate
