### ISSUE TITLE
History page don't work when changing limit

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2928] opened 2015-09-23 17:37 UTC
When trying to set a limit on the history page ,it doesnt set refreshes the page and sets the limit back to 100 with following error
```
AAAttributeError: 'History' object has no attribute '${sbRoot}/history'
AA    method = getattr(self, route)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 257, in get
```

@MGaetan89

**Comment by MGaetan89** [comment] 2015-09-23 17:45
I don't have that issue. It works fine for me

**Comment by fernandog** [comment] 2015-09-23 20:50
mine don't work either. I'm redirected to my default page (comingEpisodes)

**Comment by WebSpider** [comment] 2015-09-23 21:32
Which release does this bug exist in?

**Comment by WebSpider** [comment] 2015-09-23 21:41
Duplicate of #2881 also created by @duramato

**Comment by fernandog** [comment] 2015-09-23 21:42
Different issue

**Comment by duramato** [comment] 2015-09-23 21:52
@WebSpider no ,that one is for the saving of limit while this one is the limit not working at all

**Comment by OmgImAlexis** [comment] 2015-09-24 13:57
Does this fix it? https://github.com/SiCKRAGETV/SickRage/pull/2587

**Comment by fernandog** [comment] 2015-09-24 14:15
Now its working! Thanks

**Closed** 2015-09-24 14:45 UTC
Labels: 1: Bug / issue, 3: Confirmed

**Comment by duramato** [comment] 2015-09-24 19:19
@fernandog &  @OmgImAlexis  still not working for me

**Comment by OmgImAlexis** [comment] 2015-09-25 01:30
@duramato have you updated? I don't have an issues at all on my dev install.

**Comment by fernandog** [comment] 2015-09-25 01:31
PR another fix to history limit. now it will save setting on change

**Comment by duramato** [comment] 2015-09-25 10:03
@fernandog & @OmgImAlexis its now fixed ,but it was fernandog pr who fixed not yours :P

**Comment by fernandog** [comment] 2015-09-25 10:07
@OmgImAlexis fixed the JS issue loading the URL.
