### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/share/MD0_DATA/Download/complete/tv/_UNPACK_Covert.Affairs.S05E06.720p.WEB-DL.DD5.1.H.264-NTb/Covert.Affairs.S05E06.Embassy.Row.720p.WEB-DL.DD5.1.H.264-NTb.mkv'

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#724] opened 2015-02-22 13:51 UTC
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) 
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@652c9f33f92b3c74c0256bb3aafae5e8dc014c89
### ERROR
```
POSTPROCESSER :: Unable to move file /share/MD0_DATA/Download/complete/tv/_UNPACK_Covert.Affairs.S05E06.720p.WEB-DL.DD5.1.H.264-NTb/Covert.Affairs.S05E06.Embassy.Row.720p.WEB-DL.DD5.1.H.264-NTb.mkv to /share/Multimedia/TV/Covert Affairs/Season 05/S05E06 - Embassy Row.mkv: [Errno 2] No such file or directory: '/share/MD0_DATA/Download/complete/tv/_UNPACK_Covert.Affairs.S05E06.720p.WEB-DL.DD5.1.H.264-NTb/Covert.Affairs.S05E06.Embassy.Row.720p.WEB-DL.DD5.1.H.264-NTb.mkv'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TehWardy** [comment] 2015-02-22 13:53
This is an interesting one ... when un-packing the prefis _UNPACK_ is applied by SR ... for some reason it's trying to post process files its unpacking (sometimes) I haven't determined a pattern for this yet.

Some sort of race condition perhaps?

**Comment by TehWardy** [comment] 2015-02-22 13:55
I hope you guys don't mind all these bug reports ... I'm going out of my way to test the crap out of SR whilst It rebuilds a library I previously lost due to a nas failure.
I'm having SR generate download queues of around 1TB so it feels like this is a sort of extreme case of it's use compared most normal situations.

Makes for a good set of test scenarios though don't you think?

**Comment by neoatomic** [comment] 2015-02-22 15:04
@TehWardy 
Testing and reporting errors is always a good thing so keep up the good work.

Just make sure that its a Sickrage problem before submitting, otherwise the developers are using up a lot of precious time for non Sickrage problems.
Also provide as much info as you can, and as clear as you can. It makes locating the problem a lot faster.

**Comment by fernandog** [comment] 2015-02-23 10:33
@TehWardy 

/share/Multimedia/
/share/MD0_DATA/

are on different HDDs/partition? can you give full details of that (filesystem, permissions, etc)

**Comment by TehWardy** [comment] 2015-02-23 11:26
What I have is basically a 2 year old version of this ...
https://www.qnap.com/i/uk/product/model.php?II=107
Mines a slightly different model but the underlying architecture hasn't changed.
Its a linux based box with a single raid 5 volume that spans the full space on all 5 drives.

The volume then has shares configured which results in a folder being created on the volume (again spanning all 5 drives).
The shares show up as windows shares on my local LAN. 

On the same box I have SR and SAB setup, then on another box I have uTorrent setup.
both sab and uTorrent have their own temp folders for downloads they are working on, when downloads are completed they are moved from their temp folders in to the complete folder that SR monitors.

From there post processing occurs.

Under the bonnet I can see that if I ssh in to the box linux appears to have mounted each drive as a "folder" at root level (as I understand linux definition of a  folder anyway) the folders are then linked in to a single file system object somehow by the raid management software that handles exactly what parts of what files go where for me. 

That single folder that spans all the drives is referred to as "/share/" under which everything is stored except the OS.

 The OS runs on a separate micro ssd drive embedded on to the mobo.

There is only 1 user configured on the box ... the global admin account under which everything runs and this user total full control rights on everything.
All apps and services on the box also run under this account.

I could change this but decided that for the purpose of working with you guys it made sense to not add security as a further potential problem.

Not that i can see it making any difference but the volume is a total of 15TB as each drive is 3TB, less a bit for the RAID 5 redundancy the reality checks in around 11TB.

To ensure I took any further "issues" out of the potential SR pot for now I have stopped running uTorrent on the other box leaving only SR and SAB running together with their global admin rights locally on the nas.

SAB is basically acting as a download mule purely for SR right now.

**Comment by TehWardy** [comment] 2015-02-23 11:30
Quite a few of the errors like this that I see come up appear to be where the file "did" exist but no longer exists because SR already moved it.
SR appears to be confusing itself by taking actions on files (like moving them) then thinking it hasn't taken that action.

I can see that by looking through the destination location the file was moved and named correctly. 

I also noted that some of the errors like this are where SR is trying to move files that have the prefix "_UNPACK_" applied which SR often notes in the log file "i'll ignore this for now as it's being unpacked" then later throws an error trying to do stuff with the folder. 

Both scenarios appear to be intermittent ... perhaps some sort of threading / race condition type issue is occurring (would be my guess but I don't know python)?

**Comment by fernandog** [comment] 2015-02-23 11:36
@TagForce could you help us here please?

**Comment by TehWardy** [comment] 2015-02-23 12:04
Looking at the files I just flushed out I've noticed that sometimes SAB appears to stall / have issues during the unpack process ... it might be that where I have sab doing unpacking SR uses the same naming convention, sees the folder and is trying to do something with it too but ends up getting rejected by the OS due to file locks that SAB has.

I guess this feeds my theory that there may be some sort of race condition but that the condition is occurring between applications rather than within SR itself.

Maybe the way forward is to tell SR to ignore a folder labelled "_UNPACK_" entirely unless it was created by SR.
Where I have have post processing running on schedule it may be that over time when SAB finally sorts itself out the issue will go away as SAB will then remove the "_UNPACK_" tag.

I also wonder if perhaps that stalling in SAB might be caused by SR trying to do something too?

Lots of guessing going on here.

**Comment by TagForce** [comment] 2015-02-23 15:52
@fernandog @TehWardy Looking at this (and many other similar issues) where SR tries to move files it's already deleted. I've been away from the computer for the weekend (the kid wanted to see all his grandparents, and you don't say no to a sweet 3-year-old with big puppy eyes), so haven't gotten really far yet.

As far as I can tell it should ignore folders that start with _UNPACK:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/processTV.py#L245

Which is called here:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/processTV.py#L184

I'm trying to reproduce the error

**Comment by fernandog** [comment] 2015-02-23 15:55
I undestand that he's using SAB PP and SR PP. Is it possible to use both - at least the unrar part ?

**Comment by TagForce** [comment] 2015-02-23 16:05
Yes, you can use both. SR should ignore _UNPACK folders anyway, so it should never be an issue... Don't know why it is, atm.

**Comment by TehWardy** [comment] 2015-02-23 17:04
It may just be that im effectively "double unpacking" or something causing a clash

**Comment by TagForce** [comment] 2015-02-23 19:35
No, SR should ignore folders starting with _UNPACK, so you should never be double unpacking.
Unable to move file /share/MD0_DATA/Download/complete/tv/_UNPACK_Covert.Affairs.S05E06.720p.WEB-DL.DD5.1.H.264-NTb/Covert.Affairs.S05E06.Embassy.Row.720p.WEB-DL.DD5.1.H.264-NTb.mkv should not be a possible error, since it should never ever even try to move any file in that folder.

And I can't find why it would do that anyway... I'll get it eventually.

**Comment by TagForce** [comment] 2015-02-26 09:24
@TehWardy Can you update to the latest dev and see if it's fixed now?
Same goes for other PP issues you submitted. Test and let us know if it's fixed.

**Closed** 2015-02-27 19:42 UTC
Labels: 1: Bug / issue, 2: High Priority, 3: Confirmed, 3: Fix
