### ISSUE TITLE
Memory resources maxed out on Synology

### ISSUE THREAD

**Issue by theCheek** [SiCKRAGETV/sickrage-issues#2755] opened 2015-09-11 09:07 UTC
Branch : Master
Commit hash: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd) 
Your operating system and python version: Synology DSM 5.2-5592
What you did: Logged into DSM to investigate why services are not responding
What happened: Saw memory resources of python running at 95%
What you expected: Memory resources to be around 10-20%, like in SickBeard.
Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/theCheek/565afa9651f020b3c5ba#file-srlog

I have recently installed SickRage on my Synology DS2411, and have noticed a huge spike in Memory usage, so much so that I sometimes have to stop and restart SickRage to even access the GUI.

Perhaps it is something to do with the sheer number of shows added, but I thought that with the queing system this would not be a problem.

The error occurs when no shows are waiting to be added to the database, and usually during a backlog search (I think).

Any help much appreciated.

**Comment by neoatomic** [comment] 2015-09-12 14:01
Try to rename/remove the cache folder so that SickRage can build a fresh one.

**Comment by WebSpider** [comment] 2015-09-12 15:49
After you have removed the complete cache folder, be sure to run a full update on all shows, as your image cache will also be gone.

**Comment by theCheek** [comment] 2015-09-14 08:37
I'm travelling atm but will try this when i return on the weekend.

To clarify where is the cache folder usually located? 

Many thanks,
tc

**Comment by WebSpider** [comment] 2015-09-14 09:29
On syno it's in /usr/local/sickrage/var/cache

-----Original Message-----

**Comment by richard5mith** [comment] 2015-09-16 13:53
This is happening to me as well. Been using Sickrage for a few months without a problem, but now it can't last a day before seemingly taking over my whole box. Crashing either itself or Plex in the process.

I have tried clearing the cache folder as suggested here, but it's made no difference.

**Comment by WebSpider** [comment] 2015-09-16 14:54
Richard, are you also running on syno 24xx?
If not, can you please add all details as if you were opening a new issue?

Thanks!

-----Original Message-----

**Comment by deathnite** [comment] 2015-09-17 12:13
Posted  #2840 with same issues

**Comment by deathnite** [comment] 2015-09-17 13:56
Branch: Master
Commit hash: b7edb8a61473b140f002bea11174af47ab738bbb
Your operating system and python version: DSM 5.2-5592 Update 4 / 2.7.10-14
What you did: Copied files and folder structure from existing DS1512+ to new DS412+.
Installed Sickrage package and commenced adding shows with same naming settings.
What happened:
At idle the 'python' process sleeps at 78.1 MB
After about 8 shows imported the resource monitor shows the 'python' process at about 25% CPU and memory usage starting around 78MB and increases rapidly to over 750MB before the system becomes unstable.
Also performing Manual Post-Processing also results in the same behavior of increases rapidly to over 750MB before the system becomes unstable.
Stopping/Starting the Sickrage package is the only way gain stability

What you expected
Link to a copy/paste of your logfile with clear debug info of the error on GIST
https://gist.github.com/deathnite/85d03becc058afa8e188

My DS1512+ on Commit Hash b7edb8a61473b140f002bea11174af47ab738bbb is not exhibiting these same issues

**Comment by neoatomic** [comment] 2015-09-17 13:57
Running a Synology 415+ myself, dont have any issues.
If removing the cache folder doesn't work, then the only other thing i can think of is that your files/episodes dont have correct `quality` names in the title, so that SickRage does an in-dept scan to see what the quality is. And therefore the memory spike occurs.

https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-names-to-recognize-the-quality-of-a-file

**Comment by richard5mith** [comment] 2015-09-17 14:04
Is it doing that deep-scan on already downloaded shows, or newly downloaded shows in the post-processing folder?

Been running this for a while without any problems, so none of my existing shows have suddenly changed names. I guess it could be something stuck in my download folder, but I've seen that post-processing run manually without any problems as well.

**Comment by deathnite** [comment] 2015-09-17 14:07
Just tested that theory via manual post-processing
Single file with correct labeling WITHOUT correct quality and memory increased rapidly to over 750MB before the system becomes unstable.
Same Single file with correct labeling WITH correct quality and imported without error or memory spike

**Comment by deathnite** [comment] 2015-09-17 14:08
note - Sickbeard would import with UNKNOWN quality tag.

**Comment by richard5mith** [comment] 2015-09-17 14:11
Interesting. Well then I think I'll be going home tonight and making sure that my downloads folder is empty of all items which may have been hanging around in there a while and are stuck for whatever reason.

**Comment by theCheek** [comment] 2015-09-17 14:12
Sounds like this could very well be the culprit. As I have moved over from sickbeard, my shows are mostly named based on those settings in which I never told it to rename with quality! So yes it probably is doing the deep scan. 

I read the link but it did not mention how the deep scan works. Is it actually analysing the video file itself? If so then certainly this would hog all the resources! 

I wish I could test it but as I say I'm away until tomorrow evening.

**Comment by neoatomic** [comment] 2015-09-17 15:00
@theCheek The scan just checks the meta-data of the file. Specifically the resolution of the video.
However that check should only take a split second and not consume any notable recourses. 
So i dont have an explanation why its behaving like that. Could you extract the meta data of any of those files and post it here.? 

@miigotu Do you have any idea whats happening here.?

**Comment by richard5mith** [comment] 2015-09-19 10:07
I emptied my downloaded folder, then downloaded one show. It post-processed it, because the folder is empty again and the download has been moved to the right place, but then the process ran away with itself...

sickrage S    2725m274.7  0.0 /usr/local/sickrage/env/bin/python /usr/local/sickrage/var/SickRage/SickBeard.py

2.7GB virtual size, and 247% CPU usage. Had to kill it before it took down the box again.

**Comment by WebSpider** [comment] 2015-09-19 11:45
I'd love to find a good python memory profile, to see which part of the program is taking up the memory.

Since I have a syno myself, and am hit with the problem, it's easy to reproduce, but I haven't found the right tool to nip it in the butt!

-----Original Message-----

**Comment by richard5mith** [comment] 2015-09-19 11:54
Use strace -p on the process to see if it's getting stuck somewhere?

**Comment by WebSpider** [comment] 2015-09-19 13:35
That wont reveal what's going on inside SR unfortunately. 

Also, it isn't stuck, it's using so much memory that swapping occurs, which slows down the syno.

At least on my syno, that is.

-----Original Message-----

**Comment by richard5mith** [comment] 2015-09-19 17:16
I come from a perl rather than python background, and strace can often be useful to see what's going on. If the script is constantly doing the same file io or network io and getting stuck in a loop doing so, that's the kind of thing that can often cause a memory leak and result in what we're seeing here. It won't tell you where in the code it's happening, but you can often work that out from the system calls that are being made.

**Comment by richard5mith** [comment] 2015-09-21 17:08
I did the strace. It's stuck doing a setuid operation over and over and over again.

**Comment by miigotu** [comment] 2015-09-21 17:37
@richard5mith Stop SR, and then in sickbeard/helpers.py find `def chmodAsParent(childPath):` around line 747, and just after that add a return, so it looks like this: (4 spaces before return)

```python
def chmodAsParent(childPath):
    return
````

Start SR and see if that fixes the problem.

**Comment by richard5mith** [comment] 2015-09-21 20:12
Nope. Same. On startup it actually immediately went into high memory mode.

**Comment by forza11** [comment] 2015-09-28 09:47
By request, information from other ticket merged into this one: 
Difference with the OP is that my memory usage is normal, it's just the CPU that's maxed out.

Issue:

SR: BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) 
DSM 5.2-5592 Update 3

I moved from Sickbeard-Custom to Sickrage about a month ago. Not a migration, i just started from scratch. Ever since I did that the CPU load from my Synology 413j is constantly maxed out, the python process uses everything available (so it seems). 

important to mention:
- No searchers are active
- CPU throttling doesn't make a difference
- By disabling Sickrage while Couchpotato is enabled, the process load returns to normal
- By disabling Couchpotato (other app using python) while Sickrage is enabled, it remains maxed out.

I'm not sure where to look for a cause so any help is welcome.

Log after reboot/update: https://gist.github.com/forza11/ebdfb7d452686a6c9b5f

CPU load from a day
![sickrage](https://cloud.githubusercontent.com/assets/4203947/10084522/2d00b97a-6304-11e5-8500-6ae0983894b3.png)

**Comment by forza11** [comment] 2015-09-28 10:26
I disabled subtitle search and that seems to be the cause, i did an update immediately after and for some reason I can't enable it so i'm not 100% if it was the subtitle searcher or if it was due to the update... I will try

**Comment by Steggl** [comment] 2015-09-29 09:55
After reading this yesterday I turned off subtitle search and indeed SR behaves now. Seems like this feature is buggy.

**Comment by WebSpider** [comment] 2015-09-29 10:03
Can you let us know which syno you have?

We're almost completely relying on external libraries (subliminal and guessit) for subtitles, so I'd like to know if this is platform dependant, or library related...

-----Original Message-----

**Comment by Steggl** [comment] 2015-09-29 10:37
![syno](https://cloud.githubusercontent.com/assets/6247140/10161797/d11aacd2-66a6-11e5-8fc7-1b4715eea706.JPG)

That's my system.

**Comment by facos86** [comment] 2015-09-30 12:54
Hi,
I am experiencing the same problem of memory jumping to more than 90%. 
I cleaned the cache, and deactivated the subtitle module. Same problem.
My hardware ;
Synology NAS DS213j / 1,2 GHz / 500 Mo Ram.
DSM 5.2-5592 Update 4

**Comment by rspenc29** [comment] 2015-10-09 13:34
I had a problem when initially setting up sickrage and importing my ~60 shows. The RAM would spike to max then start swapping and everything would become unresponsive and I would have to kill the process and start over. After a few attempts, I checked the log files and noticed that it would always happen at the same episode of the same show. I moved that episode out into a different directory, tried the import again, and it all worked fine. Sickrage still uses almost 10x the ram that sickbeard used even at idle but it's not causing any issues yet and it's not enough to cause any swapping.

**Comment by nickveldrin** [comment] 2015-10-22 02:59
I'm using a DS1812+ with 3gb of ram and have subtitles on, but have quality names on all my episodes . Thankfully i'm not running into the problem. If you guys need me to check anything on my system to help, please let me know. I'm at 190 shows, over 6,900 episodes on my box.

**Comment by miigotu** [comment] 2015-10-22 03:19
@nickveldrin the subtitles problem has been fixed already. If there is another issue it will be addressed, however closing this issue for now.

**Closed by miigotu** 2015-10-22 03:19 UTC
Labels: 1: Bug / issue, 3: Unconfirmed

**Comment by deathnite** [comment] 2015-10-22 03:25
Im not sure this issue is resolved. I still have issues and I NEVER had subtitles enabled from the start. As the OP mentioned it was happening it him during 'the deep scan', just like i experienced when importing a bulk amount of files.

**Comment by miigotu** [comment] 2015-10-22 03:28
It is to be expected when importing a large amount of files, it takes resources. Also, there is no "deep scan", we only read the header of the file containers.

**Comment by deathnite** [comment] 2015-10-22 03:30
Yea sorry, I'll retract that. I just checked my python process for memory usage and its now sitting under 15MB. beforehand at idle the 'python' process slept at 78.1 MB and peaked during import.
Much better now!!

**Comment by richard5mith** [comment] 2015-10-22 18:58
I disagree with this. In the latest release, top on my Synology still shows...

5740     1 sickrage S    2718m274.0  4.9 /usr/local/sickrage/env/bin/python /usr/local/sickrage/var/SickRage/SickBeard.py

**Comment by miigotu** [comment] 2015-10-22 19:00
Problem with your database then.

**Comment by richard5mith** [comment] 2015-10-22 19:09
The solution for which is? I already deleted my cache folder at the start of this thread when it was originally suggested.

**Comment by miigotu** [comment] 2015-10-22 19:12
Try that again, delete cache.db and everything in the cache folder except the images folder.

If that doesnt work, you should check the size of your sickbeard.db

**Comment by richard5mith** [comment] 2015-10-22 19:27
Stopped SR. Deleted all those things. Started it up again (took a while). Process started at 1000m VSZ, went to home page, grew up to the same size as before.

sickbeard.db is 11MB.

**Comment by miigotu** [comment] 2015-10-22 19:29
I think you misunderstand the difference between VIRT memory and used memory.

**Comment by richard5mith** [comment] 2015-10-22 19:33
Very possibly! :) But my main Plex server on the same box uses 514m and 51% MEM, where Sickrage uses 2700Mb and 274% MEM. Eventually, the box becomes unusable and things start dying. It's not an issue I used to have, just around the same time as the other people that posted here.

**Comment by miigotu** [comment] 2015-10-22 19:35
Maybe you have way too many providers enabled, and your time between daily searches set too low....

**Comment by richard5mith** [comment] 2015-10-22 19:37
One provider (kickass). Daily search frequency, 40 minutes. Which I've never changed, so must be the default.

**Comment by miigotu** [comment] 2015-10-22 19:49
Plex is C, SR is Python.
VSZ is virtual memory (not really used, just available for quick re-use by SR)
Python does not release virtual memory back to the OS like C applications do on a free.

None of this has changed.

**Comment by miigotu** [comment] 2015-10-22 19:51
http://stackoverflow.com/questions/8836536/virtual-memory-management-in-python-2-6-2-7-will-it-reuse-the-allocated-memo

**Comment by richard5mith** [comment] 2015-10-22 19:57
I don't dispute any of that, but this worked great for me until quite recently, and it seems co-incidental that others reported the issue at the same time.

I'll keep an eye on it, but for now, I can no longer keep it running all the time like I used to. I have to start it up, let it do it's stuff and then shut it down again. 

Thanks for your suggestions.

**Comment by forza11** [comment] 2015-10-26 21:24
I can confirm that CPU and RAM are now at acceptable levels while the subtitle searcher enabled. With no active searches: RAM is constantly at around 50%, CPU is between 30 and 50%. Synology DS413j

**Comment by uph1ll** [comment] 2015-11-09 08:38
I have the same (CPU maxed out on Synology DS213) problem since maybe a week or less. Memory is normal. I have no clue what caused it, but I did remove some shows with many episodes around the same time. SickRage is up to date. Removed cache twice with only temporary effect.
Any advice highly appreciated, since my Synology has become almost unusable.

**Comment by briped** [comment] 2015-12-02 21:52
I've also experience that SickRage suddenly gobbles up all the memory. Even had it go so far as the system several times becoming completely unresponsive and a forced power off is the only solution.

At one point I set up a scheduled task to stop the SickRage service every 4 hours, and 5 minutes later start the service again. This for some reason ended up causing the entire thing to suddenly be "reset" (config file was gone, so settings and port etc was reset).

Right now it behaves, but I wanted to add my feedback too. Will keep an eye on it and report back with details, if it happens again. Yesterday it had hogged up over 1 GB of memory, after restarting the service it was down to a couple of hundred MB.

DS1511+ with 3 GB RAM.

Details as of right now...
304 Shows (136 Active) | 16231 +14 Snatched  / 16247 Episodes Downloaded (99.9%) | Daily Search: 0:11:56 | Backlog Search: 11:31:36
Memory used: 387.48 KB | Load time: 1.6102s / Mako: 1.4467s | Branch: master | Now: 2015-12-02 22:10:23.408003+01:00
