### ISSUE TITLE
Shows with quotes in the name are not added

### ISSUE THREAD

**Issue by beschoenen** [SiCKRAGETV/sickrage-issues#312] opened 2014-12-31 16:49 UTC
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
OS: Synology 5.1 / Python: 2.7.9

What you did:
added a show which has quotes in the official name (http://thetvdb.com/?tab=series&id=262112&lid=7)

What happened:
sickrage gave a popup "Show could not be added"
```
2014-12-31 17:41:26 Thread-96 :: Unable to add show due to show selection. Not anough arguments: ['theTVDB', '1', 'http://thetvdb.com/?tab=series&id=', '262112', 'Say ']
```
i think quotes are not escaped because the title it Say "I love you" and the log showing "Say "

Also,
A little typo here:
```
Not anough arguments
```

**Comment by fernandog** [comment] 2015-01-03 18:24
@beschoenen please send full logs (use pastebin)

**Comment by beschoenen** [comment] 2015-01-03 18:41
I don't know what to give you, this is the only line that popups up after i try to add the show again.
Yes i have debugging enabled.

**Comment by beschoenen** [comment] 2015-01-03 18:42
I only get 
```
2015-01-02 17:39:54 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2014-12-31 17:41:26 Thread-96 :: Unable to add show due to show selection. Not anough arguments: ['theTVDB', '1', 'http://thetvdb.com/?tab=series&id=', '262112', 'Say ']
```
and this over and over again
```
2015-01-03 16:25:20 Thread-297 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume3/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume3/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/volume3/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'
```

**Comment by fernandog** [comment] 2015-02-16 02:13
@beschoenen can you try the new develop udpate and report back?

**Comment by beschoenen** [comment] 2015-02-16 08:54
BRANCH: (develop) / COMMIT: (431d04de4a4072d64e05d34b6a81e1ba963106ac)
The error doesn't seem to be fixed
```
2015-02-16 09:53:08 Thread-306 :: Unable to add show due to show selection. Not anough arguments: ['theTVDB', '1', 'http://thetvdb.com/?tab=series&id=', '262112', 'Say ']
```

**Comment by fernandog** [comment] 2015-02-16 09:41
Full logs please

**Comment by beschoenen** [comment] 2015-02-16 10:31
Please help me with enabling full logs, cause i have enabled debug mode but i only get logs like this: http://a.pomf.se/urzqtm.txt

**Comment by fernandog** [comment] 2015-02-16 10:43
That's fine but does not show the "Unable to add show due to show selection" on it

**Comment by beschoenen** [comment] 2015-02-16 10:49
Yea that's why i think that somehow debugging isn't enabled.

But shouldn't the quotes in show names just be escape?

**Comment by fernandog** [comment] 2015-02-16 10:59
@TagForce escaping it will cause PP issues?

**Comment by fernandog** [comment] 2015-02-16 12:46
@abeloin @TagForce 
I did some tests and webserve.py is not receiving the full show name

2015-02-16 10:26:51 Thread-13 :: theTVDB|1|http://thetvdb.com/?tab=series&id=|262112|Say 

```
    def addNewShow(self, whichSeries=None, indexerLang="en", rootDir=None, defaultStatus=None,
                   anyQualities=None, bestQualities=None, flatten_folders=None, subtitles=None,
                   fullShowPath=None, other_shows=None, skipShow=None, providedIndexer=None,anime=None,scene=None):
```

https://github.com/SiCKRAGETV/SickRage/blob/93f0f0ad1fa278afb17f73d47c099b82a766dede/sickbeard/webserve.py#L2357

I think the problem is in newshow.js but I don't know how to fix it.

```
        if ($('input:radio[name=whichSeries]:checked').length) {
            show_name = $('input:radio[name=whichSeries]:checked').val().split('|')[4];
```

![quoted-show](https://cloud.githubusercontent.com/assets/2620870/6212151/09c3d750-b5c9-11e4-8a5b-5eadd72f8617.png)

**Comment by abeloin** [comment] 2015-02-16 14:24
The problem is at this line: https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/js/newShow.js#L71

**Comment by TagForce** [comment] 2015-02-16 14:46
whichSeries.replace(/"/g, '&quot') will replace the " into &quot in html...
But that would probably mess up the rest of the script.

**Comment by abeloin** [comment] 2015-02-16 14:51
The you have to decode it in addNewShow()

**Comment by TagForce** [comment] 2015-02-16 14:57
You could just remove the quotes all together.
That way you wouldn't need to decode them anywhere, and it should still work for the rest of SR (searching with or without quotes will yield the same results most of the time).

**Comment by fernandog** [comment] 2015-02-16 14:58
@TagForce yes, the double quotes could be a issue in PP. But they need be be removed from search results also otherwise SR wont recognize as a valid result

**Comment by abeloin** [comment] 2015-02-16 15:03
whichSeries.replace(/"/g, "") works

**Comment by abeloin** [comment] 2015-02-16 15:13
@fernandog Pull requests merged

**Comment by fernandog** [comment] 2015-02-16 15:15
@beschoenen update and report back

**Comment by beschoenen** [comment] 2015-02-16 16:20
It seems to work now. Thanks.
![screen shot 2015-02-16 at 17 17 16](https://cloud.githubusercontent.com/assets/1887585/6215355/05a8966a-b600-11e4-940d-ea82af34e920.png)

**Closed** 2015-02-16 16:24 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, branch: master
