### ISSUE TITLE
Post process copy very slow

### ISSUE THREAD

**Issue by kristofferbas** [SiCKRAGETV/sickrage-issues#545] opened 2015-02-03 22:34 UTC
I've been thinking for a while that post process copying is very slow, and today I did a test. I'm copying from my Mac Mini to NAS and when I'm copied a 3,5Gb movie-file it took 2 minutes and 31 seconds. Post processing the same file in SR took 28 minutes and 19 seconds. I understand that SR needs to get a new name for the file, but it looked like it only took a couple of seconds to do that, and that it's the actual copying thats really slow.

Branch: develop
Commit hash: c62d8f2c799edd7daad5648f45276a3464d83a9e
Your operating system and python version: Mac OSX Yosemite, Python 2.7.6

Thanks
/k

**Comment by kristofferbas** [comment] 2015-02-03 23:16
It looks like I had set SR to move the files and not to copy. When I changed to copy everything speeds up. The only problem is that want to delete the processed files after the copy. Now I have to do it manually.

**Comment by abeloin** [comment] 2015-02-06 01:45
@kristofferbas Can you try applying these commits? Apply in order.
Commit 1: https://github.com/abeloin/SickRage/commit/c36f39ea30f785fcd077c920dd9fc4a0e8b49d03
Commit 2: https://github.com/abeloin/SickRage/commit/4d2c36daf1d0e1d805e4012ece6acae89bf0d846

Let me know if it improved the transfer speed

**Comment by abeloin** [comment] 2015-02-09 20:25
@kristofferbas Have you had time to test the commits?

**Comment by fernandog** [comment] 2015-02-09 20:31
@kristofferbas will close this tomorrow if we don't get reply.

**Comment by kristofferbas** [comment] 2015-02-10 10:14
Oh sorry, been busy for a couple of days. No it doesn't seem as it works with those commits, but as I'm quite new to Git can you tell me how I apply them (if I didn't to it the correct way the last time).

Just to clarify - when I set SR to move files it's slow, when I set to copy it's fast.

Thanks!

**Comment by abeloin** [comment] 2015-02-10 14:26
See this for some info on how to use [patch on OSX](http://www.projectpier.org/node/501).

* Stop sickrage
* Download https://github.com/abeloin/SickRage/commit/c36f39ea30f785fcd077c920dd9fc4a0e8b49d03.diff
* Download https://github.com/abeloin/SickRage/commit/4d2c36daf1d0e1d805e4012ece6acae89bf0d846.diff
* In Terminal, go to Sickrage folder: ```cd /path/to/sickrage```
* Patch the first file: ```patch -p1 < /path/to/c36f39ea30f785fcd077c920dd9fc4a0e8b49d03.diff```
* Patch the second file: ```patch -p1 < /path/to/4d2c36daf1d0e1d805e4012ece6acae89bf0d846.diff```
* If any hunk failed, revert the changes with: ```git reset --hard```
* Start Sickrage
* Test a move

**Comment by kristofferbas** [comment] 2015-02-10 15:11
@abeloin Thanks, will definitely save that info! But move is still slow, and now copy's slow too...

**Comment by abeloin** [comment] 2015-02-10 15:29
@kristofferbas Slow shorter or slow slower? Do you have time for some additional testing?
Can you change the following value in file lib/shutil_custom/__init__.py(stop sickrage first):
from:
```def copyfileobj_custom(fsrc, fdst, length=4*1048576):```
to:
```def copyfileobj_custom(fsrc, fdst, length=512*1024):```

Then start sickrage and retry

**Comment by kristofferbas** [comment] 2015-02-10 15:38
@abeloin Slow like it takes longer for the files to process. Yeah sure, with your patches applied?

**Comment by abeloin** [comment] 2015-02-10 15:47
Yes with the patches applied. This change the buffer from 4MB to 512KB

**Comment by kristofferbas** [comment] 2015-02-10 17:09
Tried both move and copy with a 3.1gb file and it took about 30 minutes with both, so still much slower than to copy/move in Finder or copy before the patches in SR.

**Comment by abeloin** [comment] 2015-02-10 19:29
Ok, can you try this diff https://gist.githubusercontent.com/abeloin/b16a38787ae9defaf95a/raw/66e7f350d7e014ca0de78e237883f28cb754142f/shutil.diff ?

* Stop sickrage
* Download https://gist.githubusercontent.com/abeloin/b16a38787ae9defaf95a/raw/66e7f350d7e014ca0de78e237883f28cb754142f/shutil.diff
* Git clean: ```git reset --hard```
* Remove file: ```rm lib/shutil_custom/__init__.py```
* Patch the file: ```patch -p1 < /path/to/shutil.diff```
* Start Sickrage
* Test a move

**Comment by kristofferbas** [comment] 2015-02-10 19:53
I get a bunch of errors.

```
Hunk #1 FAILED at 342.
Hunk #2 FAILED at 366.
2 out of 2 hunks FAILED -- saving rejects to file sickbeard/helpers.py.rej
patching file SickBeard.py
patching file lib/shutil_custom/__init__.py
patching file setup.py
patching file sickbeard/helpers.py
Hunk #1 FAILED at 21.
Hunk #2 FAILED at 53.
2 out of 2 hunks FAILED -- saving rejects to file sickbeard/helpers.py.rej
patching file sickbeard/processTV.py
patching file sickbeard/tv.py
patching file sickbeard/versionChecker.py
Hunk #1 FAILED at 18.
Hunk #2 FAILED at 32.
2 out of 2 hunks FAILED -- saving rejects to file sickbeard/versionChecker.py.rej
patching file tests/test_lib.py
patching file updater.py
patching file SickBeard.py
patching file lib/shutil_custom/__init__.py
patching file setup.py
patching file sickbeard/helpers.py
Hunk #1 FAILED at 56.
1 out of 1 hunk FAILED -- saving rejects to file sickbeard/helpers.py.rej
patching file sickbeard/processTV.py
patching file sickbeard/tv.py
patching file sickbeard/versionChecker.py
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file sickbeard/versionChecker.py.rej
patching file tests/test_lib.py
patching file updater.py
patching file lib/shutil_custom/__init__.py
```

**Comment by abeloin** [comment] 2015-02-10 20:52
Ok,

* Stop sickrage
* Download https://github.com/abeloin/SickRage/commit/c36f39ea30f785fcd077c920dd9fc4a0e8b49d03.diff 
* Download https://github.com/abeloin/SickRage/commit/b7175a36e3ba10b8fc0a2d60c741d1efffa4778a.diff
* In Terminal, go to Sickrage folder: ```cd /path/to/sickrage```
* Git clean: ```git reset --hard```
* Remove file: ```rm lib/shutil_custom/__init__.py```
* Patch the first file: ```patch -p1 < /path/to/c36f39ea30f785fcd077c920dd9fc4a0e8b49d03.diff```
* Patch the second file: ```patch -p1 < /path/to/b7175a36e3ba10b8fc0a2d60c741d1efffa4778a.diff```
* Start Sickrage
* Test a move

**Comment by kristofferbas** [comment] 2015-02-10 21:53
It's much better now! Both move and copy in SR takes about 4 minutes (for a 3,1gb file), manual copy in Finder takes about 2 minutes. Also, it looks like the original processed file get deleted when using copy (if I haven't accidentally turned on some setting for this?).

Thanks!

**Comment by kristofferbas** [comment] 2015-02-10 21:56
Oh, and it feels like the computer is working a bit more than before too (maybe this is natural), the fans start spinning and so on.

**Comment by abeloin** [comment] 2015-02-11 03:16
@kristofferbas I can't reproduce the deleting when copying, maybe you use move instead?

As for the cpu usage, have a look in the [activity monitor](http://support.apple.com/en-us/HT201538) while the transfer to see the see sickrage cpu usage.

**Comment by kristofferbas** [comment] 2015-02-11 08:05
@abeloin Restarted the computer and everything works great now! Copy does not delete the file and the computer isn't working harder than usual. Excellent! Thank you so much.

**Comment by abeloin** [comment] 2015-02-11 11:56
@fernandog This fix would be a replacement of SiCKRAGETV/SickRage#1193 and SiCKRAGETV/SickRage#1262. The main issue with those 2 PR is that they only apply in a specific case(i.e. when called to copy), if the user choose move and the locations are not on the same partition it will use shutil.copyfile as it called shutil.move first. This apply to any other shutil command that use shutil.copyfile resulting in a slow copy. 

Using the method in the proposed commits, it monkeypatch shutil.copyfile so that anytime it's called it use the custom version instead of the original. This way we don't need to change any part of code that use shutil.

Kristofferbas tested it in Mac, I've tested it Linux and we need to test it in Windows. If it pass in Windows I'll submit a pull request

See this branch: https://github.com/abeloin/SickRage/commits/patch-shutil_copy for the proposed changes

**Comment by abeloin** [comment] 2015-03-04 03:03
@kristofferbas PR merged in develop, please update

**Comment by lis8910** [comment] 2015-03-05 16:11
Since the update I'm getting this
```
Starting sickrage.                                                              
Traceback (most recent call last):                                              
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/SickBeard.py", line 69, 
in <module>                                                                     
    import sickbeard                                                            
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", 
line 29, in <module>                                                            
    shutil.copyfile = lib.shutil_custom.copyfile_custom                         
NameError: name 'shutil' is not defined
```

**Comment by abeloin** [comment] 2015-03-05 23:49
Try:
`git reset --hard`
`git pull`
then start sickrage

**Comment by lis8910** [comment] 2015-03-06 14:44
tnx :)

**Comment by fernandog** [comment] 2015-03-06 14:46
@kristofferbas please feedback if is faster so we can close the issue

**Closed** 2015-03-09 00:28 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: develop
