### ISSUE TITLE
ERROR    POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x10 - The Down Low.avi to /media/tv/House/House - 6x10 - The Down Low.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x10 - The Down Low.avi'

### ISSUE THREAD

**Issue by rrd911** [SiCKRAGETV/sickrage-issues#697] opened 2015-02-21 02:14 UTC
Postprocessing fails stating that the file does not exist. I am using the move method. The file is deleted from the source directory.

Works for some files but a few fail

SR Version:	BRANCH: (master) / COMMIT: (ac153cf2320b3b6d0a8aa9a1b1646a51347581d6) 
SR Config file:	/home/raydias/sickrage/config.ini
SR Database file:	/home/raydias/sickrage/sickbeard.db
SR Cache Dir:	/home/raydias/sickrage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/raydias/sickrage/', '\xe2\x80\x93config=/home/raydias/sickrage/config.ini']
SR Web Root:	
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

```
2015-02-20 17:59:51 POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x10 - The Down Low.avi to /media/tv/House/House - 6x10 - The Down Low.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x10 - The Down Low.avi'
2015-02-20 17:51:50 POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x01 - Broken.avi to /media/tv/House/House - 6x01 - Broken.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x01 - Broken.avi'
2015-02-20 17:37:41 POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x07 - Teamwork.avi to /media/tv/House/House - 6x07 - Teamwork.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x07 - Teamwork.avi'
2015-02-20 17:36:11 POSTPROCESSER :: Unable to move file /media/tv_complete/Doctor Who (2005) - 4x10 - Midnight.mkv to /media/tv/Doctor Who (2005)/Doctor Who (2005) - 4x10 - Midnight.mkv: [Errno 2] No such file or directory: '/media/tv_complete/Doctor Who (2005) - 4x10 - Midnight.mkv'
2015-02-20 17:28:21 POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x14 - Private Lives.avi to /media/tv/House/House - 6x14 - Private Lives.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x14 - Private Lives.avi'

2015-02-20 17:59:51 WARNING  POSTPROCESSER :: Processing failed for /media/tv_complete/House - 6x10 - The Down Low.avi: Unable to move the files to their new home
AAIOError: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x10 - The Down Low.avi'
AA    with open(src, 'rb') as fsrc:
AA  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
AA    copyfile(src, dst)
AA  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
AA    copy2(src, real_dst)
AA  File "/usr/lib/python2.7/shutil.py", line 302, in move
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/raydias/sickrage/sickbeard/encodingKludge.py", line 58, in ek
AA    ek.ek(shutil.move, srcFile, destFile)
AA  File "/home/raydias/sickrage/sickbeard/helpers.py", line 362, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "/home/raydias/sickrage/sickbeard/postProcessor.py", line 319, in _int_move
AATraceback (most recent call last):
2015-02-20 17:59:51 ERROR    POSTPROCESSER :: Unable to move file /media/tv_complete/House - 6x10 - The Down Low.avi to /media/tv/House/House - 6x10 - The Down Low.avi: [Errno 2] No such file or directory: '/media/tv_complete/House - 6x10 - The Down Low.avi'
2015-02-20 17:59:51 INFO     POSTPROCESSER :: Folder name (tv_complete) appears to be a valid release name. Using it.
2015-02-20 17:59:50 INFO     POSTPROCESSER :: Trying to clean any empty folders under /media/tv/House/Season 6
2015-02-20 17:59:50 INFO     POSTPROCESSER :: Analyzing name u'House - 6x10 - The Down Low.avi'
2015-02-20 17:59:50 INFO     POSTPROCESSER :: Analyzing name None
2015-02-20 17:59:50 INFO     POSTPROCESSER :: Processing /media/tv_complete/House - 6x10 - The Down Low.avi (None)
```

**Comment by fernandog** [comment] 2015-02-21 02:16
@abeloin @TagForce we must found the root cause of this. There are a lot of this issue in the last days.

**Comment by Kallb123** [comment] 2015-02-21 02:23
@fernandog 
Wow, this seems like more than a coincidence. I was willing to believe I had done something wrong... Fresh install of ubuntu server, fresh virtual machines, fresh SR and Transmission. The thing pestering me is that no programs can access the files, tried MXPlayer, VLC, and obviously SR.

**Comment by fernandog** [comment] 2015-02-21 11:03
@rrd911 whats your OS? Can you access target folder? All permissions ok?

**Comment by fernandog** [comment] 2015-02-23 13:53
@rrd911

**Comment by rrd911** [comment] 2015-02-25 04:24
OS is Ubuntu 14.04

The failure doesn't occur on all files just a few. Others work just fine.

**Comment by fernandog** [comment] 2015-02-25 09:27
@Tagforce what should we do with this issues?

**Comment by TagForce** [comment] 2015-02-25 10:52
@fernandog @rrd911 
Try this commit: https://github.com/TagForce/SickRage/commit/08645eceb16abdb656bb2ee77a4ede2d5c5d8af6

Make sure you're on the latest develop branch (it was based on the develop branch that was current yesterday) before replacing the file.

**Comment by TagForce** [comment] 2015-02-25 17:31
Scratch that... Use this one first:
https://github.com/TagForce/SickRage/commit/b0133e5eb83ddbc95f8619feb24e72b0c1a4918d

This may fix the underlying issue.

**Comment by fernandog** [comment] 2015-02-26 00:44
@rrd911 did you tried that?

**Comment by TagForce** [comment] 2015-02-26 09:29
@rrd911 
Update to the latest dev. The fix was merged.
Please let us know if it's fixed.

**Comment by rrd911** [comment] 2015-02-27 19:37
So far I have not seen the error in the logs again since updating to the latest dev

**Closed** 2015-02-27 19:39 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
