### ISSUE TITLE
Deleting downloads: You're trying to post process a video that's already been processed, skipping

### ISSUE THREAD

**Issue by ActiveNine** [SiCKRAGETV/sickrage-issues#491] opened 2015-01-26 00:44 UTC
For the last few weeks SickRage has been successfully snatching and downloading episodes but when the post-processing occurs I get the error "You're trying to post process a video that's already been processed, skipping". This deletes the downloaded episode and no further searches are performed. After this occurs if I do a manual search it sometimes is successful, other times the same thing happens again. Any suggestions? Below are the details of my system and the log for an example where this happened:

- Branch:
BRANCH: (master)
- Commit hash:
COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
- Your operating system and python version:
OSX 10.6.8, Python 2.6.1
- What you did:
SickBeard downloads an episode or I manually download one (inconsistent behavior)
- What happened:
Sometimes it downloads and post-processes as expected, other times it says its already been post-processed. I have failed downloads on but I don't see any evidence that there was a failed download before this that was post-processed before the download where I get this error.
- What you expected:
The file downloads and post-processes per normal behavior
- Log file:
http://pastebin.com/TuKuHf7Z

**Comment by fernandog** [comment] 2015-01-26 11:48
@TagForce can you help me with this? I don't use PP.

**Comment by TagForce** [comment] 2015-01-26 13:14
@fernando I'll try.
@ActiveNine In the case of your logs: SR will lookup any episode with a release_name that's equal to "Girls.S04E02.480p.HDTV.x264-REenCO" or that is in your history as having been previously downloaded and has a 'resource' value equal to the full filename and path.

So basically, SR thinks it already has this episode.
Could you perform a re-scan and/or a full update on the affected Show(s)?
This should at least clear the tv_episodes table for episodes that no longer exist.

If the problem persists, please perform the following 2 queries on the sickbeard.db database:
Select * from tv_episodes WHERE release_name = "Girls.S04E02.480p.HDTV.x264-REenCO";
Select * from history WHERE resource like "%Girls.S04E02.480p.HDTV.x264-REenCO";
and post the results.

**Comment by ActiveNine** [comment] 2015-01-27 02:10
Update:
I rescanned and did a full update of the show then attempted to manually post-process the same file that had failed in the example I provided previously. The rescan and update were successful but I received the same error "You're trying to post process a video that's already been processed, skipping".

I executed the two SQL statements you requested:
0 Rows returned from: Select * from tv_episodes WHERE release_name = "Girls.S04E02.480p.HDTV.x264-REenCO"; (took 4796ms)

1 Rows returned from: Select * from history WHERE resource like "%Girls.S04E02.480p.HDTV.x264-REenCO"; (took 309ms)

The returned row contains the following data:
Action: "102"
Date: "20150124124028"
Showid: "220411"
Season: "4"
Episode: "2"
Quality: "1"
Resource: "Girls.S04E02.480p.HDTV.x264-REenCO"
Provider: "NZBs.in"
Version: "-1"

**Comment by ActiveNine** [comment] 2015-01-27 02:13
Note: The same thing occurred with episode 3 of this show (note that its not limited just to this show, its occurring sporadically with most of them). When I look at the history, I can see that it contains a single entry for this episode and it's the one that was downloaded. I'm not sure how it would have had a match for this resource in the history already if I got this error on the first attempt at downloading this episode...

Let me know if you need any further information. Thanks for your help!

**Comment by TagForce** [comment] 2015-01-27 08:44
@fernandog @ActiveNine The question I'm trying to answer for myself now is why would we check the history if there's no active episode file? It really doesn't seem to serve a purpose other than not wanting to PP a file that we've already processed before. I can name a million cases in which we DO want to do just that, and only one case where we don't, namely when we've just downloaded it and it failed. Even then, there may be times when getting the same file from a different source will fix the problem, but it doesn't check the source as it is, so SR won't know it's a different release.

**Comment by TagForce** [comment] 2015-01-27 09:35
Could you perform the following query on the db?
SELECT * from tv_episodes
WHERE tv_episodes.season = '4' and tv_episodes.episode = '2' and tv_episodes.showid = '220411';
And post the results?

If there's no result, then I think the code is botched, and it doesn't actually check if we've really downloaded that specific episode in a different quality. If there is a result, then something doesn't get deleted properly on a re-scan.

The code that gives you the 'already processed' message is the following:
 ```   search_sql = "SELECT tv_episodes.indexerid, history.resource FROM tv_episodes INNER JOIN history ON history.showid=tv_episodes.showid"```
```    search_sql += " WHERE history.season=tv_episodes.season and history.episode=tv_episodes.episode"```
```    search_sql += " and tv_episodes.status IN (" + ",".join([str(x) for x in common.Quality.DOWNLOADED]) + ")"```
```    search_sql += " and history.resource LIKE ?"```
```    sqlResult = myDB.select(search_sql, [u'%' + videofile])```

Now, I can't get my head around what the problem is, but the fact that it doesn't check for a specific episode might break it in some cases.

**Comment by TagForce** [comment] 2015-01-27 11:22
@ActiveNine @fernandog I think I have an idea where the problem might be.
"Girls.S04E02.480p.HDTV.x264-REenCO" is the name of the folder where the videofiles reside, yes?
If that is a generic name, like video.mkv, then the DB Query will hit a result if it has downloaded another release with the same format.
I just tried it by creating a folder with the episode name, and copying a random video file to it and naming it video.mkv.
I then created a history entry in the db for a completely different episode, and added that episode to the tv_episodes table as having been downloaded.
Even though I'm trying to post-process a file in the folder for S01E02, it will now fail saying that I'm trying to post-process a file that's already been processed, because the query now returns a result for S01E03 which has the same video filename in history.

I need to think about about how to fix this. It's not often a problem, but it does happen, and if it is possible to address, then we should.

Maybe get a possible show, season and episode number from the folder and use that in the query to limit the result to that specific episode. If it fails finding the numbers, then we can still do the original query, and have it fail.

As a workaround you could do a manual PP and force it using the checkbox Force already Post Processed Dir/Files. That should skip the checks completely.

**Comment by TagForce** [comment] 2015-01-27 13:34
https://github.com/TagForce/SickRage/commit/6159530537cd174ce34687bf615f5c1b2a50430d
@fernandog @ActiveNine 
Can you test if the above commit fixes your issue?
It now checks if it can find a showid, season, and episode number from the folder name, before it searches the history table. If it fails it will use the old query, but if all 3 are returned succesfully, it will use that in the query, which should limit the results from the query to the specific episodes being PPed.

**Comment by fernandog** [comment] 2015-01-27 14:51
@TagForce thanks again for the PR

**Comment by ActiveNine** [comment] 2015-01-27 22:37
@TagForce @fernandog  - You were spot on with your theory. The file in both cases was named something arbitrary (xyz.mp4). I did a manual post-processing and regular download using the new code and it worked as expected. Thanks for such a fast solution!

**Comment by TagForce** [comment] 2015-01-28 08:16
@ActiveNine @fernandog Hmmm, it breaks PP for files that are in the root TV folder or in folders that cannot be parsed into a showname. I'll retract the PR and fix that first. Stupid me for not testing that properly.

**Comment by TagForce** [comment] 2015-01-28 09:04
https://github.com/SiCKRAGETV/SickRage/pull/1257

It will now ignore exceptions thrown by nameparser so that it will continue on unparsable folders (anything without a series name, season and episode nr in it) and set parse_result to false.

Added an extra check to see if parse_result is false. If it isn't, this means we have a valid parse result, and we can use the info in the query. Tested it a million ways, and it seems to work properly now.
Maybe not the cleanest solution, but the only viable one I could think of without rewriting the nameparser itself.

**Comment by fernandog** [comment] 2015-01-29 23:41
@ActiveNine  please update SR and report back please. Fix was merged

**Closed** 2015-02-16 00:10 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: master
