### ISSUE TITLE
Mako don't accept new line filter in Windows

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2443] opened 2015-08-10 12:23 UTC
Its works in Linux but not in windows

If I remove the backslash and put everything in one line it works

``` 
% if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \
and (sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'https' \
or not sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'http:'):
```

```
Error !

CompileException: Fragment 'if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \' is not a partial control statement in file 'C:\Users\fernando\Documents\GitHub\SickRage\gui/slick/interfaces/default/inc_top.mako' at line: 196 char: 1

% if sickbeard.USE_EMBY and sickbeard.EMBY_HOST != "" and sickbeard.EMBY_APIKEY != "": <li><a href="${sbRoot}/home/updateEMBY/"><i class="menu-icon-backlog-view"></i>&nbsp;Update Emby</a></li> % endif % if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \ and (sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'https' \ or not sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'http:'): <li><a href="${sbRoot}/manage/manageTorrents/"><i class="menu-icon-bittorrent"></i>&nbsp;Manage Torrents</a></li> % endif % if sickbeard.USE_FAILED_DOWNLOADS:
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\ast.py, line 87:
code, **exception_kwargs)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\parsetree.py, line 83:
code = ast.PythonFragment(text, **self.exception_kwargs)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\lexer.py, line 134:
node = nodecls(*args, **kwargs)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\lexer.py, line 429:
self.append_node(parsetree.ControlLine, keyword, isend, text)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\lexer.py, line 237:
if self.match_control_line():
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\template.py, line 657:
node = lexer.parse()
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\template.py, line 692:
generate_magic_comment=True)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\template.py, line 378:
self.module_writer)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\template.py, line 322:
module = self._compile_from_file(path, filename)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\lookup.py, line 318:
**self.template_args)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\lookup.py, line 253:
return self._load(srcfile, uri)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\runtime.py, line 793:
return lookup.get_template(uri)
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\runtime.py, line 748:
template = _lookup_template(context, uri, calling_uri)
C:\Users\fernando\Documents\GitHub\SickRage\gui/slick/interfaces/default/home.mako, line 10:
<%include file="/inc_top.mako"/>
C:\Users\fernando\Documents\GitHub\SickRage\lib\mako\runtime.py, line 883:
callable_(context, *args, **kwargs)

```

**Comment by fernandog** [comment] 2015-08-10 12:25
https://github.com/SiCKRAGETV/SickRage/commit/8155d40eab485c72f2bc1cb1f7c67ac6829d1972

**Comment by fernandog** [comment] 2015-08-10 12:27
@zzzeek can you confirm please?

I also tested with 1.0.1 and 1.0.2 version.

http://docs.makotemplates.org/en/latest/syntax.html#newline-filters

**Comment by fernandog** [comment] 2015-08-10 13:04
@duramato do you also have this in windows?

**Comment by duramato** [comment] 2015-08-10 13:50
i dont understand the problem but i can try reprodoce ,how do i do it?

**Comment by zzzeek** [comment] 2015-08-10 13:58
no known issue with newline filters under windows.

**Comment by fernandog** [comment] 2015-08-10 14:10
Just do a fresh install with develop and open SR.

**Comment by fernandog** [comment] 2015-08-10 14:40
@duramato 
never mind. I fixed in develop. You need to test develop without my commit

**Comment by duramato** [comment] 2015-08-10 16:38
how do i git pull before a certain commit?

**Comment by fernandog** [comment] 2015-08-10 16:38
git reset --hard HEAD~1

**Comment by duramato** [comment] 2015-08-10 16:54
@fernandog confirmed that the error existed ,and comfirmed that your fix works

**Comment by fernandog** [comment] 2015-08-10 17:06
@kotysoft can you this too ?

**Comment by fernandog** [comment] 2015-08-10 17:08
@duramato whats you python version?

mine in windows:
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by duramato** [comment] 2015-08-10 17:10
2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment] 2015-08-10 17:20
@zzzeek are you sure? we have 3 reports of this.

can you please git clone our repo and try it? you don't need to do/set anything else.
You only have to 'git reset --hard HEAD~1' before 'python SickBeard.py'

thanks!

**Comment by zzzeek** [comment] 2015-08-10 17:35
If you're claiming a bug in Mako, it's always appreciated if you can take the time to produce a test case, confirm it fails, and post it as a bug report on our [issue tracker](https://bitbucket.org/zzzeek/mako/).  This saves the maintainer the time of trying to guess what might be going wrong on your end and allows the user of the library to contribute back to the project by taking the time to boil down unexpected behaviors into a reproducible format.

In this case, a test script is as follows:

    from mako.template import Template

    t1 = Template("This is a unix newline\nand this is another line")
    t2 = Template("This is a CRLF newline\r\nand this is another line")

    t3 = Template("This is a unix newline\\\nand this is the *same* line")
    t4 = Template("This is a CRLF newline\\\r\nand this is the *same* line")

    for t in [t1, t2, t3, t4]:
        print t.render()


Works as expected both on OSX:

	$ python test.py
	This is a unix newline
	and this is another line
	This is a CRLF newline
	and this is another line
	This is a unix newlineand this is the *same* line
	This is a CRLF newlineand this is the *same* line

as well as on Windows, which I attach as a [screenshot](http://i.imgur.com/1ME1J6Q.png) here.

**Comment by kotysoft** [comment] 2015-08-10 17:40
Honestly I don't know what's happening here and how can I help, but I tested the following:
(I'm just a enthusiastic end user)

* Closed running SR-master
* Created new folder and `git clone -b develop https://github.com/SiCKRAGETV/SickRage`
* Opened a cmd, typed `it reset --hard HEAD~1` ENTER `python SickBeard.py`
* Got error message in opening browser:
```
Error !
CompileException: Fragment 'if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \' is not a partial control statement in file 'C:\SR\gui/slick/interfaces/default/inc_top.mako' at line: 196 char: 1
% if sickbeard.USE_EMBY and sickbeard.EMBY_HOST != "" and sickbeard.EMBY_APIKEY != "": <li><a href="${sbRoot}/home/updateEMBY/"><i class="menu-icon-backlog-view"></i>&nbsp;Update Emby</a></li> % endif % if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \ and (sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'https' \ or not sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'http:'): <li><a href="${sbRoot}/manage/manageTorrents/"><i class="menu-icon-bittorrent"></i>&nbsp;Manage Torrents</a></li> % endif % if sickbeard.USE_FAILED_DOWNLOADS:
C:\SR\lib\mako\ast.py, line 78:
code, **exception_kwargs)
C:\SR\lib\mako\parsetree.py, line 77:
code = ast.PythonFragment(text, **self.exception_kwargs)
C:\SR\lib\mako\lexer.py, line 132:
node = nodecls(*args, **kwargs)
C:\SR\lib\mako\lexer.py, line 426:
self.append_node(parsetree.ControlLine, keyword, isend, text)
C:\SR\lib\mako\lexer.py, line 234:
if self.match_control_line():
C:\SR\lib\mako\template.py, line 647:
node = lexer.parse()
C:\SR\lib\mako\template.py, line 680:
generate_magic_comment=True)
C:\SR\lib\mako\template.py, line 378:
self.module_writer)
C:\SR\lib\mako\template.py, line 321:
module = self._compile_from_file(path, filename)
C:\SR\lib\mako\lookup.py, line 311:
**self.template_args)
C:\SR\lib\mako\lookup.py, line 245:
return self._load(srcfile, uri)
C:\SR\lib\mako\runtime.py, line 769:
return lookup.get_template(uri)
C:\SR\lib\mako\runtime.py, line 726:
template = _lookup_template(context, uri, calling_uri)
C:\SR\gui/slick/interfaces/default/home.mako, line 10:
<%include file="/inc_top.mako"/>
C:\SR\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)
````

Running on Windows 2008 R2 HU x64
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment] 2015-08-10 17:48
@zzzeek  

@miigotu any clue?


added in SickBeard.py after `name_cache.buildNameCache()`

```
14:44:24 INFO::MAIN :: Building internal name cache for all shows
14:44:25 INFO::MAIN :: This is a unix newline
and this is another line
14:44:25 INFO::MAIN :: This is a CRLF newline
and this is another line
14:44:25 INFO::MAIN :: This is a unix newlineand this is the *same* line
14:44:25 INFO::MAIN :: This is a CRLF newlineand this is the *same* line
```

**Comment by miigotu** [comment] 2015-08-10 17:53
I'll whip up a test later. @fernandog we have no reason to think this is a mako bug yet. There are steps we have to take to rule out any other possibility first.

**Comment by miigotu** [comment] 2015-08-10 22:01
Can someone try this on windows?

```python
#!/usr/bin/env python2.7
from mako.template import Template
print Template(
"""
% if True:
If works without newline filter
% endif
## btw, if there is no space before the \ it fails, and if there is a space after the \ it also fails, it should not.
% if True \
and True \
and True:
Does this fail on windows?
% endif
""").render()
```

**Comment by fernandog** [comment] 2015-08-10 22:09
@miigotu 

c:\Python27\Scripts>python test.py

If works without newline filter
Does this fail on windows?

c:\Python27\Scripts>

**Comment by miigotu** [comment] 2015-08-10 22:13
@fernandog did it fail for you before on windows?

**Comment by miigotu** [comment] 2015-08-10 22:17
```python
#!/usr/bin/env python2.7
from mako.template import Template
print Template(
"""
% if True:
If works without newline filter
% endif
## btw, if there is no space before the \ it fails, and if there is a space after the \ it also fails, it should not.
% if True \
and True \
and (True or \
False):
Does this fail on windows?
% endif
""").render()
```

**Comment by fernandog** [comment] 2015-08-10 23:00
@miigotu this one runs ok too

**Comment by fernandog** [comment] 2015-08-10 23:13
@miigotu

this fails

```
#!/usr/bin/env python2.7
from mako.template import Template
print Template(
"""
% if True:
If works without newline filter
% endif
## btw, if there is no space before the \ it fails, and if there is a space after the \ it also fails, it should not.
% if True and True != False and \
(True and True == True or \ 
not False and True == True):
Does this fail on windows?
% endif
""").render()
```

**Comment by WebSpider** [comment] 2015-08-13 19:43
so basically you can use escapes in strings, but not in evaluated statements ?

**Comment by miigotu** [comment] 2015-08-13 20:23
Guess so. We only do it in like 2 places in the templates so no big deal.

**Comment by WebSpider** [comment] 2015-08-13 23:04
I can only seem to find one occurance, where it is in a string:
````
nivo@hosting3:~/devel/SickRage$ grep -Rl '\\$' gui/slick/interfaces/default/*mako
gui/slick/interfaces/default/inc_bottom.mako
nivo@hosting3:~/devel/SickRage$
````
Guess this issue is then solved?

**Comment by miigotu** [comment] 2015-08-13 23:52
Yes, fernandog committed a fix days ago.

**Closed by miigotu** 2015-08-13 23:52 UTC
Labels: 1: Bug / issue

**Comment by ahmedtechinfo** [comment] 2015-08-20 13:40
Hi I updated Sickrage through browser today and now i am getting the following error:-

</td> <td align="center"> <img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" /> </td> <td align="center"> <% display_status = curShow.status %> % if None is not display_status:
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/gui/slick/interfaces/default/home.mako, line 818:
<img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" />
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

I am using freenas and wont be able to tell u about commits since it is not running. Please help
