### ISSUE TITLE
Sickrage Not starting up after the latest update

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2702] opened 2015-09-08 21:00 UTC
I just did an update 10 minutes ago, and after the update (pushbullet sent me a message saying update succesful "SickRage Updated To Commit#: c9729676cdbd2af5b04337b239bb3a843f5feaa4"), however sickrage does not work any longer. When restarted, following error message gets displayed on the console:

````
C:\SickRage>python SickBeard.py
08:56:35 INFO::MAIN :: Checking for shows with tvrage id's, since tvrage is gone

08:56:35 WARNING::MAIN :: Found 6 shows with TVRage ID', FIXING!
08:56:35 INFO::MAIN :: Mapping Marvel's Agents of S.H.I.E.L.D. to tvdb id 263365

08:56:35 ERROR::MAIN :: Fatal error executing query: column indexer_id is not un
ique
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickRage\sickbeard\db.py", line 88, in execute
    return self._execute(query, args)
  File "C:\SickRage\sickbeard\db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
IntegrityError: column indexer_id is not unique
Traceback (most recent call last):
  File "SickBeard.py", line 522, in <module>
    SickRage().start()
  File "SickBeard.py", line 295, in start
    sickbeard.initialize(consoleLogging=self.consoleLogging)
  File "C:\SickRage\sickbeard\__init__.py", line 1308, in initialize
    db.sanityCheckDatabase(myDB, mainDB.MainSanityCheck)
  File "C:\SickRage\sickbeard\db.py", line 254, in sanityCheckDatabase
    sanity_check(connection).check()
  File "C:\SickRage\sickbeard\databases\mainDB.py", line 46, in check
    self.convert_tvrage_to_tvdb()
  File "C:\SickRage\sickbeard\databases\mainDB.py", line 77, in convert_tvrage_t
o_tvdb
    (INDEXER_TVDB, mapping[0]['mindexer_id'], tvrage_show['indexer_id'])
  File "C:\SickRage\sickbeard\db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickRage\sickbeard\db.py", line 88, in execute
    return self._execute(query, args)
  File "C:\SickRage\sickbeard\db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
sqlite3.IntegrityError: column indexer_id is not unique
````

Thoughts?

**Comment by autronix** [comment] 2015-09-08 21:22
I am encountering a similar issue

```
2015-09-08 17:19:04 ERROR    Thread-54 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\Program Files (ext)\SickRage-master\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource
Traceback (most recent call last):
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\Program Files (ext)\SickRage-master\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource
2015-09-08 17:19:04 DEBUG    TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 257, in get
    results = yield self.async_call(method)
  File "C:\Program Files (ext)\SickRage-master\tornado\gen.py", line 807, in run
    value = future.result()
  File "C:\Program Files (ext)\SickRage-master\lib\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "C:\Program Files (ext)\SickRage-master\lib\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Program Files (ext)\SickRage-master\lib\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Program Files (ext)\SickRage-master\lib\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "C:\Program Files (ext)\SickRage-master\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\Program Files (ext)\SickRage-master\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files (ext)\SickRage-master\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\Program Files (ext)\SickRage-master\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource
```

**Comment by rrd911** [comment] 2015-09-08 21:28
My sickrage no longer starts as well with the latest commit

I get this when I try to start the service on Ubuntu 15.04
Job for sickbeard.service failed. See "systemctl status sickbeard.service" and "journalctl -xe" for details.

Details of each:
:~/sickrage$ systemctl status sickbeard.service
● sickbeard.service - LSB: starts instance of SickRage
   Loaded: loaded (/etc/init.d/sickbeard)
   Active: failed (Result: exit-code) since Tue 2015-09-08 14:20:57 PDT; 5min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 32291 ExecStop=/etc/init.d/sickbeard stop (code=exited, status=0/SUCCESS)
  Process: 1941 ExecStart=/etc/init.d/sickbeard start (code=exited, status=1/FAILURE)

Sep 08 14:20:57 rtr001 sickbeard[1941]: sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 88, in execute
Sep 08 14:20:57 rtr001 sickbeard[1941]: return self._execute(query, args)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 76, in _execute
Sep 08 14:20:57 rtr001 sickbeard[1941]: return self.connection.cursor().execute(query)
Sep 08 14:20:57 rtr001 sickbeard[1941]: sqlite3.IntegrityError: UNIQUE constraint failed: tv_shows.indexer_id
Sep 08 14:20:57 rtr001 systemd[1]: sickbeard.service: control process exited, code=exited status=1
Sep 08 14:20:57 rtr001 systemd[1]: Failed to start LSB: starts instance of SickRage.
Sep 08 14:20:57 rtr001 systemd[1]: Unit sickbeard.service entered failed state.
Sep 08 14:20:57 rtr001 systemd[1]: sickbeard.service failed.


journalctl -xe
Sep 08 14:19:04 rtr001 sickbeard[1798]: File "/home/raydias/sickrage/sickbeard/db.py", line 168, in action
Sep 08 14:19:04 rtr001 sickbeard[1798]: sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
Sep 08 14:19:04 rtr001 sickbeard[1798]: File "/home/raydias/sickrage/sickbeard/db.py", line 88, in execute
Sep 08 14:19:04 rtr001 sickbeard[1798]: return self._execute(query, args)
Sep 08 14:19:04 rtr001 sickbeard[1798]: File "/home/raydias/sickrage/sickbeard/db.py", line 76, in _execute
Sep 08 14:19:04 rtr001 sickbeard[1798]: return self.connection.cursor().execute(query)
Sep 08 14:19:04 rtr001 sickbeard[1798]: sqlite3.IntegrityError: UNIQUE constraint failed: tv_shows.indexer_id
Sep 08 14:19:04 rtr001 systemd[1]: sickbeard.service: control process exited, code=exited status=1
Sep 08 14:19:04 rtr001 systemd[1]: Failed to start LSB: starts instance of SickRage.
-- Subject: Unit sickbeard.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sickbeard.service has failed.
-- 
-- The result is failed.
Sep 08 14:19:04 rtr001 systemd[1]: Unit sickbeard.service entered failed state.
Sep 08 14:19:04 rtr001 systemd[1]: sickbeard.service failed.
Sep 08 14:19:04 rtr001 sudo[1769]: pam_unix(sudo:session): session closed for user root
Sep 08 14:19:04 rtr001 polkitd(authority=local)[797]: Unregistered Authentication Agent for unix-process:1770:180483752 (system bus name :1.332, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Sep 08 14:20:44 rtr001 sudo[1912]: raydias : TTY=pts/5 ; PWD=/home/raydias/sickrage ; USER=root ; COMMAND=/usr/sbin/service sickbeard start
Sep 08 14:20:44 rtr001 sudo[1912]: pam_unix(sudo:session): session opened for user root by raydias(uid=0)
Sep 08 14:20:44 rtr001 polkitd(authority=local)[797]: Registered Authentication Agent for unix-process:1913:180495021 (system bus name :1.333 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Sep 08 14:20:44 rtr001 systemd[1]: Starting LSB: starts instance of SickRage...
-- Subject: Unit sickbeard.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sickbeard.service has begun starting up.
Sep 08 14:20:44 rtr001 sickbeard[1941]: Starting SickBeard
Sep 08 14:20:57 rtr001 sickbeard[1941]: Traceback (most recent call last):
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "SickBeard.py", line 522, in <module>
Sep 08 14:20:57 rtr001 sickbeard[1941]: SickRage().start()
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "SickBeard.py", line 295, in start
Sep 08 14:20:57 rtr001 sickbeard[1941]: sickbeard.initialize(consoleLogging=self.consoleLogging)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/__init__.py", line 1308, in initialize
Sep 08 14:20:57 rtr001 sickbeard[1941]: db.sanityCheckDatabase(myDB, mainDB.MainSanityCheck)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 254, in sanityCheckDatabase
Sep 08 14:20:57 rtr001 sickbeard[1941]: sanity_check(connection).check()
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/databases/mainDB.py", line 46, in check
Sep 08 14:20:57 rtr001 sickbeard[1941]: self.convert_tvrage_to_tvdb()
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/databases/mainDB.py", line 77, in convert_tvrage_to_tvdb
Sep 08 14:20:57 rtr001 sickbeard[1941]: (INDEXER_TVDB, mapping[0]['mindexer_id'], tvrage_show['indexer_id'])
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 168, in action
Sep 08 14:20:57 rtr001 sickbeard[1941]: sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 88, in execute
Sep 08 14:20:57 rtr001 sickbeard[1941]: return self._execute(query, args)
Sep 08 14:20:57 rtr001 sickbeard[1941]: File "/home/raydias/sickrage/sickbeard/db.py", line 76, in _execute
Sep 08 14:20:57 rtr001 sickbeard[1941]: return self.connection.cursor().execute(query)
Sep 08 14:20:57 rtr001 sickbeard[1941]: sqlite3.IntegrityError: UNIQUE constraint failed: tv_shows.indexer_id
Sep 08 14:20:57 rtr001 systemd[1]: sickbeard.service: control process exited, code=exited status=1
Sep 08 14:20:57 rtr001 systemd[1]: Failed to start LSB: starts instance of SickRage.
-- Subject: Unit sickbeard.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sickbeard.service has failed.
-- 
-- The result is failed.
Sep 08 14:20:57 rtr001 systemd[1]: Unit sickbeard.service entered failed state.
Sep 08 14:20:57 rtr001 systemd[1]: sickbeard.service failed.
Sep 08 14:20:57 rtr001 sudo[1912]: pam_unix(sudo:session): session closed for user root
Sep 08 14:20:57 rtr001 polkitd(authority=local)[797]: Unregistered Authentication Agent for unix-process:1913:180495021 (system bus name :1.333, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)

**Comment by MGaetan89** [comment] 2015-09-08 21:53
Closing, as duplicate of #2693

**Closed by MGaetan89** 2015-09-08 21:53 UTC
