### ISSUE TITLE
LockFailed on Unraid/XFS in CacheControl

### ISSUE THREAD

**Issue by Holbert** [SiCKRAGETV/sickrage-issues#2118] opened 2015-07-15 03:08 UTC
### INFO
Python Version: **2.7.10 (default, May 26 2015, 04:16:29) [GCC 5.1.0]**
Operating System: **Linux-4.0.4-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045

### ERROR
```
2015-07-14 21:51:01 DEBUG    Thread-42 :: Searching for Show with searchterm: Pretty Little Liars on Indexer: theTVDB
2015-07-14 21:50:46 DEBUG    Thread-39 :: Searching for Show with searchterm: Pretty Little Liars on Indexer: theTVDB
```

### Expected
Tried to add show, but I keep getting **No results found, try a different search**. TVRage seems to be working, but I rather use TVDB. I've tried with proxy and without and still can't add show.

**Comment by miigotu** [comment] 2015-07-15 06:00
Update to newest master, and try unchecking the setting "SSL Verify" under config/general on the advanced tab.

**Comment by Holbert** [comment] 2015-07-15 06:26
No luck @miigotu 

```
2015-07-15 01:22:51 DEBUG    Thread-32 :: Searching for Show with searchterm: Suits on Indexer: theTVDB
2015-07-15 01:22:34 DEBUG    Thread-30 :: Searching for Show with searchterm: Pretty Little Liars on Indexer: theTVDB
2015-07-15 01:21:51 DEBUG    Thread-61 :: Checkout branch has the same DB version - Equal
2015-07-15 01:21:35 INFO     Thread-62 :: No update needed
2015-07-15 01:21:35 DEBUG    Thread-62 :: cur_commit = 608c06810abb05ab6e9d07947c86d42b1b1a21c2, newest_commit = 608c06810abb05ab6e9d07947c86d42b1b1a21c2, num_commits_behind = 0
2015-07-15 01:21:35 INFO     Thread-62 :: Checking for updates using SOURCE
```

**Comment by miigotu** [comment] 2015-07-15 07:23
Not sure how you are install SR, but something is not right there. class LockFailed(LockError): is definitly in lib/lockfile/__init__.py

**Comment by miigotu** [comment] 2015-07-15 07:34
EDIT: Develop and master are the same commit.

**Comment by Holbert** [comment] 2015-07-15 07:40
I have SR installed via a docker on Unraid. This docker specifically: https://registry.hub.docker.com/u/binhex/arch-sickrage/

**Comment by Holbert** [comment] 2015-07-15 07:50
Does this help at all?
```
Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/78804/en.xml: Traceback (most recent call last):
File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
resp = session.get(url.strip(), params=params)
File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
return self.request('GET', url, **kwargs)
File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/opt/sickrage/lib/requests/sessions.py", line 613, in send
r.content
File "/opt/sickrage/lib/requests/models.py", line 733, in content
self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
File "/opt/sickrage/lib/requests/models.py", line 656, in generate
for chunk in self.raw.stream(chunk_size, decode_content=True):
File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 273, in stream
data = self.read(amt=amt, decode_content=decode_content)
File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 203, in read
data = self._fp.read(amt)
File "/opt/sickrage/lib/cachecontrol/filewrapper.py", line 54, in read
self.__callback(self.__buf.getvalue())
File "/opt/sickrage/lib/cachecontrol/controller.py", line 244, in cache_response
self.serializer.dumps(request, response, body=body),
File "/opt/sickrage/lib/cachecontrol/caches/file_cache.py", line 99, in set
with self.lock_class(name) as lock:
File "/opt/sickrage/lib/lockfile/__init__.py", line 238, in __enter__
self.acquire()
File "/opt/sickrage/lib/lockfile/linklockfile.py", line 34, in acquire
raise LockFailed("%s" % e.strerror)
LockFailed: Function not implemented

```

**Comment by miigotu** [comment] 2015-07-15 08:57
@abeloin Know anything about this? Seems similar to chmod issue.

**Comment by miigotu** [comment] 2015-07-15 09:05
@Holbert what file system(s) are it using? This is a docker issue, with either os.link, os.stat, or os.unlink

**Comment by miigotu** [comment] 2015-07-15 09:12
Specifically os.link, this is probably related to unsupported filesystem.

**Comment by Holbert** [comment] 2015-07-15 09:12
XFS on Unraid 6. I believe it does have to do with the docker. I recently updated it and it seems to be giving me issues. I downloaded this one instead: https://registry.hub.docker.com/u/sparklyballs/beardrage/

It hasn't been updated since like May, but it works perfectly. I'm just going to not update it or anything so I at least having one that is working. I can post in the unRAID forums about this problem. The author of the docker that I have been using has a large support thread over there. He may see a way to fix the docker.

**Comment by miigotu** [comment] 2015-07-15 09:19
Just specifically ask about XFS and os.link in python, and any other limitations. It's not something we can fix here as it is within cachecontrol (which is a standard extension used for requests).

**Comment by miigotu** [comment] 2015-08-02 07:22
https://github.com/SiCKRAGETV/sickrage-issues/issues/2118#issuecomment-121540458

**Comment by Thraxis** [comment] 2015-08-10 22:07
@Holbert @miigotu @fernandog 

"LockFaild: Not Implemented" is a known issue with Unraid user shares. 

@Holbert 

use /mnt/cache/appdata/sickrage/  instead of /mnt/user/appdata/sickrage

**Comment by Holbert** [comment] 2015-08-11 04:25
@Thraxis 

So I need a cache drive for what you're saying correct? I currently don't have one.

**Comment by miigotu** [comment] 2015-08-11 04:27
@Holbert @Thraxis we have already established that using an older docker and it works, no?

**Comment by Holbert** [comment] 2015-08-11 04:34
@miigotu It worked for the most part, but there was a bit of a problem problem pulling artwork. I'm going to try and install the latest docker from binhex and see if it works now. Curious if switching my appdata to cache instead of the user share will alleviate my issues on the newer dockers. Going to throw in a small drive I have lying around to see if cache drive will help.

**Comment by MrFunbun** [comment] 2015-08-11 04:59
I'm using a cache drive with the latest docker and am having the same issue.

**Comment by Thraxis** [comment] 2015-08-11 05:01
Are you mapping your /config to /mnt/user/{something} or to
/mnt/cache/{something}

**Comment by MrFunbun** [comment] 2015-08-11 05:04
My fault I was looking at this last night and didn't see the update you put in with the /config mapping I changed it to /mnt/cache/appdata and it worked.

**Comment by miigotu** [comment] 2015-08-11 05:11
We need some wiki action for this issue... @neoatomic has been working on improving the wiki, but @Thraxis maybe you can add a page for unraid issues?

**Comment by LanMan04** [comment] 2015-08-11 19:50
FYI, I'm still using my ReiserFS-formatted disks on unRaid 6 (upgraded from unRaid 5) and I get this same issue when using the binhex docker version of sickrage (when using the "user" share instead of pointing directly at the cache disk).  Just FYI.

**Comment by miigotu** [comment] 2015-08-11 19:54
@LanMan04 so point it directly at the cache disk. it is an unraid limitation not a bug in SR.

**Comment by LanMan04** [comment] 2015-08-11 20:01
That's exactly what I did.

Interestingly, all other dockerized apps I have on unraid work fine using
the user share for their config folder.

**Comment by miigotu** [comment] 2015-08-11 20:04
Because they don't use cachecontrol, which uses file system locks, which unraid doesnt support.

**Comment by miigotu** [comment] 2015-08-14 10:47
There is a parameter to FileCache to specify lock_class, need to look into implementing a custom lock for unraid.

https://github.com/ionrock/cachecontrol/commit/e876506e4ce5f45fd397eddc2f1f82ea71eed328

**Comment by normtown** [comment] 2015-09-17 05:19
Is there a workaround for folks that don't have a cache drive?

**Comment by miigotu** [comment] 2015-09-17 05:25
negative

**Comment by normtown** [comment] 2015-09-17 05:28
Dang. Thanks for the info.

So, what exactly needs to be patched. Having trouble following where the
issue is or when it was introduced. Not sure how the pull request above is
related.

**Comment by miigotu** [comment] 2015-09-17 06:15
the code I referenced is a pointer to the code I need to utilize to male it work.

**Comment by normtown** [comment] 2015-09-17 13:58
Is it a library that is being consumed, or is it a similar change needs to
be made somewhere in SickRage?

**Comment by normtown** [comment] 2015-09-21 14:50
Is it possible to simply turn off the cache for the TVDB API? I see there's a cache flag in the constructor of the Tvdb class that forces us down branches depending on the cache, but a quick grep doesn't reveal where this is instantiated. I haven't been able trace down to whether there's a sane place to turn off this option.

Again, is pull request you linked to just an example of what needs to be implemented locally in SickRage, or is it for a library that SickRage is consuming?

Sorry for all the questions, I'm just trying to unblock myself and get SickRage working for me again without having to buy a cache disk for my unRaid server.

**Comment by miigotu** [comment] 2015-09-21 15:22
Its not the tvdb api. it is a python library (cachecontrol) which is used by requests.

**Comment by fernandog** [comment] 2015-09-30 02:07
@normtown can we close this? fixed?

**Closed** 2015-09-30 03:54 UTC
Labels: 1: Bug / issue, 3: Fixed, 4: Need feedback
