### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, instance found

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#650] opened 2015-02-18 07:31 UTC
### INFO
Python Version: **2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@e0204d048e2cfdf6ba27ee6f0a2800b8e942a1f0
Link to Log: https://gist.github.com/ef59bc00f8a77abdf8df
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, instance found
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment] 2015-02-18 08:02
Duplicate of #649

**Closed by abeloin** 2015-02-18 08:02 UTC
