### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '0.1'

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#911] opened 2015-03-10 21:33 UTC
### INFO
Python Version: **2.7.3 (default, Feb 27 2015, 20:47:22) 
[GCC 4.9.2]**
Operating System: **Linux-3.18.8-armv7l-with-glibc2.4**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
Link to Log: https://gist.github.com/90a4977ae62dd125fb35
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3719, in saveGeneral
    sickbeard.save_config()
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/__init__.py", line 1756, in save_config
    new_config['TORRENT']['torrent_seed_time'] = int(TORRENT_SEED_TIME)
ValueError: invalid literal for int() with base 10: '0.1'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-03-10 21:56
please set TORRENT SEED TIME to a integer in torrent settings

**Comment by fernandog** [comment] 2015-03-12 12:19
@abeloin 

Can we remove the INT() as this value can be float? in UI it increases in step of 0.1
    new_config['TORRENT']['torrent_seed_time'] = int(TORRENT_SEED_TIME)

or we change to float() ?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/__init__.py#L1756

**Comment by TagForce** [comment] 2015-03-12 12:48
In the UI you enter it in minutes, but using the API the seeding time is in integer seconds.
http://forum.utorrent.com/topic/21814-web-ui-api/?p=207446

So that call should actually be changed to round to an integer before sending:
time = int(3600 * float(sickbeard.TORRENT_SEED_TIME))
Otherwise you could send a float seconds which will revert to the default number of minutes (!!) you set in the UI.

So, I don't know what Transmission accepts as input for the API, but I think it'll be integer minutes.
In which case the actual call is good (cast to an integer before sending), it's just that sickbeard.TORRENT_SEED_TIME should accept either floats in minutes, or should be set in integer seconds and be rounded to the proper minimum value in the client.py files.

**Comment by fernandog** [comment] 2015-03-12 12:55
@TagForce 

it's hours in UI.

Minimum seeding time is [           ]  hours. (default:'0' passes blank to client and '-1' passes nothing)

**Comment by TagForce** [comment] 2015-03-12 13:10
@fernandog UI is not leading in this. Settings are transferred using API. I'll see if I can find out what it expects.

Yes, cast as an int, and multiply by 3600 for uT is correct. But why would we not change it to accept minutes instead of hours? Now I would need to set it to 0.00027 to get one minute of seeding time.

**Comment by fernandog** [comment] 2015-03-12 13:14
@TagForce not problem. Let's do minutes.
the problem is: what happens when user updates? They will have to change the value ? An error may occur?

**Comment by TagForce** [comment] 2015-03-12 13:23
@fernandog Yeah, it could throw errors... So we'd need to convert it...

Also, and maybe this is a bigger problem: transmission does not support a minimum seed time... What you're setting with minumum seeding time in SR is actually the Seed Idle Time Limit. If it's been inactive while seeding for sickbeard.TORRENT_SEED_TIME it will stop seeding. So it's not when seeding for sickbeard.TORRENT_SEED_TIME then stop, but when there's been no activity for sickbeard.TORRENT_SEED_TIME then stop (this could be after exactly sickbeard.TORRENT_SEED_TIME, but it could also be 5 months from today).

**Comment by abeloin** [comment] 2015-03-12 13:34
Why not simply multiple by 10 before saving and dividing by 10(except 0) when loading. This way you restore that functionality that was broken by the PR which converted torrent_seed_time from string to int

**Comment by TagForce** [comment] 2015-03-12 13:43
@abeloin If I want to set a time of 1 minute minimum seeding time in uTorrent, I'd have to enter 0.00027 in the current incarnation of sickbeard.TORRENT_SEED_TIME... No amount of multiplying by 10 will fix that :) 

Besides, transmission doesn't even support the min_seed_time setting... So a better idea would be to redo the torrent api settings page to include only those settings relevant to the client, and maybe add functionality that allows us to actually delete torrents from clients during a PP run. 

This will require a lot of code, and at least 1 more column in the database (to store the torrent hash), but I think that will solve all of the limitations in the code we now see.

Which is something that we should not do just yet... Maybe when all the other stuff is fixed and stable. This would be an excellent project to code in a 'experimental' branch :)

**Comment by fernandog** [comment] 2015-03-12 13:49
@TagForce I think there's a PR about adding torrent hash to DB. don't remember who did it

**Comment by TagForce** [comment] 2015-03-12 13:58
I know, that's why I brought it up here... I think using that as a starting point to overhaul the whole download client part in SR would be perfect.

**Comment by fernandog** [comment] 2015-03-12 13:59
let's ask @gborri to do it? =)

**Comment by TagForce** [comment] 2015-03-12 14:09
@fernandog I think this needs to be a team effort... And it needs a design before we do it...
Just so that we're all working towards the same goal :)
This is really a major overhaul, so we need to get this right.

**Comment by fernandog** [comment] 2015-03-12 14:10
yes. no problem!

**Comment by fernandog** [comment] 2015-03-12 14:11
@TagForce as for this issue, what should we do?

**Comment by gborri** [comment] 2015-03-12 14:13
@TagForce @fernandog @abeloin I've not got all your point.
I will try to explain what is in #1397 and what I have understood from your comment.

The point of PR 1307 is to store Hash on DB when torrent is snatched and remove it from trasmission (at the moment the remove procedure is built only for it) when post processed.

What i have understood from your conversation is to change seading time on trasmission (for all active torrent) when the parameter is changed on SickRage configuration, is it?

if this is what you would like to do  is feasible.

**Comment by TagForce** [comment] 2015-03-12 14:32
@gborri I know what's in your PR... We were discussing changing the minimum seed time option to allow for floats to be entered. I then checked uTorrent's API and found it was indeed in seconds (hence the 3600 multiplication to convert to hours), and when I checked Transmission's API docs, I noticed that it does not support minimum seed time (only seed idle time as explained above) and then had the idea that maybe we should overhaul the entire clients part of SR to reflect only those options for each client that they support, and add management features (like deleting torrents when done). That's when @fernandog mentioned your PR that adds a torrent hash column so it can be removed from transmission (which would also work for uTorrent if we add the code for that to utorrent.py).

So, we were discussing not just removing torrents, but the whole client system. If you feel that you can help us with that, you're welcome to. It's going to be a major undertaking, so we can use all the help we can get.

**Comment by fernandog** [comment] 2015-03-12 14:41
I would just rename the transmission setting in UI from "seed time" to "Stop Seeding When Inactive For" - the same as in Transmission UI

**Comment by gborri** [comment] 2015-03-12 14:52
@TagForce I'm not sure if i can help, but i can try.

**Comment by fernandog** [comment] 2015-03-12 15:00
In your PR can we call the remove at anytime we want? When PP for example ?

**Comment by abeloin** [comment] 2015-03-12 15:26
@fernandog Deluge doesn't support seed by time natively.

**Comment by fernandog** [comment] 2015-03-12 15:33
@abeloin any ideias how to fix this without break previous values?

**Comment by abeloin** [comment] 2015-03-12 15:40
I think for the time being, we should change the webui to only accept hours and add a notice for Transmission regarding being an idle timer.

This way we fix the issue for the time being, and later when the project scoping for the overhaul you talk about is done and implemented we migrate the value to utorrent seed_time and to transmission idle timer.

And if somebody complain about being unable to set the seed time to 1 min, we'll tell them it's currently a limitation in sickrage which will be resolved later.

**Comment by gborri** [comment] 2015-03-12 16:22
@fernandog you can call at any time the remove procedure. the key is hash in resut var. it is supposed to use it on PostProcess in order to remove after download is complete.

**Closed** 2015-03-13 13:10 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix
