### ISSUE TITLE
invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by Senaxx** [SiCKRAGETV/sickrage-issues#344] opened 2015-01-05 23:11 UTC
Branch: Develop
Commit hash: BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
Your operating system and python version: QNAP, Python 2.7.3 [GCC 4.2.3]
What you did: Adding a show and put the episodes on wanted
What happened: Generate error and did put the episodes on downloading
What you expected: Episodes where getting set on wanted and start downloading. 

````Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=272127&eps=1x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['1x1'], 'show': ['272127']}
_start_time: 1420499252.54
headers: {'Accept-Language': 'en-US,en;q=0.8,nl;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.45 Safari/537.36', 'Dnt': '1', 'Host': '217.121.161.107:8081', 'Referer': 'http://xxx.xxx.xxx.xxx.xxx:8081/home/displayShow?show=272127', 'Cookie': 'checkFW=; NAS_USER=admin; NAS_SID=uvw16s3r; home=1; QT=1420478002466'}
host: xxx.xxx.xxx.xxx:8081
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '1x1', 'show': '272127'}
_finish_time: None
query: show=272127&eps=1x1&status=undefined
path: /home/setStatus
method: GET
remote_ip: x.x.x.x

View Log(Errors)

**Comment by markheloking** [comment] 2015-01-06 10:23
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/285.

**Closed by markheloking** 2015-01-06 10:23 UTC
