### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>

### ISSUE THREAD

**Issue by icebal** [SiCKRAGETV/sickrage-issues#826] opened 2015-03-03 06:41 UTC
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@68cd0fa18e3ae75a368728aeaaae7913caf13db4
### ERROR
```
SEARCHQUEUE-BACKLOG-72454 :: [nzbgeek] :: Error while searching nzbgeek, skipping: charmap :  490 : error 0 : error 6 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment] 2015-03-03 07:45
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/823

**Closed by TagForce** 2015-03-03 07:45 UTC
