### ISSUE TITLE
After hachoir video quality guess, file operations return "Processing failed: File is locked for reading/writing"

### ISSUE THREAD

**Issue by schimi2k** [SiCKRAGETV/sickrage-issues#2534] opened 2015-08-21 09:33 UTC
Hello,
since last update my postprocess doesnt work anymore ( neither auto or manual ) - i get always this Error:

"...Processing failed: File is locked for reading/writing"

i am using: 
BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
Windows 10 Pro x64
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
EDIT:
teste also this python:
2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

the folders ( source and targets ) are not write protected, have full rights and when i test it with sickbeard it works without any problem - and it works here before the latest update also without any problems - i can move them manualy to the target folders also 
The target folders are empty and the source file is already renamed and they are not locked by any other service or so ( checked it with " what is locking this file ? ")
i tested also a different source ( different hdd ) - same problem

here is an example of my Debug Log:
https://gist.github.com/schimi2k/31c87fe2615064bfd44c

i hope you can fix this problem... i dont want back to the "old" sickbeard - and i like the sickrage icon so much hehe ;)

**Comment by WebSpider** [comment] 2015-08-21 09:50
Very possibly your torrent client is locking this file, or a stuck unrar process.

**Comment by schimi2k** [comment] 2015-08-21 09:58
first, big thx 4 the realy fast response 
1. i dont use any torrent client - i just use sickrage to "sort" my files to the right folders on my HDDs - i download them manually with sabnzbd 
2. like i wrote above - no service or any other tool is locking the files ( i just post one example, but i have test it with much more - every time with the same result )
and i can move them without any problems manualy and sickbeard works also
i have moved some already sorted files from series folder to my DL folder, and try the postprocess - same problem

so i think it must be something with sickrage, or better say, something after the latest updates ( works before realy great )

**Comment by miigotu** [comment] 2015-08-21 11:25
@schimi2k you cannot post process a file from and to the same dir.

root dir is your library, TV Download dir in PP is the dir your downloader puts unprocessed files (this cannot be the root dir, or have the root dir inside it).

If you want to add existing shows use add existing, after fixing your dirs.

**Comment by schimi2k** [comment] 2015-08-21 11:56
thx 4 answer @miigotu
i dont know if you can see it in my log file but i dont want to PP in the same dir ;)
i have a seperate DL folder - and from this folder i copy and rename the files to a "finish" folder
from this finish folder SickRage should take the file and put it to the folder on another HDD, where my TV Series is stored 
Source folder is on : j:\DOWNLOADS\FINISH\    
Dest.Folder is on different HDDs ( in my example: k:\SERIEN-K\STAR WARS REBELS\ )

and like i wrote before - it work everything perfect before the latest updates ( dont know if it was the realy last update, or maybe the update before that ... but it work 100% a week ago )
and i dont change anything !

i hope its clear now ? :)

**Comment by WebSpider** [comment] 2015-08-21 16:58
@schimi2k were you on Win10 when it worked? I know some filesystem changes were done in Win10..

**Comment by schimi2k** [comment] 2015-08-21 17:04
yes sir - i was on win10 when everything works
i have posted this problem also in your support forum, and there are other 2 with the same problem... i asked them to post their logs here too... maybe this would make it easier for you to find the "glitch"

**Comment by miigotu** [comment] 2015-08-21 17:15
@schimi2k my bad, wrote that as I was falling asleep.

**Comment by schimi2k** [comment] 2015-08-21 17:17
no problem :) i just hope ypu find a way to fix that - i realy like sickrage and your work :+1:

**Comment by Tragalix** [comment] 2015-08-21 18:11
I've the same issue. Whether the torrent client provides the file to the PP or if I manually copy a file to the folder the PP is watching most files will report as being "locked for reading/writing" when the PP runs. I say 'most' because occasionally the odd file will make it through. I've had process explorer open prior and during PP and the only process that is locking the files is Python.exe itself. I am opting to move the files rather than copy if that matters.

Python 2.7.10
BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
Windows Server 2008 R2

**Comment by neoatomic** [comment] 2015-08-21 18:50
@Tragalix Are you also moving the files also across different disks.?
And can you provide full logs.?

**Comment by miigotu** [comment] 2015-08-21 19:20
@Tragalix

Can you stop SR, open sickbeard/common.py and comment lines 262-264 like this:
```python
#        quality = Quality.qualityFromFileMeta(name)
#        if quality != Quality.UNKNOWN:
#            return quality
```

Start SR and try that again?

**Comment by schimi2k** [comment] 2015-08-21 21:06
hmmm i am sorry, i am not Tragalix, but it seems to work here with this "fix"

thx ;)

**Comment by miigotu** [comment] 2015-08-21 21:38
@WebSpider `del parser` on line 287 maybe? seems hachoir isnt closing the file fast enough for the pp.

**Comment by paulcanning** [comment] 2015-08-24 20:23
Hi, I am on Win7, 64bit, SR v4.0.51 and have just started getting this error. New files are moved to a temp folder, full access, and processing fails to move then, with the error log stating the file is locked. When I use an unlocker program, it says the file is locked by python.exe! This never used to happen.

**Comment by miigotu** [comment] 2015-08-25 05:31
Testing a commit I made for a potential fix to this issue now.

**Comment by MikeRatcliffe** [comment] 2015-08-25 10:56
I have the same issue on Ubuntu even after pulling these changes. Here are my startup logs if that helps:
```
2015-08-25 11:50:59 ERROR    CHECKVERSION :: Unable to contact github, can't check for update
AAfatal: HTTP request failed
2015-08-25 11:50:59 WARNING  CHECKVERSION :: "/usr/bin/git" fetch origin returned : error: The requested URL returned error: 403 while accessing https://github.com/SiCKRAGETV/SickRage.git/info/refs
2015-08-25 11:50:44 WARNING  POSTPROCESSER :: [/media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv : Processing failed: File is locked for reading/writing]
2015-08-25 11:50:44 WARNING  POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  
2015-08-25 11:50:44 WARNING  POSTPROCESSER :: Processing failed for /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv: File is locked for reading/writing
2015-08-25 11:50:44 INFO     POSTPROCESSER :: Processing /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv (None)
2015-08-25 11:50:44 INFO     POSTPROCESSER :: PostProcessing Path: /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads
2015-08-25 11:48:44 WARNING  POSTPROCESSER :: [/media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv : Processing failed: File is locked for reading/writing]
2015-08-25 11:48:44 WARNING  POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  
2015-08-25 11:48:44 WARNING  POSTPROCESSER :: Processing failed for /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv: File is locked for reading/writing
2015-08-25 11:48:44 INFO     POSTPROCESSER :: Processing /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads/The.Strain.S02E07.The.Born.720p.WEB-DL.DD5.1.H.264-Juggalotus-NZBgeek/I6PNSWC3YcvDomXUzF8DJ2YwXdj372QKIk9aiXcGnD8.mkv (None)
2015-08-25 11:48:43 INFO     MAIN :: Building internal name cache for all shows
2015-08-25 11:48:43 INFO     POSTPROCESSER :: PostProcessing Path: /media/f923c83e-8873-41ef-8948-09d7ba69ad9a/nzbget/downloads
```

**Comment by MikeRatcliffe** [comment] 2015-08-25 11:32
Interestingly, renaming the file from bash works fine and then Sickrage again fails to process the renamed file with the same error message.

If there is anything you need from me then let me know.

**Comment by KrisBone** [comment] 2015-08-25 12:22
I have practically identical logs on three separate machines, running Win 8.1/64bit, Win 7/64bit & Linux Mint 17.2 Rafaela/64bit install.
All are installed at different houses and have completely different linked systems (file manager, scripts, clients, etc)
All have just been pulled to BRANCH: (master) / COMMIT: (3fb81bd65d7710e59d6c89945a3be39d2dbfc386) and retested.

**Comment by fernandog** [comment] 2015-08-25 12:50
Lock check feature is windows only.

**Comment by schimi2k** [comment] 2015-08-25 17:13
hmmm i get again the same problems again after your last (?) update ? noticed it today that my downloads wont be post processed again :( after i add the "fix" from miigotu ( comment out line 262-264 ) its working again... is this means now, that i have always change this after any update ?

**Comment by miigotu** [comment] 2015-08-25 20:50
I'll look into a more complicated fix, and maybe ask the hachoir dev about this issue.

**Comment by miigotu** [comment] 2015-08-26 04:01
https://bitbucket.org/haypo/hachoir/issues/56/file-locked-for-reading-writing-after

**Comment by Franckk01** [comment] 2015-08-26 22:38
Hi,

I have the same message "Processing failed: File is locked for reading/writing" when post processing. For me it seems to be a rights issue, because I simply have to set "chmod -R 777 /mnt/media/Temp" which is my torrent finished download directory, for it can work. 
But for each new torrent downloaded, I have to do this again. When I make "ls -l", new downloaded files doesnt have the good rights. Any idea for not having to do this each time ?

I dont know if i'm clear...sorry

I use Transmission for Torrent client, on a Raspebrry Pi2 running on OSMC.

Thx

**Comment by miigotu** [comment] 2015-08-26 22:46
@Franckk01 you need to stop transmission and set umask to 0 in settings.json for transmission.

If you are using debian or ubuntu and transmission-daemon, that file is at `/etc/transmission-daemon/settings.json`

**Comment by miigotu** [comment] 2015-08-26 22:51
https://bitbucket.org/haypo/hachoir/issues/33/open-file-handles-never-closed

ugh. Need to fix that and send a PR. 
Also TODO: figure out if hachoir3 supports python2.7 still, as hachoir is no longer maintained and does not support python3 either.

**Comment by Franckk01** [comment] 2015-08-26 22:53
@miigotu Thank you ! I should have post long time ago !!

**Comment by WebSpider** [comment] 2015-08-27 02:00
Possible alternative for hachoir to help guessing video quality may be ffprobe from ffmpeg.

-----Original Message-----

**Comment by miigotu** [comment] 2015-08-27 02:16
Hachoir was chosen over mediainfo/ffprobe because it is pure python and doesn't add external binary dependancies

**Comment by miigotu** [comment] 2015-08-27 02:20
@WebSpider still trying to determine if hachoir3 works for Python 2.7, if it does that's a perfectly good option as it is still maintained and it supports Python 3

**Comment by ripper1967** [comment] 2015-08-28 12:35
Having same problem

**Comment by skydiverscott** [comment] 2015-08-28 23:57
Having same issue on Windows Home Server 2011

**Comment by Morphy99** [comment] 2015-08-30 13:43
Same here win7 x64

**Comment by miigotu** [comment] 2015-08-30 13:53
No shit. =P

**Comment by WebSpider** [comment] 2015-08-31 06:15
@miigotu haypo posted in the bitbucket issue that he wasnt planning on supporting hachoir3 ?

**Comment by miigotu** [comment] 2015-08-31 06:20
@WebSpider yes, and also hachoir itself is no longer maintained/supported, unless we submit fixes ourself.

I think I have a dirty patch that might hackfix hachoir open file handles for us, but without being able to reproduce it (idk why) it is hard to test.

Since the parser is not a class its difficult to store the handle, and the handle is passed through multiple modules of hachoir. I think I will just add a global in hachoir_parser that stores the handle, and then add a method that closes the file handle stored in the global.

Maybe we need to fork off and do some serious changes to hachoir, along with making it work for python3, since hachoir3 requires 3.4+ -.-

Some of these library module developers are not following good practices for portability and api compatibility between versions sadly. (cough subliminal)

**Comment by miigotu** [comment] 2015-08-31 06:23
I think the global will be a dict with the keys being the filename of the open file handle, and the value being the open file, so that we can stay semi thread safe (it wont be perfect unless we classify it and use it as an object) and handle multiple open files at a time.

**Comment by miigotu** [comment] 2015-08-31 07:46
Please test the latest commit to develop, and if it is still failing ping me here. Closing this for now.

**Closed by miigotu** 2015-08-31 07:46 UTC
Labels: 1: Bug / issue, 3: Fix, branch: develop

**Comment by stourwalk** [comment] 2015-10-08 03:57
Assuming that this fix is in master now - I'm still getting the same error as of today

**Comment by miigotu** [comment] 2015-10-08 05:42
You must not be really up to date (updater might be lying).

**Comment by dev-zero** [comment] 2015-10-16 13:57
I still see this error on master (136f531f93093a5287b588ca37e19c11153f47a4):

```
Oct 16 15:52:46 localhost SickBeard.py[6155]: 15:52:46 ERROR::POSTPROCESSER :: Processing failed for /somehwere/whatever.mkv: File is locked for reading/writing
Oct 16 15:52:46 localhost SickBeard.py[6155]: Traceback (most recent call last):
Oct 16 15:52:46 localhost SickBeard.py[6155]: File "/opt/sickbeard/sickbeard/processTV.py", line 555, in process_media
Oct 16 15:52:46 localhost SickBeard.py[6155]: result.result = processor.process()
Oct 16 15:52:46 localhost SickBeard.py[6155]: File "/opt/sickbeard/sickbeard/postProcessor.py", line 1056, in process
Oct 16 15:52:46 localhost SickBeard.py[6155]: raise EpisodePostProcessingFailedException("File is locked for reading/writing")
Oct 16 15:52:46 localhost SickBeard.py[6155]: EpisodePostProcessingFailedException: File is locked for reading/writing
Oct 16 15:52:46 localhost SickBeard.py[6155]: 15:52:46 ERROR::POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:
Oct 16 15:52:46 localhost SickBeard.py[6155]: None
Oct 16 15:52:46 localhost SickBeard.py[6155]: 15:52:46 ERROR::POSTPROCESSER :: [/somehwere/whatever.mkv : Processing failed: File is locked for reading/writing]
Oct 16 15:52:46 localhost SickBeard.py[6155]: None
```

**Comment by miigotu** [comment] 2015-10-16 16:41
Not caused by this issue, which has been fixed, and verified.
