### ISSUE TITLE
Propers and repacks stay in Snatched (Proper) status

### ISSUE THREAD

**Issue by goatbased** [SiCKRAGETV/sickrage-issues#1074] opened 2015-03-31 02:01 UTC
Hi guys,
Having a bit of an issue with propers and repacks. It's happened a few times and, try as I might, haven't been able to figure out how to work around this so I thought it might be time to open a bug report. I know this branch is a few days old--this issue has been happening for at least a month and across multiple commits. I've since updated and I'm waiting to see if the issue happens again. The nature of the problem is that I have to wait for a proper to be released in order to invoke the suspected bug so I thought I'd at least get this process rolling before it happens again.

Full details on how to replicate the problem:
1) SickRage identifies a new episode of a show (last night, The Walking Dead). Snatches and stores the .torrent in blackhole. uTorrent picks it up downloads and places in the TV Download Dir for post processing.
2) Post processing runs, moves the file to the correct location and marks the episode as "Downloaded (SD TV)" or "Downloaded (HD TV)" or whatever the format is.
3) Proper or repack is released.
4) SR runs the proper search. SR finds the proper and, as expected, downloads the torrent to blackhole. uTorrent finds the torrent file, downloads the content, and places it in the TV Download Dir for post processing.  All is well up until this point.
5) Post processing runs, moves the file to the correct location however does NOT mark the episode as "Downloaded" in the show. The status of the episode remains as "Snatched (Proper) [xx] TV"
6) Some time later, proper search runs again, another proper is often found, downloaded, processed, and still, status remains as "Snatched (Proper)"
7) goto 4 for as many propers as have been released.

At no point in the process does SR actually mark the completed and post processed proper as "Downloaded". I can do so by hand but it would seem that something isn't working as intended in this process.  The most recent time this has happened was for yesterday's episode of The Walking Dead (S05E16) for which I have logs, but I've seen it happen for a bunch of other episodes of various shows for the past month or so.

Edit: forcing a re-scan of the show does not seem to help either.

I would expect that, upon completion and post processing of the proper or repack, SR would mark the episode as Downloaded and call it finished. I'm also willing to admit that my understanding of the logic is incorrect or that I have a configuration issue. Either way, would appreciate someone having a look.

BRANCH: (master) / COMMIT: (4b40fceda883f76174672ab4e1423f3713e037ca) 
Windows 7 x86, Python 2.7

Logs for the past 24+ hours which show the issue happening can be found at https://www.dropbox.com/sh/5tqhb91yxsyw509/AACQCzeTP1byjnVXgPMZmawca?dl=0

I do have logs going back further and can post them if necessary.

Thanks fellas

**Comment by brimur** [comment] 2015-03-31 10:40
I guess I am not the only one then

**Comment by fernandog** [comment] 2015-03-31 10:50
@tagforce

**Comment by TagForce** [comment] 2015-03-31 10:58
Hmmm... Post Processing for Propers is in no way different from Post Processing regular episodes, other than they get accepted as a replacement for an existing episode file.

Since regular eps seem to work just fine, I can narrow down where it could go wrong... Let me have a quick look.

**Comment by TagForce** [comment] 2015-03-31 11:49
@goatbased @brimur I scanned through the code, but couldn't find an obvious issue... I'll have to try and force this by making SR believe it has snatched a proper, and then having it Post Process it... I can't do that at the moment, but I will when I get home in a few hours.

**Comment by brimur** [comment] 2015-03-31 13:09
Just wanted to add an observation from me. The common thing between all of them is that a [rarbg] is downloaded and then a different release is

**Comment by TagForce** [comment] 2015-03-31 14:05
@brimur @fernandog @abeloin We're going to have to remove those tags from release names... They're causing issues all over the place.

@brimur Do you have rarbg set as a provider?

**Comment by abeloin** [comment] 2015-03-31 14:11
@TagForce Ok, I will see the regex that need to be modified

**Comment by brimur** [comment] 2015-03-31 14:22
@TagForce Not specifically no, I just look for the release and I have noticed that when the issue occurs a [rargb] is involved

**Comment by TagForce** [comment] 2015-03-31 14:25
@brimur The problem (I think) is that since the [rarbg] is added to the releasename, SR thinks that the full release group name is RLSGROUP[rarbg] instead of just RLSGROUP... This causes it to not see that we actually already have this proper, and starts happily downloading it again.

**Comment by brimur** [comment] 2015-03-31 14:31
@TagForce Agreed but the issue is why does it download it when it has already found the proper. As in..
1. Release comes out Tv.Show.S01E01.HDTV.x264-KILLERS.mkv which is nuked
2. A proper is released Tv.Show.S01E01.PROPER.HDTV.x264-KILLERS
3. SR searches for the proper and snatches Tv.Show.S01E01.PROPER.HDTV.x264-KILLERS and downloads it
4. <THIS STEP SHOULD NO BE REACHED> SR has snatched the proper but keeps looking and downloads the proper again from a "different" release group 

Step 4 is the issue I think, once SR finds the first proper regardless of the release it should stop searching

**Comment by TagForce** [comment] 2015-03-31 14:50
@brimur It keeps looking for as long as the proper hasn't completed downloading. If it finds the rarbg one before it PPs the old one, then it will still download it (that's part of the problem... It doesn't realise the rarbg one is the same, because of the provider tag added to it, which it should totally ignore). I don't 'speak' regex, so that's why I asked Alex to help fix that part. As for the episode remaining in the status snatched proper, that's something I will try to fix later.

**Comment by brimur** [comment] 2015-03-31 14:58
That is an interesting one alright, so the PROPER processor must be different than the normal release processor since its looking at the release group instead of just for the show name, season/episode number with the added word PROPER otherwise it would happen with normal releases from different release groups too.

**Comment by TagForce** [comment] 2015-03-31 15:09
Yeah, the search for Propers is slightly different from the normal search. But not so much different that this should be an issue...

**Comment by goatbased** [comment] 2015-04-01 04:56
@brimur You sparked my curiosity about the relase group tagging. I just went back and examined the history of this on my machine. I see this happening across multiple different release groups besides rarbg.

**Comment by brimur** [comment] 2015-04-01 07:54
It looks like its not just Propers either. SR downloaded two versions of the same file last night...

http://i.imgur.com/OR7Jo2e.png

**Comment by brimur** [comment] 2015-04-01 07:54
It looks like its not just Propers either. SR downloaded two versions of the same file last night...

http://i.imgur.com/OR7Jo2e.png

**Comment by brimur** [comment] 2015-04-01 07:55
It looks like its not just Propers either. SR downloaded two versions of the same file last night...

http://i.imgur.com/OR7Jo2e.png

**Comment by abeloin** [comment] 2015-04-02 02:39
PR fix rarbg tag for rarbg: https://github.com/SiCKRAGETV/SickRage/pull/1698

@brimur The invalid proper where from which provider in your case?

**Comment by brimur** [comment] 2015-04-02 11:23
@abeloin  The above Ripsalot one was from Old Pirate Bay and the KILLERS[brassetv] came from a custom rss feed I setup for Torlock

**Comment by abeloin** [comment] 2015-04-02 11:26
PR fix for KAT: https://github.com/SiCKRAGETV/SickRage/pull/1700

**Comment by abeloin** [comment] 2015-04-04 02:48
https://github.com/SiCKRAGETV/SickRage/pull/1703

**Comment by abeloin** [comment] 2015-04-04 02:48
The fix will be merged into master on Sunday

**Comment by abeloin** [comment] 2015-04-05 19:57
PR merged please test

**Comment by goatbased** [comment] 2015-04-07 03:10
Thanks guys. I'll keep an eye on this one and will let you know the next time I see a proper get picked up and what the behavior was.

**Comment by brimur** [comment] 2015-04-10 10:08
@abeloin I thought things were ok but something strange happened again today. An ep came down and was processed and then a few hours later another one was downloaded from a different release and even though the original was 500MBs it was replaced by the new one which was only 80MBs

http://i.imgur.com/Z5dMjP2.png

````
2015-04-10 10:36:25 INFO     POSTPROCESSER :: Processing succeeded for /media/disk2/downloads/TV/The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv
2015-04-10 10:36:24 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Moving file from /media/disk2/downloads/TV/The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv to /mnt/TV Shows/The Big Bang Theory/Season 8/The Big Bang Theory - 8x20 - The Fortification Implementation.mkv
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Found release name The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: File /mnt/TV Shows/The Big Bang Theory/Season 8/The Big Bang Theory - 8x20 - The Fortification Implementation.mkv is larger than /media/disk2/downloads/TV/The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Converted parsed result The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 INFO     POSTPROCESSER :: Analyzing name u'The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv'
2015-04-10 10:36:20 INFO     POSTPROCESSER :: Processing /media/disk2/downloads/TV/The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv (None)
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-10 10:36:20 DEBUG    POSTPROCESSER :: Parsed The.Big.Bang.Theory.S08E20.720p.HDTV.x264.AAC-fullfuntoo.mkv into The Big Bang Theory - S8E20 [ANIME VER: -1] [GROUP: fullfuntoo] [ABD: False] [ANIME: False] [whichReg: ['standard']]

````

**Comment by abeloin** [comment] 2015-04-10 10:40
@brimur Can you provider the whole log for that period?

**Comment by brimur** [comment] 2015-04-10 11:18
@abeloin All logs here.. http://www.filedropper.com/logs_3

**Comment by abeloin** [comment] 2015-04-10 11:31
Ok, disable old pirate bay for now. It's return [invalid results](https://oldpiratebay.org/search.php?q=The.Big.Bang.Theory+S08E20|8x20+PROPER|REPACK&Torrent_sort=seeders.desc)

```
2015-04-10 10:06:24 DEBUG    FINDPROPERS :: [OldPirateBay] :: Search string: https://oldpiratebay.org/search.php?q=TBBT%20S08E20%7C8x20%20PROPER%7CREPACK&Torrent_sort=seeders.desc
2015-04-10 10:06:25 DEBUG    FINDPROPERS :: [OldPirateBay] :: Search string: https://oldpiratebay.org/search.php?q=The.Big.Bang.Theory%20S08E20%7C8x20%20PROPER%7CREPACK&Torrent_sort=seeders.desc
2015-04-10 10:06:31 DEBUG    FINDPROPERS :: [OldPirateBay] :: Search string: https://oldpiratebay.org/search.php?q=Big.Bang.Theory%20S08E20%7C8x20%20PROPER%7CREPACK&Torrent_sort=seeders.desc
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-HDTV-x264-LOL-ettv
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-720p-HDTV-x264-AAC-fullfuntoo-mkv
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-The-Fortification-Implementation-1080p-WEB-DL-DD5-1-H-264-YFN
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-The-Fortification-Implementation-720p-WEB-DL-DD5-1-H-264-YFN
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-720p-HDTV-x265-HEVC-RMTeam-AuP
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S08E20-1080p-HDTV-X264-DIMENSION
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-Season-1-MP4-repack-mad-madhav
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S04E18-REPACK-HDTV-XviD-ASAP-VTV-avi
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S04E18-REPACK-HDTV-XviD-ASAP
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: The-Big-Bang-Theory-S03E12-REPACK-HDTV-XviD-NoTV
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Found new proper: Greys-Anatomy-S05E01-REPACK-PROPER-720p-HDTV-x264-CTU-www-CrikeyM8-com
2015-04-10 10:06:33 DEBUG    FINDPROPERS :: Using ALL regexes
```

**Comment by abeloin** [comment] 2015-04-10 11:47
@brimur If you want to test the fix, replace sickbeard/providers/oldpiratebay.py with this one https://raw.githubusercontent.com/abeloin/SickRage/patch-oldpiratebay/sickbeard/providers/oldpiratebay.py

**Comment by goatbased** [comment] 2015-04-10 21:36
So far so good for me, guys. I had a proper download yesterday and everything looked good. Though, I will say, the proper was a fresh download and was not replacing a previously downloaded episode so perhaps not a perfect example.

**Closed** 2015-04-10 22:47 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback
