### ISSUE TITLE
[APP SUBMITTED]: list index out of range

### ISSUE THREAD

**Issue by thomasbriet** [SiCKRAGETV/sickrage-issues#1427] opened 2015-04-26 16:10 UTC
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/0ae6b0e59e5681f91495
### ERROR
```
TRAKTROLLING :: Exception generated in thread TRAKTROLLING: list index out of range
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

I'm trying to use the TRAKT rolling service. But i get an error when the service should kick in. Also on the check status page Trakt Rolling is not alive.

![schermafbeelding 2015-04-26 om 18 15 20](https://cloud.githubusercontent.com/assets/8377373/7338068/42710e9e-ec40-11e4-8e95-412987e432db.png)

Maybe this will help also, my preferences for trakt notifications 

![schermafbeelding 2015-04-26 om 18 25 16](https://cloud.githubusercontent.com/assets/8377373/7338123/0a3f86c0-ec42-11e4-82f6-bb1f4ddbf925.png)

**Comment by fernandog** [comment] 2015-04-26 16:15
@gborri please check this

**Comment by miigotu** [comment] 2015-04-26 16:53
The code there seems messy.
Possibly @ https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/traktChecker.py#L732
should be :
```
for x in range(0,num_of_ep - 1):
```
or
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/traktChecker.py#L725
should be
```
for x in range(0,num_of_ep - 1):
```
or
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/traktChecker.py#L725
should be
```
num_of_ep = num_of_download - (self._num_ep_for_season(last_per_season, sn_sb, ep_sb) - self._num_ep_for_season(last_per_season, season, episode))
```
(without + 1) at the end

**Comment by gborri** [comment] 2015-04-26 20:25
@thomasbriet I've tryed to reproduce but have no chance (same show). It's happen to me that the red colour on server status is happening when trakt 401 unautorize error occured. try to test it. Have you added the show through trakt watchlist?

**Comment by thomasbriet** [comment] 2015-04-26 20:41
The first time i added the shows to my watchlist on Trakt the first episodes were downloaded, so there is no/ should not be an/ authorazation issue. I've then turned the option to trakt roll to on and the first 3 episodes were downloaded, but now after watching the first 3 episodes it should download the next 3 episodes /because trakt notifies the watched episodes/, but it gives an error before it has the chance. Also when i add an episode to my watchlist from trakt there is no collaboration between the two programs.

**Comment by gregtotheizzo** [comment] 2015-04-26 20:47
my trakt doesn't work at all. 

To get it working are we using the trakt api for apiv2? Or username for apiv1?

**Comment by gborri** [comment] 2015-04-26 21:13
@thomasbriet if you want to make episode wanted from watchlist you need to enable sync watchlist

**Comment by gborri** [comment] 2015-04-26 21:14
@thomasbriet can you restart sickrage and provide full log?

**Comment by thomasbriet** [comment] 2015-04-27 10:47
I'm not home right now due to Kings Day here in Holland, but i will try as soon as i get home.

**Comment by thomasbriet** [comment] 2015-04-27 19:09
@gborri I just restarted Sickrage and here is the log it created.
http://pastebin.com/2ADVb4Vi

I'm not sure when the restart is initiated in the log, but i think you should find it ;)

**Comment by gborri** [comment] 2015-04-27 19:30
@thomasbriet i see that the traktrolling function was working correctly, at least this time. could you try to reproduce the problem and send full log?

**Comment by thomasbriet** [comment] 2015-04-27 21:19
@gborri You are correct, the service was "alive". But when i restarted again, i got the error again. Here is the full log.

http://pastebin.com/THmgVWPg

**Comment by thomasbriet** [comment] 2015-04-29 16:26
@gborri did you find anything?

**Comment by gborri** [comment] 2015-04-29 16:50
@thomasbriet probably it's related to trakt returning empty value

**Comment by gborri** [comment] 2015-04-29 16:58
@thomasbriet please add the log line as follow and resend full log when happens again

            last_per_season = self.trakt_api.traktRequest("shows/" + str(imdb_id) + "/seasons?extended=full")

            logger.log(u"last_per_season: " + str(last_per_season), logger.DEBUG)

            if not last_per_season:

**Comment by thomasbriet** [comment] 2015-04-30 17:55
Sorry for this noob question, but where can i find this file? I'm working with a Synology.

**Comment by gborri** [comment] 2015-04-30 19:05
@thomasbriet I think it's a problem of data returned from trakt randomly. from your log seem to happen on show with lot of season....

**Comment by thomasbriet** [comment] 2015-05-02 20:47
@gborri The error occurred again.
The exact time was at 21:53:34

Here is the log: https://gist.github.com/d3f8c8db779d9f6c3ddf.git

**Comment by gborri** [comment] 2015-05-02 21:27
@thomasbriet i can't read the log file, empty page.

**Comment by gborri** [comment] 2015-05-02 21:36
@thomasbriet have you inserted the log line? i can't see it in debug....

**Comment by thomasbriet** [comment] 2015-05-02 21:37
@gborri You mean this?
'''
2015-05-02 21:53:34 ERROR    TRAKTROLLING :: Exception generated in thread TRAKTROLLING: list index out of range
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 97, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 636, in run
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 737, in updateWantedList
IndexError: list index out of range
'''

**Comment by gborri** [comment] 2015-05-02 21:58
@thomasbriet yes. but i can't find "last_per_season: " tag on log ...

**Comment by thomasbriet** [comment] 2015-05-02 22:38
I did put the above line in traktChecker.py so it should be there. Or is there a mistake in the line?

**Comment by gborri** [comment] 2015-05-03 06:20
Should? Could you check?

Il giorno dom 3 mag 2015 00:38 thomasbriet <notifications@github.com> ha
scritto:

**Comment by thomasbriet** [comment] 2015-05-03 07:45
It's in the code.. Don't know if it's loading...

**Comment by miigotu** [comment] 2015-05-03 09:17
@thomasbriet can you try this:

find the line (mine is line # 725):
`num_of_ep = num_of_download - (self._num_ep_for_season(last_per_season, sn_sb, ep_sb) - self._num_ep_for_season(last_per_season, season, episode)) + 1`

and try removing the ` + 1` from the end, and see if the out of bounds still happens.

**Comment by miigotu** [comment] 2015-05-03 09:21
@gborri mind if I try and make that code more easy to follow tomorrow? Takes a bit to realize what some of the variables are, and I think it can be simplified some.

**Comment by gborri** [comment] 2015-05-03 16:12
You could, but the problem is not in that peace of code. The problem is
related to the last_per_season retrieved by trakt

Il giorno dom 3 mag 2015 11:21 Dustyn Wayne Gibson <notifications@github.com>
ha scritto:

**Comment by miigotu** [comment] 2015-05-03 19:23
Do we know what the failing last_per_season holds? I just wanted to make the code clearer, not that its where its failing.

**Comment by papampi** [comment] 2015-05-18 04:18
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment] 2015-05-18 06:54
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/114d8bc16cb91e10dfd1
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment] 2015-05-18 08:07
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/bf197528d92f2d8673d3
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment] 2015-05-18 08:20
app submitted qbittorrent problem here , but I dont think its related to same problem.

**Comment by miigotu** [comment] 2015-05-18 08:24
@papampi yes I know, and the qbittorrent problem has already been reported in another issue.

**Comment by thomasbriet** [comment] 2015-05-18 22:11
I can't seem to reproduce the problem anymore. I did update SickRage to the latest version, but i doubt it has something to do with that?

**Comment by miigotu** [comment] 2015-05-19 02:04
A week or two ago there was a change to trakt api committed, maybe you just got it.

**Closed by miigotu** 2015-05-19 02:04 UTC
Labels: 1: Bug / issue, 3: Confirmed, 4: Fix pending
