### ISSUE TITLE
Error special char i think after new upgrade

### ISSUE THREAD

**Issue by valantislevas** [SiCKRAGETV/sickrage-issues#122] opened 2014-12-17 18:36 UTC
After new upgrade on devel version i have this problem

my action: tried manually search of episode also daily search cant download..

SR Version:	BRANCH: (develop) / COMMIT: (3147ff2ae59a9557dd5e70e6a45044e423a9d7c8) 
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

```
2014-12-17 19:30:25 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Failed to download result
AA
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 70: ordinal not in range(128)
AA    with open(filename, 'wb') as fp:
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1250, in download_file
2014-12-17 19:30:25 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Unknown exception while loading URL http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30089: Traceback (most recent call last):
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Criminal.Minds.S10E08.HDTV.XviD-AFG[DEFTv™] from trackerrrrdomain
AAIndexError: list index out of range
AA    torrent_hash = re.findall('urn:btih:([\w]{32,40})', result.url)[0].upper()
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 142, in downloadResult
AATraceback (most recent call last):
2014-12-17 19:30:25 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Failed to download result
AA
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 70: ordinal not in range(128)
AA    with open(filename, 'wb') as fp:
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1250, in download_file
2014-12-17 19:30:25 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Unknown exception while loading URL http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30087: Traceback (most recent call last):
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Criminal.Minds.S10E06.HDTV.XviD-AFG[DEFTv™] from trackerrrrdomain
AAIndexError: list index out of range
AA    torrent_hash = re.findall('urn:btih:([\w]{32,40})', result.url)[0].upper()
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 142, in downloadResult
AATraceback (most recent call last):
2014-12-17 19:30:25 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Failed to download result
AA
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 70: ordinal not in range(128)
AA    with open(filename, 'wb') as fp:
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1250, in download_file
2014-12-17 19:30:25 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Unknown exception while loading URL http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30088: Traceback (most recent call last):
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Criminal.Minds.S10E07.HDTV.XviD-AFG[DEFTv™] from trackerrrrdomain
2014-12-17 19:30:25 INFO     POSTPROCESSER :: Successfully processed
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Quality of Criminal.Minds.S10E07.HDTV.XviD-AFG[DEFTv™] is SD TV
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Quality of Criminal.Minds.S10E08.HDTV.XviD-AFG[DEFTv™] is SD TV
2014-12-17 19:30:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Quality of Criminal.Minds.S10E06.HDTV.XviD-AFG[DEFTv™] is SD TV
2014-12-17 19:30:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Found result Criminal.Minds.S10E08.HDTV.XviD-AFG[DEFTv™] at http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30089
2014-12-17 19:30:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Found result Criminal.Minds.S10E07.HDTV.XviD-AFG[DEFTv™] at http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30088
2014-12-17 19:30:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: [trackerrrrdomain] :: Found result Criminal.Minds.S10E06.HDTV.XviD-AFG[DEFTv™] at http://trackerrrrdomain-tracker.net/download.php?type=rss&secret_key=PRIVATEKEYYYYYYYb&id=30087
```

**Comment by fernandog** [comment] 2015-02-13 10:34
@valantislevas those releases still have the trademark icon?

**Comment by fernandog** [comment] 2015-02-16 02:06
@valantislevas if you don't reply, will close this issue

**Comment by abeloin** [comment] 2015-02-16 03:15
@fernandog My guess is the open function is not receiving a Unicode string hence the conversion to ASCII.

**Comment by fernandog** [comment] 2015-02-16 09:44
Its easy fo fix? I never say that trademark in years.

**Comment by valantislevas** [comment] 2015-02-16 12:07
yes that problem exists in master version.. i hope someone can do something

**Comment by fernandog** [comment] 2015-02-19 15:14
@abeloin is this easy to fix?

**Comment by abeloin** [comment] 2015-02-19 16:22
@fernandog It's on my todo list to check, but so many things on that todo list ;)

**Comment by fernandog** [comment] 2015-02-19 16:24
ok. sorry!

**Comment by fernandog** [comment] 2015-02-20 14:49
@abeloin can we just add ek.ek ?

```
        with open(ek.ek(filename), 'wb') as fp:
            for chunk in resp.iter_content(chunk_size=1024):
                if chunk:
                    fp.write(chunk)
                    fp.flush()
```

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1284

```
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 70: ordinal not in range(128)
AA    with open(filename, 'wb') as fp:
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1250, in download_file
```

**Comment by fernandog** [comment] 2015-02-20 15:14
@valantislevas can you try this?

stop SR, edit file like this, save and start SR, and try to reproduce
https://github.com/SiCKRAGETV/SickRage/pull/1369/files

**Comment by abeloin** [comment] 2015-02-20 15:42
@fernadog You shouldn't do that there because if the requested filename change the calling process won't be able to find it.
You should instead add a rule in sanitizeFileName: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1284

**Comment by abeloin** [comment] 2015-02-20 15:45
By the way I'm unable to reproduce the issue on my system(Fedora).
@valantislevas what is the locale for the user running sickrage?

**Comment by abeloin** [comment] 2015-02-20 15:51
@fernandog 
Something like this: 
```
re.sub(ur'\u2122', '', name) # Trade Mark Sign
```

**Comment by fernandog** [comment] 2015-02-21 01:31
@valantislevas develop update. please update and report back

**Comment by fernandog** [comment] 2015-02-21 20:46
@valantislevas

**Comment by valantislevas** [comment] 2015-02-22 08:59
i cant try it now i will check it i hope today

**Closed** 2015-02-22 11:10 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Confirmed, 4: Fix pending, 4: Need feedback, branch: develop, branch: master

**Comment by Dennisreneholm** [comment] 2015-03-12 11:31
I think i have the same problem.

Running newest master, on Windows 2008 r2 server.
Can't use &,Æ,Ø or Å

**Comment by fernandog** [comment] 2015-03-12 11:34
@Dennisreneholm open a new issue following guidelines ( https://github.com/SiCKRAGETV/sickrage-issues ) AND please post:

- user that runs SR OR the contents of /etc/default/sickbeard
- post the result of this commands running as **SR user**:

```
locale
```
and
```
locale -a 
```

**Comment by valantislevas** [comment] 2015-04-20 16:03
hello new problem about other char:

title from tracker: The Messengers 2015 S01E01 HDTV x264-2HD ☆ SERIES PREMIERE ☆ [UniqueTeam]

windows:
SR Version: 	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4)
SR User:	zotac
SR Locale:	('el_GR', 'cp1253')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

on my windows installation it works and it downlods the torrent 

2015-04-20 18:26:34 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading The.Messengers.2015.S01E01.HDTV.x264-2HD..SERIES.PREMIERE..[UniqueTeam] from greekleech.info
2015-04-20 18:26:33 INFO     SEARCHQUEUE-DAILY-SEARCH :: [greekleech.info] :: Quality of The.Messengers.2015.S01E01.HDTV.x264-2HD..SERIES.PREMIERE..[UniqueTeam] is SD TV
2015-04-20 18:26:31 INFO     SEARCHQUEUE-DAILY-SEARCH :: [greekleech.info] :: Found result The.Messengers.2015.S01E01.HDTV.x264-2HD..SERIES.PREMIERE..[UniqueTeam] at http://www.greekleech.info/?p=rss&action=download&tid=....................


Linux SR Version: 
SR Version: 	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4)
SR User:	root
SR Locale:	(None, None)
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Log Dir:	/opt/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/opt/sickrage/', '\xe2\x80\x93config=/opt/sickrage/config.ini']
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

but it doesnt download in linux

**Comment by abeloin** [comment] 2015-04-20 18:17
@valantislevas The issue is the quality of your feed, SR require a clean scene name(raw name) which your feed doesn't seem to provide. Post the content of that rss feed to see if you specify an alternative title.

**Comment by valantislevas** [comment] 2015-04-20 21:56
the strange thing is that:

is the same version on windows and linux of SR so, in windows the episode downloaded ok and in linux doesnt find the torrent.. :/

**Comment by abeloin** [comment] 2015-04-20 22:07
Provide full debug logs for both windows and linux when finding(or not in case of Linux)

**Comment by fernandog** [comment] 2015-04-21 00:48
@valantislevas your locale for root is none.

From you posted info:
SR Locale: (None, None)

Please set to utf-8

**Comment by valantislevas** [comment] 2015-04-21 09:09
how i can set it? i tried  update-locale LANG=en_US.UTF-8 but nothing on ubuntu 14.04

**Comment by fernandog** [comment] 2015-04-21 11:35
@valantislevas Try to run SR with a non-root user

**Comment by valantislevas** [comment] 2015-04-21 13:56
how i can run it? to move it to other path of users because now is on /opt/sickrare and run it again from user's shell?

**Comment by fernandog** [comment] 2015-04-21 14:00
Second option

**Comment by valantislevas** [comment] 2015-04-21 14:00
after this change i restart sb but it says root again on options.. maybe restart the box to start automatic?

**Comment by fernandog** [comment] 2015-04-21 14:02
Try it

**Comment by valantislevas** [comment] 2015-04-21 14:11
i put val on the path above also run it manually from opt/sickrage and now it says 

SR Version: 	BRANCH: (master) / COMMIT: (975c0dd208c59cac8fd8a77a91da5d1dfc7235df)
SR User:	root
SR Locale:	('en_US', 'UTF-8')

**Comment by fernandog** [comment] 2015-04-21 14:40
Now try to reproduce the error

**Comment by valantislevas** [comment] 2015-04-21 15:17
i will try when i get home and i will reply.. thaNKS
