### ISSUE TITLE
Sickrage on Synology with SSL

### ISSUE THREAD

**Issue by boeggild** [SiCKRAGETV/sickrage-issues#431] opened 2015-01-17 14:36 UTC
I use SickRage on my Synology NAS. Since I added a SSL certificate to the Synology DS Sickrage fails with "DownloadStation: Authentication Failed" when I tried to fetch a torrent. The "Test Connection" option in "Search setiings" returns: "Success: Connected and Authenticated". So I am somewhat puzzled as to why this fails. Anyone else experienced something like this?

**Comment by boeggild** [comment] 2015-01-17 14:39
Forgot to mention that there is no problem when if I change the Synology DS URL back to http.

**Comment by elliottlock** [comment] 2015-01-18 09:53
I can also confirm this issue to be present

**Comment by Weggy** [comment] 2015-01-18 10:08
NO, wait I've found the issue (I think).

"boeggild", please can you tr going to the following page in sickrage:
http://n.n.n.n:n/config/general/ (e.g. http://192.168.1.1:8081/config/general/)

Tick "Enable HTTPS" and save the changes.

From there you should find searches and downloads function.

**Comment by markheloking** [comment] 2015-01-18 11:15
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by raymondtrueman** [comment] 2015-01-18 18:56
Mine is doing exactly the same. I cant paste a log because I switched my torrent snatching to use Blackhole because of the error a week ago. But here is the versions below. I traced the error to these 2 files though but couldnt figure out why it was happening:

SickRage/sickbeard/clients/generic.py
SickRage/sickbeard/clients/download_station.py

On the self.auth methods

SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
Python Version:	2.7.8 (default, Dec 12 2014, 22:38:36) [GCC 4.3.2]

**Comment by boeggild** [comment] 2015-01-18 19:35
Logs posted at http://pastebin.com/sbVwSMph

SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

**Comment by Rafkat** [comment] 2015-01-20 14:59
I've been using it in Synology for quite long time with https and haven't had any issues. Have you tried to reinstall SickRage?

**Comment by boeggild** [comment] 2015-01-22 19:13
Yes, I tried reinstalling, but unfortunately does not solve the issue.

**Comment by abeloin** [comment] 2015-01-22 22:05
@boeggild Check if you can connect with openssl:
```openssl s_client -connect your.synologyaddress.com:443```

For reference: http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

**Comment by fernandog** [comment] 2015-02-03 00:04
no reply. closing

**Comment by boeggild** [comment] 2015-02-04 18:07
OpenSSL returns this

Loading 'screen' into random state - done
CONNECTED(0000019C)
depth=0 CN = <MY DISKSTATION HOST>
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = <MY DISKSTATION HOST>
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = <MY DISKSTATION HOST>
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=<MY DISKSTATION HOST>
   i:/DC=dk/DC=boeggild/CN=boeggild-MATS-CA
---
Server certificate
-----BEGIN CERTIFICATE-----
<MY CERTIFICATE>
-----END CERTIFICATE-----
subject=/CN=<MY DISKSTATION HOST>
issuer=/DC=dk/DC=boeggild/CN=boeggild-MATS-CA
---
No client certificate CA names sent
---
SSL handshake has read 2089 bytes and written 473 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: D98F2A4970A3A5F42373B81F8CC29136132C3824E5CCDF8E9319A44BEDA0CB88

    Session-ID-ctx:
    Master-Key: 199CA72F81041719FAE362E097AB44B09146BDB652A776C565F2963F2C3FDC1C
63990A2A31965744035104389916CAC8
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 1c 65 f7 7c f5 39 20 70-83 19 5d 7f a8 9a 88 b5   .e.|.9 p..].....
    0010 - 8e 75 82 f5 31 e1 10 08-2b 17 3f a6 39 1f b7 ca   .u..1...+.?.9...
    0020 - 2a 9c 31 d1 4e 59 21 6a-43 57 7d 0a c9 7b 5a d3   *.1.NY!jCW}..{Z.
    0030 - 76 d2 d5 d5 c3 33 85 2e-58 a2 2f 89 6f 17 14 3c   v....3..X./.o..<
    0040 - 98 a8 12 9e 67 5d 6c 33-f7 c9 eb a0 d5 2b 47 dd   ....g]l3.....+G.
    0050 - a3 cb 75 15 2d 57 65 cb-2d 40 b7 9e 73 63 b6 88   ..u.-We.-@..sc..
    0060 - e3 8b 54 a7 a4 4b 06 03-0b e7 8b a1 60 eb cb 3a   ..T..K......`..:
    0070 - 4a 5a 8e ea 4d 8c a7 b8-57 73 4e e9 36 f7 da 7d   JZ..M...WsN.6..}
    0080 - dc e0 24 13 3a 87 b9 26-7e 4d 98 00 5e 60 d8 24   ..$.:..&~M..^`.$
    0090 - 54 86 67 f7 01 4e 25 76-cd c0 b6 e1 a4 f2 35 38   T.g..N%v......58
    00a0 - 5b 14 46 28 92 ff 50 63-c4 6b 88 a4 70 4a 89 7e   [.F(..Pc.k..pJ.~
    00b0 - 82 8c 4d 7b c0 df 70 08-1f af 45 69 5f ef 5b 96   ..M{..p...Ei_.[.

    Start Time: 1423072763
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)

**Comment by boeggild** [comment] 2015-02-04 18:09
Open SSL output at http://pastebin.com/Q5WQnHXm

**Comment by boeggild** [comment] 2015-02-04 18:11
OpenSSL output at http://pastebin.com/Q5WQnHXm

**Comment by boeggild** [comment] 2015-02-04 18:18
how do I reopen this issue?

**Comment by abeloin** [comment] 2015-02-05 01:36
@boeggild You have self-signed SSL certificate to which openssl reply:
```verify error:num=27:certificate not trusted```
Let me check if there's a way to disable the ssl check for the synology DS in Sickrage.

@fernandog Do you know if the synology client already has a way to disable the ssl check? I don't see it.

**Comment by fernandog** [comment] 2015-02-05 08:50
Dont know. Im a RPI user.

**Comment by raymondtrueman** [comment] 2015-02-05 11:42
Can we please formerly re-open this issue. I have no idea why it was closed when its still unresolved. I would really love to have it resolved too

**Comment by abeloin** [comment] 2015-02-05 15:27
@boeggild @raymondtrueman Can you try [this commit](https://github.com/abeloin/SickRage/commit/c8f1eb625042545ac85c847526ff507dee160d17)?

**Comment by raymondtrueman** [comment] 2015-02-06 09:50
@abeloin - Thanks I made the change. I will monitor it. I'm using NZB and Torrents so I will have to wait until something is snatched via torrent to see if it worked, and then I will give you feedback

**Comment by raymondtrueman** [comment] 2015-02-07 12:53
@abeloin @boeggild  I can confirm that commit fixed the issue...
Thank you very much

**Comment by abeloin** [comment] 2015-02-08 15:05
@boeggild Did you get a chance to try the commit?

**Comment by boeggild** [comment] 2015-02-09 08:12
Indeed I have. I can also confirm that the commit has fixed the issue. Thank you.

**Comment by fernandog** [comment] 2015-02-16 00:23
@boeggild develop update. please test and report back

**Comment by boeggild** [comment] 2015-02-16 12:10
Succes. Thank you.

**Closed** 2015-02-16 12:25 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Confirmed, 3: Fix
