### ISSUE TITLE
trakt syncLibrary problem

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1066] opened 2015-03-29 22:07 UTC
I think that syncLibrary is working not as intended.
In fact when you enable sync library all episode for all show will be added to trakt.

probably the expected behaviour is to add to library/collection only downloaded episode.

**Comment by Thraxis** [comment] 2015-03-29 23:06
@gborri  Testing now as all my current shows were already in my collection. Adding a new show

**Comment by Thraxis** [comment] 2015-03-29 23:13
@gborri Yes I can confirm that this is adding all episodes.  This would partly be due to the API itself adding all episodes when a show is added to the collection.

**Comment by abeloin** [comment] 2015-03-30 01:09
### SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)<br />
Please include the following when opening a new ticket:
 - Branch
 - Commit hash
 - Your operating system and python version
 - What you did
 - What happened
 - What you expected
 - Link to a copy/paste of your logfile with clear debug info of the error on [GIST](http://gist.github.com)

**Comment by Thraxis** [comment] 2015-03-30 02:33
This Issue affects all current versions of SickRage. my testing version info is below:

"""
SR Version:	BRANCH: (develop) / COMMIT: (a6445545807947ab6521dd99c40c16cc279661db) 
SR User:	nobody
SR Locale:	('en_US', 'UTF-8')
"""
Python Version:	2.7.3 (default, Mar 26 2013, 20:01:12) [GCC 4.4.4]
"""

@abeloin @fernandog @gborri  I've got a fix to add only downloaded shows to the collection.  Should we also be looking at removing wanted / snatched / etc from  the Collection as well (a true sync)

**Comment by fernandog** [comment] 2015-03-30 09:19
Agree.
I would like to handle show not episode in trakt watchlist (for new shows)

**Comment by Thraxis** [comment] 2015-03-30 09:27
So kinda flip the two situations.  Add shows to watchlist, not wanted episodes.  and add downloaded episodes to the trakt collection, not shows. Actually I think the episodes to watchlist could be easily encapsulated in a IF block

```python
    def syncWatchlist(self):

        logger.log(u"Syncing Trakt.tv show watchlist", logger.DEBUG)

        logger.log(u"Getting ShowWatchlist", logger.DEBUG)
        if self._getShowWatchlist():
            self.addShowToTraktWatchList()
            self.updateShows()

        logger.log(u"Getting EpisodeWatchlist", logger.DEBUG)
        if self._getEpisodeWatchlist():
            self.removeEpisodeFromTraktWatchList()
            self.addEpisodeToTraktWatchList()
            self.updateEpisodes()
```
This is the function that handles the watchlist update.  Comment out the self.addEpisodeToTraktWatchList() to remove episode adding... or add a config option and encapsulate in an IF block

**Comment by gborri** [comment] 2015-03-30 10:06
@Thraxis the reason to get episode on watchlist is that if you loose your media/sickragedb every episode in watchlist will start automatically..... the episode to watch list is removed when downloaded if checked the option. Someone asked for it beacouse said that trakt will remove episode on watchlist when added to collection.

**Comment by gborri** [comment] 2015-03-30 10:07
@fernandog you need to manage episode for collection/library beacause otherwise if you add a show to sickrage it immediatly says to trakt that you have downloaded all episode.

**Comment by fernandog** [comment] 2015-03-30 10:55
@gborri please don't open issues without guidelines. You know what we need to debug issues. If is not an issue please add "Question" to the title. Otherwise we will start closing issues. It's hard to everytime ask to follow guidelines

**Comment by gborri** [comment] 2015-03-30 11:40
@fernandog ok for guidelines. This case is different, i think is not a BUG in the code but is not a correct behavior.

**Comment by fernandog** [comment] 2015-03-30 11:41
@gborri does not matter if is bug or not. we need all those infos!

**Comment by gborri** [comment] 2015-03-30 11:41
@Thraxis it think is better a true sync with option to not remove episode.

**Comment by gborri** [comment] 2015-03-30 11:42
@fernandog ok.

**Comment by Thraxis** [comment] 2015-03-30 16:46
@gborri @fernandog I'm thinking this needs to be fleshed out into a design document so we can see how things are currently working and how they should be / are wanted to be working.

**Comment by Thraxis** [comment] 2015-03-30 17:55
Below is the current rough process flow for the traktChecker

Item added to WatchList on Trakt:

User adds a show or episode to Trakt Watchlist

TraktChecker runs as scheduled and checks if we are using Trakt.  If we are it checks if we want to sync the watchlist.  If we do want to sync the watchlist, verify we have a default root directory and if we do call the Watchlist Sync function.

The Watchlist Sync function first pulls the list of shows from the Trakt Show Watchlist it then cycles through all shows configured in SickRage and adds them to the the Trakt Show Watchlist.  After it is done checking all the episodes it pulls the Trakt Show Watchlist again and checks each show to see if we already have it in our SickRage, if we don’t have it the show is added.

Next the episode list is pulled from the Trakt Episode Watchlist and we cycle through the list and check to see if the episode status on SickRage is not WANTED, UNKNOWN, SNATCHED or SNATCHED_PROPER.  If it is not then it is flagged to be removed from the Trakt Episode Watchlist. After it is done checking all the episodes it pulls the trakt watchlist again.

The system then pulls a list of all episodes on SickRage that have a status of WANTED, SNATCHED or SNATCHED_PROPER and cycles through the list and checks if the episode is already in the Trakt Episode Watchlist if the show is not it is flagged to be added. The Trakt Episode Watchlist is pulled once again and then checks each episodes show to see if we already have it in our SickRage, if we don’t have it the show is added.

When this is done SickRage  checks if it should Sync with Trakt and if it should it cycles through all shows SickRage contains and sends an add to the Trakt Collection.  This adds the show and ALL episodes to the library.

**Comment by Thraxis** [comment] 2015-03-30 18:37
The end result of this is that every show is added to the Watchlist, all Wanted and Snatched Episodes are added to the Watchlist, and all shows and all episopdes (regardless of status) are added to the collection.

**Goals:**
* Only sync downloaded shows to Collection
   * Optionally Remove episodes from Collection that are not downloaded in SickRage
* Add support to Add show from to custom lists with different root dir destinations / options (Better Anime Support)
* Optionally Add Shows to Watchlist 
* Optionally Add Episodes to Watchlist

**Additional Notes:**
* When a show is deleted from SickRage (webserve.py or webapi.py) all the episodes are removed from the Trakt Collection

**Questions:**
* Using Watchlist / Collection to rebuild SickRage db

**Comment by fernandog** [comment] 2015-03-30 18:39
@Thraxis this can conflict with XMBC/KODI + TRAKT addon

Trakt addon removes from library if the episode don't longer exists in XBMC/KODI

**Comment by Thraxis** [comment] 2015-03-30 18:55
@fernandog Well I'd hope someone wasn't trying to use two separate applications to sync their Trakt collection, that's just asking for problems.  Which brings up the point of adding a warning to the "Enable Trakt Sync" on the config page about not using that feature if you have another application managing your Trakt Collection (such as the XBMC/KODI Trakt addon)

A possible alternative would be to add custom lists sickrage-shows, sickrage-anime, sickrage-shows-wanted, sickrage-anime-wanted.. etc.

**Comment by fernandog** [comment] 2015-03-30 18:58
or just use the same concept as official trakt addon: if the file exist, keep in collection. if not, remove it. No matter who does the sync first, the result will be the same

**Comment by Thraxis** [comment] 2015-03-30 19:09
That brings us into the trap of DOWNLOADED vs ARCHIVED and what that means to individuals.  Probably best to actually check if the file exists where the database says it should be...

**Comment by Thraxis** [comment] 2015-03-31 03:42
During testing review discovered that the sync episodes to watchlist was broken and only ever added the last item it found. 

Step 1. Fix Episode Watchlist Sync to work correctly and use a single bulk transaction

**Comment by Thraxis** [comment] 2015-03-31 06:04
**Status Update:**

* Bulk Library Sync -> Trakt Collection :: Working using status from Sickrage of Archived, or Downloaded
* Bulk Watchlist Sync (Add) -> Trakt Watchlist 
* Bulk Watchlist Sync (Remove) -> Trakt Watchlist 

**Pending**
* Remove from Collection if file doesn't exist
* Update Sync Collection to verify file exists

Notes:
When I say Bulk Update I'm talking 9000+ episodes over 344 shows. This set was tested as a sync to watchlist, sync to collection and a remove from watchlist.

**Comment by fernandog** [comment] 2015-04-01 22:36
@Thraxis PR done? can I close this issue?

**Comment by Thraxis** [comment] 2015-04-02 07:48
The PR as it is works.  It still does not Remove items from the Trakt Collection yet.  I also want to clean up a bit of the code the code to streamline it a bit..  But I could also do that in a later PR when I look at adding a the ability to create an Anime watchlist (The other Trakt PR of mine should probably be merged in at the same time as this one.

**Comment by Thraxis** [comment] 2015-04-02 08:06
To clarify what I mean bay "it works".  

I have been running this particular branch (trakt-sync + trakt-changes) for the past 3 days.  The only "error" I get in my error log is to tell me that "2015-04-02 00:21:26 SHOWQUEUE-ADD :: Show Heroes Reborn is on theTVDB but contains no season/episode data.", and that has nothing to do with SickRage itself.

What it CURRENTLY does:

1. Syncs all shows in your SickRage library to the Trakt Watchlist if TRAKT_SYNC_WATCHLIST is set
2. Removes all episodes that are not WANTED, UNKNOWN, SNATCHED or SNATCHED_PROPER
3. Syncs all episodes that are SNATCHED, SNATCHED_PROPER or WANTED to the Trakt Watchlist if TRAKT_SYNC_WATCHLIST is set
4. Syncs all episodes that are DOWNLOADED or ARCHIVED to the Trakt Collection it TRAKT_SYNC is set

**Comment by abeloin** [comment] 2015-04-04 02:53
Pushing back to v4.0.16

**Comment by abeloin** [comment] 2015-04-11 16:01
PR merged

**Comment by abeloin** [comment] 2015-04-13 12:34
@gborri Please update and report if working

**Comment by fernandog** [comment] 2015-04-15 12:42
@gborri no reply. closing

**Closed** 2015-04-15 12:42 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback
