### ISSUE TITLE
TPB & KAT, etc Failing

### ISSUE THREAD

**Issue by lwis** [SiCKRAGETV/sickrage-issues#3135] opened 2015-10-06 08:49 UTC
```
2015-10-06 07:26:13 INFO     SEARCHQUEUE-BACKLOG-269689 :: [ThePirateBay] :: Performing episode search for The Leftovers
AAExpatError: mismatched tag: line 43, column 2
AA    parser.Parse(xml_input, True)
AA  File "/opt/sickbeard/lib/xmltodict.py", line 248, in parse
AA    data = xmltodict.parse(data)
AA  File "/opt/sickbeard/sickbeard/providers/kat.py", line 137, in _doSearch
AATraceback (most recent call last):
AAExpatError: mismatched tag: line 43, column 2
AA    parser.Parse(xml_input, True)
AA  File "/opt/sickbeard/lib/xmltodict.py", line 248, in parse
AA    data = xmltodict.parse(data)
AA  File "/opt/sickbeard/sickbeard/providers/kat.py", line 137, in _doSearch
```
No providers under a proxy seem to work?

http://feathub.com/SiCKRAGETV/SickRage/+142 may help significantly, how feasible is this? If someone could point me to the areas that would need a change, I'll attempt to create a PR.

Latest commit of master, I've tried resetting and deleting my cache.db.

**Comment by SiCKRAGEB0T** [comment] 2015-10-06 08:49
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by saitoh183** [comment] 2015-10-06 13:53
Just updated and Kat doesnt seem to be work when i tried manual search
 Log: http://pastebin.com/ACEciQ9m
OS: Windows 
SR Version:	BRANCH: (master) / COMMIT: (533bf372742fbb570d066a0b3980aff127e69397) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config:	E:\Sickrage\config.ini
SR Database:	E:\Sickrage\sickbeard.db
SR Cache Dir:	E:\Sickrage\cache
SR Log Dir:	E:\Sickrage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by saitoh183** [comment] 2015-10-06 14:08
Fixed by updating to Python 2.7.10

**Comment by lwis** [comment] 2015-10-06 14:54
Still failing for me on 2.7.10 :-1:

**Comment by miigotu** [comment] 2015-10-06 14:59
@lwis not sure yet what the deal is with proxy. I know the proxies suck.

**Comment by lwis** [comment] 2015-10-06 16:06
@miigotu Is there a better way (aside from my feature request) to achieve this?

**Comment by miigotu** [comment] 2015-10-06 16:22
Disable proxy, try a different proxy, or manually change the url in the source.

**Comment by lwis** [comment] 2015-10-06 16:46
Manually changing the URL and turning off the proxy works, after a bit of digging it looks like the proxies are failing due to hotlinking, I think they all need a 'Referer' header set;

`Referer: http://<proxy>/browse.php?u=<url>&b=32&f=norefer`

**Comment by miigotu** [comment] 2015-10-06 16:49
@lwis we do set the Referer. The problem is that some of the proxy's block the torrent sites now too or the torrent sites block the proxy (getprivate).

What domain did you switch to?

**Comment by lwis** [comment] 2015-10-06 16:51
kickass.unblocked.la & accessbay.link

**Comment by miigotu** [comment] 2015-10-06 19:18
I think our solution will be to rip out the glype proxy support and allow custom urls to be set in the UI for each provider.

**Comment by josephasmith1** [comment] 2015-10-06 20:54
Can you add iptorrents to the list of providers affected by this issue?

**Comment by miigotu** [comment] 2015-10-06 23:30
Its almost all providers.

**Comment by oxivanisher** [comment] 2015-10-07 06:33
@lwis i can confirm that kickass.unblocked.la & accessbay.link are working for me too. :+1:

**Comment by SanctiMortem** [comment] 2015-10-07 22:24
I tried kickass.unblocked.la but had no luck still have the same problem, I also made sure that same url had the torrent with seeders and it did. :( are there any other solutions? or am I the only one who couldn't make it work this way, if so I might try again.

**Comment by miigotu** [comment] 2015-10-07 23:22
@SanctiMortem you also have to disable the proxy ^

**Comment by SanctiMortem** [comment] 2015-10-07 23:31
@miigotu, if you mean under General/Advanced Settings I do not have a proxy, if there is any other proxy option or setting besides that, I apologize but I don't really know where that could be :S 

I'm sorry I'm still learning my way around SickRage 

Thank you for your help!!

**Comment by miigotu** [comment] 2015-10-08 05:29
in config/providers, each provider has an optional drop down to use a proxy if you have proxy checked.

**Closed** 2015-10-09 02:25 UTC
Labels: 1: Bug / issue, 3: Fixed

**Comment by lwis** [comment] 2015-10-09 15:40
My proxy issues have been resolved, thanks @miigotu!
