### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#620] opened 2015-02-16 22:29 UTC
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:04:21) 
[GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@dbb0e551fc5e3c493c3ebd906f712a13aaa7de58
Link to Log: https://gist.github.com/684cacf38990f7f57e27
### ERROR
```
Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2029, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 211, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 421, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1037, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/notifiers/trakt.py", line 81, in update_library
    trakt_api.traktRequest("sync/collection", data, method='POST')
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 57, in traktRequest
    self.validateAccount()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 29, in validateAccount
    data=json.dumps(data), timeout=self.timeout, verify=self.verify)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by udochrist** [comment] 2015-02-16 22:36
The issue is not with the error itself, it's how sr handles the exception. When this happens the processing subscript returns an error 500 and hence a failed download to Sabnzbd which in term doesn't clean up the download directory. The downloading and moving of the ep to it's correct place has all worked out perfectly. It's simply the trakt notification that has failed.
This should not lead to a failed postprocessing. For me it's about 1 of 10 eps which trigger the notification error.

**Comment by abeloin** [comment] 2015-02-16 23:21
Thank you for the information.

Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/616

See https://github.com/SiCKRAGETV/SickRage/pull/1330 for a fix

**Closed** 2015-02-16 23:22 UTC
Labels: 5: Duplicate
