### ISSUE TITLE
Error occurred when downloading subtitles:

### ISSUE THREAD

**Issue by MickHussey** [SiCKRAGETV/sickrage-issues#1031] opened 2015-03-25 12:15 UTC
•Branch : BRANCH: (master) 
•Commit hash  COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718
•Your operating system and python version Linux raspberrypi 3.12.28+ Python 2.7.3
•What you did: Nothing....this error happens every hour
•What happened : Error message every hour
•What you expected : No error message
•Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN 

```
2015-03-25 19:51:25 ERROR    FINDSUBTITLES :: Error occurred when downloading subtitles:
Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/tv.py", line 1419, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/home/pi/SickRage/lib/subliminal/api.py", line 96, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/pi/SickRage/lib/subliminal/api.py", line 55, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/pi/SickRage/lib/subliminal/core.py", line 59, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "/home/pi/SickRage/lib/subliminal/videos.py", line 257, in scan
    video = Video.from_path(entry)
  File "/home/pi/SickRage/lib/subliminal/videos.py", line 85, in from_path
    guess = guessit.guess_file_info(path, 'autodetect')
  File "/home/pi/SickRage/lib/guessit/__init__.py", line 210, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/home/pi/SickRage/lib/guessit/__init__.py", line 138, in _guess_filename
    title2 = next(find_nodes(mtree2.match_tree, 'title'))
StopIteration
```

**Comment by fernandog** [comment] 2015-03-25 12:21
@MickHussey what's the filename of the video you are trying to download subtitle?

**Comment by MickHussey** [comment] 2015-03-25 12:27
No particular video but I have set the parameters for to automatically download subtitles so I guess it is going through some sort of backlog. How do I find out which one it is failing on?? Here is a bit more of the log:

2015-03-25 19:51:24 INFO     BACKLOG :: Seeing if we need anything from Broadchurch
2015-03-25 19:51:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from ER
2015-03-25 19:51:25 DEBUG    BACKLOG :: Nothing needs to be downloaded for Broadchurch, skipping
2015-03-25 19:51:25 INFO     BACKLOG :: Seeing if we need anything from Air Crash Investigation - Mayday
2015-03-25 19:51:25 DEBUG    BACKLOG :: Nothing needs to be downloaded for Air Crash Investigation - Mayday, skipping
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Top Gear
2015-03-25 19:51:25 ERROR    FINDSUBTITLES :: Error occurred when downloading subtitles:
Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/tv.py", line 1419, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/home/pi/SickRage/lib/subliminal/api.py", line 96, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/pi/SickRage/lib/subliminal/api.py", line 55, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/pi/SickRage/lib/subliminal/core.py", line 59, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "/home/pi/SickRage/lib/subliminal/videos.py", line 257, in scan
    video = Video.from_path(entry)
  File "/home/pi/SickRage/lib/subliminal/videos.py", line 85, in from_path
    guess = guessit.guess_file_info(path, 'autodetect')
  File "/home/pi/SickRage/lib/guessit/__init__.py", line 210, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/home/pi/SickRage/lib/guessit/__init__.py", line 138, in _guess_filename
    title2 = next(find_nodes(mtree2.match_tree, 'title'))
StopIteration
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Good Wife
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Person of Interest
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Big Bang Theory
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from House of Cards (US)
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Monty Python's Flying Circus
2015-03-25 19:51:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Monty Python: Almost The Truth (The Lawyer's Cut)

**Comment by fernandog** [comment] 2015-03-25 12:29
@MickHussey user log filter feature to filter FINDSUBTITLES

post results using ``` before and after the log

**Comment by MickHussey** [comment] 2015-03-25 12:38
Seems to be a series called Friday Night Lights:

```2015-03-25 19:51:25 ERROR    FINDSUBTITLES :: Error occurred when downloading subtitles: 
2015-03-25 19:51:19 DEBUG    FINDSUBTITLES :: 79337: Downloading subtitles for episode 1x19
2015-03-25 19:51:19 DEBUG    FINDSUBTITLES :: Setter sets location to /mnt/synology_video/TV_Shows/Friday Night Lights/Season 1/Friday Night Lights Season 1 Episode 19 - Ch-Ch-Ch-Ch-Changes.avi
2015-03-25 19:51:19 DEBUG    FINDSUBTITLES :: 79337: Loading episode details from DB for episode 1x19
2015-03-25 19:51:18 DEBUG    FINDSUBTITLES :: 79337: An object for episode 1x19 didn't exist in the cache, trying to create it
2015-03-25 19:51:18 DEBUG    FINDSUBTITLES :: Downloading subtitles for episode 1x19 of show Friday Night Lights
2015-03-25 19:51:11 INFO     FINDSUBTITLES :: Checking for subtitles
2015-03-25 19:51:06 DEBUG    FINDSUBTITLES :: Starting new thread: FINDSUBTITLES```

**Comment by fernandog** [comment] 2015-03-25 12:51
@MickHussey the problem is this "Ch-Ch-Ch-Ch"

@abeloin is there a way to fix when there's lots of "-" ?

https://github.com/SiCKRAGETV/sickrage-issues/issues/502

**Comment by MickHussey** [comment] 2015-03-25 12:59
ok....I can easily remove the "-" from the file name and see what happens.

**Comment by fernandog** [comment] 2015-03-25 13:01
@MickHussey I will work but the issue will still exists and we need to try to fix it

**Comment by MickHussey** [comment] 2015-03-25 13:03
Agreed that it should be fixed.....if you have a fix then I can easily test.
Thanks for your quick replies:)

**Comment by fernandog** [comment] 2015-03-25 13:04
@MickHussey we won't have the fix as fast as the replies! =) be patient please

**Comment by TagForce** [comment] 2015-03-25 16:28
@fernandog The problem is in the regex that defines what a release group is...
It now thinks the Ch-Ch-Ch-Changes is the release group... That gets added to the filename, and then gets seen as the release group again and gets added to the filename... You see where I'm going here?

I fixed that for our renamer (I think), by using the value it stores in the db first. Subliminal seems to suffer from a similar issue.

**Comment by fernandog** [comment] 2015-03-25 16:34
@TagForce should we contact subliminal dev in order to get a proper fix? Not just for sickrage

**Comment by TagForce** [comment] 2015-03-25 17:31
@fernandog He's not going to fix it... We should fix it ourselves or update subliminal code to the current version. Our version is wayyyy too old for him to fix it.

**Comment by fernandog** [comment] 2015-03-25 17:38
@abeloin was trying to upgrade the code

**Comment by abeloin** [comment] 2015-03-25 21:32
@fernandog allow the error is in guessit not subliminal

**Comment by fernandog** [comment] 2015-03-28 01:42
@abeloin change to milestone 4.0.15 ?

**Comment by abeloin** [comment] 2015-03-29 17:02
This issue look a lot like this one: https://github.com/wackou/guessit/issues/44

**Comment by abeloin** [comment] 2015-03-29 17:11
We need to update guessit to the final version of 0.7

**Comment by abeloin** [comment] 2015-04-09 12:54
@MickHussey Can you try replacing the content of lib/guessit by the content of this zip(content of folder guessit in guesit-0.7)?

You need to stop SR, replace the content, start sickrage

**Comment by MickHussey** [comment] 2015-04-10 01:53
I am away on a business trip right now....I will not be able to test until April 20th.

**Comment by abeloin** [comment] 2015-04-10 09:37
@MickHussey Closing the issue for now, reopen when able to test.

**Closed by abeloin** 2015-04-10 09:37 UTC
Labels: 1: Bug / issue, 2: Low Priority, 3: Confirmed, 4: Fix pending, 4: Need feedback
