### ISSUE TITLE
On update page never refreshes.

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#675] opened 2015-02-20 00:03 UTC
Branch: Master
Commit hash: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
OS: Ubuntu 14.04
Python: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

Since a few updates ago when I update nothing seems to happen on the page. I just get left with this.
![screen shot 2015-02-20 at 10 30 54 am](https://cloud.githubusercontent.com/assets/6525926/6278987/b7390598-b8eb-11e4-887e-a9aa13118641.png)
The update does happen, it just doesn't say that it's back online and refresh like it use to.

**Comment by abeloin** [comment] 2015-02-20 00:05
Duplicate of #609

**Closed** 2015-02-20 00:06 UTC
Labels: 5: Duplicate
