### ISSUE TITLE
cannot submit errors

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#413] opened 2015-01-14 18:12 UTC
Python Version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Operating System: Windows-7-6.1.7601-SP1
SR Version:	BRANCH: (master) / 
COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 

cannot submit errors
clicking the submit button generates the following error
```python
2015-01-14 18:08:43 Thread-69 :: cannot concatenate 'str' and 'exceptions.UnicodeDecodeError' objects
```
let me know if you need / want full logs

**Comment by fernandog** [comment] 2015-01-14 18:26
@pct00 full logs please

**Comment by pct00** [comment] 2015-01-14 18:39
http://pastebin.com/Nqzsm0ac

**Comment by pct00** [comment] 2015-01-14 18:50
forgot to mention, same error happens in develop branch

**Comment by markheloking** [comment] 2015-01-18 13:08
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/287. Closing this one, continue the discussion over there.

**Closed by markheloking** 2015-01-18 13:08 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Unconfirmed, 4: Fix pending, branch: develop, branch: master
