### ISSUE TITLE
Custom quality settings is doing things it's not supposed to do

### ISSUE THREAD

**Issue by eXistenZNL** [SiCKRAGETV/sickrage-issues#2621] opened 2015-08-31 19:45 UTC
I have a hard time wrapping my head around the custom quality settings, and cannot understand why SickRage started to download tons of 720P Web-DL episodes for episodes that I already own the 720P HDTV quality of.

My settings:
Quality -- Custom
Allowed -- SDTV, SD DVD, 720P HDTV, 720P Web-DL, 720p BluRay
Preferred -- 720P HDTV, 720P Web-DL, 720p BluRay
Archive on first match -- checked

Also, sometimes 'allowed' and 'preffered' is used, and sometimes 'initial' and 'replace with' is used. Those are two different things imho, 'allowed' includes the versions I want, 'initial' does not.
I believe this terminology should be updated to be consistent across SickRage.

__Exhibited behaviour (wrong)__: Starts downloading another preferred quality when I already own one. Next to the episodes in the status column is displayed `Snatched (best)`
__Expected behaviour (right)__: Knows I already have what I want and leaves it at that.

As described here https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings the 'Game of Thrones' setting needs us to first enable 'Archive on first match' and then disable this again. Why? What is the difference? Is this a hidden feature?

Please clarify.

__Branch__: master
__Commit hash__: 4db41da61c3e4639a19613a3e4f0dfeef9831fc0
__OS__: Debian 8.1 Jessie x64
__Python version__: 2.7.9

**Comment by miigotu** [comment] 2015-08-31 22:14
`Also, sometimes 'allowed' and 'preffered' is used, and sometimes 'initial' and 'replace with' is used. Those are two different things imho, 'allowed' includes the versions I want, 'initial' does not.
I believe this terminology should be updated to be consistent across SickRage.`

One place it was missed when the terms were changed. They are the same setting.

` Starts downloading another preferred quality when I already own one. Next to the episodes in the status column is displayed Snatched (best)`

Then the video you already have was snatched before you enabled archive on first match, or it would have been archived and could not be replaced.

This is all going to be improved a bit in the near future, but it is working as it is, how it was originally intended. I do agree it is not very intuitive at this time, but it has been this way since before I got here.

**Comment by eXistenZNL** [comment] 2015-09-01 05:39
`One place it was missed when the terms were changed. They are the same setting.`

So should I include or exclude the preferred qualities in the first list?

`Then the video you already have was snatched before you enabled archive on first match, or it would have been archived and could not be replaced.`

I see. When I now manually archive an episode when it's been downloaded e.g. on 720P Web-DL, it will no longer show the 720P Web-DL next to it, it will only show 'Archived'. Is there a way around this?

**Comment by miigotu** [comment] 2015-09-02 10:47
Not at this time, but I am considering changing the handling of qualities soon as it makes no sense. If the existing episdoe is in the preferred list SR should stop searching for it, period. Archiving was originally for a different use (ie: episodes that were no longer on the drive, or on removable media, but you still had them).

It SHOULD be, search for any on the initial list, and keep searching (and accepting better ones on the initial list) util you have ONE of the preferred list, and do not continue searching for it after that.

**Comment by WebSpider** [comment] 2015-09-03 00:53
Looks like a duplicate of #2523

**Comment by eXistenZNL** [comment] 2015-09-03 09:40
@WebSpider I think you are indeed right.

@miigotu Exactly! In your last comment you described exactly how I would hope this would work. Looking forward to this!

**Comment by strike84** [comment] 2015-09-15 19:11
@miigotu Any idea when archive on first match will be fixed so it works like it's supposed to? I see there are several issues open regarding this, #2562 #2523 

My settings are almost identical to @OmgImAlexis in #2523, just that I also have 720p HDTV in the initial list. One ting I haven't tried yet is to only have a quality in either initial OR preferred list, like you mentioned in #2523, but I'll try that and see if it works.

Thank you all for the awesome job you guys are doing btw! :)

**Comment by fernandog** [comment] 2015-09-16 02:13
archived feature: I would like an option to instead of changing status from "Snatched" to "Downloaded 1080p web-dl" to straight to "Archived 1080p web-dl" - if this is the best quality. Otherwise user will have to manually change all "Downloaded" to "Archived"

**Comment by kossboss** [comment] 2015-09-29 09:56
@miigotu  You mention Archiving was originally meant as "episodes that were no longer on the drive, or on removable media, but you still had them)." What about now, what is the new way it is used? Because I see it used alot. Im trying to find out what "Archive on first match means?" If we go by what it used to mean - that checkbox wouldnt make logical sense (how could one move the episode to different storage media when its first matched, unless there was some backup ability). I think ill understand this better once I find out what the new meaning of Archive is and what "Archive on first match means" and why its good. Thanks for your answers.

**Comment by miigotu** [comment] 2015-09-29 10:19
Initially it was for "backed up on external media"
It was then half adapted to mean "stop looking for a better quality in my quality settings"

It now is solely to stop searching for a new/better quality, but you still can know what quality that is in case you decide to switch it and get a better quality at any time.

**Comment by kossboss** [comment] 2015-09-29 20:45
@miigotu thanks for clearing that up

**Comment by miigotu** [comment] 2015-09-29 21:09
BTW, it will still work if the file is not there, say if you have on DVD or other external media. You can say it is "Archived DVD" or "Archived Bluray".

**Comment by neoatomic** [comment] 2015-09-30 10:49
Think we can close this, as it seems more a feature request.? 
Those need to go here.: (make sure to link to this post.)

http://feathub.com/SiCKRAGETV/SickRage

**Closed by neoatomic** 2015-09-30 10:49 UTC
Labels: 1: Support / question

**Comment by miigotu** [comment] 2015-09-30 10:52
@neoatomic not sure about that, this is about archive on first match which is supposed to archive on first match of initial list.

preferred list will always behave as if its an archived status when im done (aka no more searches once one in preferred is reached)
