### ISSUE TITLE
Failed Episode Search Throwing Attribute Error

### ISSUE THREAD

**Issue by kgpayne** [SiCKRAGETV/sickrage-issues#499] opened 2015-01-27 09:29 UTC
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
Ubuntu 14.04.1 LTS, Python 2.7.6

I marked multiple episodes in a season as 'Failed' for manual re-try of failed episode search.
Logs recorded:
AA
AAAttributeError: 'list' object has no attribute 'prettyName'
AA    logger.log(u"Marking episode as bad: [" + epObj.prettyName() + "]")
AA  File "/home/kp/sickrage_install/sickbeard/search_queue.py", line 255, in run

Episodes were not added to 'Failed Downloads' page, therefore running manual search spits out the same bad episode.

Error is reproducible, so let me know if you need further debug info!

**Comment by fernandog** [comment] 2015-01-27 12:42
@kgpayne failed downloads is a post-processing feature. you can't set as manually set as FAILED.

@Tagforce can you confirm?

**Comment by TagForce** [comment] 2015-01-27 13:30
@fernandog If you re-search manually, the last snatched episode will be marked as failed. In a way, that is setting a failed download manually.

@kgpayne Is that how you do it? If not, let me know what you did to mark them as failed.
Also, let me know how you reproduce it, so I can check if I can do the same. epObj.prettyName() should exist, as epObj is an object, and prettyName is one of its methods. prettyName is not a value, but a function which returns a string. For it to not exist would mean that epObj was created using anything other than TVEpisode.__init__(self, show, season, episode, file) or a copy of a TVEpisode object instance (which, to say the least, should not be possible).

**Comment by fernandog** [comment] 2015-01-27 13:32
@TagForce thanks for helping me with PP issues

**Comment by TagForce** [comment] 2015-01-27 13:36
@fernandog No problem, glad I can help.

**Comment by abeloin** [comment] 2015-01-27 13:41
@TagForce Steps to reproduce: Select the episode then in "Change selected episodes to:" drop-down list choose failed, then click Go.

**Comment by TagForce** [comment] 2015-01-27 13:42
@abeloin LOL... That was so obvious I totally missed that option in the pulldown.

**Comment by TagForce** [comment] 2015-01-27 14:32
https://github.com/TagForce/SickRage/commit/eedb42085b2d64a2f0aa51d269dff1fff11c4984
@fernandog @kgpayne @abeloin 
This should fix it with a rudimentary fix. Can you test this?

I'll have to dig deeper to see if the problem was created intentionally, or if it's just a mess-up and can be changed by changing a single line.

**Comment by abeloin** [comment] 2015-01-27 14:42
@TagForce Works for me.

**Comment by fernandog** [comment] 2015-01-27 14:48
@TagForce @abeloin nice! GO SICKRAGE! kkkk

**Comment by TagForce** [comment] 2015-01-27 15:38
It doesn't seem to break anything else, so I'm going to Push this one.

**Comment by kgpayne** [comment] 2015-01-27 17:27
Sorry for the radio silence! @abeloin @TagForce @fernandog Thanks for taking a look so fast! Will test when I make it home but seems legit. Will this fix ever make it to SickRage master, or is it worth cloning your repo @TagForce ?

**Comment by fernandog** [comment] 2015-01-27 17:30
@kgpayne stop SR, edit your local file, start SR
will take a while to all this commits get on master.

**Comment by TagForce** [comment] 2015-01-27 17:32
It should make it there.

**Comment by fernandog** [comment] 2015-01-27 17:34
dev is away for a while that's why will take some time

**Comment by fernandog** [comment] 2015-01-28 15:29
@TagForce Is it possible to used the failed downloads without enabling PP ? If I manually set as FAILED in the showpage, the failed.db don't get updated. Or it's a bug or we need to hide the "failed" status from the dropdown list if  PP is not enabled and failed not enabled.

**Comment by TagForce** [comment] 2015-01-28 15:32
@fernandog I don't know. I think it's just a way for SR to understand that a previously downloaded file was bad and so will download the episode again. I don't think it will actually do anything with the failed.db.

**Comment by fernandog** [comment] 2015-01-28 15:37
@TagForce So that popup showing to mark as bad does nothing?! Strange, isn't? It should at least add ti to failed.db even if the PP it's not enabled. Otherwise there's no meaning for  that popup

**Comment by TagForce** [comment] 2015-01-28 15:40
It sets the episode status to failed, which causes SR to immediately search for it again, and put it back in the daily and backlog searchqueue. So it does something, but I think (I'd have to check when I have time) it's more cosmetic that the status is failed, rather than really functional.

**Comment by TagForce** [comment] 2015-01-28 16:01
@fernandog I just checked. It deletes old snatches from failed.db's history table. It does not add a release to the failed.db. Other than that it simply creates a high priority download in the searchqueues for that episode. So the failed status seems to be cosmetic, and apart from removing old releases from the failed snatch history, seems to handle pretty much the same as setting it back to wanted.

**Comment by TagForce** [comment] 2015-01-30 09:03
@kgpayne PR was merged into develop branch. Can you update SR and see if the problems are now solved?

**Comment by abeloin** [comment] 2015-02-08 22:19
For ref: Issue #536 is resolved by removing SiCKRAGETV/SickRage#1258

**Closed** 2015-02-19 15:17 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, 4: Need feedback, branch: develop, branch: master
