### ISSUE TITLE
Daemon mode not working

### ISSUE THREAD

**Issue by sacii** [SiCKRAGETV/sickrage-issues#384] opened 2015-01-11 16:10 UTC
Fresh install

```
SR Version:		BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
SR Arguments:	['--datadir=/usr/home/sacii/.config/sickrage-torrents', '--daemon', '--pidfile=/usr/home/sacii/.config/sickrage-torrents/sickrage-torrents.pid']
Python Version:	2.7.9 (default, Dec 23 2014, 11:29:06) [GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)]
OS:				Nas4free 9.2.0.1 (FreeBSD 9.2-RELEASE-p4) x64-embedded
```

The daemon mode does not work. Trying to make any changes to the show database (adding a show, changing an episodes' status) results in the following error:

Error

disk I/O error

Traceback

```python
Traceback (most recent call last): 
File "/usr/local/share/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/share/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/share/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/share/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/share/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/share/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/share/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/share/sickrage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/local/share/sickrage/sickbeard/webserve.py", line 1161, in displayShow t.xem_numbering = get_xem_numbering_for_show(indexerid, indexer) 
File "/usr/local/share/sickrage/sickbeard/scene_numbering.py", line 380, in get_xem_numbering_for_show xem_refresh(indexer_id, indexer) 
File "/usr/local/share/sickrage/sickbeard/scene_numbering.py", line 491, in xem_refresh {'indexer_id': indexer_id}) 
File "/usr/local/share/sickrage/sickbeard/db.py", line 217, in upsert self.action(query, valueDict.values() + keyDict.values()) 
File "/usr/local/share/sickrage/sickbeard/db.py", line 170, in action sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone) 
File "/usr/local/share/sickrage/sickbeard/db.py", line 92, in execute raise e 
OperationalError: disk I/O error 
```

Request Info

```python
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=207621
query_arguments: {'show': ['207621']}
_start_time: 1420991626.83
headers: {'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Host': 'nas4free.lan:65069', 'Referer': 'http://nas4free.lan:65069/manage/backlogOverview/', 'Cookie': 'user="2|1:0|10:1420484646|4:user|44:MTkzNDI4ZTBlZTc4YjlkYjdlMDUwYjAwM2VlZmM2NDc=|32bd2813d65db37a154b52e640e38cba4d93744e11cb9a7618e3afa0aca1b64d"'}
host: nas4free.lan:65069
version: HTTP/1.1
arguments: {'show': '207621'}
_finish_time: None
query: show=207621
path: /home/displayShow
_cookies: Set-Cookie: user="2|1:0|10:1420484646|4:user|44:MTkzNDI4ZTBlZTc4YjlkYjdlMDUwYjAwM2VlZmM2NDc=|32bd2813d65db37a154b52e640e38cba4d93744e11cb9a7618e3afa0aca1b64d"
method: GET
remote_ip: 192.168.1.103
```

Just to rule out a permissions problem, I changed permissions to wide-open (777) for every file/directory in the program directory and the data directory, however, the error still occurs. The error **does not** occur when the daemon mode is not used, such as when sickrage is run in console mode in a tmux screen.

**Comment by fernandog** [comment] 2015-01-12 13:29
@sacii see this: https://github.com/SiCKRAGETV/sickrage-issues/issues/379

**Comment by sacii** [comment] 2015-01-12 22:08
@fernandog 
 
You closed this issue prematurely. Deleting cache.db in sickbeard's datadir (there is no cache.db in sickbeard's program directory) does not fix this error.

**Comment by fernandog** [comment] 2015-01-12 22:41
@sacii did you read the entire issue? Tried everything posted there?

**Comment by sacii** [comment] 2015-01-14 15:39
@fernandog 

Yes and yes. Turns out it is not a cache.db nor a HDD problem. It is a unionfs problem. Since I am running an embedded system, I make my /usr directory writeable with unionfs like this:

/mnt/Workspace/nas4free/usr ==> unionfs ==> /usr

This setup makes it possible to put python programs like sabnzbd+ and sickbeard under my /usr/local/share directory and the configuration/data directories under my /usr/home/sacii/.config directory. This setup also makes it possible to use FreeBSD's package system to install programs needed by sabnzbd+ and sickbeard.

My sickbeard program directory is /usr/local/share/sickbeard and I have two configuration/data directories, /usr/home/sacii/.config/sickbeard-nzbs and /usr/home/sacii/.config/sickbeard-torrents. This allows me to run two instances of sickbeard with different configurations and databases. Sickbeard has no problems with this setup, but, sickrage in daemon mode does not like this setup. Sickrage without daemon mode has no problems with this setup.

If I use /usr/local/share/sickrage as my program directory (again using unionfs) and /mnt/Workspace/sickrage-torrents as my configuration/data directory, sickrage in daemon mode does not generate disk I/O errors. Note, this is the exact same HDD as before, without using unionfs for the configuration/data directory.

Since sabnzbd+ in daemon mode, sickbeard in daemon mode and sickrage without daemon mode all work with a unionfs setup, I still think there is an error in sickrage's daemon mode. However, at least I can work around this error while further testing sickrage.

**Comment by fernandog** [comment] 2015-01-14 15:59
@echel0n

**Comment by fernandog** [comment] 2015-02-12 16:46
@Abeloin do you understand about this one?

**Comment by abeloin** [comment] 2015-02-12 19:41
As sacii said it seem the combination of the daemonize() function and using 2 layers/levels of unionfs(/mnt/Workspace/nas4free/usr = /usr and /mnt/Workspace/sickrage-torrents = /usr/home/sacii/.config/sickbeard-torrents) is the issue.

My guess is it's fuse-unionfs related.

Also is he using the latest version of fuse-unionfs? Maybe fixed in new releases.

There's not much we can do. He will need to debug the fuse-unionfs to find the cause.

**Comment by fernandog** [comment] 2015-02-13 16:10
@sacii

**Closed** 2015-02-16 02:08 UTC
Labels: 1: Bug / issue, 3: Unconfirmed, branch: master

**Comment by sacii** [comment] 2015-02-17 16:24
@abeloin  & @fernandog 

There is only one unionfs layer, the mounting of /mnt/Workspace/nas4free/usr above /usr.  Both the sickrage program and the configuration directory were in the writeable /usr layer. I had to move both the program and the configuration directory out of the unionfs layer to get the daemon mode to work.

I am using the mount_unionfs command (alias for mount -t unionfs) to mount the unionfs layer which is not based on fuse, it is instead a unionfs service for Linux and FreeBSD which is built into a loadable module (unionfs.ko).

I hope this information is useful, however, I do not believe that unionfs is the problem because sabnzbd+ and sickbeard have no problems with unionfs.

**Comment by fernandog** [comment] 2015-02-20 11:45
@echel0n
