### ISSUE TITLE
Episodes Unaired set to Ignored

### ISSUE THREAD

**Issue by ajtudela** [SiCKRAGETV/sickrage-issues#550] opened 2015-02-04 20:26 UTC
In the last commit, it's being comming for a week. Some unaired episodes are sets to ignored, so when the air dates came out, they don't  download.

**Comment by fernandog** [comment] 2015-02-04 20:50
How can I help you if you cant help me?

**Comment by ajtudela** [comment] 2015-02-04 20:51
Excuse me?

**Comment by fernandog** [comment] 2015-02-04 20:53
Follow the guidelines:
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by ajtudela** [comment] 2015-02-04 20:59
SR Version:	BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)
Python Version:	2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]

I use windows 8.1.

http://pastebin.com/BvkHRgaG

**Comment by ajtudela** [comment] 2015-02-04 21:01
https://dl.dropboxusercontent.com/u/11602465/Captura.PNG

**Comment by abeloin** [comment] 2015-02-05 05:48
Have you try to do a "force full update" on the show?

**Comment by ajtudela** [comment] 2015-02-05 12:13
Yes, but it's still the same

**Comment by fernandog** [comment] 2015-02-05 12:21
@ajtudela check your config.ini and post the "status_default" value

**Comment by fernandog** [comment] 2015-02-05 12:23
There's nothing in the log. with need the [DB] log. 

"How to enable debug logging for better issue logging

Shutdown Sickbeard, and edit the config.ini in your favourite editor. Add debug=1 in the configuration in the very first line and start sickbeard. Once the error happens again, use the logfile, paste it on pastebin or an equivalent site and create, or update your issue.

Don't forget to remove the debug line once you're done considering debug can be a bit spammy."

**Comment by ajtudela** [comment] 2015-02-05 13:37
http://pastebin.com/Zx4KZtDx

https://dl.dropboxusercontent.com/u/11602465/Captura2.PNG

The episode 4x12 it's unaired

**Comment by fernandog** [comment] 2015-02-05 14:44
@ajtudela mark as wanted and do a manual search. Log does not show what happens. you need to send log as soon as you see this happens again

**Comment by ajtudela** [comment] 2015-02-05 15:13
http://pastebin.com/HKiQQ78s

**Comment by fernandog** [comment] 2015-02-05 15:16
@ajtudela we need logs like this:

2015-02-05 16:12:21 DB
2015-02-05 16:12:22 DB
2015-02-05 16:12:23 DB
2015-02-05 16:12:24 DB

not just INFO DEBUG OR ERROR

**Comment by ajtudela** [comment] 2015-02-05 20:50
Lookin in the logs, I see this:

"2015-02-05 21:49:24 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode has no air date, automatically marking it skipped"

**Comment by raymondtrueman** [comment] 2015-02-06 09:27
I can confirm this. Some Unaired episodes are marked as skipped. But in my case eventually they automatically become Wanted when the show updates and the episodes get airdates

**Comment by fernandog** [comment] 2015-02-09 15:04
@ajtudela those episodes are now downloaded or still ignored?

**Comment by fernandog** [comment] 2015-02-09 15:58
@abeloin do you delete the episodes after watching them? there's a setting in config.ini to skip removed files so if a downloaded episode get's removed, SR will set as IGNORED. You can disable it by   setting skip_removed_files = 1

```
 DEBUG    SHOWQUEUE-REFRESH :: 265912: Location for 2x4 doesn't exist, removing it and changing our status to IGNORED
```

just found out this setting. I was found out this because my downloaded episodes that were downloaded are being set to IGNORED.

**Closed** 2015-02-19 14:51 UTC
Labels: 1: Support / question
