### ISSUE TITLE
[APP SUBMITTED]: Loaded module _root__sickrage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2700] opened 2015-09-08 20:34 UTC
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c9729676cdbd2af5b04337b239bb3a843f5feaa4
Link to Log: https://gist.github.com/f5b5bf4e8b8c36f6121b
### ERROR
```
Thread-54 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/root/.sickrage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/root/.sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/root/.sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/root/.sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _root__sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MGaetan89** [comment] 2015-09-08 21:56
Try to delete the `cache/mako` folder and start SickRage again.

**Comment by neoatomic** [comment] 2015-09-08 22:40
Getting this error myself from time to time. Haven't found the cause. 
However got the feeling that this happens when you have a second SR page open (like IRC) and do an update/restart. But not sure through...

**Comment by rahdjoudj** [comment] 2015-09-09 00:20
it's looking for the wrong file /usr/local/sickrage/var/SickRage/gui/slick/interfaces/default/home.mako
instead of /usr/local/sickrage/var/SickRage/gui/slick/views/home.mako.
Plus there is no interfaces folder within that path.

https://gist.github.com/3a7c9680b7d3d6a6ba91.git

**Comment by OmgImAlexis** [comment] 2015-09-09 00:26
@rahdjoudj sounds like you need to delete cache/mako

There use to be a interfaces directory and we moved to a views one.

**Comment by rahdjoudj** [comment] 2015-09-09 00:32
Cheers @OmgImAlexis , it did solve the precise file not found problem.
I guess that image issue is different then:
<img width="652" alt="screen shot 2015-09-09 at 10 31 26 am" src="https://cloud.githubusercontent.com/assets/13533445/9750656/0ee767f4-56de-11e5-9b68-3a71a766a609.png">

**Comment by OmgImAlexis** [comment] 2015-09-09 00:34
Yep, that's a known issue. @MGaetan89 is working on it.

@devenashani if you can confirm this is the same issue I'll close this.

**Comment by rahdjoudj** [comment] 2015-09-09 00:39
nice work guys :)
thanks

**Closed** 2015-09-10 06:43 UTC
Labels: 1: Bug / issue

**Comment by devenashani** [comment] 2015-09-26 07:52
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/801930bf33dfb74e77d3
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/root/.sickrage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/root/.sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/root/.sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/root/.sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _root__sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment] 2015-09-26 07:53
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/efa304c5100ba6fae3ef
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/root/.sickrage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/root/.sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/root/.sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/root/.sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _root__sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
