### ISSUE TITLE
[Feature Request] Stay on Show Page after clicking on "Update show in Kodi"

### ISSUE THREAD

**Issue by heymoe** [SiCKRAGETV/sickrage-issues#774] opened 2015-02-26 01:43 UTC
BRANCH: (develop) / COMMIT: (7c6fe7fcbe9a8ccdb8d90a252f8680f2af7fa7ec) 
OS: Linux, Python 2.6

Feature Request:
If you're viewing a show managed by SickRage and you click on the "Update show in Kodi" toward the top right of the page, the page refreshes and takes you back to the "Show List" page (The page that shows you all of the shows that SickRage is managing). 

It would seem to make more sense (to me at least) that you are returned to the Show that you were looking at / managing when you click the "Update show in Kodi" like / button instead of being taken to the list of all shows. Maybe it's even possible to trigger the Kodi update without even refreshing the page.

I don't know if the current behavior is by design and is preferred by the majority of users. If so, that's fine and I'll live with it.

**Comment by fernandog** [comment] 2015-03-02 12:32
it's by design. don't know if there's a way to fix it
what you can do: right click in the button and "open in a new tab"

**Comment by heymoe** [comment] 2015-03-02 14:50
Fair enough, I'll give the new tab work around a try. Thanks

**Comment by fernandog** [comment] 2015-04-17 10:18
merged in develop

**Comment by heymoe** [comment] 2015-04-17 18:24
Looks like it works.. Awesome!.. Thanks!

**Closed** 2015-04-17 18:24 UTC
Labels: 1: Feature request, 3: Fix
