### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/share/MD0_DATA/Download/complete/tv/The Big Bang/The Big Bang Theory S04/The Big Bang Theory S04E15.mkv'

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#690] opened 2015-02-20 21:39 UTC
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) 
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@62f45524eb9f1e3762a22af0bcd576e4285bad52
Link to Log: https://gist.github.com/dad9462894f7534081ec
### ERROR
```
Thread-80 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2047, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 211, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 421, in process_media
    result.result = processor.process()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 838, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 131, in _checkForExistingFile
    if ek.ek(os.path.getsize, existing_file) > ek.ek(os.path.getsize, self.file_path):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/share/MD0_DATA/Download/complete/tv/The Big Bang/The Big Bang Theory S04/The Big Bang Theory S04E15.mkv'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment] 2015-02-20 23:01
@TehWardy what did you do ? can you explain everything step by step?
did you deleted the episode?

**Comment by fernandog** [comment] 2015-02-21 01:37
@TehWardy do you have postpone setting disabled in PP?

**Comment by Kallb123** [comment] 2015-02-21 02:16
Looks very similar to my issue. For me, it's not just SR having trouble, but no programs can access the files, seems something wrong with transmission/ownership/permissions. Please post a solution of you find one, I'll do likewise.

**Comment by fernandog** [comment] 2015-02-21 02:18
@Kallb123 there's lot of them

https://github.com/SiCKRAGETV/sickrage-issues/search?q=%5BErrno+2%5D+No+such+file+or+directory%3A+&type=Issues&utf8=%E2%9C%93

source folder and destination folder are in the same partition/hdd?

**Comment by Kallb123** [comment] 2015-02-21 02:25
@fernandog. Physically they are, but Transmission and SR are running in a (single)  virtual machine with downloads and downloading mapped separately and then mounted on boot to /mnt/downloads and /mnt/downloading

**Comment by TehWardy** [comment] 2015-02-21 11:07
This occurs when sickrage is asked to post process lots of files.
It seems to get itself confused when moving files from a download location to a library location.

I drop my files in using sab utorrent and just straight moves in windows.

The problem appears to be the order in which events occur in the post process script or perhaps in the way its tracking the work it has done.

**Comment by fernandog** [comment] 2015-02-21 11:23
can you check if this torrent file there were a folder with the name of the episode and the episode itself inside it? 
We need to find what is common for all this errors

**Comment by TehWardy** [comment] 2015-02-21 11:31
Its a mix in my case ... Also my files are stored on a nas its a raid 5 volume spread over 5 disks so the partition is the same but the share is not as sickrage moves files from /share/download/tv/* to /share/multimedia/tv/show/season/ep name

**Comment by TehWardy** [comment] 2015-02-21 11:33
Downloading for me happens inside an in progress folder and also on another machine (in progress for sab dl other machine for utorrent) sickrage grabs nzb and torrent files and feeds both apps.

When a download is complete its moved for post processing.

**Comment by fernandog** [comment] 2015-02-21 12:17
@TehWardy 
Can you provide the following:
* User running torrent downloader
* Group membership for that user
* User running SickRage
* Group membership for that user
* File permission,owner and group for /share/MD0_DATA/Download/complete/tv/The Big Bang/The Big Bang Theory S04/
* File permission,owner and group of tv-shows folders

**Comment by TehWardy** [comment] 2015-02-21 12:44
As I mentioned above, my torrent app runs on another box but my nas holds all the files for everything even temp files during downloads.

I only have 1 user setup on the nas which is the default administration user setup by qnap (my nas vendor). 
From what I can tell that user is in all the groups configured on the box which are "users" and  "administrators". 
That user has global full control level rights to every path across the entire system.
Admittedly not the most secure setup but these apps are internal and the box does not directly have the ability to receive connections to the outside world, but it can make them if needed.

Hopefully that helps.
The one thing I would add here is that although i'm a developer myself I'm by no means clued up on linux systems but I may be able to provide you with info if you have specific commands you need me to run.

Suffice to say:
I don't believe the issue is permissions related, looking at what it appears to be doing it seems to present something like this ....
File exists.
Some processing occurs and file is moved.
Sickrage then goes back to the old location and wonders why it's not there for some reason causing the error.

I am seeing the processing occur in what appears to be the correct manner, re-running processing after this error results in more files being handled and may produce the error again or it may complete successfully.
Either way persistence seems to show that eventually I get the desired result.

**Comment by fernandog** [comment] 2015-02-24 15:52
@TagForce any thoughts?

**Comment by TagForce** [comment] 2015-02-24 17:23
@TehWardy @fernandog Ok, what happens is the following:

SR Post Processes a file in the download folder.
It does this by creating a list of all the videofiles in a folder and its subfolders (TV Download Dir).
It then runs through each videofile it found in the base folder.
It executes process_media for each file, which in turn checks if the file being processed already exists as an episode in the destination folder. If it does, it then checks if the downloaded file is larger or smaller than the one that already exists. If it's safe to overwrite, or if it doesn't exist it Post Processes the file.

When it's done with the base dir, it moves on to all the subfolders.

What it looks like to me, is that there's a file it sees in one of the subfolders, and is added to the list of videofiles to process. Then when the time comes to post process, that file is either: A) removed, or B) inaccessible by SR. It then fails the check for the filesize on the downloaded file.

That's what line 131 in PostProcessor.py does anyway. Which is ultimately where it fails, due to some problem accessing the file.

In my opinion, this can indeed happen when one of the following conditions is true:
1. The file is still being written by the downloader when PP starts, and it's not recognised as a 'syncfile'. By the time SR post processes the file, it's renamed or moved away, and the check fails. This has a small window of time to occur, unless there's a lot of files in the same folder being processed.
2. The file is done but is kept 'locked' by the downloader because it's being seeded or whatever. SR can't read the file, but can see it exists. It therefor can't read the filesize, and the check fails.
3. The user deletes the file while PP runs.

It's highly unlikely that SR deletes the file, since SR doesn't delete files until it's done with the post processing (ie after running process_media, which is the function during which you see the error). Only exception would be that it marks a videofile as 'unwanted' files, but that also seems highly unlikely.

What can we do to keep this from happening?
Well, if you're Post Processing a lot of (large) files in the same folder, then the time between getting the list of files to post process, and the actual processing of the files can be rather high.
We could add a sanity check to see if the file we're about to process still exists. This will keep it from failing files that have moved away since initiating the Post Process. It won't fix files that are locked for exclusive access by the downloader. But hey, if this doesn't fix it completely we can worry about that later.

**Comment by fernandog** [comment] 2015-02-24 17:36
@TagForce thanks for the explanation, 

about locked for exclusive access, PP will always fail in that case. We must catch that exception and move to the next file. Or entire PP will fail?
see this:
https://github.com/SiCKRAGETV/sickrage-issues/issues/743

**Comment by TagForce** [comment] 2015-02-24 18:51
@TehWardy @fernandog @Kallb123 
Can you try this commit? Hopefully fixes things at least partly. At least when you now get the same error as before we know the file is really there.
https://github.com/TagForce/SickRage/commit/08645eceb16abdb656bb2ee77a4ede2d5c5d8af6

**Comment by fernandog** [comment] 2015-02-24 18:53
@TehWardy @Kallb123 

stop SR,
edit SickRage/sickbeard/processTV.py, erase the contents and paste this
https://raw.githubusercontent.com/TagForce/SickRage/08645eceb16abdb656bb2ee77a4ede2d5c5d8af6/sickbeard/processTV.py
save, start SR

**Comment by TehWardy** [comment] 2015-02-24 19:01
Suggestion:
Rather than scanning for a list of files then processing that list could SR enter in to a loop that goes something like ...

while( (var nextFile = ScanForFile()) != null)
  Process(nextFile);

That way the processing is only occurring on a file that is absolutely there.

Also the processing should first do the checks like access and size and if there's a problem simply ignore it as "blocked for some reason" rather than running in to an exception later?

You may also find that files that just finished downloading are still being written to the pickup location for SR so whilst there may be an issue accessing the file this time round in a few mins when it does the next run the problem may have gone away.
I would perhaps consider tracking files and say that this should only be considered an exception if access was refused / impossible for some reason more than X number of times (X being configurable or something?)

In the meantime ... I will try that fix out as your last comment @fernandog .

**Comment by TehWardy** [comment] 2015-02-24 19:02
result.result = ???
wtf ... nice variable naming there!

lol

**Comment by fernandog** [comment] 2015-02-24 19:45
@TagForce what do you think about SR should test writing/moving a dummy file to PP folder before "accept" it and save it. If there's some permission error or filesystem does not allow temp file creating while copying and etc. SR should show ""Operation not supported by your OS and setup. Check your permissions and/or target filesystem"

**Comment by TehWardy** [comment] 2015-02-24 19:54
My suggestion would be:

I think that check should be done anyway at the start of a post process on the root level PP dir and cause a drop out if any issues.

Then if problems are hit with accessing files within that have a set number of "allowed fails" to allow for things like download clients still working on moving / writing the files when the PP occurs.

**Comment by TagForce** [comment] 2015-02-25 11:17
@TehWardy result is an instance of the ProcessResult class with 2 attributes:
result: Boolean
output: String

Process_Dir and Process_media return a boolean: true if succesful, false if unsuccesful.
That gets entered into result.result (the boolean).
result.output is passed to the logger to have it log the actual error messages in the log.

Yeah, it's not the most intuitive var naming.

@fernandog We don't know the destination folder before we process a file, so that check would have to come after we've determined a show, season, and episode number. Which means we'd need to copy a dummy file for every videofile we process. This would slow things down considerably. I could probably add one without too much hassle, but there may be other checks we can do that are faster than the constant writing of dummy data. Remember that a lot of people PP files to a network share, and not the machine that actually runs SR. Network file access is slow, especially with little data to be transferred. This gets negated by SR under normal circumstances, because the files we're transferring are large (100MB+), so the time it takes to gain write access is still only a fraction of the time it takes to copy the file. If we copy a small amount of data (say 64KB randomly generated data) to test if we can, then gaining access to write that data will be a considerable portion of the total time it takes to create that file. After that we need to delete the file again which costs another write access time.

Doing that check only when starting the PP run will still keep throwing errors on files that were changed in between the start of the run, and the time we actually process the file.

As for @TehWardy 's idea about entering a loop for each file, and then processing just that file, is going to be difficult as the file list it creates is filtered to seperate videofiles, rarfiles, additional files, and unwanted files. This makes sure that when processing a given videofile all the supporting files (.nfo, .srt, etc) are also copied along, and all the other files are also handled accordingly.

What we need to do is find out what is happening when it's failing. If we can find the cause for it failing certain files, we can build in checks to make sure it exits nicely instead of throwing exceptions and halting PP altogether.

**Comment by Kallb123** [comment] 2015-02-25 11:18
@TagForce Sorry for the late reply, I fixed my issue by correcting permissions (and filesystem). So I can't provide feedback on the commit you pushed.

**Comment by Kallb123** [comment] 2015-02-25 11:20
@TagForce Maybe just try the main tv folder(s)? In most cases, permissions will be the same through the sub directories, right?

**Comment by TagForce** [comment] 2015-02-25 13:50
@Kallb123 'most cases' being the operative words... I'd rather fix it for all cases, than most cases. Either way, it seems like the post-processing needs some overhaulin' to get everything sorted.

**Comment by fernandog** [comment] 2015-02-25 14:07
@TagForce should we commit your unrar PR to master or wait this overhaulin' ?

**Comment by TagForce** [comment] 2015-02-25 17:36
@TehWardy https://github.com/TagForce/SickRage/commit/b0133e5eb83ddbc95f8619feb24e72b0c1a4918d
This should fix all the errors with files not existing...

@fernandog Yes, you can commit that one, not a big change.
I have another one waiting to be tested that should be committed. The one in this post. In fact, that also fixes an issue where RAR file contents weren't deleted if process method was copy, and SR thinks something went wrong in PP (while it didn't). It will now ALWAYS delete the Rar contents.

**Comment by fernandog** [comment] 2015-02-25 17:43
@TagForce about the "[Errno 2] No such file or directory" error, is it possible to show if is permission or any other thing? It's hard to tell the actual way.

**Comment by TagForce** [comment] 2015-02-25 17:46
@fernandog Yes, I think @abeloin already did something similar a short while ago.

**Comment by abeloin** [comment] 2015-02-25 20:40
@TagForce @fernandog Nope I don't think so and you wouldn't get an error 2 for a permission issue it would be 13.

**Comment by fernandog** [comment] 2015-02-26 00:48
@TehWardy did you tested TagForce/SickRage@b0133e5 ?

**Comment by TehWardy** [comment] 2015-02-26 13:52
Yup ... looks good so far.
I did get a missing file error yesterday but I think that was my fault. 

I haven't yet tried a file dump from my pc though which is what normally causes this issue. 
I will have a crack at this later this evening when i'm back at my home pc.

**Comment by TagForce** [comment] 2015-02-26 15:58
@TehWardy Please test using only the newest develop release... The fix was merged into it (along with an option to add your own syncfile extensions, so if you want to add .tmp files as files that should stop PP, you now can).

**Comment by TehWardy** [comment] 2015-02-26 18:12
Ok according to SR im already running the latest version of the dev  branch ... no updates available.
So I would say so far all is looking good.

**Closed** 2015-02-27 19:41 UTC
Labels: 1: Bug / issue, 3: Confirmed, 3: Fix, branch: develop
