### ISSUE TITLE
Unable to submit SickRage errors to GitHub through SickRage

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#424] opened 2015-01-16 01:27 UTC
SR Version:	        BRANCH: (develop) / COMMIT: (0bb84466d06ca068e09d5f8bc2bbb828c598963a) 
SR Config file:	        /Users/ryan/SickRage/config.ini
SR Database file:	/Users/ryan/SickRage/sickbeard.db
SR Cache Dir:	        /Users/ryan/SickRage/cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
OS Version:             OSX 10.10.2

What you did: 
- Attempting to submit errors using submit error button.
- Have restarted SickRage
- Re-installed Sickrage from github
- Checked username and password for github

What happened: Got the following errors
```python
2015-01-16 12:12:32 Thread-52 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 12:08:52 Thread-71 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 12:08:46 Thread-69 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 12:08:41 Thread-68 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 12:08:35 Thread-45 :: cannot concatenate 'str' and 'GithubException' objects
2015-01-16 12:08:30 Thread-91 :: 
2015-01-16 12:02:51 FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
2015-01-16 11:31:23 Thread-43 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 11:31:18 Thread-80 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 11:31:12 Thread-58 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-01-16 11:31:06 Thread-47 :: cannot concatenate 'str' and 'GithubException' objects
2015-01-16 11:31:00 Thread-77 :: 
2015-01-16 11:12:58 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, instance found
```
Pastebin logs: http://pastebin.com/JutKFt4a

**Comment by markheloking** [comment] 2015-01-18 13:08
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/287. Closing this one, continue the discussion over there.

**Closed by markheloking** 2015-01-18 13:08 UTC
Labels: 1: Bug / issue, 2: Medium Priority, 3: Confirmed, 4: Fix pending, branch: develop
